### ISSUE TITLE
Pouvoir utiliser Libertempo sans avoir des requêtes réseau externes

### ISSUE THREAD

**Issue by cyberesprit** [wouldsmina/Libertempo#100]
Bonjour,

(je ne suis pas sûr que ce soit le bon endroit pour ce genre de ticket, merci de m'indiquer la bonne démarche si besoin)

**Pouvoir utiliser Libertempo sans avoir des requêtes réseau externes**

Un site sans dépendance à d'autres sites est bien mieux, et pour une application web comme Libertempo c'est même logique d'être indépendant, l'application peut être utilisée dans un environnement sans accès à internet (ou un utilisateur averti qui utilise des modules comme RequestPolicy).

Merci d'envisager cette indépendance et d'intégrer les différentes bibliothèques ou polices comme bootstrap, jquery et les fonts google directement avec les sources.

Librement ;-)

**Comment by Prytoegrian** [comment]
Oui et non. Je vais prendre les choses dans l'ordre : déjà, c'est tout à fait l'endroit pour proposer / discuter de ça, la liste des tickets n'est pas à voir comme une liste de bugs mais comme une liste de chose à faire, donc pas d'inquiétude là dessus.
Ensuite, j'ai déjà amorcé dans la branche de travail (qui devrait être livrée dans quelques mois) de virer Twig qui n'était pas utilisé. Je suis aussi de ceux qui pensent que jQuery a pu faciliter les choses par le passé (quand certains navigateurs faisaient de la résistance), mais sa nécessité est remise en cause depuis quelques temps, le vanilla pouvant faire le job tout aussi bien ; s'en détacher est plus ou moins un objectif. Par contre, utiliser bootstrap facilite grandement notre tâche.

Tout dépend comment tu sous-entends la notion de dépendance. Si tu parles de permettre d'utiliser l'appli sans avoir des requêtes réseau externes, je suis pour ; si c'est « enlever les dépendances complètement » je suis pas fan. Réinventer la roue à chaque fois est une perte de temps et tout temps passé sur ces devs est un temps que l'on ne passe pas à développer de nouvelles fonctionnalités pour l'appli. Tout dépend où tu veux placer la dette technique en fait.

Tout ça implique que je pense que ton titre de ticket est mal tourné, ta dernière phrase représente plus ce que tu veux dire et avec laquelle je suis en accord. Je t'invite donc à l'affiner :-)

Tu as des compétences en dev ? Parce qu'on a besoin de petites mains, si tu veux / peux t'en occuper, fais toi plaisir :-)

**Comment by cyberesprit** [comment]
Ha oui pardon, c'est effectivement « utiliser l'appli sans avoir des requêtes réseau externes » qui m'interpelle.

Utiliser des bibliothèques ne m'est absolument pas un problème, bien au contraire, tant que ça reste au minimum opensource ;-)
