### ISSUE TITLE
demande d'ajout de bouton d'annulation de congé par les agents

### ISSUE THREAD

**Issue by alainco75** [wouldsmina/Libertempo#1013]
Bonjour,
Je vous soumets ci-dessous une demande d'une utilisatrice de libertempo :

---------------------------------------------------
Serait-il possible de rajouter un bouton en face des congés validés, pour demander l'annulation dudit congé (annulation qui devrait évidemment être confirmée par le supérieur hiérarchique) ?

Cela arrive assez régulièrement qu'un jour de télétravail soit annulé ou déplacé (en fonction de réunions par exemple), et je pense que ce n'est pas à mon supérieur hiérarchique d'aller fouiller dans mes jours validés pour choisir celui qui est à annuler... (je pense d'ailleurs que les jours de TT ne devraient pas être gérés comme des congés, mais c'est un autre sujet...)

-------------------------------------------------------------

cordialement

transmis par Alain Courgey
Observatoire de Paris

**Comment by wouldsmina** [comment]
Bonjour @alainco75

Désolé, mais je n'ai plus le temps de proposer de nouvelles fonctionnalités pour Libertempo...

Légalement je crois que le responsable a le droit d'annuler un congé mais je ne sais plus si c'est 15 jours ou 48 heures avant (legifrance a la réponse mais c'est plutôt le job des rh de répondre à cela).

Je te laisse expliquer ça à ton/ta collègue qui me paraît fort sympathique 😉
Cordialement.
