### ISSUE TITLE
Notfication MAIL : Mail Congés refusé puis mail Congés accepté

### ISSUE THREAD

**Issue by ptitpopey** [wouldsmina/Libertempo#102]
Bonjour,

Je rencontre un problème avec l’envoi de mail. Lorsque le RH valide une demande  de congé, l’utilisateur reçoit deux mails, un mail de refus et ensuite un mail accepté. Une idée ??

**Comment by wouldsmina** [comment]
bonjour,

C'est une update a partir de php_conges ou une nouvelle installation?

**Comment by ptitpopey** [comment]
Nouvelle installation

**Comment by wouldsmina** [comment]
puis-je avoir plus d'infos sur le serveur? sur quel navigateur?

**Comment by ptitpopey** [comment]
Firefox 43. Os debian 8 avec package dépôt stable

**Comment by wouldsmina** [comment]
des logs apache?

**Comment by ptitpopey** [comment]
Aucune erreur dans les logs apache.

**Comment by wouldsmina** [comment]
ça va pas être simple a reproduire! la debian est fraîchement installé? j'utilise moi aussi debian sans problème, mais on m'a déjà fait part de ce soucis...

**Comment by wouldsmina** [comment]
le mail de refus est correctement formé (dates, nom...)?

**Comment by ptitpopey** [comment]
Oui :

XXXX a refusé une demande de congés pour vous dans l'application de gestion des congés.

Merci de consulter votre application Libertempo : http://X.X.X.X/Libertempo/

Détail de la demande :
Type de demande : Congés Payés
Nombre de jours : 2.00
Date de début : 02 / 03 / 2016 (am)
Date de fin : 03 / 03 / 2016 (pm)
Commentaires : 

-------------------------------------------------------------------------------------------------------
Ceci est un message automatique.

**Comment by Prytoegrian** [comment]
@ptitpopey tu as la main sur le code ? Je veux dire, si on te demande de poser un `var_dump()` ou des `backtrace` tu as la possibilité de le faire ?

**Comment by ptitpopey** [comment]
Oui

**Comment by ptitpopey** [comment]
Juste me dire le fichier la ligne et le code

**Comment by wouldsmina** [comment]
pour commencer, pourrais tu passer à la version develop? ce sera corrigé dessus...

on avance a l'aveugle, dans le fichier fonction_conges.php place le backtrace au début de la fonction construct_and_send_email

et un var_dump de : 
- la requete ligne 1015
- de la variable $objet transmis à la fonction construct_and_send_email() ligne 952

on remontera à la fonction alerte_mail() si nécessaire...

**Comment by ptitpopey** [comment]
Est ce que cela peu vous aider 

[Thu Feb 04 23:07:52.056643 2016] [:error] [pid 21526] [client 192.168.14.11:57279] PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /var/www/Libertempo_Dev/includes/fonction.php on line 233, referer: http://172.20.100.103/Libertempo_Dev/
[Thu Feb 04 23:08:03.322765 2016] [:error] [pid 15317] [client 192.168.14.11:57289] PHP Fatal error:  Call to undefined function utilisateur\\get_type_abs() in /var/www/Libertempo_Dev/utilisateur/Fonctions.php on line 116, referer: http://172.20.100.103/Libertempo_Dev/utilisateur/user_index.php?session=phpconges43d21d27e884a254006435e00b020bd7
[Thu Feb 04 23:08:30.980053 2016] [:error] [pid 15246] [client 192.168.14.11:57300] PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /var/www/Libertempo_Dev/includes/fonction.php on line 233, referer: http://172.20.100.103/Libertempo_Dev/
[Thu Feb 04 23:08:37.975519 2016] [:error] [pid 15246] [client 192.168.14.11:57300] a:5:{i:0;a:4:{s:4:"file";s:44:"/var/www/Libertempo_Dev/fonctions_conges.php";s:4:"line";i:926;s:8:"function";s:22:"constuct_and_send_mail";s:4:"args";a:7:{i:0;s:13:"accept_conges";i:1;s:13:"Sylvie COSMAO";i:2;s:18:"s.cosmao@numlog.fr";i:3;s:26:"Pierre-Alexandre CAQUINEAU";i:4;s:22:"pa.caquineau@numlog.fr";i:5;i:29;i:6;b:0;}}i:1;a:4:{s:4:"file";s:40:"/var/www/Libertempo_Dev/hr/Fonctions.php";s:4:"line";i:188;s:8:"function";s:11:"alerte_mail";s:4:"args";a:5:{i:0;s:18:"s.cosmao@numlog.fr";i:1;s:22:"pa.caquineau@numlog.fr";i:2;i:29;i:3;s:13:"accept_conges";i:4;b:0;}}i:2;a:6:{s:4:"file";s:40:"/var/www/Libertempo_Dev/hr/Fonctions.php";s:4:"line";i:422;s:8:"function";s:27:"traite_all_demande_en_cours";s:5:"class";s:12:"hr\\Fonctions";s:4:"type";s:2:"::";s:4:"args";a:3:{i:0;a:1:{i:29;s:64:"pa.caquineau@numlog.fr--1--1--2016-02-08--am--2016-02-08--pm--OK";}i:1;a:1:{i:29;s:0:"";}i:2;b:0;}}i:3;a:6:{s:4:"file";s:53:"/var/www/Libertempo_Dev/hr/hr_traitement_demandes.php";s:4:"line";i:30;s:8:"function";s:27:"pageTraitementDemandeModule";s:5:"class";s:12:"hr\\Fonctions";s:4:"type";s:2:"::";s:4:"args";a:4:{i:0;a:3:{i:1;s:14:"Cong\xc3\xa9s Pay\xc3\xa9s";i:2;s:3:"RTT";i:13;s:14:"R\xc3\xa9cup\xc3\xa9ration";}i:1;s:19:"traitement_demandes";i:2;s:41:"phpconges17f0ce6d20a6c0ba8e246cb371e25b5e";i:3;b:0;}}i:4;a:4:{s:4:"file";s:39:"/var/www/Libertempo_Dev/hr/hr_index.php";s:4:"line";i:110;s:4:"args";a:1:{i:0;s:53:"/var/www/Libertempo_Dev/hr/hr_traitement_demandes.php";}s:8:"function";s:12:"include_once";}}, referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges17f0ce6d20a6c0ba8e246cb371e25b5e&onglet=traitement_demandes
[Thu Feb 04 23:08:37.975972 2016] [:error] [pid 15246] [client 192.168.14.11:57300] , referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges17f0ce6d20a6c0ba8e246cb371e25b5e&onglet=traitement_demandes
[Thu Feb 04 23:08:37.976989 2016] [:error] [pid 15246] [client 192.168.14.11:57300] , referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges17f0ce6d20a6c0ba8e246cb371e25b5e&onglet=traitement_demandes
[Thu Feb 04 23:08:38.004830 2016] [:error] [pid 15246] [client 192.168.14.11:57300] a:5:{i:0;a:4:{s:4:"file";s:44:"/var/www/Libertempo_Dev/fonctions_conges.php";s:4:"line";i:926;s:8:"function";s:22:"constuct_and_send_mail";s:4:"args";a:7:{i:0;s:12:"refus_conges";i:1;s:13:"Sylvie COSMAO";i:2;s:18:"s.cosmao@numlog.fr";i:3;s:26:"Pierre-Alexandre CAQUINEAU";i:4;s:22:"pa.caquineau@numlog.fr";i:5;i:29;i:6;b:0;}}i:1;a:4:{s:4:"file";s:40:"/var/www/Libertempo_Dev/hr/Fonctions.php";s:4:"line";i:221;s:8:"function";s:11:"alerte_mail";s:4:"args";a:5:{i:0;s:18:"s.cosmao@numlog.fr";i:1;s:22:"pa.caquineau@numlog.fr";i:2;i:29;i:3;s:12:"refus_conges";i:4;b:0;}}i:2;a:6:{s:4:"file";s:40:"/var/www/Libertempo_Dev/hr/Fonctions.php";s:4:"line";i:422;s:8:"function";s:27:"traite_all_demande_en_cours";s:5:"class";s:12:"hr\\Fonctions";s:4:"type";s:2:"::";s:4:"args";a:3:{i:0;a:1:{i:29;s:64:"pa.caquineau@numlog.fr--1--1--2016-02-08--am--2016-02-08--pm--OK";}i:1;a:1:{i:29;s:0:"";}i:2;b:0;}}i:3;a:6:{s:4:"file";s:53:"/var/www/Libertempo_Dev/hr/hr_traitement_demandes.php";s:4:"line";i:30;s:8:"function";s:27:"pageTraitementDemandeModule";s:5:"class";s:12:"hr\\Fonctions";s:4:"type";s:2:"::";s:4:"args";a:4:{i:0;a:3:{i:1;s:14:"Cong\xc3\xa9s Pay\xc3\xa9s";i:2;s:3:"RTT";i:13;s:14:"R\xc3\xa9cup\xc3\xa9ration";}i:1;s:19:"traitement_demandes";i:2;s:41:"phpconges17f0ce6d20a6c0ba8e246cb371e25b5e";i:3;b:0;}}i:4;a:4:{s:4:"file";s:39:"/var/www/Libertempo_Dev/hr/hr_index.php";s:4:"line";i:110;s:4:"args";a:1:{i:0;s:53:"/var/www/Libertempo_Dev/hr/hr_traitement_demandes.php";}s:8:"function";s:12:"include_once";}}, referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges17f0ce6d20a6c0ba8e246cb371e25b5e&onglet=traitement_demandes
[Thu Feb 04 23:08:38.004912 2016] [:error] [pid 15246] [client 192.168.14.11:57300] , referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges17f0ce6d20a6c0ba8e246cb371e25b5e&onglet=traitement_demandes
[Thu Feb 04 23:08:38.005277 2016] [:error] [pid 15246] [client 192.168.14.11:57300] , referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges17f0ce6d20a6c0ba8e246cb371e25b5e&onglet=traitement_demandes

**Comment by wouldsmina** [comment]
merci. J'ai copié et tronqué le temps d'anonymiser...

**Comment by ptitpopey** [comment]
Un peu plus lisible 

[Thu Feb 04 23:14:03.058285 2016] [:error] [pid 16869] [client 192.168.14.11:57401] Array\n(\n    [0] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/fonctions_conges.php\n            [line] => 926\n            [function] => constuct_and_send_mail\n            [args] => Array\n                (\n                    [0] => accept_conges\n                    [1] => Sylvie COSMAO\n                    [2] => s.cosmao@numlog.fr\n                    [3] => Pierre-Alexandre CAQUINEAU\n                    [4] => pa.caquineau@numlog.fr\n                    [5] => 30\n                    [6] => \n                )\n\n        )\n\n    [1] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/hr/Fonctions.php\n            [line] => 188\n            [function] => alerte_mail\n            [args] => Array\n                (\n                    [0] => s.cosmao@numlog.fr\n                    [1] => pa.caquineau@numlog.fr\n                    [2] => 30\n                    [3] => accept_conges\n                    [4] => \n                )\n\n        )\n\n    [2] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/hr/Fonctions.php\n            [line] => 422\n            [function] => traite_all_demande_en_cours\n            [class] => hr\\Fonctions\n            [type] => ::\n            [args] => Array\n                (\n                    [0] => Array\n                        (\n                            [30] => pa.caquineau@numlog.fr--1--1--2016-02-04--am--2016-02-04--pm--OK\n                        )\n\n                    [1] => Array\n                        (\n                            [30] => \n                        )\n\n                    [2] => \n                )\n\n        )\n\n    [3] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/hr/hr_traitement_demandes.php\n            [line] => 30\n            [function] => pageTraitementDemandeModule\n            [class] => hr\\Fonctions\n            [type] => ::\n            [args] => Array\n                (\n                    [0] => Array\n                        (\n                            [1] => Cong\xc3\xa9s Pay\xc3\xa9s\n                            [2] => RTT\n                            [13] => R\xc3\xa9cup\xc3\xa9ration\n                        )\n\n                    [1] => traitement_demandes\n                    [2] => phpconges4929d7b9a41349a017aa4a9540403dec\n                    [3] => \n                )\n\n        )\n\n    [4] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/hr/hr_index.php\n            [line] => 110\n            [args] => Array\n                (\n                    [0] => /var/www/Libertempo_Dev/hr/hr_traitement_demandes.php\n                )\n\n            [function] => include_once\n        )\n\n)\n, referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges4929d7b9a41349a017aa4a9540403dec&onglet=traitement_demandes
[Thu Feb 04 23:14:03.058645 2016] [:error] [pid 16869] [client 192.168.14.11:57401] , referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges4929d7b9a41349a017aa4a9540403dec&onglet=traitement_demandes
[Thu Feb 04 23:14:03.059516 2016] [:error] [pid 16869] [client 192.168.14.11:57401] , referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges4929d7b9a41349a017aa4a9540403dec&onglet=traitement_demandes
[Thu Feb 04 23:14:03.082864 2016] [:error] [pid 16869] [client 192.168.14.11:57401] Array\n(\n    [0] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/fonctions_conges.php\n            [line] => 926\n            [function] => constuct_and_send_mail\n            [args] => Array\n                (\n                    [0] => refus_conges\n                    [1] => Sylvie COSMAO\n                    [2] => s.cosmao@numlog.fr\n                    [3] => Pierre-Alexandre CAQUINEAU\n                    [4] => pa.caquineau@numlog.fr\n                    [5] => 30\n                    [6] => \n                )\n\n        )\n\n    [1] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/hr/Fonctions.php\n            [line] => 221\n            [function] => alerte_mail\n            [args] => Array\n                (\n                    [0] => s.cosmao@numlog.fr\n                    [1] => pa.caquineau@numlog.fr\n                    [2] => 30\n                    [3] => refus_conges\n                    [4] => \n                )\n\n        )\n\n    [2] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/hr/Fonctions.php\n            [line] => 422\n            [function] => traite_all_demande_en_cours\n            [class] => hr\\Fonctions\n            [type] => ::\n            [args] => Array\n                (\n                    [0] => Array\n                        (\n                            [30] => pa.caquineau@numlog.fr--1--1--2016-02-04--am--2016-02-04--pm--OK\n                        )\n\n                    [1] => Array\n                        (\n                            [30] => \n                        )\n\n                    [2] => \n                )\n\n        )\n\n    [3] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/hr/hr_traitement_demandes.php\n            [line] => 30\n            [function] => pageTraitementDemandeModule\n            [class] => hr\\Fonctions\n            [type] => ::\n            [args] => Array\n                (\n                    [0] => Array\n                        (\n                            [1] => Cong\xc3\xa9s Pay\xc3\xa9s\n                            [2] => RTT\n                            [13] => R\xc3\xa9cup\xc3\xa9ration\n                        )\n\n                    [1] => traitement_demandes\n                    [2] => phpconges4929d7b9a41349a017aa4a9540403dec\n                    [3] => \n                )\n\n        )\n\n    [4] => Array\n        (\n            [file] => /var/www/Libertempo_Dev/hr/hr_index.php\n            [line] => 110\n            [args] => Array\n                (\n                    [0] => /var/www/Libertempo_Dev/hr/hr_traitement_demandes.php\n                )\n\n            [function] => include_once\n        )\n\n)\n, referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges4929d7b9a41349a017aa4a9540403dec&onglet=traitement_demandes
[Thu Feb 04 23:14:03.082943 2016] [:error] [pid 16869] [client 192.168.14.11:57401] , referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges4929d7b9a41349a017aa4a9540403dec&onglet=traitement_demandes
[Thu Feb 04 23:14:03.083256 2016] [:error] [pid 16869] [client 192.168.14.11:57401] , referer: http://172.20.100.103/Libertempo_Dev/hr/hr_index.php?session=phpconges4929d7b9a41349a017aa4a9540403dec&onglet=traitement_demandes

**Comment by ptitpopey** [comment]
En passant à la version DEV toujours le problème en plus le RH ne reçoit plus la notification de demande de congé de la part d'un utilisateur

**Comment by Prytoegrian** [comment]
Oui, clairement ça va nous aider. Par contre j'ai pris sur moins de supprimer les données, il y a des données perso. J'ai le fichier en cas de besoin

**Comment by Prytoegrian** [comment]
Il y a bien un refus de congés ++ un accept congés. Laisse-nous le temps d'étudier tout ça et ça devrait rouler :-)

**Comment by Prytoegrian** [comment]
> En plus le RH ne reçoit plus la notification de demande de congé de la part d'un utilisateur

Ça c'est de ma faute, fais ça et ça corrigera

```diff
diff --git a/utilisateur/Fonctions.php b/utilisateur/Fonctions.php
index 85fabfc..ab3931c 100644
--- a/utilisateur/Fonctions.php
+++ b/utilisateur/Fonctions.php
@@ -113,7 +113,7 @@ class Fonctions
    $return .= schars( _('form_modif_ok') ) . ' !<br><br>.';
    //envoi d'un mail d'alerte au responsable (si demandé dans config de php_conges)
    if($_SESSION['config']['mail_new_demande_alerte_resp']){
-       if(in_array(get_type_abs($new_type, $DEBUG), array('absences'))) {
+      if(in_array(\utilisateur\Fonctions:get_type_abs($new_type, $DEBUG), array('absences'))) {
            alerte_mail($_SESSION['userlogin'], ":responsable:", $periode_num, "new_absence", $DEBUG);
        } else {
            alerte_mail($_SESSION['userlogin'], ":responsable:", $periode_num, "new_demande", $DEBUG);
```

**Comment by Prytoegrian** [comment]
Trouvé ! Mais je vais te demander un poil de patience, je présenterai tout ça demain

**Comment by wouldsmina** [comment]
oui mais la j'ai envie de savoir! :smile: 
Merci @Prytoegrian

**Comment by ptitpopey** [comment]
Voici le code corrigé mais ce n'est pas mieux.
Erreur : PHP Parse error:  syntax error, unexpected ':' in /var/www/Libertempo_Dev/utilisateur/Fonctions.php on line 116, referer: http://172.20.100.103/Libertempo_Dev/utilisateur/user_index.php?session=phpconges30651a22a5bde340af53c5604006b415&onglet=nouvelle_absence
`
// verifie les parametre de la nouvelle demande :si ok : enregistre la demande dans table conges_periode
    public static function new_demande($new_debut, $new_demi_jour_deb, $new_fin, $new_demi_jour_fin, $new_nb_jours, $new_comment, $new_type, $DEBUG=FALSE)
    {
        //conversion des dates
        $new_debut = convert_date($new_debut);
        $new_fin = convert_date($new_fin);

        $PHP_SELF=$_SERVER['PHP_SELF'];
        $session=session_id();

        // verif validitÃ© des valeurs saisies
        $valid = verif_saisie_new_demande($new_debut, $new_demi_jour_deb, $new_fin, $new_demi_jour_fin, $new_nb_jours, $new_comment);

        // verifie que le solde de conges sera encore positif aprÃ¨s validation
        if( $_SESSION['config']['solde_toujours_positif'] ) {
            $valid = $valid && verif_solde_user($_SESSION['userlogin'], $new_type, $new_nb_jours, $DEBUG);
        }

        if( $valid ) {

        if( in_array(\utilisateur\Fonctions::get_type_abs($new_type, $DEBUG) , array('conges','conges_exceptionnels') ) ) {
                        $resp_du_user = get_tab_resp_du_user($_SESSION['userlogin']);
                        if (array_key_exists('conges', $resp_du_user)||empty($resp_du_user)) {
                                $new_etat = 'ok' ;
                                soustrait_solde_et_reliquat_user($_SESSION['userlogin'], "", $new_nb_jours, $new_type, $new_debut, $new_demi_jour_deb, $new_fin, $new_demi_jour_fin, $DEBUG);
                        } else {
                                $new_etat = 'demande' ;
                        }
                } else {
                        $new_etat = 'ok' ;
                }

            $new_comment = addslashes($new_comment);

            $periode_num = insert_dans_periode($_SESSION['userlogin'], $new_debut, $new_demi_jour_deb, $new_fin, $new_demi_jour_fin, $new_nb_jours, $new_comment, $new_type, $new_etat, 0, $DEBUG);

            if ( $periode_num != 0 ) {
                echo schars( _('form_modif_ok') ).' !<br><br>'."\n";
                //envoi d'un mail d'alerte au responsable (si demandÃ© dans config de php_conges)
                if($_SESSION['config']['mail_new_demande_alerte_resp']){
                    if(in_array(\utilisateur\Fonctions:get_type_abs($new_type, $DEBUG), array('absences'))) {
                    #if(in_array(get_type_abs($new_type, $DEBUG), array('absences'))) {
                        alerte_mail($_SESSION['userlogin'], ":responsable:", $periode_num, "new_absence", $DEBUG);
                    } else {
                        alerte_mail($_SESSION['userlogin'], ":responsable:", $periode_num, "new_demande", $DEBUG);
                    }
                }
            }
            else
                echo schars( _('form_modif_not_ok') ).' !<br><br>'."\n";
        }
        else {
            echo schars( _('resp_traite_user_valeurs_not_ok') ).' !<br><br>'."\n";
        }

        echo "<a class=\"btn\" href=\"$PHP_SELF?session=$session\">". _('form_retour') ."</a>\n";
    }
`

**Comment by Prytoegrian** [comment]
Désolé, j'ai manqué d'inattention. C'est pas mieux même avec le correctif :: ? Bizarre. 

Concernant le problème principal, j'avais pas pour objectif de teaser comme ça mais je suis malade donc j'ai pas pu vous informer ce matin. 

https://github.com/wouldsmina/Libertempo/blob/9c918f73726a71b5266fa4c450d1950efec94989/hr/Fonctions.php#L220 ce if qui est relatif au mail de refus est une duplication de celui qui est vraiment dans le Not_ok quelques lignes plus haut, je pense que c'est ça la source du Bug. 

Tiens nous au courant. Sur ce, je retourne me pieuter ^^

**Comment by ptitpopey** [comment]
Hello,

Après un peu de debug, voici la correction pour le problème de notification de mail à l'utilisateur refus puis accepter : 

hr/Fonctions.php
ligne 221 à ligne 223 à supprimer 
`
 210         if( $DEBUG ) {
 211             $return .= '<form action="' . $PHP_SELF  . '?sesssion=' . $session . '&onglet=traitement_demande" method="POST">';
 212             $return .= '<input type="hidden" name="session" value="' . $session . '">';
 213             $return .= '<input class="btn" type="submit" value="' . _('form_ok') . '">';
 214             $return .= '</form>';
 215         } else {
 216             $return .= _('form_modif_ok') . '<br><br>';
 217             /* APPEL D'UNE AUTRE PAGE au bout d'une tempo de 2secondes */
 218             $return .= '<META HTTP-EQUIV=REFRESH CONTENT="2; URL=' . $PHP_SELF . '?session=' . $session . '&onglet=traitement_demandes">';
 219         }
 220         //envoi d'un mail d'alerte au user (si demandÃ© dans config de php_conges)
 221         //if($_SESSION['config']['mail_refus_conges_alerte_user']) {
 222         //    alerte_mail($_SESSION['userlogin'], $user_login, $numero_int, "refus_conges", $DEBUG);
 223         //}
 224         return $return;`


Ensuite concernant le problème de notification du RH lorsque l'utilisateur soumet une demande
Il manquait un : pour la ligne 116
utilisateur/Fonctions.php
` 
 if(in_array(\utilisateur\Fonctions::get_type_abs($new_type, $DEBUG) , array('absences'))){

112             if ( $periode_num != 0 ) {
 113                 echo schars( _('form_modif_ok') ).' !<br><br>'."\n";
 114                 //envoi d'un mail d'alerte au responsable (si demandÃ© dans config de php_conges)
 115                 if($_SESSION['config']['mail_new_demande_alerte_resp']){
 116                     if(in_array(\utilisateur\Fonctions::get_type_abs($new_type, $DEBUG) , array('absences'))){
 117                         alerte_mail($_SESSION['userlogin'], ":responsable:", $periode_num, "new_absence", $DEBUG);
 118                     }
 119                     else{
 120                         alerte_mail($_SESSION['userlogin'], ":responsable:", $periode_num, "new_demande", $DEBUG);
 121                     }
 122                 }
 123             }`


Pour finir une petite évolution afin d'afficher le motif du refus dans le mail de notification à l'utilisateur : 
fonctions_conges.php
`
1015         $select_abs = 'SELECT conges_periode.p_date_deb,conges_periode.p_demi_jour_deb,conges_periode.p_date_fin,conges_periode.p_demi_jour_fin,conges_periode.p_nb_jours,conges_periode.p_commentaire,p_motif     _refus,conges_type_absence.ta_libelle
1016                 FROM conges_periode, conges_type_absence WHERE conges_periode.p_num='.$num_periode.' AND conges_periode.p_type = conges_type_absence.ta_id;';

1027         $sql_commentaire = $rec_abs["p_commentaire"];
1028         $sql_motif_refus = $rec_abs["p_motif_refus"];
1029         $sql_type_absence = $rec_abs["ta_libelle"];


1049     $sujet = $_SESSION['config'][$key1];
1050     $contenu = $_SESSION['config'][$key2];
1051     $contenu = str_replace("__URL_ACCUEIL_CONGES__", $_SESSION['config']['URL_ACCUEIL_CONGES'], $contenu);
1052     $contenu = str_replace("__SENDER_NAME__", $mail_sender_name, $contenu);
1053     $contenu = str_replace("__DESTINATION_NAME__", $mail_dest_name, $contenu);
1054     $contenu = str_replace("__NB_OF_DAY__", $sql_nb_jours, $contenu);
1055     $contenu = str_replace("__DATE_DEBUT__", $sql_date_deb, $contenu);
1056     $contenu = str_replace("__DATE_FIN__", $sql_date_fin, $contenu);
1057     $contenu = str_replace("__RETOUR_LIGNE__", "\r\n", $contenu);
1058     $contenu = str_replace("__COMMENT__", $sql_commentaire, $contenu);
1059     $contenu = str_replace("__MOTIF_REFUS__", $sql_motif_refus, $contenu);
1060     $contenu = str_replace("__TYPE_ABSENCE__", $sql_type_absence, $contenu);
`

Contenu du mail : 
Motif du refus : __MOTIF_REFUS__
__MOTIF_REFUS__ sera automatiquement remplacé par le motif de l'absence concernée.

**Comment by ptitpopey** [comment]
Ensuite concernant le problème de notification du RH lorsque l'utilisateur soumet une demande
Il manquait un : pour la ligne 116
utilisateur/Fonctions.php
` 
 if(in_array(\utilisateur\Fonctions::get_type_abs($new_type, $DEBUG) , array('absences'))){

112             if ( $periode_num != 0 ) {
 113                 echo schars( _('form_modif_ok') ).' !<br><br>'."\n";
 114                 //envoi d'un mail d'alerte au responsable (si demandÃ© dans config de php_conges)
 115                 if($_SESSION['config']['mail_new_demande_alerte_resp']){
 116                     if(in_array(\utilisateur\Fonctions::get_type_abs($new_type, $DEBUG) , array('absences'))){
 117                         alerte_mail($_SESSION['userlogin'], ":responsable:", $periode_num, "new_absence", $DEBUG);
 118                     }
 119                     else{
 120                         alerte_mail($_SESSION['userlogin'], ":responsable:", $periode_num, "new_demande", $DEBUG);
 121                     }
 122                 }
 123             }`

**Comment by ptitpopey** [comment]
Pour finir une petite évolution afin d'afficher le motif du refus dans le mail de notification à l'utilisateur : 
fonctions_conges.php
`
1015         $select_abs = 'SELECT conges_periode.p_date_deb,conges_periode.p_demi_jour_deb,conges_periode.p_date_fin,conges_periode.p_demi_jour_fin,conges_periode.p_nb_jours,conges_periode.p_commentaire,p_motif     _refus,conges_type_absence.ta_libelle
1016                 FROM conges_periode, conges_type_absence WHERE conges_periode.p_num='.$num_periode.' AND conges_periode.p_type = conges_type_absence.ta_id;';

1027         $sql_commentaire = $rec_abs["p_commentaire"];
1028         $sql_motif_refus = $rec_abs["p_motif_refus"];
1029         $sql_type_absence = $rec_abs["ta_libelle"];


1049     $sujet = $_SESSION['config'][$key1];
1050     $contenu = $_SESSION['config'][$key2];
1051     $contenu = str_replace("__URL_ACCUEIL_CONGES__", $_SESSION['config']['URL_ACCUEIL_CONGES'], $contenu);
1052     $contenu = str_replace("__SENDER_NAME__", $mail_sender_name, $contenu);
1053     $contenu = str_replace("__DESTINATION_NAME__", $mail_dest_name, $contenu);
1054     $contenu = str_replace("__NB_OF_DAY__", $sql_nb_jours, $contenu);
1055     $contenu = str_replace("__DATE_DEBUT__", $sql_date_deb, $contenu);
1056     $contenu = str_replace("__DATE_FIN__", $sql_date_fin, $contenu);
1057     $contenu = str_replace("__RETOUR_LIGNE__", "\r\n", $contenu);
1058     $contenu = str_replace("__COMMENT__", $sql_commentaire, $contenu);
1059     $contenu = str_replace("__MOTIF_REFUS__", $sql_motif_refus, $contenu);
1060     $contenu = str_replace("__TYPE_ABSENCE__", $sql_type_absence, $contenu);`

Contenu du mail : 
Motif du refus : __MOTIF_REFUS__
__MOTIF_REFUS__ sera automatiquement remplacé par le motif de l'absence concernée.

**Comment by ptitpopey** [comment]
Désolé pour la mise en forme je n'y arrive pas :-)

**Comment by wouldsmina** [comment]
Merci @ptitpopey! L'important c'est que ton bug soit corrigé...

Je fais quelques test avant de corriger sur develop...

**Comment by wouldsmina** [comment]
> hr/Fonctions.php
ligne 221 à ligne 223 à supprimer 

La c'est sur, ça n'a rien a faire la! et du coup je me demande pourquoi ça marche ailleurs!! :smile: 

@Prytoegrian  ligne 116 fichier utilisateur/fonction.php, as tu corrigé? sinon je le fais de suite...

**Comment by Prytoegrian** [comment]
Je l'ai corrigé dans ma branche. Je suis quasiment à la fin, la PR devrait arriver prochainement.

**Comment by wouldsmina** [comment]
ok. Et pour hr/fonction.php? ça ressemble à un raté de copier/coller, dans responsable/fonction.php il n'y a rien...

**Comment by wouldsmina** [comment]
corrigé 7915893531ca0967283da9f418d125ef490d733a
