### ISSUE TITLE
Mode Calendrier

### ISSUE THREAD

**Issue by ptitpopey** [wouldsmina/Libertempo#104]
Depuis le passage à la version 1.7.1, le mode calendrier n'est plus accessible depuis le bouton MODE.
![afa4f5cc-cc2b-11e5-8a9f-abf2224e6dd4](https://cloud.githubusercontent.com/assets/14994180/12854165/5c7d5cba-cc38-11e5-9a16-00f775b7aa1f.png)

Ca serait bien de le remettre.

**Comment by Prytoegrian** [comment]
@wouldsmina pourra confirmer que c'est pas une action volontaire ; si c'est le cas, un peu de patience... C'est un bug comme il y en a certainement d'autres, cette version n'étant pas censée être utilisée en mode production. Normalement elle sort à peine en beta en fin de mois.

**Comment by ptitpopey** [comment]
j'ai pas reussi à reproduire le cas sur une install 1.7.0 même sur la démo. Pourtant je suis sur que j'ai vu ce choix dans la liste des modes. Ou alors j'étais tropo fatigué hier soir.

En tout cas ca peut être évolution.

**Comment by wouldsmina** [comment]
Euh! Le calendrier n'a jamais été accessible depuis la liste déroulante «mode». Par contre lorsque tu est sur le calendrier, tu as le mot calendrier qui s'affiche à côté de mode. C'est sûrement ça qui t'as induit en erreur...

**Comment by wouldsmina** [comment]
Prend soin de retirer les données personnels avant de poster (sauf si ce sont des données fictives).

**Comment by ptitpopey** [comment]
Est-il possible de prendre en compte pour une prochaine évolution. Je pense que cela améliore la qualité de navigation.

Après c'est que mon avis.

**Comment by Prytoegrian** [comment]
Tu cherches à faire améliorer l'expérience utilisateur, tu m'auras donc toujours à tes côtés.
Par contre, nous sommes en train de peaufiner une nouvelle apparence pour libertempo avec @wouldsmina (c'est très récent et nous n'en avons pas encore parlé publiquement, à notre décharge). 

Je crains donc qu'on envoie un mauvais message en terme de communication si nous déplaçons une partie du menu une première fois, pour enfin lui donner sa place définitive, sans compter les potentiels pertes de repères dans l'interaction avec le logiciel.

On va laisser se décanter tout ça, mais sois en sûr, on tiendra toujours compte de ton avis, dans le but d'améliorer la qualité de la navigation.
