### ISSUE TITLE
Appel css fonts.googleapis.com en http dans le template

### ISSUE THREAD

**Issue by Shadok** [wouldsmina/Libertempo#107]
L'appel du css de la fonte est fait comme ceci dans le template :
`<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700" type="text/css" />`

Est-il possible de le changer comme ceci de façon à ce qu'il soit appelé avec le même protocole que la page (https ou https) ?
`<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400,700" type="text/css" />`

Cela concerne :
./template/reboot/error_header.php
./template/reboot/menu_header.php
./template/reboot/login_header.php
./template/reboot/popup_header.php

**Comment by wouldsmina** [comment]
Suite au ticket #100 tout sera géré localement sur la prochaine version.
