### ISSUE TITLE
Processus d'installation pas très clair

### ISSUE THREAD

**Issue by bbalet** [wouldsmina/Libertempo#111]
Sur Wamp/PHP 5.6 et la dernière version officielle, lorsqu'on va à la racine (e.g. http://localhost/Libertempo/) sans rien avoir installé on obtient :

    connexion a la database impossible, consultez le fichier INSTALL.txt !

Mais aucun fichier INSTALL.txt... Pkoi pas un lien vers le répertoire de setup ?

Ensuite, en essayant http://localhost/Libertempo/install/

On obtient :

   Choisissez votre langue :
   Choose your language :

Avec une liste déroulante contenant les codes BCP, pas très user-friendly.

IMHO, comme vous êtes un projet franco-français vous devriez tout mettre en français 'database', 'INSTALL', etc.

En outre, ces erreurs apparaissant tout au long des pages de setup:

    Notice: Undefined index: config in C:\wamp\www\Libertempo\include\plugins.php on line 8
    Warning: in_array() expects parameter 2 to be array, null given in C:\wamp\www\Libertempo\include\plugins.php on line 29

**Comment by wouldsmina** [comment]
C'est corrigé sur la branche develop.

**Comment by wouldsmina** [comment]
> IMHO, comme vous êtes un projet franco-français vous devriez tout mettre en français 'database', 'INSTALL', etc.

Notre projet prend en compte certaines des particularités françaises, c'est vrai, mais il est tout de même utilisable dans d'autres pays/langues. je corrige, bien sur, ce petit oubli de traduction...

**Comment by bbalet** [comment]
Côté langue, ça va tant que vous restez dans du latin-1 (fr, es, en, ge, nl, etc.), mais ta base de données n'est pas en UTF-8. Côté application, pas sûr que tous les scripts Unicode passent sans encombre. Si tu veux vraiment tester, il faudrait que tu injectes des chaînes en arabe (droite à gauche) et dans l'une des langues utilisant le script Brahmic (langues de l'Inde, Thaï, Khmer, Lao, etc.) à la fois en bourrant un fichier de traduction et en testant les formulaires. Une fois, bien sûr, que tu auras patché ta base.

Côté fonctionnel, ça ne passera pas dans d'autres pays à cause d'un manque de souplesse dans la saisie de certains champs. Je suis bénévole dans une ONG qui bosse dans quatre pays (France, Cambodge, Philippines et Vietnam), je peux te dire que partir du cadre législatif français est un handicap. Il y a aussi les usages hors EU où les droits à congé sont acquis au mois le mois, etc.

Après l’hyper-spécialisation sur le marché français, ça peut être différenciant et un avantage. Il y a tellement à faire, rien qu'en adaptant toutes les règles de métropole.

Vous n'avez pas un forum ou un groupe où échanger ? Parce qu'avec Github on est rapidement à l'étroit. Et je ne veux surtout pas que ce genre d'échanges soit pris pour ce qu'il n'est pas...

**Comment by wouldsmina** [comment]
Non, désolé pas de forum. On peut discuter sur irc.tuxfamily.org salon #Libertempo quasiment tous les soirs...
