### ISSUE TITLE
SUGGESTION: Supprimer la configuration de l'URL d'installation

### ISSUE THREAD

**Issue by bbalet** [wouldsmina/Libertempo#113]
En lien avec la #101 ce n'est pas évident et - techniquement - pas nécessaire de renseigner l'URL d'installation alors qu'elle peut être déduite par un code PHP simple (variable $_SERVER et segments en prenant en compte si accès via HTTP ou HTTPS, etc. il y a plein de code déjà fait sur le net).

Il y a pas mal d'impact de cette mauvaise pratique, par ex. http://localhost/Libertempo/index.php?error=session-invalid

**Comment by bbalet** [comment]
Ce qui est ballot, c'est que le lien de déconnexion n'est pas une URL relative et que si on a oublié de la configurer, on est envoyé dans les choux. Alors que la plupart des URL fonctionnent, ce n'est pas très cohérent.

**Comment by wouldsmina** [comment]
Après quelques tests, je préfère garder la configuration de l'url d'accueil. 
Et session-invalid sera affiché dans la page d'authentification.
