### ISSUE TITLE
SUGGESTION: Créer un logo et en faire un favicon

### ISSUE THREAD

**Issue by bbalet** [wouldsmina/Libertempo#114]
Le favicon serait très pratique pour distinguer Libertempo parmi plusieurs onglets ouvert dans un navigateur au lieu de la favicon par défaut du serveur web.

**Comment by Shadok** [comment]
Si on me file un logo, je peux en faire un favicon :)
(sinon je mets deux lettres LT en diagonale et hop)

**Comment by wouldsmina** [comment]
Merci @Shadok, le logo est déjà pret. J'ai simplement pas encore eu le temps de l'intégrer dans LT. On en parle sur irc tout a l'heure ;)

**Comment by Shadok** [comment]
PR effectuée.

**Comment by Shadok** [comment]
PR #170 en remplacement de la #167.

**Comment by Prytoegrian** [comment]
Du coup on close non ? (À moins qu'on considère qu'il manque le logo dans l'application)

**Comment by wouldsmina** [comment]
on close
