### ISSUE TITLE
Message d'alerte dans Administration/Backup relatif à la configuration LDAP

### ISSUE THREAD

**Issue by bbalet** [wouldsmina/Libertempo#115]
Depuis l'URL http://localhost/Libertempo//admin/admin_db_sauve.php, j'obtiens les message d'erreur suivants:

    Warning: include(../cfg/config_ldap.php): failed to open stream: No such file or directory in C:\wamp\www\Libertempo\admin\admin_db_sauve.php on line 33

    Warning: include(): Failed opening '../cfg/config_ldap.php' for inclusion (include_path='.;C:\php\pear') in C:\wamp\www\Libertempo\admin\admin_db_sauve.php on line 33

Messages que l'on retrouve dans le fichier SQL produit:

    <br />
    <b>Warning</b>:  include(../cfg/config_ldap.php): failed to open stream: No such file or directory in <b>C:\wamp\www\Libertempo\admin\admin_db_sauve.php</b> on line <b>33</b><br />
    <br />
    <b>Warning</b>:  include(): Failed opening '../cfg/config_ldap.php' for inclusion (include_path='.;C:\php\pear') in <b>C:\wamp\www\Libertempo\admin\admin_db_sauve.php</b> on line <b>33</b><br />

Effectivement, je n'utilise pas LDAP donc dans le répertoire, j'ai seulement

    config_ldap_new.php

et en faisant une copie, l'erreur disparaît.

Cependant, ce n'est pas très simple à comprendre pour un utilisateur avec un bagage technique limité et je pense qu'un fichier vide (i.e. non configuré) ou un test de présence serait top, car jusque-là aucun message d'erreur similaire n'était affiché.

Et d'ailleurs pourquoi la configuration LDAP interviendrait-elle ici ?

**Comment by wouldsmina** [comment]
en effet, le LDAP n'intervient pas pour la sauvegarde.
