### ISSUE TITLE
La langue sélectionnée dans l'écran de login n'est pas prise en compte

### ISSUE THREAD

**Issue by bbalet** [wouldsmina/Libertempo#116]
Sur la dernière version officielle, avec différents navigateurs (IE11, Chrome, FF 44, etc.),
la langue sélectionnée dans l'écran de login n'est pas prise en compte et reste en Français.

Serait-ce la locale du serveur qui primerait? Le cas échéant, pourquoi avoir le choix à la connexion?

**Comment by wouldsmina** [comment]
Si la locale n'est pas installé sur le serveur, en effet, ce n'est pas pris en compte. c'est une contrainte de gettext.
