### ISSUE TITLE
Erreur lors de la modification d'un utilisateur

### ISSUE THREAD

**Issue by bbalet** [wouldsmina/Libertempo#119]
Lorsque je tente de modifier un utilisateur, j'obtiens plusieurs erreurs (note cet utilisateur n'avait pas encore de responsable, aucune autre saisie depuis sa création):

    Notice: Undefined index: enfant malade in admin_modif_user.php on line 297
    Notice: Undefined index: enfant malade in admin_modif_user.php on line 298
    Notice: Undefined index: enfant malade in admin_modif_user.php on line 304
    Notice: Undefined index: enfant malade in admin_modif_user.php on line 305
    Notice: Undefined index: maladie in admin_modif_user.php on line 297
    Notice: Undefined index: maladie in admin_modif_user.php on line 298
    Notice: Undefined index: maladie in admin_modif_user.php on line 304
    Notice: Undefined index: maladie in admin_modif_user.php on line 305

**Comment by bbalet** [comment]
Précision: l'erreur se produit lors de la modification d'un utilisateur n'ayant pas les droits "responsable" (ni les autres droits).

**Comment by wouldsmina** [comment]
Bonjour,
Merci pour ton aide. As tu effectué ces tests sur la branche develop? Elle corrige pas mal de bugs (et doit certainement en apporter quelques autres). De plus nous allons bientôt la proposer en beta...

**Comment by bbalet** [comment]
@wouldsmina Non, en fait je regarde votre version officielle que je compare à mon projet pour voir ce qui manquerait chez moi. Tant qu'à faire je vous fait part de mes observations, mais je ne compte pas m'investir plus que ça dans votre développement.

Pour revenir au bug, une erreur similaire apparaît dans le mode RH (utilisateur + responsable + RH), dans le mode RH puis onglets:
* Page Principale.
* Ajout de congés.
* clôture/début d'exercice.

On obtient les mêmes erreurs.

**Comment by wouldsmina** [comment]
Ce bug a été corrigé sur develop...
