### ISSUE TITLE
Mode RH, messages de debug?

### ISSUE THREAD

**Issue by bbalet** [wouldsmina/Libertempo#122]
Dans le mode RH puis onglets:
* Page Principale.
* clôture/début d'exercice.

On a des messages affichés qui semblent être des informations de debug laissées en dur dans le code, par exemple :

    list_groupes_double_valid = 

    Afficher Édition Papiertotototo100%000000Afficher Édition Papier

    toto 	toto 	100% 	0 (0) 	0 (0) 	0 (0) 	0 (0) 	

à moins que ce soit autre chose, mais ça fait pas sérieux.

**Comment by wouldsmina** [comment]
Déjà corrigé sur develop.
