### ISSUE TITLE
Dossier dump inexistant et contenu du mail d'alerte manquant

### ISSUE THREAD

**Issue by Shadok** [wouldsmina/Libertempo#123]
Sur la dernière stable de phpconges (1.7), je viens d'avoir un mail d'erreur ayant en sujet "Errors php-conges" et un corps vide.

Je trouve une erreur dans les logs apache, correspondant à la date et heure du mail, indiquant ceci :

```
PHP Warning:  fopen(../dump/sql_1455542847.dump): failed to open stream: Aucun fichier ou dossier de ce type in /conges/include/sql.class.php on line 144, referer: http://conges.domaine.tld/responsable/resp_index.php?...
```

J'ai donc créé manuellement le dossier dump.
Pourtant, l'utilisateur sous lequel apache & php tournent est bien propriétaire du dossier conges et a tous les droits dessus.

**Comment by wouldsmina** [comment]
J'ai aussi rencontré des erreurs SQL, en créant le dossier dump à la racine du site, j'ai eu le log...
est ce que tu as trouvé la source du bug sql?

**Comment by Shadok** [comment]
Du bug sql non, je ne me souviens pas en avoir eu.
Par contre, pour l'erreur du dossier dump, ci-dessus, c'est tout simplement qu'il n'est pas dans git ni dans l'archive, alors qu'il devrait y être, vu que le chemin est déclaré dans le code : 
./define.php:   define('DUMP_PATH', ROOT_PATH . 'dump/');

**Comment by Prytoegrian** [comment]
Un répertoire seul ne peut pas être dans git, et de ce fait il est impossible de nous le passer de repo en repo. Par contre, un petit `is_dir` + `mkdir` entre l'erreur et sa tentative d'écriture et le tour est joué !

**Comment by Shadok** [comment]
Oui mais il suffit de mettre un fichier .htaccess dedans en "deny from all" / "require all deny", ce qui est de toute façon nécessaire, question de sécurité, et le tour est joué :)

**Comment by Prytoegrian** [comment]
Je suis pas super fan de passer par .htaccess, t'es quand même dans le source de ton serveur alors que tu ne devrais pas y être. Dans l'idéal, on devrait être en dehors des sources pour être tip-top niveau sécurité (et pour ne pas mélanger les sources avec des méta) ; c'est le même problème qu'avec la configuration logicielle. Tu pourrais me rétorquer que j'ai fais exactement le contraire de ce que je propose avec le [module de débug](https://github.com/wouldsmina/Libertempo/pull/106) et tu aurais bien raison :-p …

**Comment by Shadok** [comment]
Je ne vois pas le problème.
Tu as un dossier dump à la racine du site, et potentiellement des fichiers sql dedans, il faut bien en protéger l'accès.

**Comment by Prytoegrian** [comment]
Je viens de le dire :cry:  

![https://sarahcradit.files.wordpress.com/2013/04/sadpanda.jpg](https://sarahcradit.files.wordpress.com/2013/04/sadpanda.jpg)

**Comment by Shadok** [comment]
Elle était pas claire ton argumentation :o
En gros tu voudrais que ça se fasse en dehors du dossier php_conges.
Ok, mais ça rajoute une complexité à l'installation mais pourquoi pas ? D'autres scripts, comme vtiger ou sugarcrm font ça avec un htaccess (wordpress idem) et ça ne dérange pas.

**Comment by Prytoegrian** [comment]
*[On est d'accord que c'est du plus, complètement en dehors de la résolution du bug hein]*

Ok, c'est un raté de communication, j'étais au boulot et j'ai pas pris le temps de développer ; je vais tenter d'être plus clair : 

Tel que je le vois, dans une architecture idéale, il ne faudrait rendre visible à Apache ( / N'importe quel serveur web) que le minimum : le Front Controller et les Assets. C'est tout. Le reste des fichiers, étant appelés par la résolution des dépendances, devraient être ailleurs pour éviter d'être appelés directement. Dans la même veine mais avec une contrainte plus forte encore, je mettrais tout ce qui ne touche pas à l'application elle-même (donc la config, les dump et les rapports de debug, tout ce que j'appelle « *méta de l'applicatif* ») dans un répertoire à part, accessible à `www-data` pour qu'il y puisse écrire / lire mais inaccessible aux yeux du `DocumentRoot` du Serveur Web, et de `git`. 

*[Après réflexion, on peut laisser des exemples de meta dans le source à la condition que le `DocumentRoot` soit un sous-répertoire de `/` de l'application et que le `.gitignore` soit bien rempli, là ça m'irait, ce serait même la meilleure des options].*

La solution que tu proposes est par essence liée à Apache, ce qui va nous obliger à avoir un fichier de filtrage par serveur web, avec le risque d'en oublier. En plus de ça, en tant que dev, `git` va nous notifier en permanence des fichiers modifiés (je pense à la config notamment) dans le répertoire libertempo vu qu'on a forcément des divergences entre l'environnement des utilisateurs, la prod, et notre environnement à nous, le dev. Ça engendre forcément de la pollution visuelle (car ce n'est pas vraiment des changements, et ça nous rend suspicieux) et des bugs potentiels (on est pas à l'abri d'un commit rapide qui embarque ces changements). De plus, quand on doit faire de vrais changements dans ces fichiers, c'est la cata.
Enfin, pour le lecteur du code, un répertoire vide (ou presque) est incompréhensible et suscite l'interrogation.


On ne devrait jamais confier la sécurité à l'utilisateur seul, c'est à l'appli de gérer sa propre sécurité. Autrement dit, ça va nous obliger à vérifier l'existence du répertoire (tout à fait normal), mais aussi de tous les fichiers de restriction, car on est pas à l'abri que l'utilisateur supprime ces fichiers.
Tu écris donc du code qui n'a rien à voir avec l'appli pour palier une faille dans la configuration ; lui aussi est une forme de pollution visuelle. Associé au fait que tout code écrit est de la maintenance à faire.

Bien sûr, il n'y a jamais de bonnes réponses tandis que les autres seraient mauvaises, donc je suis prêt à discuter avec plaisir, mais c'est comme ça que j'imagine une appli bien structurée.

Je ne me permettrais pas de discuter de sugar ou de vtiger car je ne les connais pas, mais je ne pense pas que wordpress soit un exemple à suivre en terme d'architecture et de sécurité.


Là où je suis pas d'accord c'est lorsque tu dis que ça va rajouter une complexité à l'installation, mais là encore je suis prêt à en discuter.

*J'espère ne pas être trop sec, ce n'est pas mon intention. Nous débattons pour améliorer l'appli et c'est le moindre des respects pour toi que d'avoir une pensée organisée*

**Comment by Shadok** [comment]
Oui, je vois ce que tu veux faire, je le fais sur certains scripts.
En gros, tu as un dossier www dans le script et c'est là que pointe le virtualhost, tous les dossiers parents n'étant pas accessibles en ligne, mais le serveur web a bien les droits dessus.

**Comment by Shadok** [comment]
7 mois plus tard, la réflexion a été longue :D

**Comment by Shadok** [comment]
Par contre, tu as utilisé "deny from all".
A savoir qu'à partir d'apache 2.4 (et donc d'Ubuntu 14.04), il faut utiliser "require all deny" si tu ne veux pas finir en erreur 500.
Je ne suis pas certain que continuer à se baser sur apache 2.2 soit une bonne idée à l'heure actuelle.

**Comment by Prytoegrian** [comment]
> 7 mois plus tard, la réflexion a été longue :D

T'es vache là.

**Comment by wouldsmina** [comment]
> 7 mois plus tard, la réflexion a été longue :D

on t'attendait pour s'en occuper! :p

**Comment by Shadok** [comment]
Bon sinon, plus sérieusement, pour le .htaccess, faites plutôt ça :
# Apache 2.2
<IfModule !mod_authz_core.c>
    deny from all
</IfModule>

# Apache 2.4
<IfModule mod_authz_core.c>
    Require all denied
</IfModule>

**Comment by Prytoegrian** [comment]
Je t'invite à mettre cette critique dans la PR https://github.com/wouldsmina/Libertempo/pull/237, en tant que remarque de review afin d'avoir la traçabilité des diff. Tu peux même mettre un veto au merge tant que tes remarques n'ont pas été prises en compte. Par contre il faut être collaborateur je crois, mais @wouldsmina peut te le faire rapidement si le cœur t'en dit (et que le cœur lui en dit).
