### ISSUE TITLE
Gérer les congés en heures

### ISSUE THREAD

**Issue by bouil** [wouldsmina/Libertempo#127]
Nous avons essayé d'utiliser Libertempo pour nos congés.

Nous nous sommes heurtés au problème d'un salarié en temps partiel : il ne travaille pas 2 après-midis par semaine, et termine le vendredi à 15h au lieu de 17h. Il est donc nécessaire de gérer son temps de travail/congé en heures. Un certain nombre d'heures de congés lui sont alloués par an, et les heures de congés sont décomptés selon le planning de travail.

Est ce qu'il est envisageable d'avoir une gestion des congés en heures ? Serait-ce complexe à patcher ?

PS: nous sommes au Luxembourg, et il est très courant ici de gérer les congés en heures. Cela permet de ne pas se prendre la tête quand les salariés changent leur durée de travail hebdomadaire (temps complet à temps partiel, changement du quota de partiel).

**Comment by Shadok** [comment]
A mon avis, ce n'est pas gagné, Libertempo étant une solution adaptée pour la France, cela nécessiterait pas mal de modifications pour passer sur une gestion de congés en heures.
Après, tu pourrais contourner le problème en ajoutant des absences de 2h à ton salarié.

**Comment by norisknimo** [comment]
Bonjour, 
j'ai aussi le même problème, chez nous il est possible de poser des RTT en heure, mais sur l'application impossible de ne prendre qu'une heure de RTT, seulement une demie-journée....
pas de solution ?

**Comment by wouldsmina** [comment]
Libertempo ne gère et ne gérera jamais tous les congés par heure. 

On pourrait faire un plugin qui transformerait, au besoin, un jour en heure, mais le dépôt d'une heure de congés ne serait de toute façon pas traité dans libertempo...

**Comment by wouldsmina** [comment]
Re,

La demande de gestion des heures ne cesse d'augmenter, nous étudions donc une solution ne remettant pas en cause le fonctionnement actuel de LT...

A+

**Comment by wouldsmina** [comment]
en préparation dans develop.

**Comment by weshpoupou** [comment]
Bonjour
Nous sommes aussi intéressé par la gestion des congés en heures pour notre collectivité.
Cette fonctionnalité est-elle prévue dans un prochain développement ?
merci d'avance

**Comment by prytoegrian** [comment]
Bonjour,

d'après les docs que nous avons, il n'est pas possible dans le droit français de décompter les congés en heures. La fonctionnalité qui s'en rapproche que nous avons développée est la gestion des heures de repos / additionnelles (un mix entre les congés en heure et les heures supp donc). Elles n'ont par contre pas de compteur et sont à gérer manuellement. Cette fonctionnalité est disponible depuis LT 1.9 (avec l'activation de l'option admin « Gestion des heures »).
