### ISSUE TITLE
Active directory V1.8

### ISSUE THREAD

**Issue by newcaledo** [wouldsmina/Libertempo#130]
Bonjour,

après avoir renseigné les paramètres LDAP pour me connecter à un AC 2003 je n'arrive pas à avoir la bare de liste déroulant pour ajouter un nouvelle utilisateur.

savez vous si il y a une soucis également avec cette version?

Cordialement

**Comment by wouldsmina** [comment]
Bonjour,

sur quel version, 1.7 ou 1.8beta?

**Comment by wouldsmina** [comment]
C'est dans le titre! Ce doit être a cause du paramètre ajouté suite au ticket #73. 

MS2003 n'étant plus supporté par MS on ne va pas corriger...

Désolé.

**Comment by Mendy1996** [comment]
J'ai installer libertempo version 1.8 je n'arrive pas à exporter les utilisateurs de l'active directory.

**Comment by wouldsmina** [comment]
Sur quel version de serveur?

**Comment by Mendy1996** [comment]
c'est sur un server  wamp .
description :
wampserver3_x64_apache2.4.17_mysql5.7.9_php5.6.16_php7.0.0

**Comment by wouldsmina** [comment]
@Mendy1996 merci de créer un nouveau ticket. au passage, donne moi plus d'infos sur ton probleme, en particulier quelle version de MS server tu as? (si c'est 2003, pas besoin de nouveau ticket, la réponse est juste au dessus).
