### ISSUE TITLE
Erreur CAS

### ISSUE THREAD

**Issue by pmietlicki** [wouldsmina/Libertempo#132]
Problème à la création de session pour libertempo 1.8 quand on sélectionne une authentification CAS. On a le message "Pas de session ouverte, veuillez vous authentifier".

La solution est d'ajouter "session_destroy()" avant "session_create($usernameCAS)" dans le fichier index.php à la ligne 102.

Merci de voir si cette solution est ok et l'intégrer dans une future version.

Bonne journée,
Pascal

**Comment by wouldsmina** [comment]
test ok. Merci @pmietlicki, j’intègre ta proposition.

**Comment by pmietlicki** [comment]
Bonjour,
En fait, j'ai changé le code.
J'ai modifié dans index.php le session_create et mis le session_destroy dans la fonction authentification_passwd_conges_CAS()
Ca fonctionne mieux comme ça.
Bonne journée

diff --git a/index.php b/index.php
index bdafe44..7ca8f3a 100644
--- a/index.php
+++ b/index.php
@@ -100,11 +100,7 @@ else
 	if ( $_SESSION['config']['how_to_connect_user'] == "cas" && $session_username != "admin" && ( $session_username != "conges" || !$_SESSION['config']['responsable_virtuel'] ) )
 	{
 		$usernameCAS = authentification_passwd_conges_CAS();
-		if($usernameCAS != "")
-		{
-			session_create($usernameCAS);
-		}
-		else //dans ce cas l'utilisateur n'a pas encore été enregistré dans la base de données db_conges
+		if($usernameCAS == "")
 		{
 			header_popup();
 
diff --git a/include/fonction.php b/include/fonction.php
index 3769a99..519b098 100644
--- a/include/fonction.php
+++ b/include/fonction.php
@@ -320,9 +320,9 @@ function authentification_ldap_conges($username,$password)
 // - renvoie ""        si authentification FAIL
 function authentification_passwd_conges_CAS()
 {
+
+    //On supprime la session creee par phpCAS
+    session_destroy();
+    //On cree la session php_conges
     session_create($usernameCAS);
 
     //ON VERIFIE ICI QUE L'UTILISATEUR EST DEJA ENREGISTRE SOUS DBCONGES
-    $req_conges = 'SELECT u_login FROM conges_users WHERE u_login=\''.SQL::quote($usernameCAS);
+    $req_conges = 'SELECT u_login FROM conges_users WHERE u_login=\''.SQL::quote($usernameCAS).'\'';
     if($num_row_conges !=0)
         return $usernameCAS;
-
-    return '';
+    else
+        return '';
 }

**Comment by Prytoegrian** [comment]
```diff
diff --git a/index.php b/index.php
index bdafe44..7ca8f3a 100644
--- a/index.php
+++ b/index.php
@@ -100,11 +100,7 @@ else
 	if ( $_SESSION['config']['how_to_connect_user'] == "cas" && $session_username != "admin" && ( $session_username != "conges" || !$_SESSION['config']['responsable_virtuel'] ) )
 	{
 		$usernameCAS = authentification_passwd_conges_CAS();
-		if($usernameCAS != "")
-		{
-			session_create($usernameCAS);
-		}
-		else //dans ce cas l'utilisateur n'a pas encore été enregistré dans la base de données db_conges
+		if($usernameCAS == "")
 		{
 			header_popup();
 
diff --git a/include/fonction.php b/include/fonction.php
index 3769a99..519b098 100644
--- a/include/fonction.php
+++ b/include/fonction.php
@@ -320,9 +320,9 @@ function authentification_ldap_conges($username,$password)
 // - renvoie ""        si authentification FAIL
 function authentification_passwd_conges_CAS()
 {
+
+    //On supprime la session crÃ©er par phpCAS
+    session_destroy();
+    //On crÃ©Ã© la session php_conges
     session_create($usernameCAS);
 
     //ON VERIFIE ICI QUE L'UTILISATEUR EST DEJA ENREGISTRE SOUS DBCONGES
-    $req_conges = 'SELECT u_login FROM conges_users WHERE u_login=\''.SQL::quote($usernameCAS);
+    $req_conges = 'SELECT u_login FROM conges_users WHERE u_login=\''.SQL::quote($usernameCAS).'\'';
     if($num_row_conges !=0)
         return $usernameCAS;
-
-    return '';
+    else
+        return '';
 }
```
