### ISSUE TITLE
Erreur calcul des quotas de congés

### ISSUE THREAD

**Issue by pmietlicki** [wouldsmina/Libertempo#133]
Bonjour,
Un bug grave persiste depuis php congés sous libertempo, il est lié à la gestion des sessions.
Le cas d'utilisation en question est celui là :
- Un agent fait une demande de congés de 5 jours sur ces 25 jours annuels
- Un responsable ouvre 2 onglets vers l'application Libertempo sur la page permettant d'annuler ou valider les congés
- Il accepte une première fois la demande ce qui retire 5 jours de congés à l'agent
- Le responsable fait d'autres trucs (boire un café, lire ses mails, etc.) puis il revient sur le 2ème onglet où, du coup, la page des demandes affiche toujours celle de l'utilisateur en question
- Le responsable (un peu perdu faut bien l'avouer) revalide la même demande
- L'agent est donc décrété de 10 jours de congés pour la même demande de 5 jours (il se sent un peu arnaqué du coup, pas super content l'agent car il ne lui reste plus que 15 jours de CA)

Le problème est le même en sens inverse (double annulation de congés). Dans ce cas là, l'agent est super content car ça augmente son quota.

J'avais résolu cela en faisant des tests niveau serveur (dans resp_traite_user et resp_traitement_demandes) avec un truc comme ça pour vérifier le champ p_etat du congé avant une MAJ :
Dans resp_traite_user
````
        $sqlv = 'SELECT p_etat from conges_periode WHERE p_num=\''.SQL::quote($numero_int).'\'';
        $ReqLogv = SQL::query($sqlv);
        $resv = $ReqLogv->fetch_array();
        if ($ReqLogv && $resv["p_etat"]!="annul")
        {
            /* UPDATE table "conges_periode" */
            $sql1 = 'UPDATE conges_periode SET p_etat="annul", p_motif_refus=\''.SQL::quote($motif_annul).'\', p_date_traitement=NOW() WHERE p_num=\''.SQL::quote($numero_int).'\' ';
            $ReqLog1 = SQL::query($sql1);
````
Dans resp_traitement_demandes
````
$sqlv = 'SELECT p_etat from conges_periode WHERE p_num=\''.SQL::quote($numero_int).'\'';
            $ReqLogv = SQL::query($sqlv);
		$resv = $ReqLogv->fetch_array();
            if ($ReqLogv && $resv["p_etat"]!="ok")
            {
````

**Comment by Prytoegrian** [comment]
Joli ! :+1:

**Comment by wouldsmina** [comment]
ca a été corrigé dans la fonction `traite_all_demande_en_cours()` : 
````
                /* UPDATE table "conges_periode" */
                $sql1 = 'UPDATE conges_periode SET p_etat="ok", p_date_traitement=NOW() WHERE p_num="'.\includes\SQL::quote($numero_int).'" AND ( p_etat=\'valid\' OR p_etat=\'demande\' );';
                /* On valide l'UPDATE dans la table "conges_periode" ! */
                $ReqLog1 = \includes\SQL::query($sql1) ;
                if ($ReqLog1 && \includes\SQL::getVar('affected_rows') ) {

                    // Log de l'action
                    log_action($numero_int,"ok", $user_login, "traite demande $numero ($user_login) ($user_nb_jours_pris jours) : $reponse");

                    /* UPDATE table "conges_solde_user" (jours restants) */
                    soustrait_solde_et_reliquat_user($user_login, $numero_int, $user_nb_jours_pris, $type_abs, $date_deb, $demi_jour_deb, $date_fin, $demi_jour_fin);

                    //envoi d'un mail d'alerte au user (si demandé dans config de php_conges)
                    if($_SESSION['config']['mail_valid_conges_alerte_user']) {
                        alerte_mail($_SESSION['userlogin'], $user_login, $numero_int, "accept_conges");
                    }
````
Je vais appliquer la même méthode pour `traite_demandes()`
