### ISSUE TITLE
Peut-on ... ?

### ISSUE THREAD

**Issue by cyberesprit** [wouldsmina/Libertempo#135]
Bonjour,

Avec Libertempo, peut-on :
- Renseigner les jours d'ouvertures ?
- Pointer les heures supplémentaires ?
- Gérer les plages horaires et journalières ?

Nous n'avons pas trouvés ces fonctionnalités, d'où la question.
En espérant que ce ne soit pas bête ^^

Librement

**Comment by wouldsmina** [comment]
Salut,

Les jours d'ouverture, non! Mais les jours de fermetures peuvent être déclaré par le RH. :p

Pour le planning horaire et les heures supp à récupérer, on y réfléchi, Mais on ne promet rien pour le moment...

**Comment by cyberesprit** [comment]
D'accord, merci. C'est la secrétaire d'une mairie pour qui j'ai installé Libertempo pour tester qui me pose les questions.

**Comment by wouldsmina** [comment]
Ok. J'ai corrigé le lien mort sur la doc : http://libertempo.tuxfamily.org/documentation/jours-chomes-fermeture/

A+

**Comment by wouldsmina** [comment]
doublon #127
