### ISSUE TITLE
Problème avec l'envoi de mail

### ISSUE THREAD

**Issue by Mendy1996** [wouldsmina/Libertempo#137]
Bonjour , je tient d'abord à te féliciter pour le bon travaille effectué.

J'ai installer libertempo version 1.8 , dans la configuration des mail lorsque je clique sur ****tester l'envoi de mail****  l'application charge pendant environt 1min30 et affiche ce message:

2016-03-11 08:19:40	Connection: opening to 10.10.10.10:80, timeout=300, options=array ( ) 2016-03-11 08:19:40	Connection: opened

Mais je ne reçois aucun mail.

**Comment by wouldsmina** [comment]
Bonjour,

As tu configuré le fichier cfg/config_SMTP.php ?

**Comment by Mendy1996** [comment]
je vient de configurer le fichier  l'adresse ip du serveur et le port  mai j'ai une nouvel erreur :
**Echec de la connection smtp**

**Comment by Mendy1996** [comment]
pourtant tous les parametre sont bons

**Comment by wouldsmina** [comment]
juste pour être sur, peut tu faire un telnet depuis le serveur hébergeant Libertempo vers ton serveur smtp : 
````
telnet adresse.ip port
````
si tu n'as pas de probleme, creer une page php à la racine de ton site Libertempo avec comme contenu : 
````
<?php
require_once('library/phpmailer/PHPMailerAutoload.php');

$mail             = new PHPMailer();


$mail->IsSMTP(); // telling the class to use SMTP
$mail->Host       = "mail.yourdomain.com"; // SMTP server
$mail->SMTPDebug  = 1;                     // enables SMTP debug information (for testing)
$mail->SMTPAuth   = true;                  // enable SMTP authentication
//$mail->SMTPSecure = "tls";                 // sets the prefix to the server
$mail->Host       = "mail.yourdomain.com"; // sets the SMTP server
$mail->Port       = 26;                    // set the SMTP port for the GMAIL server
$mail->Username   = "yourname@yourdomain"; // SMTP account username
$mail->Password   = "yourpassword";        // SMTP account password

$mail->SetFrom('name@yourdomain.com', 'First Last');

$mail->Subject    = "PHPMailer Test Subject via smtp";

$mail->Body    = "Test OK"; // optional, comment out and test

$address = "whoto@otherdomain.com";
$mail->AddAddress($address, "John Doe");

if(!$mail->Send()) {
  echo "Mailer Error: " . $mail->ErrorInfo;
} else {
  echo "Message sent!";
}
````

Pense a décommenter SMTPSecure si besoin...

Je te demande cela pour être sur que le problème viens bien de Libertempo. dit moi ce que ça donne...

**Comment by Mendy1996** [comment]
Actuellement je suis chez moi , je ne suis pas dans l'entreprise jai donc pas acces aux dossier libertempo  . je ne pourrai malheureusement te repondre que lundi .

**Comment by Mendy1996** [comment]
Bonjour , j'ai fait  un telnet avec l'adresse ip et le port du serveur smtp et je n'ai eu aucun probleme .


Ensuite j'ai créer le fichier php  avec le code que tu ma donné à la racine de mon site , et lorsque je lance le fichier j’obtiens ce message d'erreur :

**Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in C:\wamp64\www\Libertempo\library\phpmailer\class.smtp.php on line 344**

**Comment by wouldsmina** [comment]
Ce problème est lié à ton serveur smtp qui utilise, apparemment, un certificat auto-signé. [source](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#php-56-certificate-verification-failure)

tu peux outrepasser la sécurité mais, évidemment, c'est vivement déconseillé.

**Comment by wouldsmina** [comment]
J'ai peut etre fermé ce ticket un peu trop vite! @Mendy1996 est ce que, au moins, tu utilise tls ou ssl pour ton smtp? je rencontre un soucis similaire avec PHPMailer et debian 8 (avec php5.6)...

**Comment by Mendy1996** [comment]
J'utilise tls et ca marche tres bien maintenant.

**Comment by wouldsmina** [comment]
en désactivant la vérification du certificat dans PHPMailer?

**Comment by Mendy1996** [comment]
Oui jai desactiver la verfication et jai aussi  mis 587  comme port du serveur .

**Comment by wouldsmina** [comment]
Si tu as quelques minutes, peux tu venir sur [irc](irc://irc.tuxfamily.org/Libertempo)  pour en parler?

**Comment by wouldsmina** [comment]
irc://irc.tuxfamily.org/Libertempo

**Comment by Mendy1996** [comment]
Le lien ne marche pas

**Comment by wouldsmina** [comment]
si tu n'as pas de client irc, va sur [mibbit](http://www.mibbit.com/). Merci

**Comment by wouldsmina** [comment]
avec ca c'est mieux https://client02.chat.mibbit.com/?url=irc%3A%2F%2Firc.tuxfamily.org%2FLibertempo

**Comment by wouldsmina** [comment]
passe sur l'onglet Libertempo

**Comment by wouldsmina** [comment]
Pour permettre l'utilisation d'un smtp sans tls, malgré que le serveur le permet, il faut forcer PHPMailer : 
`$mail->SMTPAutoTLS = false;`
[source](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#opportunistic-tls)
Je corrige ca sur la beta.
