### ISSUE TITLE
Erreur décompte congés payés selon droit français

### ISSUE THREAD

**Issue by pab691** [wouldsmina/Libertempo#138]
Bonjour
tout d'abord bravo pour votre travail !
Mais je suis un peu surpris car votre produit n'est pas compatible avec le droit Français (à moins que je n'ai pas compris comment le paramétrer..)

Normalement même si les samedi sont non travaillés ils sont décomptés, hors cela ne semble pas être le cas.
Par exemple pour des congés pris du 03/08/2015 au 21/08/2015, nous devons décompter 17 jours, hors votre logiciel en décompte 16..

**Comment by wouldsmina** [comment]
Bonjour,
cette méthode de calcul n'est pas une obligation dans le droit français, d'autres méthodes existent. Mais c'est vrai que Libertempo ne gère pas encore cette subtilité. D'ailleurs un ticket à ce sujet existe déjà : #14 .

**Comment by pab691** [comment]
Oui effectivement, le décompte peut être effectué autrement, mais je pense que la majorité des entreprises utilisent la méthode à 25 jours par an de congés avec comptabilisation des samedis.
C'est dommage que cela ne soit pas pris en compte, car votre travail serait parfait
