### ISSUE TITLE
Calendrier : un décalage des cellules se produit à la navigation

### ISSUE THREAD

**Issue by jjmz** [wouldsmina/Libertempo#139]
Bonjour,

Lors du défilement du calendrier de semaines en semaine, un bug d'affichage se produit au niveau du calcul des 'colspan' en passant du mois courant au mois suivant, provoquant un décalage - voire un mauvais calcul du niveau du numéro de semaine : 

![2016-03-15 08_25_37-libertempo _ calendrier des conges](https://cloud.githubusercontent.com/assets/5535976/13770497/b559ffce-ea87-11e5-8e45-b4ef5484d5b6.png)

**Comment by wouldsmina** [comment]
As tu bien paramétré le timezone dans php.ini?

**Comment by Prytoegrian** [comment]
je viens de vérifier, j'ai le problème aussi. Tu peux me détailler pourquoi il a besoin d'une modif de timezone dans le ini ?

**Comment by jjmz** [comment]
Juste pour confirmer : j'ai bien date.timezone = Europe/Paris dans le php.ini.

**Comment by wouldsmina** [comment]
@Prytoegrian, je sais plus précisément pourquoi, peut etre pour mktime... 
Mais le problème ne semble pas venir de la...

**Comment by Prytoegrian** [comment]
Je viens de le remarquer à nouveau, avec pour conséquence des semaines à moins de 7 jours et donc des décalages sur le nombres de cellules.

Comme résolution du bug, je propose que le calendrier colle au système civil, autrement dit de toujours faire commencer ses semaines par le lundi (ou autre chose si paramétrage différent) et de compter par cycle de 7 jours. On pourra toujours afficher différemment la cellule du jour courant pour différencier.

**Comment by Prytoegrian** [comment]
Corrigé par #229.
