### ISSUE TITLE
demande de congés non prise en compte

### ISSUE THREAD

**Issue by clad63** [wouldsmina/Libertempo#140]
Bonjour, après passage à la version 1.8 quand un utilisateur (gérés par double-responsable) fait une demande de congé celle ci n'est pas prise en compte et n'apparait pas dans les demandes en cours.
En regardant le log apache j'ai après une demande n'ayant pas aboutie:

PHP Fatal error:  Call to undefined function utilisateur\\verif_solde_user() in /var/www/html/Libertempo/utilisateur/Fonctions.php on line 92, referer: http://192.168.0.142:8080/utilisateur/user_index.php?session=phpconges1c61bc096d8e4857e58ab8c0297aac4d

**Comment by Prytoegrian** [comment]
merci de ta précision, ça va nous aider

**Comment by wouldsmina** [comment]
ok, cela ce produit lorsque les soldes négatifs sont interdits (je n'avais pas testé cette fonction). 
normalement tout rentre dans l'ordre en remplacant la ligne 92 par : 
````
            $valid = $valid && \utilisateur\Fonctions::verif_solde_user($_SESSION['userlogin'], $new_type, $new_nb_jours);
 ````

Il semble aussi y avoir un problème au niveau de la première validation. Le formulaire de validation du grand responsable est un peu bancale...

**Comment by clad63** [comment]
effectivement je viens de tester en mettant les solde positif à false et les demandes sont du coup prisent en compte. le problème se situait bien ici, merci ;)
