### ISSUE TITLE
Paramétrages

### ISSUE THREAD

**Issue by johnfr59** [wouldsmina/Libertempo#141]
Bonjour,

peut-on sur libertempo faire en sorte que les utilisateurs ne voit que leur propre calendrier et pas ceux des membres de leur groupe?

Peut-on faire en sorte que le responsable puisse valider les demandes d'absences?

Merci

**Comment by wouldsmina** [comment]
Bonjour,

> peut-on sur libertempo faire en sorte que les utilisateurs ne voit que leur propre calendrier et pas ceux des membres de leur groupe?

Non, tu peux interdire l'accès au calendrier, l'utilisateur peut toujours consulter son historique.

> Peut-on faire en sorte que le responsable puisse valider les demandes d'absences?

Non, les absences ne sont pas soumise à validation. Seul un mail d'information est transmis au responsable (Version 1.8)

**Comment by johnfr59** [comment]
Bonjour,

avec la version 1.7 quand j'interdit l'accès au calendrier aux utilisateurs, les responsables, le RH et l'administrateur n'ont plus l'accès également.

Merci

**Comment by Prytoegrian** [comment]
Salut John,

Nous demandes-tu s'il le logiciel le permet **actuellement** ou voudrais-tu qu'on le code ?

Si c'est la seconde option, il nous faudrait avoir des détails sur ce que tu cherches à obtenir via ces fonctionnalités. Charge à toi de nous convaincre, donc :-)

**Comment by johnfr59** [comment]
Salut,

je me suis mal exprimer. Il me semble que dans les options il est possible de désactiver l'accès au  calendrier pour les utilisateurs dans la configuration point 5 Utilisateurs:

> // AFFICHAGE DU BOUTON DE CALENDRIER POUR L'UTILISATEUR
//--------------------------------------------------------------------------------------
// si à FALSE : les utilisateurs n'ont pas la possibilité d'afficher le calendrier des congés
// si à TRUE : les utilisateurs ont la possibilité d'afficher le calendrier des congés (TRUE est la valeur par défaut)
user_affiche_calendrier = FALSE

> 

Mais quand je passe cette fonction à TRUE, le bouton Calendrier disparait également pour les personnes définit comme responsable.
Est ce normal?

Merci.

**Comment by wouldsmina** [comment]
>Mais quand je passe cette fonction à TRUE, le bouton Calendrier disparait également pour les personnes définit comme responsable.

a FALSE tu veux dire. le responsable à toujours accès au calendrier à condition qu'il soit en mode responsable et que la config l'autorise : 
````
/ AFFICHAGE DU BOUTON DE CALENDRIER POUR LE RESPONSABLE
//--------------------------------------------------------------------------------------
// si à FALSE : les responsables n'ont pas la possibilité d'afficher le calendrier des congés
// si à TRUE : les responsables ont la possibilité d'afficher le calendrier des congés (TRUE est la valeur par défaut)
resp_affiche_calendrier = TRUE
````

**Comment by johnfr59** [comment]
Bonjour,

C'est actuellement le cas,  voici ce que j'ai:

> // AFFICHAGE DU BOUTON DE CALENDRIER POUR L'UTILISATEUR
//--------------------------------------------------------------------------------------
// si à FALSE : les utilisateurs n'ont pas la possibilité d'afficher le calendrier des congés
// si à TRUE : les utilisateurs ont la possibilité d'afficher le calendrier des congés (TRUE est la valeur par défaut)
user_affiche_calendrier = FALSE
>

> // AFFICHAGE DU BOUTON DE CALENDRIER POUR LE RESPONSABLE
//--------------------------------------------------------------------------------------
// si à FALSE : les responsables n'ont pas la possibilité d'afficher le calendrier des congés
// si à TRUE : les responsables ont la possibilité d'afficher le calendrier des congés (TRUE est la valeur par défaut)
resp_affiche_calendrier = TRUE

> 

Et le bouton calendrier en mode responsable n'est pas visible.

Merci de vos réponses

**Comment by wouldsmina** [comment]
je ne rencontre pas ce problème sur la 1.8. Est ce que tu peux faire un essai?

**Comment by johnfr59** [comment]
Bonjour,

je ne préfère pas installer la version 1.8 tant qu'elle sera en version BETA.

Merci quand même.

**Comment by wouldsmina** [comment]
oui, évidemment il ne faut pas l'utiliser en prod.

**Comment by wouldsmina** [comment]
ping @johnfr59.
