### ISSUE TITLE
error Removing Exceptionnal out of office

### ISSUE THREAD

**Issue by Lguillois** [wouldsmina/Libertempo#142]
Hi
whe wanted to remove the exceptionnal out of office reason from Libertempo but it's forbidden because an entry has been recorded, but when I check I don't find any entry in the program...
can you tell me how i can fix this?

regards
[libertempo.docx](https://github.com/wouldsmina/Libertempo/files/188088/libertempo.docx)

**Comment by wouldsmina** [comment]
Hi,
have you request directly into the db (SQL)?
````
SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle` 
FROM `conges_periode`, `conges_type_absence` 
WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 2 
````
change `conges_type_absence.ta_id = 2` according your needs

J'ai l'impression que tu es français. Je me trompe? (c'est la recherche dans ta capture d'écran qui t'as trahi!)

**Comment by Lguillois** [comment]
Bonjour

Oui je suis Français … #demasqué

En fait le but de tout ceci est de supprimer les lignes de congés exceptionnels dont nous ne nous servons pas et que j’ai renommé Inutile (voir la copie d’ecran)


[cid:image001.jpg@01D18673.4722F790]

Mais quand j’essaie de le faire il me dit ceci :

[cid:image002.jpg@01D18673.4722F790]

Pourtant nous n’avons saisi aucun congé de ce type pour nos utilisateurs…
Avez-vous une idée ?
Vous trouverez en piece jointe la reponse à la requete que vous m’avez donné et je ne vois effectivement de conges que de type congés payés et heures compteurs … aucun congé de type inutile …

Merci beaucoup pour votre réponse.
Laurent GUILLOIS
Administrateur Systèmes et Réseaux
[PRONAL Elastomer Engineering]<http://www.pronal.com/>
Tel: +33 (0)3 62 72 29 07 / Fax: +33 (0)3 20 99 75 20
Z.I. Roubaix Est BP 18, 14 Rue du Trieu du Quesnoy, 59115 LEERS, FRANCE
http://www.pronal.com<http://www.pronal.com/> / Skype: Lguillois
[Discover PRONAL Today!]<http://www.pronal360.com/>
Ce message et toutes les pièces jointes sont établis à l'intention exclusive de ses destinataires et sont confidentiels. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur.
This e-mail and/or attachment(s)is (are) confidential and may be legally protected.This message is addressed to the intended recipient only. If you are not the intended recipient of the message, please notify the sender immediately. Any disclosure, use or dissemination, either in whole or in partial, shall be prior authorised.

[Think before you print.]

De : wouldsmina [mailto:notifications@github.com]
Envoyé : jeudi 24 mars 2016 20:04
À : wouldsmina/Libertempo <Libertempo@noreply.github.com>
Cc : GUILLOIS Laurent <laurent.guillois@pronal.com>
Objet : Re: [Libertempo] error Removing Exceptionnal out of office (#142)


Hi,
have you request directly into the db (SQL)?

SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`

FROM `conges_periode`, `conges_type_absence`

WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 2

change conges_type_absence.ta_id = 2 according your needs

J'ai l'impression que tu es français. Je me trompe? (c'est la recherche dans ta capture d'écran qui t'as trahi!)

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/wouldsmina/Libertempo/issues/142#issuecomment-200973112>

mysql> SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`  FROM `conges_periode`, `conges_type_absence`  WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 2;
+-------------------+------------+------------+---------+-----------------+
| p_login           | p_date_deb | p_date_fin | ta_type | ta_libelle      |
+-------------------+------------+------------+---------+-----------------+
| lguillois         | 2016-03-21 | 2016-03-21 | conges  | Heures Compteur |
| lguillois         | 2016-05-06 | 2016-05-06 | conges  | Heures Compteur |
| aachille          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| jarias            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| nbenslim          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| eberriot          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fberteloot        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fbialon           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| pbleuse           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| aboucheneb        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| tbrige            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| ccappe            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| scarlier          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| dclauss           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fcunrath          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| scustodio         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| rdaci             | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fdecastro         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| xdereviere        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| ederosny          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fdelezenne        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| cdelgrange        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fdelobelle        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| mdelparte         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| adelrue           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| rdemdoum          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fdespatures       | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| xdudzinski        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| ddupont           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| aelkarkouri       | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| jesprit           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| jfollet           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| jforestier        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| bfresko           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| jgaglio           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| sgaudiere         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| mgodart           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fgoube            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| sgoudet           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| vgrumetz          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| mguerin           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| lguillois         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| shamidi           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| ahamidi           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| rhamidi           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fheldre           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fherbert          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| phonore           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| choste            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| shoucke           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fhulard           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| jjalia            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| sjeannin          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| skechout          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| hkechout          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| kkerrouche        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| skhalfallah       | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| nleclercq         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| clefebvre         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| rlemaire          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| rlison            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| tloyer            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| cmadeira          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| cmanuel           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| emartin           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| mmerali           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| smerikhi          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| rmerikhi          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| mmissaoui         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| amonnet           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| lmoulart          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| pnasti            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| aolla             | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| fparreira         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| ypicotin          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| krazki            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| mrobert           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| orommelaere       | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| jpschneider       | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| stordoir          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| ttribouilloy      | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| cvanderplaetsen   | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| dvanheerswynghels | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| pfveckens         | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| lverbeke          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| sverlyck          | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| jvieren           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| awadin            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| pwaroquier        | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| cweiand           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| swesse            | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| mwrobel           | 2016-03-23 | 2016-03-23 | conges  | Heures Compteur |
| lguillois         | 2016-04-20 | 2016-04-20 | conges  | Heures Compteur |
+-------------------+------------+------------+---------+-----------------+
93 rows in set (0.00 sec)

mysql> SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`  FROM `conges_periode`, `conges_type_absence`  WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 3;
Empty set (0.00 sec)

mysql> SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`  FROM `conges_periode`, `conges_type_absence`  WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 1;
+-------------------+------------+------------+---------+--------------+
| p_login           | p_date_deb | p_date_fin | ta_type | ta_libelle   |
+-------------------+------------+------------+---------+--------------+
| ypicotin          | 2016-04-13 | 2016-04-18 | conges  | congés payés |
| aachille          | 2016-03-21 | 2016-03-21 | conges  | congés payés |
| aachille          | 2016-03-21 | 2016-03-21 | conges  | congés payés |
| aachille          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| jarias            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| nbenslim          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| eberriot          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fberteloot        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fbialon           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| pbleuse           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| aboucheneb        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| tbrige            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| ccappe            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| scarlier          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| dclauss           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fcunrath          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| scustodio         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| rdaci             | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fdecastro         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| xdereviere        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| ederosny          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fdelezenne        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| cdelgrange        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fdelobelle        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| mdelparte         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| adelrue           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| rdemdoum          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| ddepre            | 2016-03-21 | 2016-03-21 | conges  | congés payés |
| ddupont           | 2016-04-25 | 2016-04-25 | conges  | congés payés |
| ddupont           | 2016-04-08 | 2016-04-08 | conges  | congés payés |
| jvieren           | 2016-05-16 | 2016-05-20 | conges  | congés payés |
| pfveckens         | 2016-03-25 | 2016-03-25 | conges  | congés payés |
| fdespatures       | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| xdudzinski        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| ddupont           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| aelkarkouri       | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| jesprit           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| jfollet           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| jforestier        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| bfresko           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| jgaglio           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| sgaudiere         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| mgodart           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fgoube            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| sgoudet           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| vgrumetz          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| mguerin           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| lguillois         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| shamidi           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| ahamidi           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| rhamidi           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fheldre           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fherbert          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| phonore           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| choste            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| shoucke           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fhulard           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| jjalia            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| sjeannin          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| skechout          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| hkechout          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| kkerrouche        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| skhalfallah       | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| nleclercq         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| clefebvre         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| rlemaire          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| rlison            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| tloyer            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| cmadeira          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| cmanuel           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| emartin           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| mmerali           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| smerikhi          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| rmerikhi          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| mmissaoui         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| amonnet           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| lmoulart          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| pnasti            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| aolla             | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| fparreira         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| ypicotin          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| krazki            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| mrobert           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| orommelaere       | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| jpschneider       | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| stordoir          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| ttribouilloy      | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| cvanderplaetsen   | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| dvanheerswynghels | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| pfveckens         | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| lverbeke          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| sverlyck          | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| jvieren           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| awadin            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| pwaroquier        | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| cweiand           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| swesse            | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| mwrobel           | 2016-03-23 | 2016-03-23 | conges  | congés payés |
| lguillois         | 2016-03-24 | 2016-03-24 | conges  | congés payés |
+-------------------+------------+------------+---------+--------------+
99 rows in set (0.00 sec)

mysql> SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`  FROM `conges_periode`, `conges_type_absence`  WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 4;
Empty set (0.00 sec)

mysql> SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`  FROM `conges_periode`, `conges_type_absence`  WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 5;
Empty set (0.00 sec)

mysql> SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`  FROM `conges_periode`, `conges_type_absence`  WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 6;
Empty set (0.00 sec)

mysql> SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`  FROM `conges_periode`, `conges_type_absence`  WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 0;
Empty set (0.00 sec)

mysql> SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`  FROM `conges_periode`, `conges_type_absence`  WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 7;
Empty set (0.00 sec)

mysql> SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle`  FROM `conges_periode`, `conges_type_absence`  WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 8;
Empty set (0.00 sec)

**Comment by wouldsmina** [comment]
Fait attention, ta reponse par mail contient un peu trop de donner perso, repond sur github c'est plus sur. En plus je n'ai pas eu les captures... tu peux aussi m'ecrire directement wouldsmina@gmail.com

**Comment by wouldsmina** [comment]
La requête précédente est un exemple (elle retourne uniquement les RTT), pour avoir les congés du type que tu veux supprimer, exécute celle ci : 
````
SELECT * FROM `conges_type_absence` 
````
elle devrait te retourner quelque chose comme : 
````
1 	conges 	congés payés 	cp
2 	conges 	rtt 	rtt
3 	absences 	formation 	fo
4 	absences 	misson 	mi
5 	absences 	autre 	ab
6 	absences 	malade 	mal
````

prend le numéro correspondant au type de congés que tu veux supprimer pour le mettre à la fin de cette requête (a la place du 2) : 
````
SELECT `p_login`,`p_date_deb`,`p_date_fin`,`ta_type`,`ta_libelle` 
FROM `conges_periode`, `conges_type_absence` 
WHERE conges_periode.p_type = conges_type_absence.ta_id AND conges_type_absence.ta_id = 2 
````

**Comment by wouldsmina** [comment]
je viens de voir tout le contenu de ton mail. oubli mon message précédent!

**Comment by wouldsmina** [comment]
on va faire plus simple (et comme le fait Libertempo). Lorsque tu es à l'étape de confirmation de la suppression, recherche dans le code source `<input type="hidden" name="id_to_update" value=`

dans mysql, execute : 
`SELECT p_num FROM conges_periode WHERE p_type=`
en ajoutant le numéro trouvé dans le code source à la fin de la requête.

**Comment by wouldsmina** [comment]
peux tu aussi me donner le résultat d'un debug en procédant comme suit : 
- créé le dossier debug à la racine de ton site (avec les bons droit)
- dans define.php ligne 11 remplace `define('ENV', ENV_PROD);` par `define('ENV', ENV_DEV);`
- dans le fichier config/Fonction.php ligne 515 ajoute `debug($sql);`
- essai de supprimer le type de congé que tu veux

cela aura pour effet de créer un fichier html dans le dossier debug. Tu auras peut etre des erreurs directement sur l'interface de Libertempo, dit le moi.

Bien sur tout cela doit être fait hors production (mais c'est normalement le cas puisque tu utilise la beta).

**Comment by Prytoegrian** [comment]
@wouldsmina Surtout pas `ENV_DEV`, `ENV_TEST` est fait pour ça

**Comment by wouldsmina** [comment]
ok. c'est noté ;)

**Comment by Lguillois** [comment]
Bonjour

J’ai créé le dossier debug dans mon /var/www/html (le site est dans ce répertoire html)

J’ai ensuite remplacé l’env comme indiqué par celui de TEST…

Par contre pour le fichier /config/Fonction.php, la ligne 515 que j’ai est-elle la meme que la vôtre ?

[cid:image002.jpg@01D18A64.BC0C7230]

Car je n’ai rien dans le repertoite debug quand je tente la suppression du type de congé …

Merci beaucoup en tout cas pour vos nombreux mails et votre aide précieuse.

Cordialement
Laurent GUILLOIS
Administrateur Systèmes et Réseaux
[PRONAL Elastomer Engineering]<http://www.pronal.com/>
Tel: +33 (0)3 62 72 29 07 / Fax: +33 (0)3 20 99 75 20
Z.I. Roubaix Est BP 18, 14 Rue du Trieu du Quesnoy, 59115 LEERS, FRANCE
http://www.pronal.com<http://www.pronal.com/> / Skype: Lguillois
[Discover PRONAL Today!]<http://www.pronal360.com/>
Ce message et toutes les pièces jointes sont établis à l'intention exclusive de ses destinataires et sont confidentiels. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur.
This e-mail and/or attachment(s)is (are) confidential and may be legally protected.This message is addressed to the intended recipient only. If you are not the intended recipient of the message, please notify the sender immediately. Any disclosure, use or dissemination, either in whole or in partial, shall be prior authorised.

[Think before you print.]

De : wouldsmina [mailto:notifications@github.com]
Envoyé : samedi 26 mars 2016 13:17
À : wouldsmina/Libertempo <Libertempo@noreply.github.com>
Cc : GUILLOIS Laurent <laurent.guillois@pronal.com>
Objet : Re: [Libertempo] error Removing Exceptionnal out of office (#142)


peux tu aussi me donner le résultat d'un debug en procédant comme suit :

  *   créé le dossier debug à la racine de ton site (avec les bons droit)
  *   dans define.php ligne 11 remplace define('ENV', ENV_PROD); par define('ENV', ENV_DEV);
  *   dans le fichier config/Fonction.php ligne 515 ajoute debug($sql);
  *   essai de supprimer le type de congé que tu veux

cela aura pour effet de créer un fichier html dans le dossier debug. Tu auras peut etre des erreurs directement sur l'interface de Libertempo, dit le moi.

Bien sur tout cela doit être fait hors production (mais c'est normalement le cas puisque tu utilise la beta).

**Comment by wouldsmina** [comment]
> Par contre pour le fichier /config/Fonction.php, la ligne 515 que j’ai est-elle la meme que la vôtre ?

En effet, c'est ligne [539](https://github.com/wouldsmina/Libertempo/blob/beta/config/Fonctions.php#L539), juste au dessus de `return $return;`, désolé.

**Comment by wouldsmina** [comment]
@Lguillois, on peut fermer ce ticket?

**Comment by Lguillois** [comment]
Bonjour

Oui bien sur, je n’ai pas la solution mais j’ai trouvé une échappatoire

Par contre je vous en ouvrirais un autre car j’ai un message d’erreur lorsque je créé une absence (formation, mission)
Le mail ne s’envoie pas et c’est beaucoup plus problèmatique…

Merci beaucoup

[cid:image002.jpg@01D1AA0D.1B40BFA0]
Laurent GUILLOIS
Administrateur Systèmes et Réseaux
[PRONAL Elastomer Engineering]<http://www.pronal.com/>
Tel: +33 (0)3 62 72 29 07 / Fax: +33 (0)3 20 99 75 20
Z.I. Roubaix Est BP 18, 14 Rue du Trieu du Quesnoy, 59115 LEERS, FRANCE
http://www.pronal.com<http://www.pronal.com/> / Skype: Lguillois
[Discover PRONAL Today!]<http://www.pronal360.com/>
Ce message et toutes les pièces jointes sont établis à l'intention exclusive de ses destinataires et sont confidentiels. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur.
This e-mail and/or attachment(s)is (are) confidential and may be legally protected.This message is addressed to the intended recipient only. If you are not the intended recipient of the message, please notify the sender immediately. Any disclosure, use or dissemination, either in whole or in partial, shall be prior authorised.

[Think before you print.]

De : wouldsmina [mailto:notifications@github.com]
Envoyé : lundi 9 mai 2016 15:44
À : wouldsmina/Libertempo <Libertempo@noreply.github.com>
Cc : GUILLOIS Laurent <laurent.guillois@pronal.com>; Mention <mention@noreply.github.com>
Objet : Re: [wouldsmina/Libertempo] error Removing Exceptionnal out of office (#142)


@Lguillois<https://github.com/Lguillois>, on peut fermer ce ticket?

**Comment by wouldsmina** [comment]
ok. Merci du retour. Le problème d'envoi de mail pour une absence à déjà été remonté, ce sera corrigé sur la 1.9. voici le correctif : https://github.com/wouldsmina/Libertempo/commit/9f1128c126a8cfb863c2d13ab1f1064bc8ed0093

**Comment by Lguillois** [comment]
Je vous remercie 1000 fois ^^

Cordialement

Laurent GUILLOIS
Administrateur Systèmes et Réseaux
[PRONAL Elastomer Engineering]<http://www.pronal.com/>
Tel: +33 (0)3 62 72 29 07 / Fax: +33 (0)3 20 99 75 20
Z.I. Roubaix Est BP 18, 14 Rue du Trieu du Quesnoy, 59115 LEERS, FRANCE
http://www.pronal.com<http://www.pronal.com/> / Skype: Lguillois
[Discover PRONAL Today!]<http://www.pronal360.com/>
Ce message et toutes les pièces jointes sont établis à l'intention exclusive de ses destinataires et sont confidentiels. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur.
This e-mail and/or attachment(s)is (are) confidential and may be legally protected.This message is addressed to the intended recipient only. If you are not the intended recipient of the message, please notify the sender immediately. Any disclosure, use or dissemination, either in whole or in partial, shall be prior authorised.

[Think before you print.]

De : wouldsmina [mailto:notifications@github.com]
Envoyé : lundi 9 mai 2016 16:18
À : wouldsmina/Libertempo <Libertempo@noreply.github.com>
Cc : GUILLOIS Laurent <laurent.guillois@pronal.com>; Mention <mention@noreply.github.com>
Objet : Re: [wouldsmina/Libertempo] error Removing Exceptionnal out of office (#142)


ok. Merci du retour. Le problème d'envoi de mail pour une absence à déjà été remonté, ce sera corrigé sur la 1.9. voici le correctif : 9f1128c<https://github.com/wouldsmina/Libertempo/commit/9f1128c126a8cfb863c2d13ab1f1064bc8ed0093>
