### ISSUE TITLE
Notice PHP : constante déja définie

### ISSUE THREAD

**Issue by si-smo2** [wouldsmina/Libertempo#143]
Bonjour, 

En mode responsable une erreur dans le define.php apparait en partie gauche de la page web.
Dans les autres modes (users, RH et admin), tout est OK.

Je n'ai rien trouvé de probant en ligne 4 de define.php mais je suis une biquette en dev... Merci de vos lumières

@+
![erreur libert](https://cloud.githubusercontent.com/assets/18138113/14102729/a6a9435c-f59c-11e5-8cee-7b4d8b41970c.PNG)

**Comment by wouldsmina** [comment]
Bonjour,

En effet, il y a un petit problème avec la constante PHP_CONGES qui sera corrigé sur la version 1.9. 

Par contre, le message ne devrait pas s'afficher à l'écran donc soit tu as modifié la constante ENV (dans define.php) ou tu as configuré php pour afficher les erreurs à l'écran...

**Comment by DreDoU** [comment]
Bonjour,

J'ai également le même souci avec un user import de l'AD 2012 R2 dans la partie "Responsable"

![erreur define](https://cloud.githubusercontent.com/assets/16799641/14605426/d1996e02-0578-11e6-80ce-7800e964f92a.JPG)

Dans define.php  : 

![define](https://cloud.githubusercontent.com/assets/16799641/14605355/7d4ae59c-0578-11e6-8d9d-cdf8cd2392bd.JPG)

Quand sortirait cette version 1.9 ?

**Comment by wouldsmina** [comment]
Je ne peux pas donner de date précise, désolé. Par contre, tu ne devrait pas avoir ces messages en prod. Vérifie ta configuration PHP. De tête, dans php.ini il faut modifier `display_errors`.

**Comment by Prytoegrian** [comment]
J'ai trouvé, c'est pas un truc qu'on a déjà corrigé dans la 1.9 ; ce qui est étrange, c'est que toi tu le vois comme ça.

Je me dis qu'on pourrait, de la même manière qu'on l'a fait pour `ENV_DEV`, forcer une certaine configuration applicative (qui en afficherait le moins possible, évidemment) parce que ton PHP est trop restrictif là.


Je vais voir si je peux le corriger dans la soirée. Ce qui est sûr c'est qu'il ne passera pas en hotfix pour outrepasser tous nos processus de validation. Ça n'a rien de bloquant, c'est juste désagréable, aussi je mettrai le commit dans develop et je te laisserai transposer les changements du commit dans tes fichiers @DreDoU.
