### ISSUE TITLE
Modif des soldes non fonctionnel

### ISSUE THREAD

**Issue by si-smo2** [wouldsmina/Libertempo#144]
Bonjour, 

Quel que soit le user avec droits responsable, RH ou avec l'admin libertempo (admin-responsable) la modification du solde de jours d'un utilisateur ne prend pas effet. 
On peut parfaitement modifier le solde dans l'appli en mode responsable ou admin, aucune erreur particulière à la validation, rien dans les logs . Par contre le solde effectif ne bouge pas.

Les tests ont été effectués avec un user responsable, un user admin, l'admin local libertempo rien à faire.

Les droits semblent bon car l'on peut supprimer un compte user sans soucis, en créer etc...

@+

**Comment by wouldsmina** [comment]
Je n'arrive pas a reproduire le problème. Ce doit etre lié à ta configuration de Libertempo. Peut tu faire l'essai sur la [demo](http://libertempo.tuxfamily.org/demo) et si tu constate le même problème, m'expliquer les étapes pour reproduire...

Les comptes qui vont bien...
Admin : admin/responsable
paolo: paolo/paolo

**Comment by si-smo2** [comment]
Bonjour, 

Je viens de faire le test sur la version de démo avec paolo/paolo et cela fonctionne . En tant que admin je peux modifier le solde de l'utilisateur k.legrand .(passage de 9 à 10 jours de reliquat..)

Je m'oriente donc vers un soucis avec ma version de Libertempo mais je ne vois pas trop d'où cela peut venir . Le serveur de test est un Wheezy avec toute les dernières versions de PHP, mysql à jour. Phpcongés 1.5.1 fonctionnait à merveille dessus, libertempo est basé sur cette version, il y a eut install normale de libertempo avec migration de la base sql 1.5.1 en 1.8.

la conf est basique, pas de tuning particulier..Qqun aurait une idée ?

@+

**Comment by wouldsmina** [comment]
ok. Tu as le même problème pour un utilisateur fraîchement créé? est ce que tu peux modifier d'autres champs? (prénom, temps partiel...)

créé un dossier debug (avec les bons droits) à la racine, puis modifie define.php:11 en remplaçant `define('ENV', ENV_PROD);` par `define('ENV', ENV_TEST));`.

dans admin\Fonction.php:2141 ajoute `debug($sql);` 

dans Libertempo, modifie le solde d'un utilisateur (uniquement 1 champ). cela va générer un fichier html dans le dossier debug. Envoi le moi.

**Comment by wouldsmina** [comment]
ajoute aussi `debug($return);` dans admin\Fonction.php:2272 juste au dessus de `return $return;`
Merci.

**Comment by si-smo2** [comment]
Bonjour,

Merci pour ces pistes. Voici le fichier HTML généré.

@+

[dbg-2016-03-31.html.zip](https://github.com/wouldsmina/Libertempo/files/197213/dbg-2016-03-31.html.zip)

**Comment by si-smo2** [comment]
Bonjour,

Pour donner encore plus d'éléments : Nous pouvons créer et/ou supprimer un user (importation depuis LDAP). A la création l'on peut affecter le nombre de jours de CP, RTT etc. et cela est bien pris en compte. Par contre une fois le user créé il est impossible d'y apporter la moindre modification que se soit sur son nom, rajouter ou enlever des jours.
Les demandes de congés et le traitement par le N+1-N+2 sont par contre fonctionnelles : un utilisateur verra sont solde diminuer, il recevra bien le mail etc..

Tout a été testé en double avec l'admin local (admin/responsable) et un compte user avec les droits admin, rh etc... Rien à faire. Toute modif semble bloquée sans message particulier,  sans erreur qui apparaissent dans les logs.

Merci de vos lumières.

**Comment by wouldsmina** [comment]
je n'arrive pas à ouvrir le zip (archive corrompu)!

**Comment by si-smo2** [comment]
Je l'ai juste renommé, c'est un faux zip. enlève l'extension.zip

**Comment by wouldsmina** [comment]
ah oui! merci

**Comment by wouldsmina** [comment]
à première vue : 
- tu obtiens bien un message d'erreur : ERREUR ! Modifications NON enregistrées ! ! mais tellement furtif...
- Le debug que tu m'a transmis, montre un problème au niveau du login dans le tableau $tab_new_user ligne 2544, il n'est pas correctement transmis.

Reste à comprendre pourquoi! je cherche...
A+

**Comment by wouldsmina** [comment]
[HORS-SUJET]
@Prytoegrian on ne peut pas avoir la synthèse de 2 debug() en même temps? c'est normal?
Actuellement le dernier debug() écrase l'html...

**Comment by wouldsmina** [comment]
@si-smo2 je pense avoir mis le doigt sur le problème mais je ne pourrais tester que demain. Est ce que tu utilise un ldap pour importer test utilisateurs? si c'est le cas, juste pour tester, modifie ta configuration (export_users_from_ldap=FALSE) puis essaye de modifier le solde d'un utilisateur...

**Comment by wouldsmina** [comment]
C'est corrigé : https://github.com/wouldsmina/Libertempo/commit/f88aae0e7484a81908f6b885a1a073280db320de

A+

**Comment by Prytoegrian** [comment]
C'est « voulu » dans le sens où on demande au debuguer d'aggréger tous les debug() appelé dans une même occurrence et de créer / reset le fichier. Si tu fais un second passage dans la même journée, le premier disparaît effectivement. 

La méthode simple serait de faire : 
```diff
- date('Y-m-d')
+ date('c')
```
[ici](https://github.com/wouldsmina/Libertempo/blob/develop/define.php#L57) pour garantir l'unicité

Joli avatar au passage.

**Comment by wouldsmina** [comment]
> Joli avatar au passage.

Merci :smile: 

> on demande au debuguer d'aggréger tous les debug() appelé dans une même occurrence

Ok. Donc si je met 2 debug a la suite, le résultat est concaténé; mais si je relance 4 fois le script, je n'aurai qu'un fichier. Si c'est ça, ça me va.

**Comment by si-smo2** [comment]
Merci pour la soluce ça fonctionne.

@+
