### ISSUE TITLE
Vue Calendrier : solde toujours visible

### ISSUE THREAD

**Issue by LRCorwin** [wouldsmina/Libertempo#145]
Bonjour,

tout d'abord, félicitations et bon courage à la Team qui a repris le dev de php_congés pour en arriver là.

Ensuite, j'ai un souci avec la vue "calendrier".
En Bout de tableau apparait toujours le solde des utilisateurs alors que dans la config, j'ai passé à **FALSE** l'attribut **affiche_soldes_calendrier** qui se trouve dans **13_Divers**.
J'ai vérifié en BdD, le false est bien présent.
Y aurait-il un bout de configuration que je n'aurais pas  #fait, ou est-ce un bug fixable ?

Merci :)

**Comment by wouldsmina** [comment]
Bonjour,
En effet, c'est un bug.
Merci.

**Comment by wouldsmina** [comment]
En fait, non. c'est pas un bug. affiche_soldes_calendrier n’influe que sur un utilisateurs simple. les admins, RH et responsable y ont toujours accès.

**Comment by LRCorwin** [comment]
Bonjour,

Aïe. C'est pour moi : j'ai en effet effectué les premiers tests avec des agents qui disposent du rôle responsable.
Je finis de valider (sur une VM de tests) le passage de php_congés 1.5 à libertempo 1.8 bêta.

Bravo pour le boulot, et désolé de ce post inutile.

**Comment by Prytoegrian** [comment]
J'ai pas pu m'empêcher de relever le fait que tu utilisais une VM pour tes tests. C'est fréquent ou ça n'a été que ponctuel ? (C'est pour savoir si je dois me mettre un coup de pied au derrière pour donner mon docker libertempo au plus grand nombre…)

**Comment by LRCorwin** [comment]
les VM, c'est quasi systématiques, mais nous n'en sommes pas encore aux containers.
Nous travaillons sur une base Kvm/Qemu, avec une VM modèle Débian Jessie.
On peaufine ensuite en fonction du besoin.
D'ailleurs, je viens de voir que Quinnis était officiellement sorti : je vais donc reprendre ma validation sur cette nouvelle base.

Mais (toujours un "mais", hein), Docker est en cible à moyen terme.

**Comment by Prytoegrian** [comment]
Ok. Je le pousserai dès que je le pourrais ; je t'invite à surveiller l'arrivée d'un docker libertempo, ça pourra certainement vous aider.
