### ISSUE TITLE
Migration de Php_conges v1.5.1 vers Libertempo 1.8

### ISSUE THREAD

**Issue by DreDoU** [wouldsmina/Libertempo#147]
Bonjour,

Sur un environnement de test Windows 2012 R2 ou est un installé un Xampp 1.7.7 
Apache 2.2.21 Php 5.3.8 

J'ai installé Php_conges v1.5.1 sans aucun problème.
J'ai téléchargé la version de Libertempo 1.8 sortie début avril.
J'ai copié l'ensemble des fichiers de Libertempo 1.8 dans le dossier php_conges , ça m'a remplacé un grand nombre de fichier.

J'ai reconfiguré le dbconnect.php et le config_ldap dans le dossier cfg.

Je pointe dans mon navigateur Web sur  http://localhost/php_conges et j'ai une page blanche qui apparaît. Je n'arrive pas sur une page pour effectuer la maj de l'application.

Aurais je oublié une étape ? Qu'elle serait le problème à votre avis ?

merci

Bonne journée

**Comment by wouldsmina** [comment]
Bonjour,

Pas de redirection vers la page d'update pour le moment. Tu dois te rendre sur l'url  http://localhost/php_conges/install et choisir de faire une mise a jour.

**Comment by DreDoU** [comment]
Bonjour,

Je viens d'essayer de me rendre sur l'url http://localhost/php_conges/install 

J'ai également une page blanche.

A quel niveau ça pourrait bloquer ?

merci

**Comment by wouldsmina** [comment]
as tu des logs apache, la réponse doit certainement s'y trouver...

Pour le passage de la 1.5.1 à la 1.8, je te conseil de copier Libertempo dans un nouveau dossier puis de suivre la procédure d'installation (par http://localhost/nouveau_dossier/ ) en prenant soin de saisir les identifiants de la base de donnée de la version 1.5.1.

**Comment by Prytoegrian** [comment]
Je me permets de mettre mon grain de sel : 
* vérifie bien que ta config BDD soit correcte et que ta BDD soit accessible à l'utilisateur en écriture 
* si tu as des connaissances en développement, tu peux faire, dans le fichier define.php
```diff
-define('ENV', ENV_PROD)
+define('ENV', ENV_TEST)
```
et utiliser la fonction `d()` sur toutes les variables qui t'intéressent.

Je plussoie @wouldsmina, l'erreur log (j'ignore où il est sous windows) nous donnera plus d'informations

**Comment by DreDoU** [comment]
Bonjour,

J'ai regardé dans le log access.log d'apache. J'ai la ligne suivante.
Mon client arrive bien sur la page.

191.10.2.28 - - [07/Apr/2016:09:45:17 +0200] "GET /Libertempo/install/ HTTP/1.1" 200 - "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"

J'ai pas d'erreur dans le log error.log  d' apache.

J'ai essayé sur un autre Xampp 1.7.7 même constat. Page blanche.

J'ai essayé sur un autre serveur de test Windows 2012 R2 avec un Xampp différent v 5.6.19 (Apache 2.4.17 , Php 5.6.19)

Je pointe sur http://localhost/Libertempo/install

La page apparaît (choix de la langue) etc ... 


Choisissez votre langue :
Choose your language :

OK

Warning: include(../cfg/dbconnect.php): failed to open stream: No such file or directory in C:\xampp\htdocs\Libertempo\includes\SQL.php on line 28

Warning: include(): Failed opening '../cfg/dbconnect.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Libertempo\includes\SQL.php on line 28

Notice: Undefined variable: mysql_serveur in C:\xampp\htdocs\Libertempo\includes\SQL.php on line 30

Notice: Undefined variable: mysql_user in C:\xampp\htdocs\Libertempo\includes\SQL.php on line 30

Notice: Undefined variable: mysql_pass in C:\xampp\htdocs\Libertempo\includes\SQL.php on line 30

Notice: Undefined variable: mysql_database in C:\xampp\htdocs\Libertempo\includes\SQL.php on line 30



J'ai l'impression que pour la version de Libertempo 1.8 il faut un Php à jour  v5.6.19

Je viens d'essayer sur mon Xampp 1.7.7 (Php 5.3.8) la version Libertempo 1.7 . 

Je pointe sur http://localhost/Libertempo/install

J'arrive bien sur la page d'installation avec le choix de la langue.

**Comment by Prytoegrian** [comment]
Wow. Ok j'ai pigé, on va te faire un correctif au plus tôt (mais tu l'as cherché t'es sur Windows aussi :-p)

Tip : c'est un problème de realPath.

**Comment by DreDoU** [comment]
Oui oui je l'ai cherché :)

Merci pour le correctif.

**Comment by Prytoegrian** [comment]
Je l'ai reproduis, Suis dessus.

**Comment by Prytoegrian** [comment]
@DreDoU j'ai fais le commit minimal pour que ça marche ; d'après mes tests tout est opérationnel (https://github.com/wouldsmina/Libertempo/commit/1593c17f2133fd4424efaa9260c3a966c6437f06). Je t'invite à télécharger la branche beta pour vérifier que tout fonctionne et si tout se passe pour toi on déploiera pour tout le monde.

**Comment by DreDoU** [comment]
@Prytoegrian 

Sur mon Xampp 1.7.7 WIndows Serveur 2012 R2 Apache 2.2.21 Php 5.3.8

Je viens d'effectuer ta modification sur le fichier define.php sur le dossier Libertempo 1.8
Quand je pointe sur http://localhost/Libertempo/install . J'ai toujours une page blanche qui me répond.
Est ce que je dois télécharger la version 1.8 beta et effectuer ta modification ? 

Pour info :
Sur mon Xampp  version    xampp-win32-5.6.19-0-VC11 (Apache 2.4.17 , Php 5.6.19) sur 2012 R2

Sans effectuer ta modification.
Quand je pointe sur http://localhost/Libertempo/install . La page d'installation apparaît. Définir la langue puis pointer sur la base.

Actuellement Php_conges 1.5.1 est en production dans mon entreprise sur un Xampp 1.7.7
Je voudrais effectuer la MAJ sur mon serveur de prod en Libertempo 1.8

merci

**Comment by Prytoegrian** [comment]
Si tu as Libertempo 1.8 pour tes tests et que tu as fait la modif dans `define.php`, c'est pas utile que tu télécharges 1.8-beta. Par contre je ne pige pas pourquoi le fait que tu aies fait ces modif rend ta page complètement blanche. Tu es toujours en `ENV_TEST` ? Le `error.log` d'apache dit un truc ?

**Comment by DreDoU** [comment]
Sur l’environnement de test 2012 R2 Xampp 1.7.7 :

Depuis le serveur je lance http://localhost/Libertempo/install

Dans mon fichier access.log d'apache , je vois que mon client se connecte bien. 200

[11/Apr/2016:14:22:40 +0200] "GET /Libertempo/install/ HTTP/1.1" 200 - "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"

Dans mon fichier  error.log d'apache, je n'ai aucune erreur.

Je suppose que c'est un problème d'affichage avec le Php, que la version de Php 5.3.8 est trop vielle pour effectuer la MaJ en 1.8 
En qu'elle version de php travailles tu ?

**Comment by Prytoegrian** [comment]
Désolé, oublié de répondre. J'ai une version php 5.4.12 et ça tourne. Je te propose de migrer sur une php 5.6 vu que c'est le seul point de divergence entre tes deux config ; si c'est pas ça, au moins on l'aura éliminé de la liste.

Profites-en pour me dire : 
* quelle est la valeur de la constante ENV
* si ça fonctionne (évidemment) avec ou sans le patch que je t'ai proposé

**Comment by DreDoU** [comment]
En effet pour faire tourner Libertempo 1.8, il faut une version de Php à jour (à partir de la version 5.4 je pense...)
J'avais eu le cas avec GLPI 0.90 (prérequis Php 5.4 minimum). 

Sur un environnement de test Xampp 1.7.7 WIndows Serveur 2012 R2 Apache 2.2.21 Php 5.3.8

J'ai pu effectuer la migration de Php_conges 1.5.1 vers Libertempo 1.7 sans problème.

Sur un autre environnement de test  2012 R2 xampp-win32-5.6.19-0-VC11 (Apache 2.4.17 , Php 5.6.19) 

J'ai pu effectuer la migration de Libertempo 1.7 vers Libertempo 1.8
Pas besoin de ta modification sur define.php pour faire tourner l'application.

Mon problème était sur la version de Php 5.3.8 trop ancienne pour faire la migration de Php_conges 1.5.1 vers Libertempo 1.8

Je pense qu'il serait intéressant de le signaler dans la documentation de MAJ de l'application sur votre site dans la partie prérequis pour faire tourner Libertempo 1.8 :) .

En tous cas merci pour votre travail ...

**Comment by wouldsmina** [comment]
Merci pour l'info. C'est corrigé dans la doc...

**Comment by Prytoegrian** [comment]
Dans le doute, vu que j'avais mois-même l'erreur, je vais laisser https://github.com/wouldsmina/Libertempo/commit/1593c17f2133fd4424efaa9260c3a966c6437f06.
NOTE : faire un cherry-pick de ce commit dans develop
