### ISSUE TITLE
reliquat lors d'une annulation de congés

### ISSUE THREAD

**Issue by pnrm** [wouldsmina/Libertempo#148]
Bonjour,
Lors de l’annulation d'un congés par un salarié est il possible  d'attribuer le congé annulé (si ce congé est déposé et annulé entre le 1er janvier et 30 avril) au reliquat (jusqu’à épuisement de celui ci) plutôt qu'au solde uniquement?
Merci

**Comment by wouldsmina** [comment]
Bonjour,
Non, ce n'est pas possible. Pourquoi attribuer au reliquat? y a t il un cadre légal à cela ou est ce une particularité de ton entreprise?

**Comment by pnrm** [comment]
En effet c'est une particularité de notre collectivité. Nous devons consommer notre reliquat de congés avant le 30 avril, si par exemple je dispose de 5 jours de reliquat et que je les poses et les annules. Ca n'apparait plus en tant que reliquat et on perd la lisibilité des congés à prendre avant le 30 avril.

**Comment by wouldsmina** [comment]
>  je dispose de 5 jours de reliquat et que je les poses et les annules...

Si tu les poses et que le responsable les valides puis les annules. c'est seulement dans ce cas que le solde varie...

Non, on ne va pas pouvoir faire cela. désolé.
