### ISSUE TITLE
pose d'absence

### ISSUE THREAD

**Issue by howvrell** [wouldsmina/Libertempo#149]
bonjour,

j'ai créé "récupération" dans la partie "configurer les types de congés à gérer" sous "Absences (Les types d'absences listés ici ne sont pas décomptés".

les responsable reçoit bien un mail de pose de récupération mais ne vois pas le contenu.

pourquoi

**Comment by wouldsmina** [comment]
Bonjour,
C'est normal, les absences n’étant pas soumis à validation, le mail ne fait qu'informer le responsable.
