### ISSUE TITLE
Utilisateur sans responsable

### ISSUE THREAD

**Issue by katacore** [wouldsmina/Libertempo#15]
Bonjour,

Tout d'abord, étant utilisateur de php_conges depuis un moment, j'ai été content de voir que le projet avait été forké et remis au gout du jour. Je tenais à vous en remercier !

Au cours de mes tests j'ai constaté quelques petites choses :

- Il n'y a pas d'avertissement pour l'utilisation de Libertempo sous Internet Explorer : c'est dommage car le Template est sans dessus dessous lorsqu'on se connecte avec ce navigateur.

- Le message : ATTENTION : certains champs saisis ne sont pas valides ...... apparait lorsqu'on essai de créer un compte utilisateur avec un tiret "-" dans le u_login. La seule manière de contourner ce problème pour l'instant est de créer le compte avec un login sans tiret puis de renommer par la suite.
Mon serveur CAS utilise des login sous la forme nom-p, les symptômes sont les mêmes avec l'import via LDAP.

- Comment un utilisateur qui n'a pas de responsable peut-il valider ses propres congés ? En effet, un utilisateur sans responsable se retrouve assigné au "conges responsable-virtuel" mais ses congés restent en attente de validation, il ne sont pas validés par défaut.

Encore merci !

**Comment by wouldsmina** [comment]
Bonjour,
1. Il est vrai que je n'ai pas poussé les test sur ie, mais lorsque j'ai testé le calcul des jours à la volée, je n'ai pas remarqué de défaut d'affichage. Sur quelle version d'ie êtes vous? Pour remédier a ce problème, je vais ajouter dans la doc qu'il faut utiliser un navigateur respectant les normes du web...

2. Pour le login, ce sera corrigé rapidement...

3. comment faîtes vous avec php-conges?

**Comment by katacore** [comment]
1. Les tests ont été effectués sur IE 11 exclusivement. Le navigateur n'affiche pas certaines images de navigation ainsi que les différents cadres du Template. Elle devient donc suffisamment altérée pour être inutilisable. Voila pourquoi je proposais un message d'avertissement voire un script bloquant l'utilisation d'IE.

2. ok impeccable

3. Sur Php conges un utilisateur qui a le respons pas de responsable ne passe pas par l'étape de validation : il pose ses congés et ceux-ci sont directement reportés comme congés validés dans l'application. Dans Libertempo, l'utilisateur ayant le responsable virtuel (donc qui n'a pas de responsable) se retrouve avec des congés en instance de validation mais personne n'a le pouvoir de les valider car le responsable virtuel n'est pas un compte utilisable.

**Comment by wouldsmina** [comment]
1.Je vais voir ce que je peux faire pour mettre un message au login avec IE.

3.Je connaissais pas cette subtilité de php_conges. je n'arrive pas à trouver quelle partie du code (v.1.5.1) effectue cela : j'ai recherché ou la fonction "soustrait_solde_et_reliquat_user" était appelée et c'est uniquement le cas pour le resp et l'admin! Il faut que je l'installe pour voir...
En tout cas, il existe bien un compte de responsable virtuel (conges/conges). Le HR doit aussi pouvoir valider les congés de tous (pour le moment c'est pas le cas :smile:, je fais encore des test avant de mettre à jour).

Merci pour les infos.

**Comment by katacore** [comment]
Pour IE, j'utilise un code pour d'autres applis qui détecte le navigateur de la manière suivante : 
if(preg_match('/MSIE/i',$_SERVER['HTTP_USER_AGENT']))
	{ echo "";	} else { echo "ATTENTION, Vous utilisez Internet Explorer"; }
On peut aussi l'utiliser pour bloquer purement et simplement le login sur détection de IE. 
Source avec les autres browser : 
http://www.itx-technologies.com/blog/2190-detecter-un-fureteur-ie-firefox-chromeen-php

Pour les personnes sans responsable ou les HR (donc sans personne au dessus hiérarchiquement), une solution pourrait consister à mettre l'utilisateur responsable de lui-même, cela lui permettrait de voir ses propres demandes en mode responsable et de les valider. J'ai testé à l'instant sur php_conges 1.5.1 et cela fonctionne. Le soucis dans Libertempo, c'est qu'un utilisateur ne peut se voir lui même dans traiter toutes les demandes du mode responsable.

**Comment by katacore** [comment]
Une autre chose constatée au moment de la modif d'un compte utilisateur : quand le mode DEBUG est activé dans admin_modif_user.php et que les types de congés exceptionnels enfant malade et maladie de l'install par défaut existent, la var $valid_3 est = a vide à la validation du formulaire. Du coup, l'enregistrement est annulé. Si tous les types de congés exceptionnels sont supprimés $valid_3 est ok (forcement) et la modif passe sans problème. Si on ajoute ensuite un nouveau type de congés exceptionnels, cela refonctionne, le $valid_3 est ok

**Comment by wouldsmina** [comment]
J'ai ouvert un nouveau ticket pour votre dernier message...

En effet, dans Libertempo, il a été décidé qu'un responsable ne pouvait pas se valider lui même. 
Je pense plutôt remettre en place la possibilité de ne pas mettre de responsable (et donc que les demandes de congés soit directement "ok" et décomptés).

Merci pour l'exemple de code pour IE, je m'en occupe rapidement.

**Comment by wouldsmina** [comment]
Sauf erreur de ma part, php_conges 1.5.1 passe obligatoirement une demande par un responsable, virtuel ou non. Reprenons la procédure d'une de mande de congés : 
- a l’exécution de la page utilisateur/user_index.php, le formulaire de demande "saisie_nouveau_conges()" est appelé ligne 312 (si l'onglet à été selectionné). cette fonction (dans le fichier fonction_conges.php ligne 1052) affiche le formulaire de saisie.
- à la validation de ce formulaire, la variable $new_demande_conges (entre autres) et passé à 1. Ce qui a pour effet d’exécuter la fonction "new_demande()" fichier utilisateur/user_index.php ligne 436.
-Cette fonction passe systématiquement les demandes de congés et de congés exceptionnels à l'état demande : 
if( (get_type_abs($new_type, $mysql_link, $DEBUG)=="conges") || (get_type_abs($new_type, $mysql_link, $DEBUG)=="conges_exceptionnels") )
			$new_etat="demande" ;

Si je vous explique tout cela, c'est parce que je pense que votre installation de php_conges à peut être été modifiée (en local) pour prendre en compte cette particularité. 
Pourriez vous comparer le fichier utilisateur/user_index.php, en particulier le dernier point, de votre install avec celui en téléchargement sur le site php_conges?

**Comment by katacore** [comment]
Bonjour,

Nous avons trois Php_conges qui tournent chez nous à l'heure actuelle. ils ne sont effectivement pas égaux, des modifications ont été effectuées sur certaines parties du code pour les calendriers, l'affichage, la présentation des infos, la génération icalc, la création d'un espace consultation exclusif etc. Je me suis un peu penché sur cette question après votre message  : 

- Deux de nos plateformes utilisent le système suivant : les comptes des responsables (n'ayant aucune personne au dessus pour valider les congés) ont comme responsable leur propre login. Ce qui a pour effet de leur donner les droits sur la validation de leurs congés sans toucher au processus de demande et de validation d'origine de Php_conges. Cette manipulation est autorisé par défaut dans le logiciel.
- La troisième plateforme a été modifiée pour qu'un compte avec responsable = Y et le compte responsable-virtuel en responsable ne passe pas par la demande. En effet, les congés posés sont immédiatement validés et décomptés pour ces comptes.

Je me suis pour l'instant concentré sur le comportement du logiciel et je n'ai pas encore regardé comment cela a été fait pour la troisième plateforme. Souhaitez vous que je me penche sur le code pour vous le communiquer ?

**Comment by wouldsmina** [comment]
Oui, ça pourrait être intéressant de proposer une option dans la config pour valider automatiquement les demandes des utilisateurs avec le responsable virtuel. Ça me parait même assez simple à faire. il suffirait d'ajouter une condition dans la fonction new_demande() : si $valid_virtuel_auto et rep_du_user==conges alors $new_etat=ok ; appel de la fonction soustrait_solde_et_reliquat_user()...
C'est peut être ce que vous avez...
Par contre, ce ne sera pas dans cette version.

Je serais bien intéressé par vos modifications sur ical. Puis je en savoir plus à ce sujet?
Merci.

**Comment by katacore** [comment]
Nous avons mis en place une génération automatique de fichier ical pour tous les utilisateurs de Php_conges. Nous voulions que ceux-ci puissent synchroniser via URL leur agenda zimbra et/ou leur smartphone avec la plateforme. Concrètement, la date de début des évènements dans le fichiers correspond à la date de début du dernier exercice. Puis tous les évènements suivants cette date sont indiqués au fur et a mesure dans le fichier. A chaque modification, ajout ou suppression du responsable sur un compte utilisateur, une update du fichier ical est déclenchée. Les fichiers sont générés au départ en randomize sur 8 caractères alphanumériques pour que les autres utilisateurs ne puissent pas lire les congés d'un autres. Un lien dans le panneau des congés permet à l'utilisateur connecté de connaitre l'URL à ajouter pour effectuer sa synchro.

**Comment by wouldsmina** [comment]
ça m’intéresse encore plus! pouvez vous me transmettre le code source? wouldsmina@tuxfamily.org

**Comment by katacore** [comment]
ok, il faut que je demande l'autorisation à la personne ayant fait ces modifs en premier lieu et je vous les transmets dès que c'est le cas.

**Comment by wouldsmina** [comment]
j'ai répondu sur l'autre ticket à propos du bug des congés exceptionnels.

**Comment by wouldsmina** [comment]
validation automatique des utilisateurs sans responsable poussé en beta.
Merci.

PS : Si tu pouvais me répondre dans le ticket #16 à propos du bug que tu m'avais mentionné, ça m'aiderait.
