### ISSUE TITLE
L'impression du PDF du calendrier a perdu les couleurs

### ISSUE THREAD

**Issue by LRCorwin** [wouldsmina/Libertempo#152]
Hello,

la mise en prod de la 1.8 quinnis depuis Php-conges 1.5 s'est bien passée : les utilisateurs apprécient le nouveau look.
Le serveur est en Débian Jessie mise à jour (enfermée dans une VM kvm/qemu).

Les utilisateurs me remontent cependant un souci lors de l'impression du calendrier et de la génération du pdf de la vue calendrier : on perd les couleurs !
J'ai fait des tests sur plusieurs stations (Linux et Windows) avec plusieurs navigateurs et viewers PDF.

L'impression directe est purement monochrome (on n'a même pas les gris sur les cases weekend).
Sur le pdf, on a le tableau de légende des absences et les jours de weekend grisés, mais pas les congés, rtt, absences...

Un problème de CSS alternatives pour ces modes ?

**Comment by wouldsmina** [comment]
Bonjour
Le calendrier pdf n'est pas encore au top. Je cherche justement une alternative a html2pdf qui ne permet pas d'utiliser le css comme on voudrait. Pour l'impression direct je regarde ce qui ne va pas...

**Comment by LRCorwin** [comment]
merci :)

Tant que j'y suis (mais tu préfères peut-être que j'ouvre un autre ticket ?), je viens de regarder la fonction "éditions papier" : on obtient un premier tableau avec les droits annuels et les soldes, puis un second qui récapitule bien les absences suite à congés payer, mais on ne voit pas apparaître les RTT...
Fonctionnement normal ?

**Comment by wouldsmina** [comment]
A priori c'est pas normal. Oui, fait un nouveau ticket avec screenshot si possible.

**Comment by wouldsmina** [comment]
> L'impression directe est purement monochrome (on n'a même pas les gris sur les cases weekend).

J'ai pas de problème avec Firefox. Tu utilise ie?

**Comment by LRCorwin** [comment]
Non, pas d'IE, mais je vais tester aussi.
Firefox 35esr et Chrome sur Win7 Entreprise ;
IceWeasel 31.6 et Chromium sur Debian Jessie.
On passe par un serveur Cups pour l'impression, mais je doute que cela ait un quelconque impact...

**Comment by Prytoegrian** [comment]
Corrigé par #229, il n'y a plus de calendrier PDF car aucun rendu n'était probant. Nous espérons faire ressortir un besoin suite à la livraison.
