### ISSUE TITLE
Problème envoi de mail

### ISSUE THREAD

**Issue by CCA171** [wouldsmina/Libertempo#155]
Bonjour,

Impossible d'envoyer un mail automatique, un message d'erreur apparaît : 

2016-04-19 09:01:29 Impossible d'instancier la fonction mail. Message was not sent 
Mailer Error: Impossible d'instancier la fonction mail.

J'ai renseigner mes paramètres SMTP dans config_smtp_new 

Que faire ?

**Comment by wouldsmina** [comment]
Bonjour,
Il faut renommer le fichier config_smtp_new.php en config_smtp.php

**Comment by CCA171** [comment]
Oui en effet, maintenant un autre message d'erreur m'affiche ceci :

Mailer Error : Echec de la connexion SMTP : https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by wouldsmina** [comment]
Cela me semble plutot lié a ton serveur SMTP. c'est sous Exchange?

**Comment by CCA171** [comment]
Tout est réglé, le problème venait de GMAIL qui bloquait la connexion, il pensait à une tentative de connexion non sécurisée, 

Merci pour votre aide et à la rapidité de vos réponses :)

**Comment by wouldsmina** [comment]
:+1:
