### ISSUE TITLE
Pas d'affichage des RTT sur les éditions

### ISSUE THREAD

**Issue by LRCorwin** [wouldsmina/Libertempo#156]
Bonjour,

comme signalé sur un autre ticket, j'ai un souci avec les éditions "papiers" (ou pdf) des congés.
J'ai bien le listing des congés payés mais pas le récapitulatif des RTT.
Pourtant le tableau en en-tête de la page présente les bons droits et soldes.

J'ai une capture d'écran d'un compte, mais malgré ses 131ko, github n'arrive pas à la récupérer :(
(_Something went really wrong, and we can’t process that file._ ￼)

**Comment by wouldsmina** [comment]
Bonjour,
https://lut.im pour la capture
Merci.

**Comment by LRCorwin** [comment]
hop
ici : https://lut.im/t0DTmPgJdV/qQd9wyG3DxGDhHQ3.jpg

**Comment by wouldsmina** [comment]
Ok! j'y étais pas! je pensais que tu me parlais de l'édition du calendrier et non des états récapitulatifs...

**Comment by wouldsmina** [comment]
corrigé sur develop
