### ISSUE TITLE
Autovalidation systématique après upgrade depuis PHP_CONGES

### ISSUE THREAD

**Issue by LRCorwin** [wouldsmina/Libertempo#157]
Bonjour,

une semaine après la mise en service de Quinnis en upgrade depuis Php_Congés 1.5, un vrai problème apparait : toutes les demandes des utilisateurs passent en "auto validation".

Dans les logs, pour chaque agent concerné, j'ai le bon login (date etc) puis "saisie de congés" et dans la colonne état "OK".
Si je remonte dans les lignes de logs de la précédente version, on peut lire en commentaire "demande de congés" et dans la colonne état "demande".

Tous les utilisateurs font partie d'un groupe qui a au moins un responsable désigné.
Chaque compte d'utilisateur a aussi un responsable nommé.

J'ai bien vu le schéma ici : http://libertempo.tuxfamily.org/documentation/deposer-une-demande/
j'ai donc l'impression que mon workflow dégage directement par la droite en "Aucun".

Y a-t-il une manière de vérifier ça ? et de bloquer l'autovalidation ?

merci

**Comment by wouldsmina** [comment]
Bonjour,

Dans le menu de modification d'un utilisateur, vérifie que le responsable direct est bien renseigné. Il ne faut pas que ce soit le responsable virtuel (sinon validation auto).

**Comment by LRCorwin** [comment]
oui oui, le responsable est bien renseigné.
Sur un utilisateur, je l'ai changé pour "voir", mais j'ai le même mécanisme avec cette différence dans la syntaxe des logs (saisie VS demande).

A force, je me demande si mes nombreux problèmes ne proviennent pas de la montée en version depuis php_congés 1.5.....

**Comment by wouldsmina** [comment]
Non, je ne pense pas que ce soit lié a l'upgrade. 
Est ce que tu as une plate-forme de test? J'ai besoin que tu fasses des manipulations dans le code pour trouver l'erreur : 
- dans define.php, passer l'environnement à TEST : `define('ENV', ENV_TEST);`
- dans utilisateur/Fonctions.php:98 ajoute `d($resp_du_user);` juste en dessous de : 
````
 if( $valid ) {
            if( in_array(\utilisateur\Fonctions::get_type_abs($new_type) , array('conges','conges_exceptionnels') ) ) {
                $resp_du_user = get_tab_resp_du_user($_SESSION['userlogin']);
````

**Comment by wouldsmina** [comment]
On peut voir ça en direct sur irc://irc.tuxfamily.org/Libertempo si tu as le temps...

**Comment by wouldsmina** [comment]
Pour ton installation en prod, tu peux commenter les lignes suivantes dans le fichier utilisateur/Fonctions.php:98
````
//                $resp_du_user = get_tab_resp_du_user($_SESSION['userlogin']);
//                if (array_key_exists('conges', $resp_du_user)||empty($resp_du_user)) {
//                    $new_etat = 'ok' ;
//                    soustrait_solde_et_reliquat_user($_SESSION['userlogin'], "", $new_nb_jours, $new_type, $new_debut, $new_demi_jour_deb, $new_fin, $new_demi_jour_fin);
//                } else {
                    $new_etat = 'demande' ;
//                }
````
$new_etat = 'demande' ; ne doit pas être commenté.

cela va retirer l'auto-validation.

Je vais ajouter une option dans la config pour la désactivé pour la 1.9...

**Comment by LRCorwin** [comment]
La bonne nouvelle : la parade fonctionne très bien (test à l'instant).
La moins bonne : comme dit sur IRC (où je suis connecté), j'ai créé à part une instance libertempo, monté avec une BdD vierge (en utilisant le script sql 1.5 fourni dans le répertoire install/sql) -> je n'ai pas d'autovalidation.
MAIS je n'ai pas remis en route la gestion par groupe, juste l'import des users du LDAP...

En faisant le test dont tu parles en "env_test", je dois m'attendre à quoi ?
je pourrais copier/coller ma VM pour faire des essais, mais je ne peux pas faire ça "à chaud"

**Comment by wouldsmina** [comment]
Arf, je suis plus devant mon pc. Je reviens vers 19h. Sinon on remet ça a demain matin 9h30 si tu veux.

Pour le debugage, j'ai oublié de te dire qu'il faut créer un dossier debug a la racine du site avec les bons droits. Après cela, dépose une demande. Cela va générer un fichier html dans le dossier debug...

**Comment by LRCorwin** [comment]
ok ! j'essayerai ça demain matin, avant que mes users débarquent !

**Comment by LRCorwin** [comment]
J'ai créé le fichier debug à la racine du site, droits 777 et le bon proprio, mais rien ne s'y est créé.
Par contre, dans l'appli, au moment de la demande de congés, j'ai eu ça : 
https://lut.im/oMRdrkeBTz/porB3ZpTJfzUVtUs.jpg

**Comment by wouldsmina** [comment]
C'est un dossier debug. Mais la capture d'écran montre qu'il y a bien le responsable virtuel «conges» dans la boucle...
Mais vue que ce user a plusieurs resp, ca devrait pas auto valider...

**Comment by LRCorwin** [comment]
Faudrait-il que je désactive en BdD ce responsable virtuel ?
Parce que ce compte "congés", on ne le voit pas par ailleurs, si ?

**Comment by wouldsmina** [comment]
je suis dispo sur irc...

**Comment by wouldsmina** [comment]
Donc, finalement le problème vient bien de PHP_conges (donc de l'upgrade comme tu le soupçonnais) qui ajoute automatiquement l'utilisateur virtuel "conges" en responsable de chaque groupe. Pour remédier à ce problème, il faut supprimer dans la table `conges_groupe_resp` toute les lignes contenant `gr_login='conges'`. 

PS : J'ai oublié de te demander (sur irc) si tu utilise la double validation? Si c'est le cas, vérifie aussi la table `conges_groupe_grd_resp`.

**Comment by LRCorwin** [comment]
En effet, on utilise la double validation pour certains groupes.
Je regarderai la BdD tout à l'heure.

**Comment by Prytoegrian** [comment]
@LRCorwin je t'invite à mettre à jour avec la nouvelle 1.8, on a corrigé

**Comment by Prytoegrian** [comment]
Corrigé dans la [1.8.1](https://github.com/wouldsmina/Libertempo/releases/tag/v1.8.1)
