### ISSUE TITLE
CCA171

### ISSUE THREAD

**Issue by CCA171** [wouldsmina/Libertempo#158]
Bonjour,

J'aimerai savoir si il est possible lorsque l'on ajoute un utilisateur dans la partie "Saisie des jours d'absence pour RTT ou temps partiel" d'ajouter le samedi ?

Merci,

**Comment by wouldsmina** [comment]
Bonjour,

Oui, il faut simplement [configurer les jours ouvrés](http://libertempo.tuxfamily.org/documentation/config/#Conf09).
