### ISSUE TITLE
RH : Ajout de conges individuel impossible

### ISSUE THREAD

**Issue by wouldsmina** [wouldsmina/Libertempo#159]
Impossible d'ajouter des jours à un utilisateur. Pas de message d'erreur, mais pas d'incrémentation du solde! En tant que responsable, pas de problème.

**Comment by lolito34** [comment]
Bonjour,

Je me permets d'écrire dans ce post car je rencontre actuellement le même problème. J'ai pourtant la dernière version installé (1.8.1), est-ce le fait d'avoir fait une migration de la 1.5 à la 1.8.1 qui en serait la cause ?

Merci

**Comment by lolito34** [comment]
Oups !! au temps pour moi, je me suis trompé de version, j'étais en 1.8. En passant en 1.8.1, le problème est résolu. Désolé :(
