### ISSUE TITLE
Pb de mise à jour V1.7 vers 1.8

### ISSUE THREAD

**Issue by johnfr59** [wouldsmina/Libertempo#163]
Bonjour,

Suite à la sortie de la version 1.8 j'ai voulu remplacer ma version 1.7. Cependant, après le téléchargement et le remplacement du dossier j'ai un message Restricted access sur IE.

Pouvez vous m'aider?

**Comment by wouldsmina** [comment]
Bonjour,

Avez vous exécuté la procédure de mise à jour? http://libertempo.tuxfamily.org/documentation/install_update/

**Comment by johnfr59** [comment]
Bonjour,

C'est exactement la procédure que j'ai faite.

**Comment by wouldsmina** [comment]
Si vous avez un peu de temps, je suis disponible sur irc irc://irc.tuxfamily.org/Libertempo.

**Comment by johnfr59** [comment]
Bonjour je viens de revenir.
Je ne connais pas ce procédé IRC. Merci de m'envoyer le lien dés que vous êtes dispo.

**Comment by wouldsmina** [comment]
[cliquez ici](https://client02.chat.mibbit.com/?url=irc%3A%2F%2Firc.tuxfamily.org%2FLibertempo) pour utiliser un client en ligne.

**Comment by Prytoegrian** [comment]
C'est un peu maigre comme info ; aide-nous à t'aider : peux-tu nous dire : 
* à quelle page tu tentes d'accéder ?
* quelles sont les versions de php / mysql ?
* des erreurs apparaissent-elles dans le logger du serveur web (pour apache /var/log/apache2/error.log)

**Comment by wouldsmina** [comment]
@Prytoegrian j'ai discuté avec @johnfr59 sur irc, il  devait mettre à jour ses serveurs, mais je n'ai pas eu de nouvelle. Je ferme, @johnfr59 si tu as toujours le problème n'hésite pas a revenir sur ce ticket.
