### ISSUE TITLE
Probleme installation

### ISSUE THREAD

**Issue by ComCB42** [wouldsmina/Libertempo#164]
J'ai un probleme durant l'installation de Libertempo,
tout d'abord j'ai quelques Warning lorsque je lance l'installation

```
Warning: mysqli::mysqli(): in C:\Program Files (x86)\EasyPHP\www\Libertempo\includes\SQL.php on line 106
Warning: mysqli::query(): Couldn't fetch includes\Database in C:\Program Files (x86)\EasyPHP\www\Libertempo\includes\SQL.php on line 138
Warning: includes\Database::query(): Couldn't fetch includes\Database in C:\Program Files (x86)\EasyPHP\www\Libertempo\includes\SQL.php on line 141
```

J'ai crée ma base de données db_conges avec l'utilisateur conges et un mot de passe, mais lordque je le renseigne un autre message d'erreur survient : 

`Fatal error: Call to undefined function write_db_config() in C:\Program Files (x86)\EasyPHP\www\Libertempo\install\index.php on line 131`

Que faire ?

**Comment by wouldsmina** [comment]
Bonjour, 

quel version de PHP? je pense que le problème est le même que #147. Auquel cas, il faut modifier le fichier define.php comme ici : https://github.com/wouldsmina/Libertempo/commit/1593c17f2133fd4424efaa9260c3a966c6437f06

**Comment by ComCB42** [comment]
C'est réglé il m'a suffit de relancer l'installation :)
Merci de votre aide
