### ISSUE TITLE
Jours de fermeture par groupe non pris en compte

### ISSUE THREAD

**Issue by Shadok** [wouldsmina/Libertempo#165]
La fonction is_active recherche un login dans le champ u_login de conges_users.
Mais quand on utilise un LDAP, en tout cas un Active Directory, le champ u_login correspond à un genre d'id (je n'en ai pas trouvé trace dans l'ad).

Pour exemple, le champ u_login de mon utilisateur est 6768696c74.

Cela pose pas mal de problèmes. Par exemple, si j'ajoute un jour de fermeture, rien ne sera ajouté dans conges_periode, tous les utilisateurs étant considérés comme inactifs.

**Comment by wouldsmina** [comment]
Le champ u_login est au format binary. En effet, cela ne pose aucun problème.

**Comment by Shadok** [comment]
Ok, donc le problème est ailleurs, car is_active ne renvoie pas true.
Je regarde.

**Comment by wouldsmina** [comment]
Mais le problème des fermetures ne viens pas de la. Sinon ce serait aussi le cas pour une fermeture globale. Je ferai un debug de is_active ce soir pour comprendre d'ou viens le problème...
A+

**Comment by Shadok** [comment]
Ok, vu.
Dans hr/Fonctions.php, line 2766, tu as ceci :
```
$current_login = trim($current_login, "\'");
```

Sauf que $current_login est sous la forme "<login>" donc le trim ne retire rien, et login cherche <"login"> dans la base au lieu de <login>.

**Comment by wouldsmina** [comment]
Ouaip, ca me parait plausible!

**Comment by Shadok** [comment]
Confirmé dans get_list_users_du_groupe, de fonctions_conges.php, tu as ceci :
```
$list_users[] = '"'.\includes\SQL::quote($resultat1["gu_login"]).'"';
```

Par contre, get_list_all_users utilise bien des apostrophes.

**Comment by wouldsmina** [comment]
Testé? Tu me fait un petit PR que je puisse tester stp?

**Comment by Shadok** [comment]
J'ai besoin de ton aide suite à mes tests précédents avant de pouvoir tester sur ma prod, j'ai le 06/05/2016 qui est grisé sur le calendrier alors que j'ai viré l'entrée dans conges_jours_fermeture et que j'ai n'ai rien d'autre en base sur ce jour là.

**Comment by Shadok** [comment]
Je rajoute un ```
$current_login = trim($current_login, "\"");
```
dans verif_periode_chevauche_periode_groupe() et dans commit_annul_fermeture() et je teste.

**Comment by Shadok** [comment]
Je confirme la résolution du bug, je prépare la PR.

**Comment by Shadok** [comment]
PR faite.

**Comment by Prytoegrian** [comment]
Corrigé dans la [1.8.1](https://github.com/wouldsmina/Libertempo/releases/tag/v1.8.1)
