### ISSUE TITLE
Erreur à l'édition PDF "Truncated incorrect double"

### ISSUE THREAD

**Issue by igual** [wouldsmina/Libertempo#169]
Bonjour,

Je suis RSI dans une PME et nous allons mettre Libertempo en production le mois prochain.
J'ai une erreur lors des impressions PDF 
Je subodore un pb de "," et "." puisqu'il interprète une liste en nombre.
Mais pourquoi cela ne plante que là ?
Un paramètre langue à modifier ?
Je suis sur IIS/Windows serveur 2008 R2

Merci,

Erreur : 
login : BCAPALDI
uri   : /edition/edition_pdf.php?user_login=PBOULET&edit_id=0
dump  : ../dump/sql_1462194794.dump

file  : D:\APPS\Libertempo\edition\fonctions_edition.php
line  : 96
fx    : $SQL->query
error : Truncated incorrect DOUBLE value: '1, 2, 11'
sql   : UPDATE conges_periode SET p_edition_id='18' 
			WHERE p_login = 'PBOULET'
			AND p_edition_id IS NULL
			AND (p_type IN ('1, 2, 11') )
			AND (p_etat!='demande')

**Comment by Prytoegrian** [comment]
Hello ! Il te suffit de supprimer les quotes autour de « 1, 2, 11 » dans la zone incriminée. Par contre, peux-tu nous dire quelle version de libertempo tu cherches à utiliser ? Je n'ai pas les mêmes fichiers que toi, ce qui me fait dire que ta version n'est pas toute fraîche. Pour que tu puisses profiter du correctif qu'on va déployer ainsi que des améliorations qu'offre la dernière version, je te laisse jeter un œil à https://github.com/wouldsmina/Libertempo/releases

**Comment by igual** [comment]
Merci beaucoup pour cette réponse, en effet je me suis trompé de serveur j'ai envoyé le message issus de la 1.7 (qui est en pré-production pilote), voilà le message de la version 1.8 en test sur un deuxième serveur. Ce qui est étonnant c'est que le message apparaît lors du lancement de l'édition dans la section "Prochaine Edition", par contre la ligne s'insère bien dans la table "historique des éditions" et le clic sur "Editer à nouveau en PDF" fonctionne bien.

J'ai trouvé la ligne de code associée à l'update dans /edition/Fonctions.php (module enregistrement_edition)
AND (p_type IN (\''.$list_abs_id.'\') )
Vous dites supprimer les quotes autour de "1,2,11"  ?? (;-) c'est à dire ?

login : BCAPALDI
uri   : /edition/edition_pdf.php?user_login=PBOULET&edit_id=0
dump  : ../dump/sql_1462259490.dump

file  : D:\Apps\Libertempo\includes\SQL.php
line  : 59
fx    : $SQL->query
error : Truncated incorrect DOUBLE value: '1, 2, 11'
sql   : UPDATE conges_periode SET p_edition_id='23'
                WHERE p_login = 'PBOULET'
                AND p_edition_id IS NULL
                AND (p_type IN ('1, 2, 11') )
                AND (p_etat!='demande')

**Comment by Prytoegrian** [comment]
Je ne le reproduis pas malheureusement, mais ce que je voulais dire dans mon commentaire précédent était ceci, à corriger dans `edition/Fonctions::1250` : 

```diff
$sql_update = 'UPDATE conges_periode SET p_edition_id=\''.$new_edition_id.'\'
                 WHERE p_login = \''.$login.'\'
                 AND p_edition_id IS NULL
-                AND (p_type IN (\''.$list_abs_id.'\') )
+                AND (p_type IN ('.$list_abs_id.') )
                 AND (p_etat!=\'demande\') ';
         $ReqLog_update = \includes\SQL::query($sql_update);

```
Dis-nous si cela a corrigé ton problème. Sinon, peut-on avoir les versions de php et de mysql (surtout mysql en fait) ?

**Comment by igual** [comment]
Super cela fonctionne.
Pb résolu, un grand merci.
Je suis en MySQL 5.6.20 et Php 5.4.31

Je vais me permettre une dernière (?) question dans un autre ticket.

**Comment by Prytoegrian** [comment]
Corrigé dans la [1.8.1](https://github.com/wouldsmina/Libertempo/releases/tag/v1.8.1)
