### ISSUE TITLE
Le lien du calendrier n'apparaît pas sur mobile

### ISSUE THREAD

**Issue by Shadok** [wouldsmina/Libertempo#176]
Je viens de tester la 1.8 depuis mon smartphone (Nexus 4 sous Android 6.0.1 / Cyanogen) et je n'ai pas le bouton du calendrier qui apparait (test sous Firefox).

**Comment by Prytoegrian** [comment]
Tu peux nous donner davantage d'info ? Par exemple : 
* le type de la page,
* le type d'utilisateur,
* l'endroit où il est sensé apparaître (oui, je sais... mais ya du legacy)

Enfin, tout ce qui est nécessaire pour reproduire en somme.

**Comment by Shadok** [comment]
Type de page ? 
J'ai essayé avec mon compte admin, en me promenant un peu partout, à savoir dans le mode utilisateur, responsable, rh et admin. 
Normalement je l'attendais dans la barre de menu ou en haut à droite, dans la barre de menu horizontale. 
Bref, je ne l'ai trouvé nulle part.

**Comment by Prytoegrian** [comment]
Je ne reproduis ni chez moi, ni sur la demo :disappointed:
@wouldsmina une idée ?

**Comment by wouldsmina** [comment]
Je confirme le bug, la barre verticale n'apparaît pas sur smartphone.

**Comment by Prytoegrian** [comment]
Ah exact, j'avais zappé qu'il y avait du responsive.

**Comment by Prytoegrian** [comment]
Ok, je confirme aussi. La solution peut être à rapprocher de #104, mais je vais avoir la même remarque que j'ai eu là-bas. Vous en pensez quoi vous ?

**Comment by Shadok** [comment]
Il faudrait quand même avoir accès au calendrier, mais sans pour autant  n'afficher une barre verticale juste pour un bouton. 
Pourquoi ne pas le caser sur la barre horizontale à droite ou dans le menu, juste pour la version mobile ? (faisable en css)

**Comment by Prytoegrian** [comment]
C'est certain, c'est d'ailleurs pour ça que je l'ai mis en Bug. J'émettais des réserves vis à vis du message envoyé aux utilisateurs et à la perte de repères mais en fait ça va bien au delà, car la déco n'est pas possible non plus. Donc je sais pas.

**Comment by Shadok** [comment]
Généralement, en design responsive, tout est dans le menu, donc c'est là qu'il faudrait mettre le calendrier et la déconnexion.

**Comment by Prytoegrian** [comment]
Nous ne pouvons pas faire ce que tu proposes @Shadok car les choix actuels ont définis que ce qu'il y avait dans le menu était les « Modes » d'utilisation de LT.

Après réflexion, il s'agit d'un bug, nous devons donc le considérer comme tel, autrement dit corriger le problème sans chercher à améliorer l'existant ; ça c'est un autre sujet.

Le menu est ce qu'il est, nous devons en prendre acte pour le moment ; sur mobile / tablette nous devons nous assurer d'avoir les mêmes fonctionnalités que sur desktop. Je propose donc pour corriger ça d'afficher le calendrier et la déconnexion dans une ligne au-dessus / au-dessous. C'est du bricolage, c'est moche, mais ça corrige le bug.

**Comment by Shadok** [comment]
Pas de problème. Pour la suggestion d'amélioration, je ferai, à l'occasion, une PR pour la 2.0.

**Comment by Shadok** [comment]
Voilà, j'ai quand même fait un test en groupant tout sur le menu déroulant (c'est quand même plus pratique, surtout sur mobile, de tout avoir au même endroit) :p

**Comment by Prytoegrian** [comment]
Ref https://github.com/wouldsmina/Libertempo/pull/181#issuecomment-220151273

La première partie est en passe d'être faite, restera plus qu'à mettre le burger.
