### ISSUE TITLE
echange rtt : Mois de 32 jours

### ISSUE THREAD

**Issue by VV666** [wouldsmina/Libertempo#18]
Le mois d'août compte 32 jours ... Pour corriger cela : 
dans : user_echange_jour_absence.php

remplacer : $last_jour_mois_timestamp    = mktime(0,0,0,$mois +1 , 1,$year);
par            : $last_jour_mois_timestamp    = mktime(0,0,0,$mois +1 , 0,$year);

Corrigé par Vincent ;-)

**Comment by wouldsmina** [comment]
Est ce que cela n'influe pas sur les autres mois?
