### ISSUE TITLE
Demande de congés automatiquement validée alors qu'elle ne devrait pas

### ISSUE THREAD

**Issue by jjcadt34** [wouldsmina/Libertempo#182]
Bonjour,

Je viens d'installer Libertempo.
Je fais des tests. 
Je suis en statut resposable.
Quand une personne de mon équipe fait une demande, je reçois bien le mail, mais je ne trouve pas la demande dans les demandes en attente et dans l'historique de l'utilisateur, le congés est déjà compté et le décompte des jours est fait et correct.
Bref, c'est comme s'il n'y avait pas de validation...
Dans l'admin, j'ai pourtant bien en "configuration de l'application" en 05 Utlisateur la variable user_saisie_demande=TRUE.
Une idée ? Merci par avance.

**Comment by Prytoegrian** [comment]
Hello !
En quelle version es-tu ?
Quel responsable est noté dans le profil de l'utilisateur, toi-même ?
Les groupes sont-ils configurés ?

**Comment by jjcadt34** [comment]
Oh merci de ta réponse.
Oui mes groupes sont configurés et le suis bien responsable du groupe.
Je suis en 1.8
Pour ce groupe il n'y a pas de double validation. 
Par contre une chose m'étonne, dans l'utilisateur de mon groupe avec qui je fais les tests, le "Identifiant du responsable" est une autre personne (la secrétaire de direction). Pourquoi ? Quelle est la différence entre "identifiant du responsable" dans l'utilisateur et le responsable du groupe de cet utilisateur (moi) ?
J'ai une autre question. Après sa demande de congés mon utilisateur ne reçoit pas de message de confirmation de prise en compte de sa demande alors que je reçois bien le mail comme quoi il y a une demande en attente.
Merci

**Comment by Prytoegrian** [comment]
*Le joueur @Prytoegrian invoque @wouldsmina*

**Comment by wouldsmina** [comment]
Hello, je suis déconnecté tout le we. Je m'en occupe dès mon retour...

**Comment by wouldsmina** [comment]
@jjcadt34, tu as fait une installation ou une upgrade?
Dans tous les cas, passes à la 1.8.1 et met toi comme responsable de
l'utilisateur. Si le problème persiste, j'essaierai de reproduire...

**Comment by wouldsmina** [comment]
ping @jjcadt34

**Comment by jjcadt34** [comment]
Ok je vais essayer

**Comment by wouldsmina** [comment]
la version 1.8.1 est spécialement faites pour corriger ce bug, ça devrait le faire...

**Comment by jjcadt34** [comment]
On vient de le vérifier. On fait les tests cet aprem. Si y'a problème je te le dis. Merci en tous les cas ;-)

**Comment by wouldsmina** [comment]
j'en déduit qu'il n'y a plus de problème ;)
