### ISSUE TITLE
Procédure mise à jour 1.8 > 1.8.1

### ISSUE THREAD

**Issue by Philippe-M** [wouldsmina/Libertempo#183]
Bonjour,

Comment faire la mise à jour la la 1.8 à 1.8.1 ?

Merci d'avance.

**Comment by wouldsmina** [comment]
Bonjour,
- décompresser la 1.8.1
- modifier les fichiers dans le dossier cfg/ 
- lancer la procédure d'installation dans le navigateur
- choisir dans la liste déroulante de mettre à jour à partir de la version 1.8 (après le choix de la langue)

**Comment by Philippe-M** [comment]
Parfais merci.

Peut être qu'il faudrait l'ajouter dans la doc ?

**Comment by wouldsmina** [comment]
Tout a fait, c'est en cours...
