### ISSUE TITLE
Clôture d'exercice pour les utilisateurs

### ISSUE THREAD

**Issue by DreDoU** [wouldsmina/Libertempo#184]
Bonjour,

Sur la version de Libertempo 1.8 en mode R.H.

On voudrait clôturer l'exercice sur l'ensemble des utilisateurs.
Nous avons des utilisateurs dont on ne pas clôturer car il y a des croix rouge dans la case clôturer. (voir ci dessous)

![image](https://cloud.githubusercontent.com/assets/16799641/15705231/b0170864-27ee-11e6-8530-a3dfec2b527d.png)

Pourquoi ? Comment peut'on résoudre le problème ?

merci

Bonne journée

**Comment by wouldsmina** [comment]
Bonjour,

C'est qu'une clôture a déjà été appliqué à cette utilisateur. la croix permet de l'annuler.
