### ISSUE TITLE
Le RH ne peut pas saisir de congés dans le passé si on l'interdit aux utilisateurs

### ISSUE THREAD

**Issue by Shadok** [wouldsmina/Libertempo#185]
Si interdit_saisie_periode_date_passee est à true, même le RH ne peut pas saisir de dates de congés dans le passé pour un utilisateur.

Il faudrait soit un second réglage propre au RH, soit l'autoriser quoi qu'il arrive pour le RH (plus logique).

**Comment by wouldsmina** [comment]
salut,

en effet, le RH doit pouvoir poser des congés dans le passé pour d'autre utilisateur même si interdit_saisie_periode_date_passee est a true. Le travail qu'a fai @Prytoegrian sur le JS devrait permettre assez facilement de modifier cela...

**Comment by Shadok** [comment]
En attendant, je peux le fixer de quelle manière ?

**Comment by wouldsmina** [comment]
hmm, en fait, ça va être un poil compliqué. Je vois pas d'ou viens le datepicker de la saisie d'un congés par le RH, il doit certainement venir du mode utilisateur, ce qui n'est pas très bon! Je chercherai plus ce soir, au moins pour comprendre.
De mon point de vu, corriger ça fait partie de la refonte du code. Si on corrige à la va vite on risque d’être confronté à d'autres problèmes plus tard...

**Comment by wouldsmina** [comment]
@Shadok, Pour fixer ce problème, je pense qu'il faut modifier le test dans fonction_conges.php:949 comme suit
```PHP
    if( $_SESSION['config']['interdit_saisie_periode_date_passee']  && $j_timestamp < $timestamp_today && !is_hr($_SESSION['userlogin']) )
````
Je corrigerai ça avant la prochaine beta...

**Comment by Shadok** [comment]
Modification ajoutée :)
