### ISSUE TITLE
All : virer les en-têtes des fichiers

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#187]
Rien de méchant mais c'est lourd ; on devrait pouvoir entrer dans le code le plus tôt possible. Les fichiers LICENSE et CONTRIBUTORS sont là pour ça.

**Comment by Prytoegrian** [comment]
?

**Comment by wouldsmina** [comment]
oups. Fait https://github.com/wouldsmina/Libertempo/commit/e5360940ed5219fa947fb9f632b728f9d4643449
