### ISSUE TITLE
Calendrier : le calendrier n'apparaît pas dans le menu

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#193]
Tout est dit.

**Comment by wouldsmina** [comment]
Petite précision : uniquement lorsque c'est le calendrier qui est affiché, dans la vue utilisateur ou responsable, il est dans le menu.

**Comment by Prytoegrian** [comment]
Ah oui désolé. D'après la convention de nommage des titres que je m'étais fixé, ça me paraissait évident.
