### ISSUE TITLE
SUGGESTION: module de pointeuse electronique

### ISSUE THREAD

**Issue by SARTECHRUN** [wouldsmina/Libertempo#194]
Bonjour, serait-il possible d'implémenter une pointeuse électronique qui permettrait de générer des jours de congés supplémentaires en cas d'heures sup. et inversement?

**Comment by wouldsmina** [comment]
Bonjour,

Pour pourrais tu nous donner un peu plus d'informations sur tes besoins?

**Comment by SARTECHRUN** [comment]
Bonjour, et merci pour ta réponse. Je n’ai pas pu te répondre plus tôt car je suis en déplacement professionnel  sur Mayotte.
En fait on recherche actuellement un produit Opensource qui permettrait de pouvoir gérer le badgeages en plus des congés des agents avec une option
qui permettrait en cas d’heures supplémentaires au niveau du badgeage de générer un solde d’heures (positif ou négatif ) à la fin du mois, ce qui permettrait
au n+1 de créditer ou débiter des RTT additionnels  (il s’agit d’une administration ). Avec éventuellement une possibilité d’ éditer à la façon des congés le solde des heures.
On est deux techs dans le service et disposer à aider dans la mesure de nos compétences.

Bonne fin de journée à toi et  bientôt.

Cordialement,

Nicolas HOAREAU
Technicien-ingénieur informatique du SAR
de la Cour d’appel de Saint Denis de la Réunion
0262.40.58.39




De : wouldsmina [mailto:notifications@github.com]
Envoyé : mercredi 8 juin 2016 22:17
À : wouldsmina/Libertempo
Cc : HOAREAU Nicolas; Author
Objet : Re: [wouldsmina/Libertempo] SUGGESTION: module de pointeuse electronique (#194)


Bonjour,

Pour pourrais tu nous donner un peu plus d'informations sur tes besoins?

**Comment by wouldsmina** [comment]
Libertempo est une application de gestion des congés, une pointeuse sert a géré le temps de présence... Je ne pense pas qu'une telle solution ai sa place dans ce projet...

tu devrais plutôt rechercher des applications de gestion de temps (time tracking), ce sera certainement plus proche de tes besoins...
