### ISSUE TITLE
Question prise de congés

### ISSUE THREAD

**Issue by CCA171** [wouldsmina/Libertempo#196]
Bonjour,

Lorsqu'un utilisateur prend un congé, si son responsable est absent, qui prend le relais ?

J'aimerai pouvoir sélectionner précisément le n+2 en cas d'absence mais je ne trouve pas comment faire.

Merci

**Comment by wouldsmina** [comment]
Bonjour,

Lorsqu'un responsable est absent, la demande de l'un de ses collaborateurs peut être transmise au responsable du responsable. Pour cela il faut activer l'option globale `gestion_cas_absence_responsable`.

**Comment by CCA171** [comment]
Et par hasard on ne peut pas sélectionner un autre n+2 ? 
Merci de votre réponse

**Comment by wouldsmina** [comment]
ah non, le n+2 est automatiquement déduit c'est forcément le n+1 de n+1.

**Comment by CCA171** [comment]
Ok merci de ton aide :)
