### ISSUE TITLE
Jours fériés : Problèmes de saisies sur le calendrier (+ affichage)

### ISSUE THREAD

**Issue by benjoo** [wouldsmina/Libertempo#197]
Bonjour,

J'ai rencontré un bug lorsque j'ai manipulé le calendrier pour les jours chômés.

Supposons qu'il soit vide (il n'est pas complété automatiquement..), et bien lorsque j'enlève l'ensemble des jours fériés, j'obtiens comme erreur:
![bug](https://cloud.githubusercontent.com/assets/19833499/15922129/7930ff9c-2e26-11e6-8bfe-f5d635906d32.png)

Donc je vous le partage pour savoir si cette erreur arrive aussi pour vous, et si tel est le cas, essayer de la corriger.

De plus, juste un petit bug d'affichage sur le calendrier des jours chômés, voilà:
![sans titre](https://cloud.githubusercontent.com/assets/19833499/15922186/c6d5624c-2e26-11e6-8f65-a7236466ae82.png)

En tout cas merci pour votre travail, et j'attends vos réponse !

**Comment by wouldsmina** [comment]
Bonjour,
J'ai réussi a reproduire le bug. pour corriger cela, il faut modifier la fonction hr/Fonctions.php::pageJoursChomesModule() : 
remplacer:
````
         $tab_checkbox_j_chome        = getpost_variable('tab_checkbox_j_chome');
````
par : 
````
        $tab_checkbox_j_chome        = (empty(getpost_variable('tab_checkbox_j_chome'))) ? array() : getpost_variable('tab_checkbox_j_chome');
````
Cela permet de créer un tableau vide si getpost_variable('tab_checkbox_j_chome') ne contient rien.

 :warning: Il n'est pas possible d'utiliser Libertempo sans avoir configuré au moins un jour chomés...

A+

**Comment by wouldsmina** [comment]
PS : Oui, je connais le bug d'affichage, mais j'ai pas encore trouvé comment rectifier cela...

**Comment by benjoo** [comment]
Merci pour la réponse.

Et pour ton petit "attention", j'avais déjà vu (cf test d'ajout d'absence..) mais je voulais voir comment marchais le site donc j'ai fais pleins de petits tests.

Mais je te remercie ! 

D'accord, on va laisser comme ça pour le moment...

Bonne continuation ;)

**Comment by wouldsmina** [comment]
N'hésite pas a torturer l'appli et a nous remonter les bugs que tu rencontre, on a jamais assez de testeur...

Je laisse le ticket ouvert le temps de corriger sur develop...

**Comment by benjoo** [comment]
Oui je vais essayer de faire ça !

Et oui je l'ai fermé un peu tôt.. Juste un truc, comment est-il possible d'avoir accès au "backup" mais seulement pour le compte admin de la base de donnée et non pour les comptes admin du LDAP ?
Comme c'est ton application, je pense que c'est plus facile pour toi de me répondre..

En attendant, je vais essayer de faire ça !

**Comment by Prytoegrian** [comment]
Même mieux :wink: : 
```php
$var = getpost_variable('tab_checkbox_j_chome');
$tab_checkbox_j_chome = (!is_array($var) || empty($var)) ? [] : $var;
```

**Comment by wouldsmina** [comment]
> comment est-il possible d'avoir accès au "backup" mais seulement pour le compte admin de la base de donnée et non pour les comptes admin du LDAP?

ce n'est pas possible, ça mérite bien un nouveau ticket...

**Comment by Prytoegrian** [comment]
> ce n'est pas possible, ça mérite bien un nouveau ticket...

Cf #198

**Comment by Prytoegrian** [comment]
@benjoo je viens de percuter, les messages d'erreurs que t'as posés, ça vient d'une instance de test ou de celle que tu déploie en prod ?
