### ISSUE TITLE
Erreur: faute de frappe dans login_bottom.php

### ISSUE THREAD

**Issue by benjoo** [wouldsmina/Libertempo#199]
Ne sachant pas comment faire pour vous le faire parvenir, j'ouvre un ticket que l'on fermera aussitôt mais pour le moment, ligne 40:
`39 </footer>`
`40 <body>`
`41 </html>`

`<body> -> </body>`

(à moins que je me trompe vraiment mais..)

Voilà^^

**Comment by wouldsmina** [comment]
bien vu. Si tu veux, tu peux fork mon projet, faire la modification puis me l'envoyer en faisant un Pull Request. Si tu veux de l'aide, on est sur irc :  irc://irc.tuxfamily.org/Libertempo

**Comment by benjoo** [comment]
J'ai effectué ça pour une autre erreur^^

Petit soucis, je n'arrive pas à me connecter à ton serveur, peut être le port je ne sais pas...

**Comment by wouldsmina** [comment]
si ton navigateur ne te propose pas un client irc, tu dois en installer un ou utiliser un client en ligne : http://irc.lc/irc.tuxfamily.org/Libertempo
