### ISSUE TITLE
Impossible de créer une nouvelle absence en utilisateur simple

### ISSUE THREAD

**Issue by nicofrand** [wouldsmina/Libertempo#2]
Sur l'espace de démo, en utilisateur simple, impossible de créer une nouvelle absence du 09/06/2015 au 11/06/2015.

La fonction "compter les jours" ne fonctionne pas (voir console JS) et lorsqu'on valide le formulaire les messages d'erreur suivants sont affichés : 

> ERREUR : mauvaise saisie : valeurs manquantes !!!
> ERREUR ! Les valeurs saisies sont invalides ou manquantes !!! !

**Comment by wouldsmina** [comment]
Pas eu d'erreur lors de la validation mais en effet, la fonction js de calcul ne marche plus!
Merci
