### ISSUE TITLE
Couleurs fades

### ISSUE THREAD

**Issue by VV666** [wouldsmina/Libertempo#20]
Bonjour, 
est-il possible d'avoir des couleur plus vive dans le calendrier ? (pour les abs, cp, etc)
Merci

**Comment by wouldsmina** [comment]
Ah, les goût et les couleurs... Le plus simple c'est de modifier en local selon tes préférences. Bon c'est vrai que le fichier css du template et condensé mais par chance ce que tu recherche est a la fin.

**Comment by VV666** [comment]
(pour le calendrier général) j'ai pas changé dans ces fichiers mais dans ceux là : 
template/reboot/css/reboot.css
et
calendrier.php : 

	echo "      <tr align=\"center\">\n" ;
	echo "         <td bgcolor=\"#DCDCDC\" class=\"cal-legende\"> - </td>\n" ;
	echo "         <td class=\"cal-legende\"> ". _('calendrier_legende_we') ."</td>\n" ;
	echo "      </tr>\n" ;
	echo "      <tr align=\"center\">\n" ;
	echo "         <td bgcolor=\"#8addf2\" class=\"cal-legende\">abs</td>\n" ;
	echo "         <td class=\"cal-legende\"> ". _('calendrier_legende_conges') ."</td>\n" ;
	echo "      </tr>\n" ;
	echo "      <tr align=\"center\">\n" ;
	echo "         <td bgcolor=\"#ffc1ff\" class=\"cal-legende\">abs</td>\n" ;
	echo "         <td class=\"cal-legende\"> ". _('calendrier_legende_demande') ."</td>\n" ;
	echo "      </tr>\n" ;
	echo "      <tr align=\"center\">\n" ;
	echo "         <td bgcolor=\"#ffffad\" class=\"cal-legende\"> - </td>\n" ;
	echo "         <td class=\"cal-legende\"> ". _('calendrier_legende_part_time') ."</td>\n" ;
	echo "      </tr>\n" ;
	echo "      <tr align=\"center\">\n" ;
	echo "         <td bgcolor=\"#acffb6\" class=\"cal-legende\">abs</td>\n" ;
	echo "         <td class=\"cal-legende\"> ". _('calendrier_legende_abs') ."</td>\n" ;
	echo "      </tr>\n" ;
	echo "      <tr align=\"center\">\n" ;
	echo "         <td bgcolor=\"#CEB6FF\" class=\"cal-legende\">abs</td>\n" ;
	echo "         <td class=\"cal-legende\"> ". _('divers_fermeture') ."</td>\n" ;
	echo "      </tr>\n" ;

Les couleurs sont plus vives et son donc visible lorsque l'écran est en mode lecture/texte.

**Comment by wouldsmina** [comment]
ok, c'est bien le fichier reboot.css dont je parlais et non reboot.php comme je l'ai écrit. Je modifie cela pour la prochaine version.
Merci.

**Comment by wouldsmina** [comment]
poussé dans la branche 1.7.1beta
