### ISSUE TITLE
Jours de fermetures: problème de redirection + d'ajout de jours de fermetures

### ISSUE THREAD

**Issue by benjoo** [wouldsmina/Libertempo#201]
Re-bonjour,

J'ai trouvé deux autres petites erreurs.

1. La première, un problème de redirection:
Mode RH > Jours de fermetures > Abandonner
On est alors rediriger vers /admin/admin_index.php mais on a une erreur 404. Il manque peut être un "ROOT_PATH" quelque part...

2. La deuxième un problème d'affichage:
Mode RH > Jours de fermetures > Saisie des jours de fermetures
![sans titre](https://cloud.githubusercontent.com/assets/19833499/15931068/50aaace6-2e56-11e6-84b2-8ab79fe17ab3.png)
Donc la le problème est plus gros. J'ai seulement dans la BDD les deux premières fermetures listées ci-dessus (cf calendrier fermeture)
Les autres, sont des anciens jours de fermetures mais ne sont pas présent dans la BDD. Je les retrouve également sur le calendrier. Or, quand j'essaye de les supprimer, j'obtiens cette erreur:
![sans titre2](https://cloud.githubusercontent.com/assets/19833499/15931151/b838c636-2e56-11e6-96fc-d823c6d33bb2.png)

Ce problème est survenu la première fois lorsque j'ai voulu saisir un jour de fermeture mais que celui-ci se chevauchait avec un jour de congés d'un utilisateur, donc le jour de fermeture n'a pas été accepté mais ça l'as ajouté quelques parts et présent dans le calendrier par la suite..

Voilà, j'ai essayé d'être clair mais ça reste flou pour moi aussi....

EDIT:
Les jours de fermetures sont présent pourtant dans la table: conges_periode

J'ai ajouté des jours de fermeture, tout a bien marché. J'ai voulu les enlevé, j'ai obtenu l'erreur ci dessus mais pourtant, les jours de fermetures ne sont plus présents dans la BDD mais toujours sur le calendrier..

**Comment by issadseif** [comment]
Salut wouldsmina ! 
Je rencontre également deux problemes aux sujets des jours de fermeture.

1er probleme:

En mode RH, dans l'onglet clôture/début d'exercice, si je choisis la "clotûre d'exercice pour Tous" et que je valide impossible par la suite de revenir en arrière par ex en choisissant "clôture par personne"... et du coup dans la rubrique jours de fermeture on peut que parametrer "Fermeture pour tous" et donc une seul plage de date pour tous

2eme probleme (idem que benjo a priori):

En admettant que je reste sur la "clôture globale pour tous", en paramétrant une plage de date pour les jours de fermeture, si j'essaye d'annuler en appuyant sur le bouton "abandonner" j'ai une erreur 404 objet non trouvé 

et depuis impossible de changer la plage de date...j'ai le messge d'erreur suivant:

"Erreur: la fermeture saisie chevauche une autre fermeture ou un congé pris par un utilisateur concerné !!! veuillez recommencer"

voila j'espère avoir été clair...

**Comment by wouldsmina** [comment]
salut ,
@benjoo as tu corrigé cela dans tes PR?
