### ISSUE TITLE
Suggestion: permettre à la RH d'ajouter des jours d'absences pour le compte de quelqu'un

### ISSUE THREAD

**Issue by benjoo** [wouldsmina/Libertempo#203]
Bonjour,

Comme expliciter dans le titre, le problème est le suivant.

Le futur déploiement de libertempo (que j'opère) se fera en interne. De ce fait, on ne peut pas poser de congés si on est chez soi et ce n'est pas tout les utilisateurs qui ont un accès au réseau lorsqu'ils travaillent.

C'est pourquoi, ils serait peut être possible d'ajouter une option (qu'on peut désactiver) permettant à la RH d'ajouter des congés pour une personne (après qu'ils aient reçu un mail par exemple).

De ce fait, il serait possible à des utilisateurs qui n'ont pas accès à libertempo, d'ajouter des congés.

Voilà, je vous remercie et attends vos réponses^^

**Comment by wouldsmina** [comment]
il suffit d'activer l'option resp_saisie_mission, mais cela ne devrait pas influer sur le RH...
