### ISSUE TITLE
ATTENTION : certains champs saisis ne sont pas valides ...... (ldap)

### ISSUE THREAD

**Issue by adminSNAO** [wouldsmina/Libertempo#21]
Bonjour,
nous venons d'installer Libertempo sur le meme serveur que php_conges (en doublon).
Nous faisons une authentification par ldap et lors de l'ajout du premier utilisateur (en se connectant avec le compte admin), il propose bien les agents de notre ldap mais au moment d'enregistrer il donne l'erreur suivante:
 ATTENTION : certains champs saisis ne sont pas valides ......
pierre.martin---MARTIN---Pierre---100---N---conges
0---0
0---0
0---0
0---0

cette fonctionalité fonctionne bien sous 1.5.1 !
est-ce le "." dans le uid qui ne passe pas ? ( dans un autre post on parle du "-" comme separateur qui pose probleme !)

pourtant nous arrivons a creer des groupes (ce n'est pas un probleme d'ecriture dans la base ...)

merci de votre aide

cordialement
Eric

**Comment by wouldsmina** [comment]
Arfff! Je vais retirer le filtre qui pose problème et plutôt faire un
escape_string pour éviter l'injection sql...
Merci.

**Comment by wouldsmina** [comment]
Ps: il faut modifier le preg_match, ligne 287 du fichier admin/admin_ajout_user.php

**Comment by wouldsmina** [comment]
c'est corrigé sur github et sur tuxfamily.
Merci

**Comment by adminSNAO** [comment]
ca marche !
bravo merci pour votre reactivité.
PS: pour info dans le paquet, les fichiers config_*_new.php n'existent pas, ils sont directement en en config_*.php.
Cela peut poser probleme en cas de mise a jour ....

Merci

**Comment by adminSNAO** [comment]
De nouveau la même erreur pour un utilisateur ... (pour le moment)
Le message affiché est sous cette forme :
ATTENTION : certains champs saisis ne sont pas valides ......
marie-caroline.griguou---GRIGUOU---Marie-Caroline---100---N---julie.garissaud
0---0
0---0
0---0
0---0
(les noms sont volontairement faux mais le nombre de caractères est respecté)

Par rapport aux agents qui ont pu être rentrés, tout ce qui se trouve après le nom du responsable n'apparait pas.
Nous avons testé ce même agent avec d'autres responsables et sans responsable => idem
Testés aussi d'autres agents avec un prénom composé => pas de pb ...
Testé sans affecter à un groupe => idem
Le problème semble se situé au niveau de l'agent, avez-vous une solution svp ??

**Comment by adminSNAO** [comment]
Il semble qu'au delà de 20 caractères dans le champs uid, l'erreur se crée.
Nous avons bcp d'agents dans ce cas-là, est-il possible de modifier la définition de la variable ??

**Comment by wouldsmina** [comment]
ça doit etre sympa de taper son login plusieurs fois par jour! ;-p 
Je ferais cette modif pour la prochaine version, en attendant, vous pouvez modifier la ligne 287 du fichier admin/admin_ajout-user.php : 
|| !preg_match('/^[a-z.\d_-]{2,20}$/i', $tab_new_user['login'])
mettez la valeur que vous voulez à la place du 20.

**Comment by VV666** [comment]
On avait ce soucis. Depuis le passage à la 1.7, c'est ok pour nous.
