### ISSUE TITLE
Problème Local Fr serveur

### ISSUE THREAD

**Issue by issadseif** [wouldsmina/Libertempo#210]
Salut wouldsmina 

J'ai un souci à l'installation du logiciel, sur mon serveur local l'url d'installation "http://127.0.0.1/Libertempo/install/ " me renvoi a une erreur située dans le fichier lang_profile.php à la ligne 70 : 
"bindtextdomain($nomDesFichiersDeLangue, LOCALE_PATH ); // On indique le chemin vers les fichiers .mo"

Voicl l'erreur:

Fatal error: Call to undefined function bindtextdomain() in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo\include\lang_profile.php on line 70

Est ce que c parce que je n'ai pas de local FR f sur easyphp ?
Peux tu m'aider ? 
merci à toi

**Comment by wouldsmina** [comment]
Salut,
Je pense qu'il te manque php-gettext. Qu'elle est la version de php et mysql?

**Comment by issadseif** [comment]
J'utilise easyphp 14.1VC9 dans lequel j'ai un répertoire avec PHP en version 5.4.24 et un répertoire mysql en version 5.6.15.

Concernant php-gettext, il est possible qu'il me le manque car je ne l'ai jamais installé.

J'ai suivi à la lettre le guide d'installation disponible sur Libertempo, il y a effectivement une étape "vérifier que la locale FR_fr est bien installé sur le serveur", est ce que c'est en rapport avec gettext ?

**Comment by wouldsmina** [comment]
pour que Libertempo fonctionne, il te faut php-gettext et pour l'avoir en francais, il te faut la locale FR.

As-tu redémarré ton serveur apache après la modification dans php.ini?

**Comment by issadseif** [comment]
Bonjour,

Mon php-gettext.dll est dans le repertoire ext de PHP mais je ne sais pas ou vérifier la présence de la locale FR

Et dans mon répertoire Apache dans easyphp je n'ai pas de fichier php.ini, Le .ini est dans le répertoire php.

En redémarrant le serveur l'url "http://127.0.0.1/Libertempo/install/" me propose le choix de la langue dont le fr mais j'ai 2 erreurs dans le fichier plugins.php à la ligne 8 et 29:

Notice: Undefined index: config in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo\include\plugins.php on line 8

Warning: in_array() expects parameter 2 to be array, null given in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo\include\plugins.php on line 29

Quepassa ?

merci

**Comment by wouldsmina** [comment]
pour vérifier que la locale FR est installé, tu peux faire un [phpinfo()](http://php.net/manual/fr/function.phpinfo.php).

Pour les erreurs que tu as, ce n'est pas bloquant...

**Comment by issadseif** [comment]
Effectivement ce n'est pas bloquant...par contre à l'étape de la création de la base de données je rentre bien:
Server :localhost
Database name: db_conges
User: dbconges
password:0000

Il est mentionné génération du fichier de configuration de la bdd...avec succès (j'ai un fichier dbconnect qui est généré dans le répertoire cfg) mais en appuyant sur continuez...la base de donnée n'est pas accessible 
La base de données n'est pas accessible ... Veuillez vérifier les paramètres du fichier(Assurez vous que la base de données, l'utilisateur et les privilèges MySQL ont bien été créés.)

Pourtant j'ai bien crée dans phpmyadmin une bdd db_congés, j'ai même ajouté un utilisateur avec les données identiques à celles dans db_connect_new

J'ai même injecté le fichier sql php_congés_v1.7.0 mais j'ai toujours des erreurs qui me suivent....


Warning: mysqli::mysqli(): (HY000/1045): Access denied for user 'conges'@'localhost' (using password: YES) in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo\include\sql.class.php on line 105

Warning: mysqli::query(): Couldn't fetch Database in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo\include\sql.class.php on line 137

Warning: Database::query(): Couldn't fetch Database in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo\include\sql.class.php on line 140


Ca m'inquiete cette histoire, je galère avant même de travailler sur le logiciel...

En fait je compte le déployer en essai dans une petite pme..merci de ton aide

**Comment by wouldsmina** [comment]
ok, le problème ne vient pas de Libertempo mais bien des droits d'accès mysql : Access denied for user 'conges'@'localhost'

vérifie bien le fichier cfg/dbconnect.php...

**Comment by wouldsmina** [comment]
d'ailleurs, tu me dis que le user c'est dbconges, pourtant ton message d'erreur fait référence un l'utilisateur "conges"...

**Comment by issadseif** [comment]
Wouldsmina j'ai checké le fichier dbconnect et j'ai rectifié le user à "root" et là j'ai bien l'étape "choix de la langue" puis directement une étape d'installation avec le choix entre "nouvelle installation" ou "déja installé"...je pense que ça fonction puisque l'url passe à index.php pour une connexion avec utilisateur et mdp

En utilisant "admin" et mdp "responsable" je rentre dans l'interface de gestion mais ça ne fonctionne pas avec:
"root" et "mot de passe vide" 

Ni avec les users présents dans la table conges_users comme par exemple "conges" et mdp "3cdb69ff35635d9a3f6eccb6a5e269e6"

C'est normal ?

En tout cas merci pour ta disponibilité !

**Comment by issadseif** [comment]
d'ailleurs, tu me dis que le user c'est dbconges, pourtant ton message d'erreur fait référence un l'utilisateur "conges"...

oui j'ai rectifié le user dans dbconnect à "root" 

Mais dans la table users j'ai un u_login="61646d696e"  dont u_nom est "conges" et un u_passwd= "636d61cf9094a62a81836f3737d9c0da"

C'est normal de pas pouvoir s'identifier ?

**Comment by wouldsmina** [comment]
oui, c'est normal, l'utilisateur "conges" n'existe plus, il a été remplacé par les droit RH. Cela m'étonne qu'il soit encore dans la base! Tu installe la 1.8 ou la 1.8.1?

**Comment by issadseif** [comment]
J'ai installé la 1.7

**Comment by wouldsmina** [comment]
tu devrais directement installer la version 1.8.1, elle est bien plus stable que la 1.7...

**Comment by issadseif** [comment]
ok ça marche, je fais ça tout de suite, il me restera ensuite la configuration de l'envoi des mails avec un smtp gmail

**Comment by issadseif** [comment]
J'ai installé la 1.8.1 et la configuration ne pose pas de problème.

Par contre je rencontre un problème que j'avais déjà eu avec phpmylab c'est au sujet du serveur smtp

Je voudrais tester l'appli sur mon serveur local et envoyer les mails via ma boite gmail.com et les recevoir aussi sur ma boite gmail pour voir si ça marche

j'ai crée le fichier config_SMTP avec les variables suivantes:

$config_SMTP_host = "smtp.gmail.com";		//adresse serveur smtp
$config_SMTP_port = 465; 	//port smtp
$config_SMTP_sec  = "ssl";		//ssl, tls ou vide
$config_SMTP_user = "issadseif@gmail.com";		//nom utilisateur (peut être vide)
$config_SMTP_pwd = "motdepasse de la boite mail";		//mot de passe (peut être vide)

Dans le fichier php.ini j'ai aussi modifier les variables suivantes:

[mail function]
; For Win32 only.
; http://php.net/smtp
**SMTP = smtp.gmail.com**
; http://php.net/smtp-port
**smtp_port = 465**

; For Win32 only.
; http://php.net/sendmail-from
**sendmail_from = issadseif@gmail.com**

Puis j'ai redémarré easyphp...mais quand je fais un test d'envoi email j'ai l'erreur suivante:

Notice: Undefined variable: sql_date_fin in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo-1.8.1\fonctions_conges.php on line 722

ERROR : No recipient address for the message!
Message was not sent 
Mail_test_ok

Est ce que c'est parce que j'ai pas de destinataire ou bien c un probleme de config_SMTP ?

**Comment by wouldsmina** [comment]
> ERROR : No recipient address for the message!

tu n'a pas de destinataire (l'adresse mail du compte que tu utilise pour tester)

> Notice: Undefined variable: sql_date_fin in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo-1.8.1\fonctions_conges.php on line 722 

Pas bloquant...

**Comment by issadseif** [comment]
je pensais que ça correspondait à la variable $config_SMTP_user = "issadseif@gmail.com"; //nom utilisateur (peut être vide)...

Sinon ou est ce que je renseigne l'adresse de destinataire ?

merci encore wouldsmina ! t vachement serviable !!

**Comment by wouldsmina** [comment]
j'ai un peu de temps en ce moment ;)
l'adresse email ce paramètre dans la table conges_users.email
$config_SMTP_user : c'est l'identifiant pour ce connecter au serveur smtp...

**Comment by issadseif** [comment]
Je reviens aux nouvelles, j'ai gardé la même config_SMTP.php que précédemment, j'ai décommenté dans php.ini l'extension openssl mais j'ai une erreur, as-tu une config de config_SMTP.php a me proposé qui fonctionne ?

**Comment by wouldsmina** [comment]
quel est le message d'erreur?

**Comment by wouldsmina** [comment]
pour gagner du temps, je t'invite a nous rencontrer sur irc : https://client02.chat.mibbit.com/?url=irc%3A%2F%2Firc.tuxfamily.org%2FLibertempo

**Comment by issadseif** [comment]
salut wouldsmina j'espere que ca va ! Je savais pas trop ou te joindre du coup je suis repassé là...
Dis moi, today je bosse un peu sur la compréhension du code de LT. Du coup je pense que c important de comprendre "comment les différents fichiers sont organisés, certains dans des répertoires d'autres directement dans le répertoire principal Libertempo comme par exemple define.php,fonction ou focntion_conges,etc",

J'ai parcours un peu le fichier index et les autres fichiers que t'incluent au fur et à mesure mais j'aimerai avant tout savoir ou est dispatché le script html pour comprendre de quoi tu parles à chaque fois que t'evoques une $variable php

merci à toi

**Comment by wouldsmina** [comment]
salut,
Je vais etre un peu plus occupé aujourd'hui, mais je trouverai bien du temps pour te répondre... Viens sur irc, ce sera plus simple...

**Comment by issadseif** [comment]
ok ça marche
