### ISSUE TITLE
[Amélioration] Possibilité de faire une demande d'absence sur deux types de congés différents 

### ISSUE THREAD

**Issue by benjoo** [wouldsmina/Libertempo#211]
Bonjour,

Comme explicité sur IRC, je vais essayer de développer le pourquoi de l'amélioration qui pourrait être fait.

**Problème:** LT ne permet pas, pour une même demande, de poser 2 jours de congés payés et 1 jours de RTT pour un total de 3 jours de congés.

Pour aller plus loin, le problème est que si on veux déposer 5 jours de congés mais qu'il nous reste:

- 4 jours de congés payés
- 1 jour de RTT

on doit effectuer deux demandes pour opérer cela.

Il faudrait alors une petite refonte du système pour permettre un allègement, au niveau de la BDD (enfin je pense) et de l'historique. 

**Solution (possible):** ce serait de modifier les boutons radios par des input number et quand on fait une demande de 5 jours, les 5 jours sont par défaut sur les congés payés (ou le premier de la liste) mais qu'on a plu qu'a choisir alors où les dispatcher. 
![sans titre](https://cloud.githubusercontent.com/assets/19833499/16580066/0658b51e-42a3-11e6-9bab-be1ddfdd69eb.png)

Ce problème peut être utile à résoudre pour les CET par exemple puisque les CET, si je ne me trompe pas, ne peuvent pas être rempli par n'importe quels types de congés.. 

Enfin voilà, le problème reste là en attendant, peut être, une future amélioration ;)

**Comment by wouldsmina** [comment]
je ne sais pas trop. Est ce que cela ne va pas plus compliquer les choses que les simplifier...
Alors c'est vrai qu’être obligé, dans ce cas, de faire 2 demandes c'est un peu contraignant...
Mais il faudra (avec ta proposition) de toute façon faire des manipulations pour répartir les jours dans les différents types de congés (ce qui ne sera pas forcément évident pour l'utilisateur)...

**Comment by benjoo** [comment]
Et bien, si jamais vous vous voyez opérer ce changement, c'est vrai qu'il faudra changer pas mal de choses et qu'il faut avant bien réfléchir au pour et contre..

Mais concernant la solution, concernant l'utilisateur, je pensais plutôt à:
 - il choisit une période de 5 jours, et en dessous, dans les input number, par défaut les 5 jours sont sur congés payés tu voit, donc au final, pas de changements à faire sauf cas exceptionnel, mais après à voir quoi

**Comment by Prytoegrian** [comment]
L'un des problèmes de ce genre de procédé, c'est qu'il manque de traçabilité. En faisant ça, tu ne sauras pas quel jour est un jour de RTT, quel jour est un CP, etc.

Après, il y a en plus des questions métiers et ça c'est une autre paire de manche.

Je comprends l'idée, mais je me dis qu'une demande n'est pas une demande pour « ne pas être au boulot le jour X » mais une demande « je prends des CP » ou « je prends mes RTT », chacune avec les règles précises. Il faut donc que l'employé prennent conscience de ça.

**Comment by wouldsmina** [comment]
+1
En terme métiers, ce sont deux demandes distinct (même si on pourrait imaginé que la demande soit éclatée en 2 avant traitement...)

**Comment by Prytoegrian** [comment]
Vu que les règles de comptage (entre autres) sont différentes, je propose de fermer ce ticket
