### ISSUE TITLE
Erreur lors d'une demande de NOUVELLE ABSENCE 

### ISSUE THREAD

**Issue by issadseif** [wouldsmina/Libertempo#214]
Lorsque l'utilisateur fait une demande de nouvelle absence, lorsqu'il choisit CONGES, la demande est bien prise en compte et le mail est envoyé. Cela fonctionne si je refais une nouvelle demande de conges payes ou RTT et ainsi de suite. Donc mon envoi d'emails fonctionne pour les CP et les RTT

Mais si l'utilisateur fait une nouvelle demande de type ABSENCE cette fois-ci (ex mission,formation), et bien dans ce cas là les modifications sont enregistrées avec succès mais il y a une erreur qui s'affiche et le mail n'est pas envoyé. Les absences sont seulement visibles sur le calendrier et dans l'"historique des autres absences" visible par le RH seulement.

 Voici les erreurs:

Notice: Undefined index: mail_new_absence_sujet in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo-1.8.1\fonctions_conges.php on line 715

Notice: Undefined index: mail_new_absence_contenu in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\Libertempo-1.8.1\fonctions_conges.php on line 716
Message was not sent

Mailer Error: Corps du message vide.

Modifications enregistrées avec succès ! !

Au départ je pensais que dans la configuration de LT faites par l'admin, il fallait faire le choix d'avoir comme type de demande CONGES (cp et rtt) et aussi ABSENCE(formation,mission,etc) car LT distingue les conges des absences et que certaines entité ne veulent que les congés par ex. Mais à priori ce n'est pas le cas. LT propose d'emblée demande de CONGES et des ABSENCES.

Du coup j'ai jetté un coup d'oeil à la configuration des mails envoyés faites par l'administrateur mais je ne vois pas de "mail_new_absence_contenu" ou "mail_new_absence_sujet"

Je trouve uniquement le paragraphe concernant mail_new_absence_conges (qui est d'ailleurs bien rempli)

Quelqu'un a déjà rencontré ce cas de figure ?

**Comment by wouldsmina** [comment]
bonjour,
C'est déja corrigé sur develop https://github.com/wouldsmina/Libertempo/commit/9f1128c126a8cfb863c2d13ab1f1064bc8ed0093
