### ISSUE TITLE
Erreur en mode Responsable

### ISSUE THREAD

**Issue by sSergiOo** [wouldsmina/Libertempo#217]
Bonjour,

Lorsque je me connecte sur un utilisation qui a les droits "Responsable", j'ai systématiquement cette erreur sur la page:

Notice: Constant _PHP_CONGES already defined in C:\wamp64\www\Libertempo\define.php on line 4
Call Stack
# Time    Memory  Function    Location

1   0.0000  264056  {main}( )   ...\resp_index.php:0
2   0.0010  291776  require_once( 'C:\wamp64\www\Libertempo\define.php' )   ...\resp_index.php:30
3   0.0010  291952  define ( )  ...\define.php:4

Merci pour votre aide

SergiO

**Comment by benjoo** [comment]
Salut,

Erreur que j'ai aussi, dans le fichier **define.php** à la racine de ton dossier, remplace la ligne 4 (il me semble) par:
`defined('_PHP_CONGES') or define('_PHP_CONGES', 1);`

C
