### ISSUE TITLE
Modif USER pour saisie des jours d'absence pour RTT ou temps partiel

### ISSUE THREAD

**Issue by adminSNAO** [wouldsmina/Libertempo#22]
Il semble qu'il ne soit pas possible de modifier les jours d'absence RTT ou TP d'une fiche agent.
Les autres paramètres de la fiche peuvent être modifiés sans problème.
Si ces jours sont renseignés dès la création de la fiche, il ne se produit pas de problème.
Donc problème à la modification (pas à la création)
Précision : Authentification par ldap

L'erreur est la suivante :

login : admin
uri   : /Libertempo/admin/admin_index.php?onglet=modif_user&u_login_to_update=pierric.fougirey
dump  : ../dump/sql_1441876611.dump

file  : /var/www/Libertempo/admin/admin_modif_user.php
line  : 468
fx    : $SQL->query
error : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''2015-09-10' at line 1
sql   : DELETE FROM conges_artt WHERE a_login='pierric.fougirey' AND a_date_debut_grille='2015-09-10

(nom volontairement modifié)

**Comment by wouldsmina** [comment]
C'est parce qu'il manque un ' a la fin de la requête! je corrige ce soir...

**Comment by adminSNAO** [comment]
Ils sont tous créés depuis Libertempo

**Comment by adminSNAO** [comment]
J'ai essayé de créer l'utilisateur anne-marie.pelletier-de-la-rombière sur la démo (donc sans ldap), je récupère l'erreur : 

ATTENTION : certains champs saisis ne sont pas valides ......
anne-marie.pelletier-de-la-guillardière---pelletier-de-la-rombière---anne-marie---100---N---no_resp
0---0
0---0
0---0
0---0
(la même que notre 1ère issue)

**Comment by adminSNAO** [comment]
Même erreur sur la démo : 

login : admin
uri   : /demo/admin/admin_index.php?onglet=modif_user&u_login_to_update=albert
dump  : ../dump/sql_1441888878.dump

file  : /data/web/56/ec/2a/libertempo.tuxfamily.org/htdocs/demo/admin/admin_modif_user.php
line  : 468
fx    : $SQL->query
error : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''2015-09-10' at line 1
sql   : DELETE FROM conges_artt WHERE a_login='albert' AND a_date_debut_grille='2015-09-10

**Comment by wouldsmina** [comment]
ok donc c'est bien la fin de la requete qui déconne. C'est corrigé sur github, je met a jour sur tuxfamily ce soir.

**Comment by adminSNAO** [comment]
c'est dans le fichier admin/admin_modif_user.php : ligne 467
Ca marche chez nous
merci
