### ISSUE TITLE
libertempo et active directory

### ISSUE THREAD

**Issue by en3rgizz** [wouldsmina/Libertempo#220]
Bonjour, 
j'ai instalé libertempo sur un serveur unbutu, 
lors de la configuration pour la liaison ont dois modifier $config_ldap_user   = « CN=user_ldap,dc=mon_domaine,dc=com » ; // utilisateur autorisé à accéder au serveur
par $config_ldap_user   = « CN=user@mondomaine.com,dc=mon_domaine,dc=com »

par contre je rencontre une erreur lors de l'ajout des utilisateur via la liste déroulante 

ATTENTION : certains champs saisis ne sont pas valides ......
---------190---N---no_resp
25.0---0.0
12.0---0.0

Merci d'avance pour votre retour

**Comment by wouldsmina** [comment]
Bonjour,
Ça ressemble à #216... En identifiant, il faut mettre domaine/user

**Comment by en3rgizz** [comment]
les utilisateur de mon active directory apparaisse  bien dans la liste déroulante mais lors de l'affectation des droits Rh ou autre( nombre de congés etc.. j'ai ce message
ATTENTION : certains champs saisis ne sont pas valides ......
---------190---N---no_resp
25.0---0.0
12.0---0.0

**Comment by wouldsmina** [comment]
Oui, et dans les logs apache? Tu as une erreur du style invalid credentials, c'est ca?

**Comment by en3rgizz** [comment]
oui c'est bien cela

**Comment by wouldsmina** [comment]
C'est bien le même problème que #216.
L'identifiant qui te permet de faire un bind sur ton AD doit etre au format domaine/users.

**Comment by jdelvecchio** [comment]
Sous quelle forme exactement doit être le ldap_user ? je rencontre le même soucis.
$config_ldap_user = 'domaine/user'; ?

**Comment by wouldsmina** [comment]
@jdelvecchio "$config_ldap_user = 'domaine/user';"
je t'invite à ouvrir un nouveau ticket pour ton problème en prenant soin de compléter le formulaire...
