### ISSUE TITLE
Gestion ARTT

### ISSUE THREAD

**Issue by Teave** [wouldsmina/Libertempo#221]
Peut-on configurer les ARTT par forfait horaire, c'est à dire:
une journée fait 7h30.
un ARTT équivaut à 1/3 de la durée de la journée soit 2h30
donc 1 ARTT pour ap.midi
         2 ARTT pour le matin
         3 ARTT pour la journée entière

Merci d'avance pour votre aide et votre support.

**Comment by wouldsmina** [comment]
non, il n'est pas possible de gérer les congés en heure. Nous travaillons actuellement sur une fonction de gestion d'heure complémentaire, mais cela ne semble pas correspondre à vos besoins.
Cordialement.
