### ISSUE TITLE
Safari : Bug décompte des jours d'absence

### ISSUE THREAD

**Issue by Teave** [wouldsmina/Libertempo#222]
Le décompte des jours de congé ne prend pas en compte les cases à cocher des demi-journées.
Ex: Départ le 16/8 AM retour le 17/8 AM ----> Nb jours  2
      Départ le 16/8 AM retour le 17/8 PM ----> Nb jours  2
      Départ le 16/8 PM retour le 17/8 AM ----> Nb jours  2
      Départ le 16/8 PM retour le 17/8 PM ----> Nb jours  2

**Comment by wouldsmina** [comment]
Quel version de Libertempo? Et tant qu'à faire, quel OS serveur, versions, navigateurs...

Est ce que tu as des erreurs JS?

**Comment by Teave** [comment]
Version en ligne et Libertempo 1.8.1 Quinnis serveur MAMP OSX 10.9.
Egalement, pour adapter le RTT, j'ai procédé à une motif dans le fichier : 
 ---> fonctions_calcul.php  
     ----> function make_tab_demi_jours_periode
en y intégrant une condition : 
	if ($new_type=="RCP")
		{
			while($current_day!=$date_limite)
			{
				$jour['am']=2;
				$jour['pm']=1;
				$tab_periode_calcul[$current_day]=$jour;
				$current_day=jour_suivant($current_day);
			}
		}
			
		else
		{
			while($current_day!=$date_limite)
			{
				$jour['am']=1;
				$jour['pm']=1;
				$tab_periode_calcul[$current_day]=$jour;
				$current_day=jour_suivant($current_day);
			}
		}
Cette condition n'est pas prise en compte. Comment faire pour avoir la variable libelle court congé ?

**Comment by wouldsmina** [comment]
A quoi te sert cette modification? C'est quoi des RCP? est ce que le bug de calcul est lié à ta modification ou pas? Tu n'as pas d'erreur dans la console JS?

Pour répondre a ta question, la fonction `make_tab_demi_jours_periode` ne reçoit pas le type de congés en paramètre, tu ne peux donc pas l'avoir... Si tu nous explique tes besoins, on pourra peut être t'aider.

**Comment by Teave** [comment]
C’est une modif pour décompter de l’ARTT (dénommé pour ce service RCP) forfaitairement, 2 RCP pour une matinée et 1 RCP l’après midi, soit 4 et 2 dans la fonction make_tab_demi_jours_periode, le résultat étant multiplié par 0.5 au final. Afin d’appliquer ce mode de calcul sur cet ARTT  uniquement et sans modifier le mode de calcul des congés et autres absences normales, il me faudrait accéder au type de congé dans la fonction make_ab_demi_jours_periode.

Le bug n’apparaît que sous Safari. Pas de pb avec Firefox.

Pour la console JS, message d’erreur JS :
                       Une chaîne vide a été transmise à « getElementById() ».

Message d’erreur CSS très nombreux.

**Comment by wouldsmina** [comment]
Ok. Pour ta modification, tu peux essayer de modifier le comportement de cette fonction : https://github.com/wouldsmina/Libertempo/blob/develop/utilisateur/Fonctions.php#L53
en adaptant les if a partir de la ligne 72...
Pour le bug avec Safari, je vais regarder ce qu'il se passe...
a+

**Comment by wouldsmina** [comment]
corrigé par a38a892bdd640fa3d11024a0075a8c0ffe074093 et testé.
