### ISSUE TITLE
Jours feriés : Page blanche

### ISSUE THREAD

**Issue by pousterlus** [wouldsmina/Libertempo#223]
Bonjour,

Il semble qu'il y ait un bug dans la version 1.8.1 (màj depuis version 1.7.0).
Lorsqu'un utilisateur ayant les droits RH clique sur la catégorie RH, puis "Jours chômés", rien n'apparait.
Les autres fonctions sont OK.

J'ai parcouru un peu la liste des Issues sur Github, et j'ai vérifié qu'il y avait bien au moins un jour chômé, c'est le cas : 

```
mysql> select * from conges_jours_feries;
+------------+
| jf_date    |
+------------+
| 2015-11-11 |
| 2015-12-25 |
| 2016-01-01 |
| 2016-03-28 |
| 2016-05-01 |
| 2016-05-05 |
| 2016-05-08 |
| 2016-07-14 |
| 2016-08-15 |
| 2016-11-01 |
| 2016-11-11 |
| 2016-12-25 |
+------------+
12 rows in set (0.00 sec)
```
Je ne vois pas bien comment fournir de plus amples informations car j'ai un peu de mal à m'y retrouver dans ce code).

Si vous avez des idées de directions vers lesquelles regarder, ce serait sympa :)

Merci !

-- 
Léo.

**Comment by pousterlus** [comment]
Ah, si, un log peut-être : 

> [Mon Aug 22 12:56:44.103585 2016] [:error] [pid 57050] [client 192.168.****:****] PHP Fatal error:  Call to undefined function hr\\easter_date() in /usr/local/www/apache24/data/****/hr/Fonctions.php on line 1638, referer: http://192.168.****/****/hr/hr_index.php?session=phpconges230a14f078fe2afb9951119122914efa&onglet=jours_chomes

**Comment by pousterlus** [comment]
Bon, et bien, il fallait ajouter le module "php56-calendar" (je suis sous FreeBSD).
Désolé du dérangement ! :)

-- 
Léo.

**Comment by wouldsmina** [comment]
Salut,
Voilà un problème vite réglé :p
Merci pour l'infos...

**Comment by pousterlus** [comment]
Héhé, j'avoue je m'en suis voulu de pas avoir regardé dans les logs avant...
C'est lundi, hein ;)

Peut-être prévoir une entrée dans le manuel d'installation dans la section "Troubleshooting" pour plus tard, quand vous aurez fait tout ce qu'il y a de plus urgent ?

En tout cas, merci pour tous ces efforts qui ont fait de Libertempo une belle application !

-- 
Léo.
