### ISSUE TITLE
AMELIORATION - Jour chômés par groupe / utilisateur

### ISSUE THREAD

**Issue by bopware** [wouldsmina/Libertempo#224]
Bonjour,

Tout d'abord, un grand merci pour ce logiciel open source.

Après installation et configuration de la v1.8.1, je me suis retrouvé confronté devant le problème suivant : 
Nous sommes une trentaine de salariés répartis dans différents services.
Les services (ou groupe d'utilisateurs) n'ont pas les mêmes jours de repos (certains ont le week-end, d'autres le mercredi et le dimanche...)
Je n'ai rien vu de tel dans la configuration.

Est-ce que cette fonctionnalité serait prévue ultérieurement ?

Merci

**Comment by wouldsmina** [comment]
Bonjour,
Tu peux déja le faire, même si c'est pas vraiment adapté.
En tant qu'admin dans la création/modification d'un utilisateur, il te suffit de cocher les samedis et dimanches en RTT. Dis moi si ça te va...

Par contre, nous travaillons actuellement sur la création de planning horaire ainsi que la gestion des heures complémentaires/repos : https://github.com/wouldsmina/Libertempo/tree/topic/heure
Je pense que le planning collera bien mieux à tes besoins.
a+

**Comment by bopware** [comment]
Super,  merci pour l'astuce.
Ça marche parfaitement !

En attendant avec impatience la prochaine mise à jour ;)
