### ISSUE TITLE
Compatibilité avec Mysql 5.7.13 (ubuntu)

### ISSUE THREAD

**Issue by GuillaumeAMM12** [wouldsmina/Libertempo#225]
Bonjour, tout d'abord félicitation pour ce projet, il est vraiment bien pensé.
Je rencontre quelques problèmes pour l'utilisation de libertempo 1.8.1.
Hormis la correction que j'avais déjà appliqué concernant les dates par défauts ("0000-00-00")
lorsque je veut ajouter un groupe j'ai l'erreur suivante:

login : admin
uri   : /admin/admin_index.php?onglet=admin-group
dump  : ../dump/sql_1473411504.dump

file  : /var/www/Libertempo-1.8.1/includes/SQL.php
line  : 59
fx    : $SQL->query
error : Data truncated for column 'g_double_valid' at row 1
sql   : INSERT INTO conges_groupe SET g_groupename='ADPSA', g_comment='', g_double_valid ='' 

Je viens de regarder  le code et la table, et éffectivement un type ENUM('Y','N') ne supporte pas la saisie vide.
J'ai rajouter dans le code la gestion de la variable passée en paramètre > $new_group_double_valid
de la fonction "ajout_groupe($new_group_name, $new_group_libelle, $new_group_double_valid)"
Cette variable est pourtant bien reprise dans les champs de configurations (il s'agir de la double validation) mais elle n'arrive pas dans cette fonction.
Après correction cela fonctionne. Mais je me demande si le problème n'est pas plus global ?
Et si cela va se reproduire sur d'autres variables de configurations ?

**Comment by Prytoegrian** [comment]
Hello !

J'ai compris où était le problème. Laisse-moi le temps de monter un docker avec mysql 5.7 pour reproduire parfaitement le bug et on le corrigera.

Mais pour répondre à ta question plus globale, oui, c'est un problème plus général qui va se reproduire. Si tu as les compétences pour mettre les mains dans le cambouis, je t'invite à le faire (et nous pouvons t'y aider), mais ça va être difficile pour nous de nous y plonger complètement. La fonctionnalité que nous développons pour 1.9 - Ceres est plus grosse qu'attendue et nous serons en retard pour la livraison de la fin d'année.

**Comment by GuillaumeAMM12** [comment]
Ok merci de ces précisions. 
Question tout autre , j'ai cherché mais je n'ai pas trouvé la fonctionnalité qui permettrai à un utilisateur de 
changé un type de congé (RTT/Congé) une fois sa demande validée ? voir même de la supprimer ? 

Merci 

Cordialement 

Mail: guillaume.maniaval@adpsa12.fr 
Tel direct: 05 65 73 77 88 
Tel Standard : 05 65 73 78 80 

Guillaume Maniaval 

Adpsa Multimédia 
Carrefour de l'agriculture 
Boulevardu du 122 ieme RI 
12026 Rodez cedex 09 

----- Mail original -----

De: "Prytoegrian" <notifications@github.com> 
À: "wouldsmina/Libertempo" <Libertempo@noreply.github.com> 
Cc: "GuillaumeAMM12" <guillaume.maniaval@adpsa12.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 12 Septembre 2016 21:48:11 
Objet: Re: [wouldsmina/Libertempo] Compatibilité avec Mysql 5.7.13 (ubuntu) (#225) 



Hello ! 

J'ai compris où était le problème. Laisse-moi le temps de monter un docker avec mysql 5.7 pour reproduire parfaitement le bug et on le corrigera. 

Mais pour répondre à ta question plus globale, oui, c'est un problème plus général qui va se reproduire. Si tu as les compétences pour mettre les mains dans le cambouis, je t'invite à le faire (et nous pouvons t'y aider), mais ça va être difficile pour nous de nous y plonger complètement. La fonctionnalité que nous développons pour 1.9 - Ceres est plus grosse qu'attendue et nous serons en retard pour la livraison de la fin d'année.

**Comment by wouldsmina** [comment]
Salut,
modifier ou supprimer un congés validé c'est pas possible pour l'employé. Par contre le responsable peut supprimer un congés qu'il a validé.
L'employé peut modifier une demande tant qu'elle n'a pas été traitée. Par contre, il n'est pas possible de modifier le type de congés, pour cela il doit supprimer et refaire une demande...

**Comment by GuillaumeAMM12** [comment]
Ok merci 


Cordialement 

Mail: guillaume.maniaval@adpsa12.fr 
Tel direct: 05 65 73 77 88 
Tel Standard : 05 65 73 78 80 

Guillaume Maniaval 

Adpsa Multimédia 
Carrefour de l'agriculture 
Boulevardu du 122 ieme RI 
12026 Rodez cedex 09 

----- Mail original -----

De: "wouldsmina" <notifications@github.com> 
À: "wouldsmina/Libertempo" <Libertempo@noreply.github.com> 
Cc: "GuillaumeAMM12" <guillaume.maniaval@adpsa12.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 14 Septembre 2016 11:39:21 
Objet: Re: [wouldsmina/Libertempo] Compatibilité avec Mysql 5.7.13 (ubuntu) (#225) 



Salut, 
modifier ou supprimer un congés validé c'est pas possible pour l'employé. Par contre le responsable peut supprimer un congés qu'il a validé. 
L'employé peut modifier une demande tant qu'elle n'a pas été traitée. Par contre, il n'est pas possible de modifier le type de congés, pour cela il doit supprimer et refaire une demande...

**Comment by wouldsmina** [comment]
je déterre ce sujet pour savoir si ce problème n'est pas lié au mode SQL (cf. #235)?

**Comment by Prytoegrian** [comment]
[Très certainement, si]

**Comment by wouldsmina** [comment]
alors on ferme.
