### ISSUE TITLE
Convention de codage ?

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#23]
Hello, je souhaiterais contribuer au projet mais je n'ai trouvé nul part mention d'une convention de codage (formelle ou perso). Laquelle suivez-vous ? Je voudrais pousser correctement les quelques améliorations que j'ai en tête.

**Comment by wouldsmina** [comment]
Salut,
En fait il n'y en a jamais eu 😅
En reprenant le code de php-conges j'ai essayé de garder la même syntaxe.
Si tu veux on peut travailler sur une convention de codage ensemble...
En tout cas, tes contributions sont le bienvenue!
A+

**Comment by Prytoegrian** [comment]
D'habitude, j'ai tendance à tout simplement suivre la [PSR-2](http://www.php-fig.org/psr/psr-2/) dans mes projets mais je suis pas contrariant ; au moins ça peut donner une base de réflexion. Je te laisse y jeter un œil, si tu as des points de désaccord avec une règle et que tu préfères une autre forme, discutons-en ! :)

**Comment by wouldsmina** [comment]
C'est à quelques détails près la convention utilisée. la grosse différence c'est l'indentation que je fais avec des tabulations plutôt que 4 espaces. c'est bien la PSR-2! ça me servira de pense bête...
Merci.

PS : les prochaines améliorations se feront sur la version 1.7.1

**Comment by Prytoegrian** [comment]
Dis moi si tu veux conserver les tabulations plutôt que les espaces, histoire que je mette à jour mon IDE.
Va pour la PSR2 (j'en profiterais pour mettre à jour le `readme` pour l'y mentionner, pour les futurs contributeurs).
Pas de souci, je pousserai sur ta branche de `1.7.1beta`, dans le week-end si tout va bien.

**Comment by wouldsmina** [comment]
Oui, vue que le projet est quasiment qu'avec des tabulations, c'est plus simple de continuer comme ça.
Merci.

**Comment by Prytoegrian** [comment]
Ok. Par contre, plus j'avance et plus je me dis que je devrais pousser sur une `develop` car je fais des gros changements et je suis un peu frileux vis à vis de ça. Mes tests sont bons mais comme je n'ai pas ton œil, je préférerais ; ça n'atteint pas encore le niveau d'exigence d'une `beta`. Tu pourrais créer une branche `develop` ? À moins que tu ai une autre idée.

**Comment by wouldsmina** [comment]
Ok. Pas de soucis, je te fais une nouvelle branche tout a l'heure.

**Comment by Prytoegrian** [comment]
C'est bon, j'ai eu ma réponse !
