### ISSUE TITLE
Heures de récupération

### ISSUE THREAD

**Issue by bopware** [wouldsmina/Libertempo#231]
Bonjour,

Est-il possible de paramétrer des heures de récupération ?

Je m'explique : un salarié fait 2 heures supplémentaires. Il faudrait que son responsable puisse lui attribuer ses 2 heures afin que le salarié puisse les prendre par la suite en congés exceptionnels par ex.

Merci pour votre retour.

**Comment by wouldsmina** [comment]
[on y travail](https://github.com/wouldsmina/Libertempo/tree/topic/heure) pour la prochaine version.
wait and see ;)

**Comment by bopware** [comment]
Vivement la prochaine version ;-)

Autre question qui n'a rien à voir : est-ce qu'un utilisateur qui fait une demande de congés peut recevoir sa demande par mail ?

Merci

**Comment by wouldsmina** [comment]
> est-ce qu'un utilisateur qui fait une demande de congés peut recevoir sa demande par mail ?

Non, ce n'est actuellement pas possible. Les notifications devraient être revues dans une futur version (1.10 certainement)...
Si tu en as absolument besoin, fait nous une demande sur la [mailing list](http://libertempo.tuxfamily.org/mailing-list/) en détaillant bien le besoin et l'utilité d'une telle fonction. Si tu arrive à nous convaincre, on le mettra sur notre (longue) todo-list ;)
