### ISSUE TITLE
Faire de l'intégration continue 

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#233]
Nous avons un cycle de dev relativement lent mais je pense que nous gagnerions à lancer une batterie de tests automatisés pendant nos développements. En effet, je me suis aperçu que les quelques tests que nous avons réalisés en TU échouaient ; j'ignore encore si c'est grave et depuis combien de temps c'est le cas. 
Cela me fait me dire que nos tests sont plus là à but de décor qu'autre chose

Vu l'avancement de la roadmap et de ses objets, cela pourrait ne pas être pleinement utile mais ça nous fera prendre l'habitude de voir le petit badge de build et nous aidera à travailler pour le rendre vert et surtout, pertinent. 

Il y a quelques outils sur le net gratuits pour les projets libres, comme [Travis](https://travis-ci.org/). Ça mérite de se pencher dessus.

**Comment by wouldsmina** [comment]
Ok! je connaissais pas. L'idée me plait, je creuse le sujet et on fait le nécessaire...

**Comment by Prytoegrian** [comment]
Close?

**Comment by wouldsmina** [comment]
ouaip!
