### ISSUE TITLE
[Heures additionnelles / repos] Refusionner les heures

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#251]
En terme de données et de métier, il est préférable que les heures additionnelles et de repos soient séparées et ça a été l'objet d'une PR de faire cela. Malgré cela, ce n'est pas utilisable. Je créé donc ce ticket pour le mettre dans le backlog du [projet de la 1.9](https://github.com/wouldsmina/Libertempo/projects/2).

**Comment by Prytoegrian** [comment]
Tu me conseilles quoi comme ergonomie ?

**Comment by wouldsmina** [comment]
Tu fais référence à une vue particulière ou tout est a revoir??
Pour commencer, je pense qu'il faut que le responsable puisse attribuer un planning à ses employés.
Pour le reste, on en parlera en direct...

**Comment by Prytoegrian** [comment]
? Je parle des heures additionnelles / de repos. Je te demandais si tu avais des idées pour l'apparence

**Comment by wouldsmina** [comment]
Vu sur irc. en résumé on regroupe les onglets dans un dropdown.

**Comment by Prytoegrian** [comment]
Tu veux dire maintenant ?

**Comment by wouldsmina** [comment]
euh, non. c'est pour pas zapper

**Comment by Prytoegrian** [comment]
Ok, je clos donc, pour le moment
