### ISSUE TITLE
Utilisateur base de données

### ISSUE THREAD

**Issue by lordystyle** [wouldsmina/Libertempo#252]
Bonjour petite question : 
Quelle droits doit avoir le user de la base de données dans libertempo ? 
En effet j'aimerai limiter les comptes avec trop d'accès sur la BD car ouverture du serveur web à l’extérieur? 

Ou peux on changer l'utilisateur dans libertempo ? un fichier de conf ?

**Comment by wouldsmina** [comment]
> Quelle droits doit avoir le user de la base de données dans libertempo ?

Il doit avoir les droits standards sur sa base de données.

> En effet j'aimerai limiter les comptes avec trop d'accès sur la BD car ouverture du serveur web à l’extérieur

ton serveur mysql est sur le même serveur que le web?? 

> Ou peux on changer l'utilisateur dans libertempo ? un fichier de conf ?

Ouaip! dans cfg/dbconnect.php

**Comment by lordystyle** [comment]
> Il doit avoir les droits standards sur sa base de données.
J'ai testé pour l'instant ça marche

> ton serveur mysql est sur le même serveur que le web?? 
Oui c'est ça
> Ouaip! dans cfg/dbconnect.php
Ok c'est fait merci

**Comment by wouldsmina** [comment]
il est inutile, voir même dangereux de mettre ton serveur mysql en dmz. Je ne peux que te conseiller de monter un serveur mysql a part. Ou au moins (si tu n'as pas le choix), faire en sorte que ton serveur mysql n'écoute qu'en local...

**Comment by lordystyle** [comment]
Ok je prends note. je vais testé tout ça (pour l'instant c'est sur un serveur synology donc bien pratique) et quand je mettrais la dmz je vais migrer ma base.
Merci du conseil

**Comment by Prytoegrian** [comment]
Il ne t'est pas possible de créer un user mysql qui n'a accès qu'à LT et qu'à LT seulement ? Ou j'ai compris le problème de travers ?

**Comment by lordystyle** [comment]
Salut Pryto, 
Si bien sur que si c'est possible c'est ce que j'ai fais. ^^ mais c'est juste que j'avais initialement installé avec le root

**Comment by Prytoegrian** [comment]
![](http://fr.web.img6.acsta.net/r_x_600/newsv7/14/09/18/14/28/0959700.jpg)

**Comment by lordystyle** [comment]
^^ c'était un serveur test
