### ISSUE TITLE
Erreur envoie de mail libellé "Absenceé

### ISSUE THREAD

**Issue by Vertacou** [wouldsmina/Libertempo#253]
Bonjour,

J'ai configuré dans Libertempo différents types d'absences.
Quand je fais une nouvelle absence en selection un de mes libellés "absences" j'ai ce message d'erreur :

Message was not sent 
Mailer Error: Corps du message vide.
Modifications enregistrées avec succès ! !

La demande est bien prise en compte mais aucun mail ne part.
Tout fonctionne bien pour un congé ou un congé exceptionnel.

Merci encore pour le travail fournit !

Nicolas

**Comment by wouldsmina** [comment]
Bonjour,

C'est corrigé [ici](https://github.com/wouldsmina/Libertempo/archive/1.8.zip). cf. #242 

a+

**Comment by Vertacou** [comment]
Merci.
Que je comprenne bien, j'ai juste à écraser les fichiers existants part ceux du zip ?

**Comment by wouldsmina** [comment]
oui, tu peux faire comme ça, même si, perso, je préfère déplacer le dossier existant, puis copier le dossier cfg dans la nouvelle version...

**Comment by Vertacou** [comment]
Merci.
