### ISSUE TITLE
Responsable : Délégation du traitement des demandes en cas d'absences

### ISSUE THREAD

**Issue by wouldsmina** [wouldsmina/Libertempo#258]
La délégation du traitement des demandes en cas d'absence du responsable permet, en cas d'absence du N+1, N+2 (soit le responsable du responsable et non le grand responsable) a la possibilité de traité les demandes de N+1. Cette fonctionnalité est paramétrable depuis la configuration générale.

Dans le version 1.9, le traitement des demandes a été intégralement revue. Il faut donc rétablir cette fonctionnalité. 
Cette dernière sera quelques peux différentes de l'actuel, en voici la liste : 
- En plus de l'option globale, l'option devra être paramétrable directement par le responsable concerné
- Les demandes déléguées seront séparées des demandes lambda (de la même façon que les demandes du grand responsable?)

D'autres points se revelerons peut être au fur et à mesure du développement...

**Comment by Prytoegrian** [comment]
> En plus de l'option globale, l'option devra être paramétrable directement par le responsable concerné

Tu peux m'en parler davantage ? Je vois pas ce que tu veux dire.

> Les demandes déléguées seront séparées des demandes lambda

Est-ce-qu'il y a des ergonomies existantes sur lesquelles on pourrait s'appuyer ? Sinon on pourrait juste mettre une icone pour représenter le fait qu'il s'agit d'une délégation. Genre un dans ce style là http://fontawesome.io/icon/share-square/

Sinon, j'ai besoin d'informations. J'arrive pas à me représenter ce que ça change que ce soit le responsable du responsable qui soit le délégué plutôt que le second validateur.

**Comment by wouldsmina** [comment]
> Tu peux m'en parler davantage ? Je vois pas ce que tu veux dire.

Si l'option globale est activée, chaque responsable dispose d'une option permettant d'activer cette fonctionnalité. S'il ne l'active pas, les demandes ne sont pas déléguées.

>  Est-ce-qu'il y a des ergonomies existantes sur lesquelles on pourrait s'appuyer ?

Sur la 1.9, les demandes de premières et de secondes validation sont séparées par un titre (j'ai pas de capture sous la main, je te sors ça dés que possible).

> Sinon on pourrait juste mettre une icone pour représenter le fait qu'il s'agit d'une délégation

Pourquoi pas, je ferai un essai.

> J'arrive pas à me représenter ce que ça change que ce soit le responsable du responsable qui soit le délégué plutôt que le second validateur.

- Dans le cas d'une double validation et si le resp du resp (N+2) n'est pas grand resp, la demande sera validé par N+2 puis le grand resp (la double validation est maintenu). 
- Dans le cas de la simple validation, il n'y a pas de grand resp.
- Dans le cas ou le responsable n'a pas de responsable, les demandes reste en attente...

**Comment by wouldsmina** [comment]
fait sur topic/heure
