### ISSUE TITLE
Mise en place de bibliothèques de fonctions

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#26]
Comme évoqué par #25 (et afin d'avoir à terme une structure objet), nous gagnerions à factoriser le code en bibliothèques de fonctions.

J'ai déjà amorcé le chantier et voici la liste des choses à faire, par module : 
#### Utilisateur
* [x] changer de mot de passe
* [x] absence (ajout, modif, suppression)
* [x] demande en cours
* [x] échange
* [x] historique (congés, autre)

#### Responsable
* [x] ajout congés
* [x] cloture exercice
* [x] traitement demande
* [x] traitement utilisateur

#### Admin
* [x] gestion utilisateur (ajout, suppression, modif)
* [x] gestion groupe
* [x] configuration
* [x] sauvegarde db

#### Installation
* [x] installation
* [x] mise à jour

#### Édition
* [x] pdf
* [x] utilisateur
* [x] papier

#### Export
* [x] vcard
* [x] ics

#### HR (qu'est ce que c'est d'ailleurs ?)
* [x] traitement utilisateur
* [x] traitement demande
* [x] ajout congés
* [x] cloture
* [x] jours chomés
* [x] jours de fermeture

#### Calendrier
* [x] calendrier

**Comment by wouldsmina** [comment]
Quel chantier! J'ai encore des petites retouches a faire sur /utilisateur attend un peu avant de modifier. 
Pareil pour hr, qui est le haut responsable (même si j'aime pas trop ce choix de dénomination). Clairement, cette vue permet de consulter et d'éditer  les demandes de tous les utilisateurs. Chez moi, c'est la secrétaire du grand responsable (n+2) qui a ces droits.

**Comment by Prytoegrian** [comment]
Même si normalement git retrouvera ses billes entre nos correctifs, t'inquiète pas pour ça (au pire je ferai un merge avant de pousser). Ça avance vite mais j'en ai encore pour un moment.

Comment on accède au module de haut responsable ?

**Comment by wouldsmina** [comment]
ah oui, je vois qu' "utilisateur" est quasi-fini. :smiley: 
Sur la [demo](http://libertempo.tuxfamily.org/demo/), c'est pierre (mdp: pierre) qui a les droits HR. Dans la liste déroulante en haut a gauche tu pourras choisir HR.

**Comment by Prytoegrian** [comment]
Oui, ça avance bien, c'est que du déplacement de code après tout. J'ai poussé ma branche de travail sur mon repo, on est déjà à 1500 lignes de diff, autrement dit si je finis tout dans la même PR ça sera sûrement inbuvable ; la revue et le test vont forcément en pâtir. Faut que je trouve une manière de présenter les choses correctement, mais pas ce soir. Je vais laisser mûrir tout ça.

**Comment by Prytoegrian** [comment]
J'avais dans l'idée de faire une PR à la fin de chaque module, pour qu'on puisse digérer, discuter, revoir et tester tout ça tranquillement.
Dis moi ce que tu préfères.

**Comment by wouldsmina** [comment]
je suis justement en train de regarder ce que tu as pousser hier... Je pense aussi qu'une PR pour chaque module vaut mieux que tout d'un bloc, déjà que pour un module c'est énorme...

**Comment by Prytoegrian** [comment]
Ok, je ferai donc une PR ce soir (sauf erreur) avec la factorisation du module utilisateur. Fais chauffer les tests ! :p

**Comment by Prytoegrian** [comment]
Je m'attelle à `admin` et je suis incapable de trouver comment on accède à toutes les pages relatives aux groupes. Un coup de main ?

**Comment by wouldsmina** [comment]
Je te fais un topo ce soir...

**Comment by wouldsmina** [comment]
Pour accéder à la gestion des groupes, il faut que gestion_groupes soit à true dans la configuration (ou dans la table conges_appli si tu préfère).
dans la page principale de l'admin ( admin_index.php ligne 63) tu a les 3 onglets : 
admin-group-responsables : pour definir les responsables et grand resp de chaque groupe. Il faut au moins un utilisateur avec les droits responsables.
admin-group-user : pour mettre les users dans les groupes
admin-group : Pour créer les groupes

Ces menus te permettent de définir les groupes par utilisateur ou les utilisateurs d'un groupe (idem pour les responsables).

**Comment by wouldsmina** [comment]
au fait, j'ai déplacé la définition des fermetures et des jours fériés vers l'accès RH sur la branche [1.7.1beta](https://github.com/wouldsmina/Libertempo/commit/ec5f6cc7c6e92cd4806de69b7e46cc6c1bed90a7)

**Comment by Prytoegrian** [comment]
Nickel merci, je vais configurer tout ça.
Tu peux me mettre tes changements dans ton `develop` ? Comme ça je ne vadrouille pas sur plusieurs branches chez toi, je ne me tiens à jour que de `develop`. Merci d'avance.

**Comment by wouldsmina** [comment]
c'est fait cc9b8544e0f171d3bd98a52a2ceba087043f3c52

**Comment by wouldsmina** [comment]
Lorsque le responsable annule le congés d'un utilisateur, la page bloque sur un fond bleu. Erreur apache : 

PHP Warning:  fopen(../dump/sql_1445170528.dump): failed to open stream: Aucun fichier ou dossier de ce type in /var/www/html/Libertempo-develop/includes/SQL.php on line 145, referer: http://localhost/Libertempo-develop/responsable/resp_index.php?session=phpcongesbb1f5715efdef9259ac15a5030e8943f&onglet=traite_user&user_login=georges

**Comment by Prytoegrian** [comment]
Ah, je cherchais ton rapport de bug, je savais plus où il était caché ! C'est la gestion des droits système – en plus d'un répertoire parent inexistant – qui pose problème. Je ne sais pas encore comment contourner ça.

Remarque : le bug apparaît dans n'importe quel cas de requête sql qui plante.

**Comment by Prytoegrian** [comment]
Hum, il faudrait un repertoire `dump` avec les mêmes droits que `cfg` et s'assurer de son existence lors de la résolution du `path`. S'il n'existe pas, une petite fonction du type : 
```php
createDir($pathName, $rights, $owner, $group = '') {
}
```

devrait faire le job

**Comment by wouldsmina** [comment]
>  il faudrait un repertoire dump

oui j'ai découvert cela avec ce bug : https://github.com/wouldsmina/Libertempo/commit/da5d18312ef2de742145a9f7f1a4a6b35c9c40de , ce qui m'étonne c'est qu'avant je n'avais pas le dossier dump, mais j'obtenais tout de même un rapport de bug...

**Comment by wouldsmina** [comment]
Pour le dossier hr, tu devrais retrouver la même structure que le responsable, il n'y a que quelques fonctions ou requêtes qui varient...
Une fois que tu as terminé (revue et testé), on merge vers la beta. ok?

**Comment by Prytoegrian** [comment]
Il doit y avoir avoir un droit qui a différé dans ton repo local, je vois que ça. Chez moi, les fichiers sont tous chez mon user, et www-data n'a aucune possibilité d'écrire.

J'ai commencé à jeter un petit coup d'oeil, ça ressemble beaucoup oui. Normalement le week-end prochain ou le suivant on sera bon.

Je pense aussi qu'il faut merger tout de suite après. Déjà pour faire vivre le code au sein de beta, et aussi pour que tous les contributors puissent se familiariser avec la nouvelle forme. 
Je créé un nouveau ticket pour la prochaine étape, histoire qu'on commence à en discuter.

**Comment by Prytoegrian** [comment]
\o/ :shipit:
