### ISSUE TITLE
Fonctionnalité heures additionnelles et heures de repos

### ISSUE THREAD

**Issue by augras** [wouldsmina/Libertempo#271]
Bonjour,
Je reprends ici, sur un fil dédié, comme préconisé suite à un échange de mail, la problématique des heures supp/récup.... qui seront intégrées sous la forme d'heures additionnelles et heures de repos dans la prochaine version : excellente nouvelle.
Actuellement on utilise au boulot un tableau que j'ai adapté pour calculer les récupérations générées par un dépassement du temps de travail.
Un coefficient spécifique est appliqué en fonction des différents cas de figure, les bornes des horaires de nuit sont renseignées, et les jours fériés/de fermeture/week-end identifiés : le tableau est actualisé à chaque changement d'année.
Il suffit ainsi d'indiquer la date du dépassement avec les bornes horaires et le tableau calcule automatiquement, en fonction du jour (samedi/dimanche/férié/fermeture), de l'heure (normale ou de nuit) le temps à récupérer.
Est-ce que dans la future version le fonctionnement est similaire ? On fait une demande de dépassement horaire en indiquant la date et les bornes horaires et le calcul est automatique ?
Je suppose que vous envisagez un max de cas de figure mais lors de l'utilisation de ce tableau maison il y a eu un soucis assez tardivement dans l'année : quand quelqu'un dépassait 24h ça dysfonctionnait car 24h faisant une journée...
Merci,
Philippe

**Comment by wouldsmina** [comment]
Bonjour,
La gestion des heures additionnelles/repos ne permet pas l'application de coefficient, désolé. Son fonctionnement est, somme toute, assez simple, le formulaire d'heures additionnelles incrémente un compteur et celui des repos le décrémente. Les heures sont aussi soumises à validation avec les mêmes règles que les congés.
a+

**Comment by augras** [comment]
Bonjour,
Merci. 

	Il faut donc conserver notre tableau pour faire les calculs et intégrer le résultat dans la demande d'heures sup. C'est déjà bien que l'on puisse gérer les demandes d'heures sup et de repos : on peut sans soucis demander des heures sup sous la forme 3h34 par exemple et poser une récup comme 2h10 ? 

	On peut tester déjà ? 

	Merci,

Philippe

2 décembre 2016 16:22 "wouldsmina"  a écrit: 
	Bonjour,
La gestion des heures additionnelles/repos ne permet pas l'application de coefficient, désolé. Son fonctionnement est, somme toute, assez simple, le formulaire d'heures additionnelles incrémente un compteur et celui des repos le décrémente. Les heures sont aussi soumises à validation avec les mêmes règles que les congés.
a+

**Comment by wouldsmina** [comment]
hmm, je pensais t'avoir répondu! désolé.
Notre travail ce trouve [ici](https://github.com/wouldsmina/Libertempo/tree/topic/heure). Il nous reste encore #300 , #256 et la traduction à faire passer et ce sera opérationnel (en beta). 

Je ferme ce ticket, il fait doublon avec #127 

a+
