### ISSUE TITLE
Erreur du mailer lors de la pose d'une absence formation

### ISSUE THREAD

**Issue by Shadok** [wouldsmina/Libertempo#273]
Avec la 1.8.1 et PHP 7.0.13/Nginx, lors de pose d'une absence de type formation sur 24h (journée entière) :
Message was not sent
Mailer Error: Corps du message vide.

Aucune information n'a été ajoutée dans le champ "Commentaire".
J'ai utilisé mon compte admin (pas le compte admin principal) pour créer cette demande en mode utilisateur (demande pour moi-même, donc).

Je suis le responsable de mon groupe.

**Comment by wouldsmina** [comment]
c'est corrigé [ici](https://github.com/wouldsmina/Libertempo/commit/a02cb9e917e08a25c766105e3d589d12745f032a)
