### ISSUE TITLE
CP en attente de validation mais aucune demande à valider

### ISSUE THREAD

**Issue by Shadok** [wouldsmina/Libertempo#274]
Avec la 1.8.1 et PHP 7.0.13/Nginx, j'ai posé des jours de congés (CP) depuis mon compte qui a les droits d'admin/RH (pas le compte admin générique), et je suis responsable de mon groupe.

Aucun email n'a été envoyé vu que je suis mon propre responsable, mais :
- mes congés apparaissent comme étant non encore validés dans le calendrier
- si je passe en mode responsable, je n'ai aucune demande à valider
- dans la liste des utilisateurs (section admin), je n'étais pas le responsable de mon propre compte (j'ai ensuite changé cela, mais cela n'a rien fixé)

**Comment by Shadok** [comment]
Par contre, si je passe en mode RH (toujours depuis mon compte), je vois bien la demande à valider.
Normal ?

**Comment by wouldsmina** [comment]
Oui, normal. un responsable ne peut pas se valider lui même. Il est possible d'auto-valider les demandes à condition que l'utilisateur n'ai pas de responsable (ni direct, ni de groupe)
