### ISSUE TITLE
Plusieurs responsables de même niveau

### ISSUE THREAD

**Issue by obinoby** [wouldsmina/Libertempo#279]
Bonjour,

Nous avons des employés dont le temps est réparti sur plusieurs équipes. Pour eux il serait utile de pouvoir déclarer plusieurs responsables qui recevraient tous la demande de congé et devraient tous la valider pour qu'elle soit acceptée.

Cordialement,

**Comment by wouldsmina** [comment]
Bonjour,
C'est déjà possible avec la gestion des groupes...
Il est prévu d'améliorer la gestion des groupes, jette un oeil à #219
