### ISSUE TITLE
53 semaines dans l'année ?

### ISSUE THREAD

**Issue by VV666** [wouldsmina/Libertempo#28]
Bonjour, 
si on regarde de plus prêt le calendrier, l'année 2015 compte 53 semaine sauf que 53*7 = 371 jours.
Ça crée un bug dans le calcul automatique des congés !

En fait,  au lieu que la semaine 1 de l'année 2016 commence le lundi 28 décembre 2015, Libertempo crée un 53ème semaine pour 2015, qui dépasse sur 2016. et la semaine 1 pour 2016 commence le lundi 4 janvier.
Merci pour vos corrections.

**Comment by VV666** [comment]
Précision, 
comme il y a un décalage, les temps partiels avec semaine paire / impair sont complétement faux. J'ai failli ouvrir un autre bug, mais visiblement, ça serait lié.

**Comment by wouldsmina** [comment]
Je dois revoir integralement la gestion des temps partiels. Je vais quand même essayer de corriger ce bug rapidement en attendant...
A+

**Comment by wouldsmina** [comment]
j'ai corrigé une erreur dans le calendrier d'échange des temps partiels. Je regarde demain pour les 53 semaines.

**Comment by wouldsmina** [comment]
2015 a bien 53 semaines!!! Je suis tout aussi étonné mais dans les calendriers de la poste, et si la poste le dit c'est que c'est vrai.  :stuck_out_tongue_winking_eye:
les numéros de semaine sont tiré de la commande date(), je peux donc pas y faire grand chose.

Pour ton problème de décalage semaine pair/impair, c'est sur l'année 2016 ou 2015?

**Comment by VV666** [comment]
C'est pour 2016 ... Le problème apparait après le 1 janvier.
Cela dit, on a 52 semaines sur les calendriers fournit par l'académie ... ^^

**Comment by wouldsmina** [comment]
nous vla propre!!

**Comment by wouldsmina** [comment]
Mais du coup, si 2015 a 52 semaines dans ton calendrier, c'est 2016 qui se retrouve avec 53 semaines? sinon, si on pousse la logique des 52 semaines sur le long terme, la première semaine de 2018 sera intégralement en 2017...

**Comment by VV666** [comment]
ben ... p'tê't ^^
Mais ça résoud pas nos soucis ^^

**Comment by wouldsmina** [comment]
Juste pour être sur, ton soucis c'est bien une inversion des semaines paires/impaires liée à la première semaine de 2016 qui selon l'académie débute le 28/12/15 mais pour le reste du monde :smiley: débute le 04/01/15 ?

**Comment by VV666** [comment]
oui, je me suis renseigné aussi et y a bien 53 semaine pour l'académie aussi...
Je vois demain avec la collègue qui a se souci. Et je reviens vers toi.

**Comment by Prytoegrian** [comment]
Ah ben j'apprends des trucs tiens ! :-p

**Comment by wouldsmina** [comment]
Pareil, j'avais jamais remarqué de 53eme semaine jusqu'à maintenant.

Vv666, je viens de comprendre se qui dérange ta gestionnaire, il y a 2 semaines impaire qui se suivent entre 2015 et 2016. Mais à défaut d'avoir un article de loi ou quoi que ce soit d'officiel à ce sujet, il faut appliquer la règle bêtement : déduire les TP impaire sur les 2 semaines.

**Comment by VV666** [comment]
Ok, j'ai transmis l'info. Merci pour vos recherches.

**Comment by wouldsmina** [comment]
pas de problème, on aura au moins appris qu'il peut y avoir 53 semaines dans l'année...
