### ISSUE TITLE
2 Bugs Edition pdf

### ISSUE THREAD

**Issue by scargoll** [wouldsmina/Libertempo#283]
Bonjour,

J'utilise Libertempo 1.8 Quinnis sur une Ubuntu 14,  Apache 2.4.7, PHP 5.5.9, MySql 5.5.53.

Un premier petit bug et sa solution : 

Depuis la vue "Calendrier", je sélectionne un "groupe à afficher", je valide, la page se rafraichit et l'affichage est nickel.

Si je vais sur "version imprimable", pareil c'est nickel , mais si je vais sur "version pdf", le tableau est bien affiché mais pas rempli : j'ai bien la liste des utilisateurs (colonne "nom" ), la quotité (colonne "%") mais aucun congé ni aucun solde n'apparait.

Dans les logs, j'ai remarqué : 
`PHP Warning:  array_map() expects parameter 1 to be a valid callback, class 'SQL' not found in /var/www/html/libertempo/calendrier-pdf.php on line 190`

En effet si dans calendrier-pdf.php je remplace la ligne 190 (ligne 164 par rapport aux sources dispo sur Github) : 

`tab_logins = array_map("SQL::quote", $tab_logins);`

par

`$tab_logins = array_map("\includes\SQL::quote", $tab_logins);`

La version pdf est maintenant correctement remplie.

Dans ce même fichier calendrier-pdf.php, j'ai repéré le même problème sur la ligne 1041 (ligne 1015 par rapport aux sources dispo sur Github), mais pas vu le bug que ca doit provoquer.

Un deuxième petit bug, sans solution, dans cette même impression pdf, si on a des personnes avec des noms très (trop!) longs on ne voit pas les colonnes de droite ("Solde"), il faudrait forcer le tableau à 100% de la largeur de la page ...

Cordialement, Scargoll.

**Comment by Prytoegrian** [comment]
Hello,

la génération PDF du calendrier a disparu de la prochaine version à livrer. Notre fonctionnalité majeure de la version est la gestion des heures additionnelles de travail et des heures de repos et nous avons dû refondre quelques pans de l'appli pour intégrer ces outils. Le calendrier a aussi profité de cette refonte (au passage, ça a permis de corriger de nombreux tickets de bugs ouverts) et vu le format, nous avons dû nous résoudre à faire disparaître le calendrier PDF, aucun rendu n'était probant (ça allait du très moche à l'illisible).
Suite à la livraison, ce que nous espérons, c'est que s'il y a un vrai besoin sur l'impression PDF d'un calendrier, nous puissions avoir le besoin fondamental pour trouver un visuel satisfaisant pour tout le monde.


Beaucoup de blabla de contexte pour te dire de ne pas t'inquiéter, le bug est connu et il ne sera plus là pour la prochaine version (que nous sommes en train de peaufiner) :octocat:

**Comment by scargoll** [comment]
Bonjour,

Merci pour ton retour, vivement la prochaine version alors !

Bonne continuation, Scargoll.
