### ISSUE TITLE
Congé posé par le RH

### ISSUE THREAD

**Issue by messinac** [wouldsmina/Libertempo#286]
Une petite question, est-il possible pour le RH de poser les congés des employés?
Il nous serait très utile car nous sommes tous en consultance dans la société et lorsque les timesheet sont remise, il s'avère que certaines personnes ont posé des congés sans les entrer dans l'appli et il faut ensuite le courir après pour qu'ils soient ajouté. Et donc si cette opportunité était disponible ce serait un gain de temps.

Merci d'avance et désolé si la réponse était déjà connu, je ne l'ai pas trouvé.

**Comment by wouldsmina** [comment]
Salut,
Dans la page principale du RH clique sur l'oeil en face de l'utilisateur que tu veux...

**Comment by messinac** [comment]
Merci.
