### ISSUE TITLE
Légende du calendrier

### ISSUE THREAD

**Issue by messinac** [wouldsmina/Libertempo#287]
Bonjour,

Je vais vous embêter encore un peu, mais je ne trouve pas le fichier à modifier pour change le texte de la légende du calendrier.
Quelqu'un peu m'éclairer?

Merci beaucoup

**Comment by Prytoegrian** [comment]
Il s'agit de traductions officielles, elle sont donc compilées lors de la mise en production. Que cherches-tu à faire ? Sachant que la version qui arrive a complètement refondu le calendrier et cette partie n'apparaîtra plus…

**Comment by messinac** [comment]
Bonjour et bonne année.
En fait il y a des légendes donc je n'ai pas besoin, par exemple, nous n'avons pas de RTT. 
C'était donc pour mettre une légende "maison" on va dire.

**Comment by Prytoegrian** [comment]
Ok. Dans ce cas je te confirme que lorsque tu migreras sur la 1.9, il n'y aura rien à faire.
