### ISSUE TITLE
Gestion de la granularité des congés

### ISSUE THREAD

**Issue by DjMomo** [wouldsmina/Libertempo#289]
Bonjour,

Je suis un peu dans le même cas que @lacausse pour la gestion du pas (#260), qui montre qu'il manque une gestion de la granularité adaptée à chaque type de congé. 

Dans mon administration, dans un même service, 2 groupes de personnels à horaires de travail et systèmes de congés différents.
Chaque groupe possède sa propre organisation de congés (et ne peut faire une demande de CP/ARTT de l'autre groupe) :
Pour le premier, des jours _entiers_ de congés payés et des jours _entiers_ de RTT,
Pour le second, des _cycles_ de congés payés et des jours _entiers_ de RTT.

Pour le premier groupe, il faudrait pouvoir ne poser que des journées entières de CP/RTT (avec la v1.8.1 on peut actuellement poser des 1/2 journées). La granularité devrait passer de 0,5 à 1 pour les congés de ce groupe.

Pour le second groupe, c'est le même principe.
Les _cycles_ sont basés sur des semaines entières de 7 jours. L'agent doit poser une semaine entière du lundi au dimanche et cela lui décompte 1 cycle entier (il dispose de N cycles (et non pas N*7 jours) de congés payés par an). Ici, la granularité des CP devrait être de 7 (avec éventuellement un jour de semaine de début pré-établi).

Est-ce que cette amélioration est envisageable ?

**Comment by wouldsmina** [comment]
Bonjour,

Cela va être compliqué de mettre en œuvre un tel fonctionnement, d'autant plus sans cadre juridique. Nous nous concentrons surtout à améliorer le code actuel et à se calquer sur la réglementation française, ce qui est déjà pas évident vu tout les cas particulier...
désolé.
