### ISSUE TITLE
service RH tatillon : mode HR affiché une fois sélectionné

### ISSUE THREAD

**Issue by adminSNAO** [wouldsmina/Libertempo#29]
Bonjour,

Merci pour les corrections de la semaine dernière, ça marche impec.

Notre service RH nous fait remarquer qu'une fois le mode RH sélectionné, c'est "MODE HR" qui s'affiche et ça les gêne ENORMEMENT ... ;o)
J'ai regardé pour modifier les fichiers .po et .mo mais je ne trouve pas de MSGSTR affichant "MODE HR" dans le .po qui correspondrait à ce "souci".
Merci d'avance de corriger cette faute impardonnable ! ;o)

**Comment by wouldsmina** [comment]
Le mieux serait de trouver une meilleur dénomination pour cette vue. Pour info :
HR=haut responsable.
RH=ressources humaines.

A terme, cette vue permettra de:
- valider (ou refuser), modifier ou ajouter une demande pour n'importe quel utilisateur.
- ajouter, désactiver, modifier ou supprimer un utilisateur.
- gérer les groupes et responsable.
- jours de fermeture, jours chômés...

En clair, les droits admin sans la configuration général.

Une idée de nom? Sinon, je reste sur la moins pire: RH

Tu ne trouve pas la traduction car HR est codé en dur! Et ça je vais le modifier sans attendre...
Merci.

**Comment by Prytoegrian** [comment]
Peut-être que le problème est à prendre dans l'autre sens. Je veux dire : reprendre les deux termes « responsables » pour identifier clairement : 
* un responsable qui ne gère que son groupe (il me semble qu'un « simple » responsable ne possède qu'un groupe, corrige-moi si je me trompe)
* un responsable de l'appli entière

**Comment by wouldsmina** [comment]
Oui et non :D. Il y a aussi le grand responsable, qui valide les demandes des utilisateurs après une première validation par le responsable. cela est possible seulement si la double validation est activée. Dans ce cas de figure, il y a clairement une notion de hiérarchie. Par contre ce qui me dérange pour le HR, c'est qu'il n'est pas forcément le supérieur du grand resp. 

Sinon, tu verrais ça comment?

**Comment by wouldsmina** [comment]
Non, un responsable peut gérer plusieurs groupe, l'inverse est moins évident mais ça c'est un autre problème...

**Comment by Prytoegrian** [comment]
Ah ok, j'avais pas conscience de ces subtilités. Je sais pas trop pour le moment, je vais me replonger dans l'appli, voir si j'ai un éclair de génie (on peut rêver ! ^^)

**Comment by wouldsmina** [comment]
en attendant, je vois pas d’où viens ce "HR"! :open_mouth:

**Comment by wouldsmina** [comment]
C'est bon. Tu peux télécharger la correction...

**Comment by adminSNAO** [comment]
nouveau texte = "BUTTON_HR_MOD" :o/

**Comment by wouldsmina** [comment]
As tu mis a jour le fichier local/fr_fr/php_conges.mo et po.
J'ai ajouté la traduction pour faire propre.

**Comment by adminSNAO** [comment]
oui avec celui du .zip

**Comment by Prytoegrian** [comment]
Tu as vraiment redémarré Apache pour des trad ? Ça semble un peu poussif, on devrait pouvoir faire mieux.

**Comment by wouldsmina** [comment]
oui, c'est bizarre, j'ai fait mes test à la volée sans problème. Bon l'important c'est que le problème est réglé, la prochaine fois essaye un reload pour voir...

**Comment by adminSNAO** [comment]
Ca a l'air de fonctionner parfaitement comme ça (c'est pas pour le temps que ça prend de redémarrer apache ...)
Encore une fois, merci pour ta réactivité, on sent que le projet te tiens à coeur :o)

**Comment by Prytoegrian** [comment]
Non, bien sûr. J'ignore quel est ton archi réseau derrière donc chez toi ça pourrait se passer sans encombre et c'est tant mieux. Je levais juste le fait que, normalement, une mise à jour légère comme les trads de l'appli ne devrait demander qu'un patch des sources, éventuellement un patch DB, mais pas plus. Dans le cas contraire, l'appli fait des suppositions sur une couche plus bas niveau, ce qui ne devrait pas arriver. Mais si @wouldsmina dit que c'est pas « normal », je le crois :smile:

**Comment by wouldsmina** [comment]
Tu dois avoir du cache quelques part (reverse proxy, APC)...

**Comment by wouldsmina** [comment]
j'ai corrigé un bug lié à cette modif. la barre de menu est vide, c'est particulièrement gênant pour l'admin...
