### ISSUE TITLE
Erreur suite a insertion d'une balise <SCRIPT> dans la partie commentaire dans  demande de congès

### ISSUE THREAD

**Issue by GDenis13** [wouldsmina/Libertempo#292]
Le fait de mettre une balise   `<SCRIPT>` alert("totot");  dans le commentaire d'une demande de congès fait planter l'affichage de la liste des demandes en cours.
La demande n'est plus accessible en modification, suppression...
Pas de messages d'erreur dans les logs.
Le seul moyen d'intervenir est de modifier la données dans la table concernée.

**Comment by wouldsmina** [comment]
@GDenis13 il manque peut être une partie de ton message. non??

**Comment by GDenis13** [comment]
yep c'est le "nettoyeur" de code qui est passé par la...

c'est modifié

**Comment by wouldsmina** [comment]
ok. @Prytoegrian a bossé sur la sécurité avec ZAP. Cette faille est corrigée [ici].(https://github.com/wouldsmina/Libertempo/pull/284/files#diff-a2067f13fb53ade9f7bd2564012fe865R136)
Tu peux le tester si tu veux, c'est dans cette PR : #284  

Merci et n'hésite pas a nous remonter d'autres faille si tu en trouve ;)

**Comment by wouldsmina** [comment]
PS : je ferme avant que #284 soit mergé, mais ça ne saurait tarder... donc disons que j'ai pris de l'avance :p
