### ISSUE TITLE
[Traduction] script pour identifier les traductions manquantes

### ISSUE THREAD

**Issue by wouldsmina** [wouldsmina/Libertempo#296]
J'ai créer un petit script en perl pour identifier les traductions manquantes dans LT. Je le met ici pour ne pas le perdre/oublier.

```Perl
#!/usr/bin/perl
use File::Find;

find(\&chercheGettext, "Libertempo/");
my $file = "Libertempo/locale/fr_FR/LC_MESSAGES/php-conges.po";

sub chercheGettext
{
    my $getText ='';
    my @list =();
    @list = contenuPo();
    open   (FILE, "$_");
    while($line= <FILE> ){
        if ($line =~ /(_\(\'.*?\'\))/){
            $getText = substr $1,3,-2;
            if (!(grep {$getText eq $_} @list)){
                print $File::Find::name." : $. : $1\n";
            }
        }
    }
    close FILE; 
}

sub contenuPo
{
    my @list = ();
    open   (FILE, "$file");
    while($line= <FILE> ){
        if ($line =~ /^msgid/){
            if($line =~ /"([^"]+)"/) {
                push @list, $1;
            }
        }
    }
    close FILE; 
    return @list;
}
```

Ce n'est peut être pas parfait, mais ça a le mérite de faire ce qu'on lui demande.

Pour l'utiliser, rien de plus simple il suffit d’exécuter la commande `pl fichier.pl > resultat.txt` en prenant soin, au préalable, de modifier la variable $file et le chemin contenu en second paramètre de la commande `find`.

l'idéal pour compléter ce script serait d'avoir les traductions non utilisées dans LT, avec tous les changement opéré depuis php_conges, il doit certainement y avoir des valeurs inutilisées...

**Comment by Prytoegrian** [comment]
Tu as gist qui peut t'aider à récolter les quelques petits scripts dans le genre. Je trouve que là bas ça manque de visibilité mais c'est une option.

Sinon tu as : 
* Le wiki
* Un repo pour tous les scripts de LT
* La possibilité de mettre ton script dans https://github.com/Prytoegrian/libertempo-docker directement, dans une trousse à outil du parfait petit dev de LT

Voilà, choisis ta came copain :-)

**Comment by wouldsmina** [comment]
va pour le wiki dans un premier temps...
