### ISSUE TITLE
Demande de congé qui apparait en rose dans le calendrier même après acceptation du manager

### ISSUE THREAD

**Issue by Skyzeun** [wouldsmina/Libertempo#297]
Bonjour,

J'ai un petit problème. J'ai fais la mise à jour vers la 1.8.1 sans problème. Mon collègue a souhaité faire une demande de congés qui a ensuite été accepter par mon manager mais dans le calendrier elle reste en rose et ne passe pas en bleu. est ce un bug ou une fausse manipulation?

**Comment by wouldsmina** [comment]
salut,

On prépare une nouvelle version avec un calendrier intégralement revu.

wait and see ;)
