### ISSUE TITLE
message d'erreur suite à validation demande d'absence

### ISSUE THREAD

**Issue by augras** [wouldsmina/Libertempo#299]
Bonjour,
Lorsqu'un utilisateur saisi une demande d'absence le message suivant apparaît :
"Message was not sent
Mailer Error: Corps du message vide.
Modifications enregistrées avec succès ! !"
Comme indiqué l'absence est bien enregistrée et apparaît correctement partout. Par contre pas de massage au responsable !
Philippe

**Comment by wouldsmina** [comment]
pourtant il mériterait bien un massage ce pauvre responsable :p 
c'est corrigé sur [github](https://github.com/wouldsmina/Libertempo/commit/a02cb9e917e08a25c766105e3d589d12745f032a), mais j'ai (encore) oublié de mettre à jour le paquet sur le blog :/
