### ISSUE TITLE
Envoi de mail impossible

### ISSUE THREAD

**Issue by boicdelo** [wouldsmina/Libertempo#3]
Bonjour,

Je test depuis ce matin, et impossible d'envoyer des mails, lors d'une demande de congé par exemple.
J'ai remarqué une FATAL ERROR : 
PHP Fatal error:  Cannot access protected property PHPMailer::$to in /var/www/libertempo/fonctions_conges.php on line 1043

J'ai remplacé $mail->to par $mail->To et plus de fatal.
Par contre toujours pas d'envoi de mails puisque $mail->To est vide, mais si je remplace par FALSE pour toujours passer a l'envoi, le mail part bien.

Cordialement.

**Comment by wouldsmina** [comment]
Ce doit être lié à la mise a jour de phpmailer. J'ai modifié le test...
Merci.
