### ISSUE TITLE
Solde N+1

### ISSUE THREAD

**Issue by skonkuyt** [wouldsmina/Libertempo#306]
Bonjour,

Nous commençons à utiliser votre applicatif pour le tester dans notre environnement et nous nous heurtons à la problématique des congés pour l'exercice prochain.
En effet comment fait on pour avoir deux compteurs un de l'année N et N+1 ( dépose des congés d'été par exemple ou congés plus éloignés. ) ?
D'autre part dans les mails de double validation, au second nous perdons le salarié concerné.
Enfin comment gérer vous les demandes de congés sans solde , si le paramétrage interdit les congés négatifs ?
Merci de votre aide

**Comment by wouldsmina** [comment]
Bonjour,

Ce n'est pas possible. Il faut nécessairement changer d'exercice pour pouvoir poser des congés sur N+1, sinon c'est le solde N qui est décrémenté. Néanmoins il y a le ticket #171 à ce sujet, mais on ne sait pas encore penché sérieusement sur la question...
