### ISSUE TITLE
Détail de la hiérarchie des droits

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#32]
Je n'utilise pas l'appli donc ça peut expliquer que ça soit un peu flou pour moi, mais j'ai du mal à comprendre tous les types d'utilisateurs ainsi que les droits qui en découlent. Tu pourrais me faire un point dessus ?

**Comment by wouldsmina** [comment]
je vais commencer par le plus simple : 
- l'utilisateur : dépose des demandes (si autorisé dans la conf générale) et consulte ses congés.
Lors de sa création, il doit avoir un responsable, sinon c'est le responsable virtuel qui le gère (compte conges).
- le responsable, il dépose ou valide les demandes des utilisateurs dont il a la responsabilité. Il peut aussi ajouter des jours de congés de ses utilisateurs
- le grand responsable (qui en fait est un responsable n+2) est défini dans la gestion des groupes. ah oui, je te parle des groupes après...
- le RH, il  peut gerer les utilisateurs à tous les niveaux (je l'ai expliqué dans un autre ticket).

La gestion des groupes n'est pas obligatoire, lorsque cette fonction est activée, elle permet : 
- de gérer plus facilement les utilisateurs pour les responsables (de plusieurs équipes)
- de gérer la double validation (si activée) en définissant le ou les grands responsables par groupe.

n'hésite pas si tu as besoin de plus de détail sur un point.

**Comment by Prytoegrian** [comment]
Je me permets de te citer pour avoir tout sous les yeux : 

> Il y a aussi le grand responsable, qui valide les demandes des utilisateurs après une première validation par le responsable. cela est possible seulement si la double validation est activée. Dans ce cas de figure, il y a clairement une notion de hiérarchie. Par contre ce qui me dérange pour le HR, c'est qu'il n'est pas forcément le supérieur du grand resp.

 […]
>A terme, cette vue [haut responsable] permettra de:

> * valider (ou refuser), modifier ou ajouter une demande pour n'importe quel utilisateur.
* ajouter, désactiver, modifier ou supprimer un utilisateur.
* gérer les groupes et responsable.
* jours de fermeture, jours chômés...
En clair, les droits admin sans la configuration général.

J'ai le sentiment d'une grande complexité :cry: Mais c'est peut être inhérent à la manière dont fonctionne les congés en France, je saurais pas dire.

**Comment by wouldsmina** [comment]
oui c'est complexe :laughing:. A cause des particularités des congés en France (ou ailleurs, mais c'est vrai que c'est plutôt orienté France par méconnaissance du fonctionnement des autres pays), mais aussi du fait des évolutions multiples du code depuis les début de PHP_congés.

**Comment by Prytoegrian** [comment]
On se bat tous avec le legacy code ^^
Mais là d'où je suis, je perçois que tu as beaucoup de vérifications à faire pour savoir si une configuration est activée ou si un utilisateur a les droits sur un autre. Tu t'en sors ?

**Comment by wouldsmina** [comment]
pas toujours, mais j'y travail :smile:
comme je l'ai dis [dans mon premier article](http://libertempo.tuxfamily.org/libertempo-fork-de-php_conges) : "Libertempo est clairement arrivée au bout de ces capacités sous cette forme. Une refonte intégrale de l’application, afin d’offrir une version 2.0 plus proche des méthodes de développement d’aujourd’hui, est indispensable."

Et grâce à toi on s'approche d'une version 2.0 bien plus vite que je l’espérais!

**Comment by Prytoegrian** [comment]
T'as bien fait de linker l'article, je l'avais pas lu celui-là. C'est avec plaisir que je contribue, j'espère avoir assez de compétences pour apporter quelques choses.

Je te remercie de ta réponse complète, elle m'a aidée à y voir plus clair. À relire les différents rôles, je me demande si cette organisation n'irait pas : 
*(Tous les utilisateurs doivent être associés à des employés)*
* Utilisateur lambda : 
  - dépose des demandes
  - appartient à un groupe
* Responsable de groupe
  - gère les demandes de son (ses) groupe(s)
  - que l'utilisateur associé à l'employé soit créé ou non, il peut ajouter un congé pour l'employé, sous forme de demande uniquement si la double vérification est activée, sinon validée automatiquement
* Responsable du personnel
  - gère les employés (au sens large, responsable de groupe compris)
  - gère les groupes
  - valide les doubles vérif si activée
  - défini les jours non travaillés
* Admin
  - peut ajouter des utilisateurs et les associer à des employés
  - configure l'appli (mail, double vérif, etc)
  - met à jour l'appli

Ce système est sous forme de poupée russe, où chaque niveau possède tous les droits du rôle au-dessus de lui. Il y a évidemment quelques petites adaptations à faire : un responsable du personnel ne « demande » pas un congé, il est automatiquement validé, ce genre de choses…

Dans cette structure, la hiérarchie est claire, linéaire et sûre. Il me semble que le grand responsable fait doublon si le double check est activé (et dans le pire des cas, tu peux ne jamais t'en sortir, si par exemple un responsable demande un congés, il faudrait deux grands responsables, etc. Enfin il me semble), et de trop s'il ne l'est pas. Je l'ai donc fusionné avec le responsable du personnel. J'ai aussi trouvé des termes que je trouve parlant, ça vaut ce que ça vaut.


Dis-moi ce que tu en penses.

**Comment by wouldsmina** [comment]
Les multiples paramètres de configuration sont certes complexes à gérer, mais c'est l'essence de l'appli il faut le maintenir. c'est d'ailleurs le seul souhait du dev initial de php_conges. Je pense tout de même qu'une révision de la configuration serait bénéfique (tant au niveau de l'interface qu'au niveau du code).
Je reprends ta structure avec mon grain de sel : 

> *(Tous les utilisateurs doivent être associés à des employés)* 

cela veux dire qu'il peut y avoir des employés dans l'appli sans compte utilisateur associé? c'est a réfléchir...
> * Utilisateur lambda : 
  - dépose des demandes 

ou dépose directement un congés si pas de responsable (le responsable virtuel ne serait plus nécessaire)
>  - appartient à un groupe 

ou pas, dans ce cas, on considère qu'il n'a pas de responsable.
>* Responsable de groupe 
  - gère les demandes de son (ses) groupe(s)
  - que l'utilisateur associé à l'employé soit créé ou non, il peut ajouter un congé pour l'employé, sous forme de demande uniquement si la double vérification est activée, sinon validée automatiquement

non, même si la double validation n'est pas activée, un utilisateur peut être responsable d'un groupe et faire partie d'un autre groupe dans lequel il n'est pas le responsable (il pourra, par exemple, consulter le calendrier des 2 groupes, ces demandes seront validées par le resp du groupe si il y en a un...). La double validation (lorsqu'elle est activée dans la config général de Libertempo) est défini par groupe. Lorsqu'un groupe est soumis a double validation, un employé dépose une demande > le responsable accepte cette demande > le grand responsable accepte aussi (et c'est à ce moment seulement que le solde de l'employé est décompté).
J'ajouterai, à propos du grand responsable, qu'il peut aussi être responsable d'un service. 
> * Responsable du personnel
  - gère les employés (au sens large, responsable de groupe compris)
  - gère les groupes
  - valide les doubles vérif si activée

Il peut valider toutes les demandes. Il peut recevoir un mail à chaque demande (s'il le souhaite).
 > - défini les jours non travaillés
* Admin
  - peut ajouter des utilisateurs et les associer à des employés

Je vois ça coté responsable du personnel plutôt.
 > - configure l'appli (mail, double vérif, etc)
  - met à jour l'appli

Ça ajoute de la complexité (trop?), mais ça permet de viser large en terme de public pouvant utiliser cette appli (de l'association à la structure hiérarchique à plusieurs niveaux). Par contre, la double validation ne doit pas dépasser N+2 (si il faut attendre la réponse de 12 personnes avant d'obtenir un congés, autant se porter pale :stuck_out_tongue_winking_eye:).

**Comment by Prytoegrian** [comment]
Hum, t'es dur en affaire ! ^^  Normal, c'est le but.
Pour les employés sans utilisateur, oui, c'est une idée que j'ai eu comme ça. Selon l'utilisation de l'appli, il pourrait être possible d'avoir tous les « employés » listés dans l'appli sans que ceux ci aient un compte dans le logiciel. Sous cette forme, c'est l'un des responsables qui définirait les congés.


> un utilisateur peut être responsable d'un groupe et faire partie d'un autre groupe dans lequel il n'est pas le responsable

 Hum, je n'avais pas pensé à ce cas là. Je me démonte pas, je vais trouver une autre idée :p 

Pour l'admin, j'ai hésité à laisser l'ajout des utilisateurs à un responsable, mais du coup il n'y a plus que la config sous sa coupe, je ne sais si ça donne vraiment le bon impact.

J'essaie de bien comprendre comment visualiser / organiser tout ça, pour ne pas tâtonner dans le code quand je vais vraiment m'y attaquer ^^

**Comment by Prytoegrian** [comment]
Je viens de percuter que tu as ajouté une nouvelle notion "responsable de *service*". Tu vois quoi derrière ce terme ? Dans ma tête, c'est le sens que je donnais à groupe.

**Comment by wouldsmina** [comment]
Ah non, on fonctionne en service la ou je bosse, mais je pensais responsable de groupe.

A propos de l'admin, en partant du principe des "poupées russe", il devrait aussi avoir les droits "responsable du personnel", non?

**Comment by Prytoegrian** [comment]
C'est ce que je me dis oui. Dans mon idée, c'est le seul utilisateur qui ne soit pas associé à un « employé », ça devrait être une forme d'utilisateur virtuel. De ce fait, on a aucun intérêt à ce qu'il ai accès au module utilisateur / employé pour demander des congés (et le reste des cas qui s'appliquent à l'utilisateur / employé) parce qu'il ne fait pas vraiment partie de l'entreprise.
Par contre, on pourrait décider de lui donner tous les autres droits.

À dire vrai, le problème que j'ai avec l'admin c'est que je ne sais pas quel humain aura accès au compte, donc je ne sais pas comment mutualiser les droits qu'il a.

---
Je me permets de rebondir sur ce que tu dis, service / groupe. Il t'est possible de me détailler la forme de la hiérarchie de là où tu bosses à titre d'exemple ? (dans le logiciel j'entends)

**Comment by wouldsmina** [comment]
>C'est ce que je me dis oui. Dans mon idée, c'est le seul utilisateur qui ne soit pas associé à un « employé », ça devrait être une forme d'utilisateur virtuel. De ce fait, on a aucun intérêt à ce qu'il ai accès au module utilisateur / employé pour demander des congés (et le reste des cas qui s'appliquent à l'utilisateur / employé) parce qu'il ne fait pas vraiment partie de l'entreprise.
Par contre, on pourrait décider de lui donner tous les autres droits.

La dessus on est tout a fait d'accord.

>À dire vrai, le problème que j'ai avec l'admin c'est que je ne sais pas quel humain aura accès au compte, donc je ne sais pas comment mutualiser les droits qu'il a.

Partout ou j'ai vue php_conges d'installé, c'était toujours un informaticien qui avait les droits admin...

>Je me permets de rebondir sur ce que tu dis, service / groupe. Il t'est possible de me détailler la forme de la hiérarchie de là où tu bosses à titre d'exemple ? (dans le logiciel j'entends)

oui, mais pour bien détailler, je préfère te l'envoyé en privé...

**Comment by Prytoegrian** [comment]
D'accord, donc c'est : « *en cas de besoin d'un nouvelle config, je fais appel au service informatique car ce n'est pas une opération considérée comme habituelle dans l'appli* ». Si c'est ça, ça remet en cause le fait d'avoir le système de poupées russes pour l'admin…

Je te la mets là, je la supprimerai quand tu l'auras `prytoegrian[at]protonmail.com`. Sinon, dans le `git log` tu l'avais :wink:

**Comment by wouldsmina** [comment]
C'est noté.

**Comment by wouldsmina** [comment]
Je me demande si je ne vais pas ré-ouvrir ce ticket! 
En préparant la doc, je me rend compte que c'est le responsable (x) du responsable (y) qui valide une demande en cas d'absence de x. 
Pour moi le responsable du responsable c'est aussi le grand responsable. Je me demande comment ça ne serait pas le cas?

Pour compliquer tout cela, il y a le responsable définit dans l'ajout d'utilisateur et, les responsables définit dans la gestion des groupes! 

ça mérite réflexion...

**Comment by Prytoegrian** [comment]
> En préparant la doc, je me rend compte que c'est le responsable (x) du responsable (y) qui valide une demande en cas d'absence de x.

Tu ne t'es pas emmêlé les pinceaux ? En cas d'absence de X, c'est X qui valide une demande ?

**Comment by wouldsmina** [comment]
Si, tu as raison c'est en cas d'absence de Y!

**Comment by Prytoegrian** [comment]
Alors dans le concept ça me choque pas. Qu'est ce qui t'ennuie ?

**Comment by wouldsmina** [comment]
J'essaie de comprendre dans quel cas le responsable du responsable ne serait pas le grand responsable. Pour ma part je n'ai jamais eu cette situation, mais on pourrait imaginer des services (avec des responsables) regroupé dans un pole (avec un coordinateur qui serait donc le responsable du responsable), mais que le grand responsable serait le directeur, patron...

A part ça, je vois pas à quoi peut servir la notion de GR si l'on peut déduire le responsable du responsable...

**Comment by Prytoegrian** [comment]
Ah, mes excuses, je crois que j'avais compris ce que tu disais alors qu'en fait pas du tout, du coup mon raisonnement est biaisé. Qu'est-ce-qui définit X comme responsable de Y dans ton exemple ?

**Comment by wouldsmina** [comment]
C'est le champ u_resp dans la table conges_users. Cette valeur est accessible depuis le menu d'ajout ou modif d'un utilisateur. Alors que la gestion des groupes touche a d'autre table. 

La fonction get_tab_resp_du_user fait d'abord une requete sur la table conges_users et SI la gestion des groupes est activée ALORS il interroge la table conges_groupe_resp. Il retourne un tableau contenant 1 ou plusieurs resp...

**Comment by wouldsmina** [comment]
En fait mon problème c’était surtout que je n'arrivais pas à comprendre se fonctionnement dans l'application  :persevere:
En disant : cela permet de définir le grand responsable à n'importe quel niveau de la hiérarchie de l'entreprise.
Donc pas forcément le responsable du responsable!! ça règle mon problème (qui finalement n'en était pas un  :laughing:)

**Comment by Prytoegrian** [comment]
En étant complètement cru, si tu ne comprends pas ce fonctionnement, c'est que tu dois l'enlever. Tu devrais pouvoir tout expliquer dans l'appli, si c'est pas le cas pour une chose, c'est signe qu'elle n'a pas sa place.

**Comment by wouldsmina** [comment]
C'est clair, justement le fait de rédiger la documentation me permet aussi de faire le point et de retirer/modifier ce qui me semble incohérent. Par exemple le responsable virtuel (compte conges) saute au profit du RH...
