### ISSUE TITLE
SAISIE DES CONGES ET ABSENCES ETC. PAR LE RESPONSABLE

### ISSUE THREAD

**Issue by gregpf81** [wouldsmina/Libertempo#332]
Bonjour,

Dans la version 1.8.1,
 il est possible pour le responsable de saisir les congés des utilisateurs.
Mais lorsque que l'on essaye de le faire un message d'erreur apparaît. un message semblable à celui de la version de démo en ligne.

"Notice: Undefined variable: numero_int in/data/web/56/ec/2a/libertempo.tuxfamily.org/htdocs/demo/hr/Fonctions.php on line 1125
albert---2017-02-21_am---2017-02-21_pm---0------1
Modifications enregistrées avec succès !"

Y a t'il eu une solution ou faut il attendre la prochaine mise à jour ?

Merci Beaucoup.
Greg

**Comment by wouldsmina** [comment]
Bonjour,

Ce bug est corrigé [ici ](https://github.com/wouldsmina/Libertempo/pull/328/files#diff-b367ac1978f88b70abbc5ad7ca1cf61aL1107) il sera appliqué a la prochaine version et à l'actuel.

a+

**Comment by gregpf81** [comment]
Merci beaucoup, vous êtes trop top.
