### ISSUE TITLE
Validation automatique des congés

### ISSUE THREAD

**Issue by lolito34** [wouldsmina/Libertempo#344]
Bonjour,

Ce problème reprends en partie la demande #68 

Je viens de passer en version 1.8.1 et je rencontre un petit problème, je m'explique:

- j'étais précédement passé de la version 1.5 vers la version 1.8. Ma responsable saisissait ses congés et ils étaient automatiquement validé car je lui avait mis le responsable virtuel comme responsable.
- le problème est qu'en passant en version 1.8.1, le responsable virtuel a disparu et je ne trouve pas de solution alternative à cela. En effet, ma responsable ne saisie ses conges que de manière informative et ne sont pas soumis au système de validation. Elle peut évidemment valider ses congés elle-même mais franchement, le système précédent nous était bien pratique.

Y aurait-il un moyen de retrouver ce fonctionnement avec la 1.8.1 ? 

D'avance merci et bravo pour votre travail.

**Comment by wouldsmina** [comment]
Bonjour,
Un employé sans responsable est automatiquement validé, c'est toujours le cas pour la 1.8.1. Par contre, il faut mettre à jour le responsable direct dans la modification de l'utilisateur et s'assurer qu'il ne fait parti d'aucun groupe (en tant qu'employé)

**Comment by lolito34** [comment]
Rebonjour,

Ca marche, effectivement ma responsable était encore inscrite dans un groupe. A présent, ça marche.

Merci pour votre réponse rapide.
