### ISSUE TITLE
Probleme avec l'auth LDAP sur 1.7.0

### ISSUE THREAD

**Issue by ycamus** [wouldsmina/Libertempo#35]
Dans library/authLDAP.php
en ligne 130 mettre =>
          $info = ldap_get_entries($ds,$sr);
		  if( isset($info['count']) && $info['count']>0)$dn=$info[0]["dn"];
          else $dn=false;

pour eviter les problème en cas d'utilisateur introuvé.

**Comment by wouldsmina** [comment]
ok, poussé en beta.. Merci.
