### ISSUE TITLE
Disparition des menus header pour l'utilisateur et l'admin

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#36]
Suite à ce commit, https://github.com/wouldsmina/Libertempo/commit/61544f2a74b12c776ca1722c9eb8e6cd97cc8d69, les menus spécifiques aux utilisateurs / admins tels que les exports, la config, etc. se sont volatilisés.
Il n'a pas l'air d'aimer la mise en trad pour `$user_mode`.

**Comment by wouldsmina** [comment]
c'est corrigé dans la branche master https://github.com/wouldsmina/Libertempo/commit/01a8784fe3244323eec5da59135231cbb7c277e2
J'ai oublié de reporter...

**Comment by wouldsmina** [comment]
ça doit être mieux maintenant...

**Comment by Prytoegrian** [comment]
oui, bien vu. Par contre, j'ai un conflit quand j'essaie de merger master dans develop. Tu seras sans doute plus rapide que moi pour corriger, tu as l'occasion de regarder ?

**Comment by wouldsmina** [comment]
je veux bien, mais j'ai pas encore bien compris comment faire un merge. En fait, quand je suis les instructions de github, j'ai un message d'erreur du style "la branche ... existe déjà". Ne voulant pas tout casser j'ai laissé tombé. je voulais merger 1.7.1beta dans develop...
Pourtant, j'ai bien compris l'utilisation de mergetool pour corriger les conflits. Tu peux me donner quelques conseils?

**Comment by Prytoegrian** [comment]
Quand tu as un conflit de branche sur github, ça t'oblige à passer par le terminal.

Si t'as une distro Linux tout bête avec git dessus, tu peux faire un simple : 
`git pull`
`git checkout laBrancheOuJeVeuxAller`
`git merge laBrancheQueJeVeuxMettreDansLAutre`

c'est là qu'il va te dire qu'il peut pas le faire (logique !), en t'expliquant les fichiers en conflit que tu dois modifier à la mano.

Je vais tenter de le faire, je suis dessus. En posant une PR on y verra plus clair.

**Comment by wouldsmina** [comment]
ok.Laisse moi faire, pour apprendre. Merci.

**Comment by Prytoegrian** [comment]
Arf, je l'avais déjà ^^ ! De ce que j'ai vu, ça n'avait rien de méchant, c'était juste un déport de fonctions que git n'a pas su faire + ce commit https://github.com/wouldsmina/Libertempo/commit/2114dfcee463e2debf9f83d56e40d84959bd7d01

Tu verras, une fois qu'on connait, c'est tout con.

PS : ah oui, j'ai compris ton trouble ! Quand je disais « *en posant une PR* » je parlais pour moi, vu que tout changement que je veux pousser dans ton dépôt passe par une PR. Toi tu as libre accès.

**Comment by wouldsmina** [comment]
désolé :grinning: . j'utilise Meld pour comparer mes fichiers. Dois je modifier tout les fichiers ou uniquement le fichier qui à le bon nom (sans local ou remote)?

**Comment by Prytoegrian** [comment]
Il te suffit de « vider » le fichier `utilisateur/user_echange_jour_absence.php` et ne laisser que le defined et l'import de la fonction du Module (c'est le seul qui est en conflit entre master et develop chez moi).
Ensuite tu mets à jour `utilisateur/Fonctions.php` pour y mettre les changements que tu as mis dans https://github.com/wouldsmina/Libertempo/commit/2114dfcee463e2debf9f83d56e40d84959bd7d01 pour qu'on soit tout propre et c'est bon.

Je ne connais pas Meld mais j'y jetterai un œil.

**Comment by wouldsmina** [comment]
je merge develop avec 1.7.1beta, ça me permettra de tester mes modifs avec les tiennes...

**Comment by Prytoegrian** [comment]
Ok ! Hésite pas si tu as un souci.
