### ISSUE TITLE
Class SMTP

### ISSUE THREAD

**Issue by boicdelo** [wouldsmina/Libertempo#4]
Bonjour,

Toujours en test, toujours sur les mails :)
J'ai voulu tester l'envoi via SMTP, et la encore une FATAL ERROR : 
PHP Fatal error:  Class 'SMTP' not found in /var/www/libertempo/library/phpmailer/class.phpmailer.php

Du coup j'ai ajouté require_once 'class.smtp.php'; au début du fichier class.phpmailer.php

Je ne pense pas que ce soit la manière la plus élégante de faire ça, mais ça marche :)

**Comment by wouldsmina** [comment]
Bonjour,

oui c'est pas très classe de modifier une lib. Essaye plutôt de remplacer : 

	require_once( LIBRARY_PATH .'phpmailer/class.phpmailer.php' );  // ajout de la classe phpmailer
par
	require_once( LIBRARY_PATH .'phpmailer/PHPMailerAutoload.php' );  // ajout de la classe phpmailer

dans le fichier fonction_conges.php ligne 877. Dit moi si cela règle le problème ou pas.
Merci.

**Comment by boicdelo** [comment]
Tout marche et en effet c'est plus propre

Merci.

**Comment by X-Ryl669** [comment]
Je ne savais pas que l'on pouvait faire du require_once direct dans une fonction. C'est étrange, j'aurais pensé que le require_once était comme les #include du C, faisant une sorte de copier/coller du fichier inclus dans le fichier à la position de l'inclusion.
