### ISSUE TITLE
Échange jour RTT, temps partiel / jour travaillé

### ISSUE THREAD

**Issue by adminSNAO** [wouldsmina/Libertempo#42]
Bonjour,
pour l'echange de jour RTT...
le calendier (ordinaire ou souhaité) proposé donne des choix "bizzarres":
- aucun 1er du mois,
- 32 Décembre 2015 et 32 Juillet pour le jour d'absence ordinaire ( OK pour jour d'absence souhaité)
- la semaine 1 de 2016 n'apparait pas (du 1 au 3 janvier)...

**Comment by wouldsmina** [comment]
Normalement c'est déjà corrigé. Télécharge [Libertempo](https://github.com/wouldsmina/Libertempo/archive/v1.7.0.tar.gz) et remplace simplement le contenu de ton serveur (pas besoin de lancer une mise à jour). 

2015 est une année à 53 semaines! la dernière semaine se termine le 3/01/16, et c'est tout a fait normal. On en parle dans le ticket #28

**Comment by wouldsmina** [comment]
Ps :  pour info, la correction est [ici](https://github.com/wouldsmina/Libertempo/commit/2114dfcee463e2debf9f83d56e40d84959bd7d01)
