### ISSUE TITLE
Administration > modification des utilisateurs : on peut supprimer l'identifiant d'un utilisateur

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#43]
La mise à jour de l'utilisateur se fait sans encombre et c'est déjà un bug en soit.
De plus, puisque les pages de modifications d'utilisateurs sont basées sur l'identifiant, on ne peut plus retourner dans la page de l'utilisateur.

**Comment by wouldsmina** [comment]
Ok. Je vais verrouiller le champ lorsqu'on import en ldap et, dans tout les cas, vérifier que le champ login n'est pas vide.
 En fait même dans la base de données ce champ ne devrait pas pouvoir être vide...

**Comment by Prytoegrian** [comment]
Je te dis tout ça de mémoire, mais il me semble que le champ peut être `vide || null` si tu t'y prends bien (le desc de la table montre que tu as un default null), l'indexation et les jointures doivent être un peu chaotiques suite à ça mais j'ai pas cherché plus loin je t'avoue.

Tu pourrais rendre obligatoire la présence du champ oui – je ne sais pas si ça existe déjà, j'ai pas vu ça –, via un contrôle serveur et un petit `required` sur le champ pour être tout propre :-)

**Comment by wouldsmina** [comment]
c'est corrigé 90b2bb8020165d62417cb4207893aa999275ab2b

**Comment by Prytoegrian** [comment]
Cool !
Tip : Si tu veux aller plus vite, tu peux aussi profiter de l'autoclose de GitHub

**Comment by wouldsmina** [comment]
ok! merci, je connaissais pas.
