### ISSUE TITLE
Administration > modification des utilisateurs : on ne peut pas mettre plus de 100 jours de congés payés par an

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#44]
Quand je cherche à mettre plus de 100 jours de congés par an, j’obtiens après soumission du formulaire « 99.99 » (pareil pour les RTT).
Je ne sais pas dire si une telle limite est logique donc je te laisse en décider. Par contre, je suis davantage inquiet sur les répercussions d'une valeur comme « 99.99 » dans le calcul des soldes.

**Comment by wouldsmina** [comment]
j'ai remarqué ça lorsque je faisais des tests avec openXSS. Il ne devrait pas afficher 99.99 mais j'ai pas encore recherché l'origine du problème (peut être une limite dans la bdd).

**Comment by Prytoegrian** [comment]
Trouvé :-) 
Le type decimal de mysql définit que la syntaxe `decimal(M,D)` comme suit : 
* le nombre est un décimal (évidemment)
* M est le nombre total de chiffre
* D est le nombre significatif, autrement dit après la virgule 

([Source](https://dev.mysql.com/doc/refman/5.1/en/precision-math-decimal-characteristics.html))

Si je dis pas de bêtise, c'est la table `conges_solde_user` qui est responsable de notre problème. Les colonnes su_nb_an, su_solde, su_reliquat sont on `decimal(4,2)`, donc ne peuvent pas dépasser 99,99 par nature.

(Vu la nature de la transformation, ça ressemblait bien à un souci de bdd.)

**Comment by wouldsmina** [comment]
Je m'en doutais. Je vais faire un alter table pour le passer en 5,2...
J'ai pensé mettre 4,1 mais il y a quelques (float) dans le code qui risque de poser problème...
Merci.

**Comment by Prytoegrian** [comment]
;-)

**Comment by wouldsmina** [comment]
Finalement, et après pas mal de test, je pense mettre decimal(4,1) pour le champ solde. Si quelqu'un arrive a dépasser les 999 jours de congés (et donc bloqué a 999,9), je lui tire mon chapeau!

**Comment by Prytoegrian** [comment]
Tu es sûr ? Ça m'intéresserait bien 999 jours par an ^^
Ça me paraît bien oui. Et pour le "1", ça craint rien ?

**Comment by wouldsmina** [comment]
J'ai testé dans tout les sens, pas remarqué de problème...

**Comment by Prytoegrian** [comment]
fail autoclose
