### ISSUE TITLE
Congés (a cheval sur la date limite des reliquats) non décompté

### ISSUE THREAD

**Issue by VV666** [wouldsmina/Libertempo#45]
Lorsque la double validation est active, si le SG valide, les CP sont validé dans le calendrier, mais l'utilisateur ne reçoit pas de mail et sont solde n'est pas mis à jour.
J'en déduis que la MAJ du solde est lié au mail.

Du coup, si la personne n'a pas eu de mail, son solde est faux alors que les congés ont été validés.

**Comment by wouldsmina** [comment]
Je n'ai pas remarqué ce problème! Non le descompte n'est pas lié au mail.
Je viens de faire l'essai sur la [démo](http://libertempo.tuxfamily.org/demo) sans rencontrer de problème!

Demandeur : kevin
Responsable : paolo
GR : pierre

Pourrais tu m'en dire plus sur la configuration de libertempo et sur ta gestion des groupes...

**Comment by VV666** [comment]
à la DRH : 
J.C, validé par Chef de Div survalidé par le SG.
J.C à un solde à 26 après décompte des jours de fermeture obligatoire. Elle prends 5 jours, c'est affiché validé dans le calendrier.
MAIS, elle n'a pas eu de mail de confirmation de la validation de ses congés, sont solde est toujours à 26 (vu par le SG et l'admin Libertempo).

// ENVOI DE MAIL AU RESPONSABLE POUR UNE NOUVELLE DEMANDE :
//----------------------------------------------------------
// si à FALSE : le responsable ne reçoit pas de mail lors d'une nouvelle demande de congés par un utilisateur (FALSE est la valeur par défaut)
// si à TRUE : le responsable reçoit un mail d'avertissement à chaque nouvelle demande de congés d'un utilisateur
mail_new_demande_alerte_resp = TRUE


// ENVOI DE MAIL AU USER POUR UN NOUVEAU CONGES SAISI OU VALIDE :
//----------------------------------------------------------------
// si à FALSE : l'utilisateur ne reçoit pas de mail lorsque le responsable lui saisit ou accepte un nouveau conges (FALSE est la valeur par défaut)
// si à TRUE : l'utilisateur reçoit un mail d'avertissement à chaque fois que le responsable saisit un nouveau congés ou accepte une demande pour lui
mail_valid_conges_alerte_user = TRUE


// ENVOI DE MAIL À L'UTILISATEUR ET AU GRAND RESPONSABLE APRÈS LA PREMIÈRE VALIDATION D'UNE DEMANDE (cas d'une double validation de demande) :
//----------------------------------------------------------------
// si à FALSE : l'utilisateur et le grand responsable ne reçoivent pas de mail lorsque le responsable valide une demande (première validation). (FALSE est la valeur par défaut)
// si à TRUE : l'utilisateur et le grand responsable reçoivent un mail d'alerte lorsque le responsable valide une demande (première validation).
mail_prem_valid_conges_alerte_user = TRUE


// ENVOI DE MAIL AU USER POUR LE REFUS D'UNE DEMANDE DE CONGÉS :
//----------------------------------------------------------------
// si à FALSE : l'utilisateur ne reçoit pas de mail lorsque le responsable refuse une de ses demandes de congés (FALSE est la valeur par défaut)
// si à TRUE : l'utilisateur reçoit un mail d'avertissement à chaque fois que le responsable refuse une de ses demandes de congés.
mail_refus_conges_alerte_user = TRUE


// ENVOI DE MAIL AU USER POUR L'ANNULATION PAR LE RESP D'UN CONGÉ DÉJÀ VALIDE :
//---------------------------------------------------------------------------------
// si à FALSE : l'utilisateur ne reçoit pas de mail lorsque le responsable lui annule un congé (FALSE est la valeur par défaut)
// si à TRUE : l'utilisateur reçoit un mail d'avertissement à chaque fois que le responsable annule un de ses congés.
mail_annul_conges_alerte_user = TRUE


// SERVEUR SMTP À UTILISER
//---------------------------------------
//ne pas utiliser!!! SMTP à configurer dans le fichier cfg/config_SMTP.php, laissez cette variable vide ("")
serveur_smtp = smtp.ac-nantes.fr


// OU TROUVER LES ADRESSES MAIL DES UTILISATEURS
//-------------------------------------------------
// plusieurs possibilités pour retrouver les adresses mail des utilisateurs :
// si à "dbconges" : le mail des utilisateurs se trouve dans la table users de la database
// si à "ldap" : le mail des utilisateurs se trouve dans un annuaire LDAP que l'on va interroger (cf fichier config_ldap.php)
// ATTENTION : toute autre valeur que "dbconges" ou "ldap" entraînera une erreur !!!
where_to_find_user_email = ldap


// GESTION DES GROUPES D'UTILISATEURS
//--------------------------------------
// on définit ici si l'on veut pouvoir gérer les utilisateurs par groupe ou pas.
// si à TRUE : les groupes d'utilisateurs sont gérés dans l'application ...
// si à FALSE : les groupes d'utilisateurs ne sont PAS gérés dans l'application ...(FALSE est la valeur par défaut)
gestion_groupes = TRUE


// AFFICHAGE DU CALENDRIER : tous les utilisateurs ou les utilisateurs d'un groupe seulement
//--------------------------------------------------------------------------------------------
// si à FALSE : tous les personnes apparaissent sur le calendrier des congés (FALSE est la valeur par défaut)
// si à TRUE : seuls les personnes du même groupe que l'utilisateur apparaissent sur le calendrier des congés
affiche_groupe_in_calendrier = TRUE


// AFFICHAGE DU CALENDRIER : Sélection du groupe : choix entre tous les groupes ou non
//--------------------------------------------------------------------------------------------
// si la gestion des groupes est active, on définit ici si le choix du groupe à afficher dans le calendrier inclut tous les groupes ou pas.
// si à FALSE : seuls les groupes de l'utilisateur (ou dont il est responsable) apparaissent dans la sélection sur le calendrier des congés (FALSE est la valeur par défaut)
// si à TRUE : tous les groupes apparaissent dans la sélection sur le calendrier des congés
calendrier_select_all_groups = TRUE


// GESTION DES FERMETURES PAR GROUPE : Fermetures d'établissement / de service par groupe ou non
//--------------------------------------------------------------------------------------------
// si la gestion des groupes est active, on définit ici si les fermetures d'établissement sont différentes suivant les groupes d'utilisateurs ou pas.
// si à FALSE : les fermetures s'appliquent à tous les personnels (la fermeture leur est débitée en congés) (FALSE est la valeur par défaut)
// si à TRUE : les fermetures d'établissement / de service sont gérées par groupe et peuvent être différentes d'un groupe à l'autre.
fermeture_par_groupe = FALSE

**Comment by VV666** [comment]
à priori, chez nous ça concerne tout le monde ...
Sachant qu'on a fait la mise à jour depuis PHP_congés 1.5.1 et qu'on a donc gardé la base MySQL de PHP_Congés, est-ce qu'on pourrait se trainé un mauvais paramètre de l'ancienne base ?

**Comment by wouldsmina** [comment]
ok. vue que c'est une update, cela ne doit pas venir de la conf générale. Dans la modification d'un utilisateur, vérifie que tout les champs de solde sont renseigné (CP, RTT et surtout les congés exceptionnels). 

Au vue de ta conf, je pense que l'on se connait :wink:

**Comment by VV666** [comment]
Voui voui, j'ai pris ta succession ;-)

**Comment by wouldsmina** [comment]
Je m'en doutais. 
Envoi moi une extraction de ta bdd par mail, il y a forcément un truc bancale dedans...

**Comment by wouldsmina** [comment]
J'ai bien découvert un bug, mais ça déduit, malgré tout, les soldes!

```
Le GR avait beaucoup de demande en attente, lorsqu'on les valide tous, Libertempo s’arrête avant la fin sans prévenir, Apache donne cette erreur : 
PHP Fatal error:  Cannot redeclare compter() (previously declared in /var/www/html/fonctions_calcul.php:30) in /var/www/html/fonctions_calcul.php on line 30, referer: http://localhost/responsable/resp_index.php?session=phpconges28d6548babfe4b9eb1a9fb2f5e1795c6&onglet=traitement_demandes

**Comment by Prytoegrian** [comment]
Ya moyen d'avoir la backtrace ou tu es tombé dessus par hasard ? Ça pue la boucle d'importation

**Comment by wouldsmina** [comment]
backtrace?

**Comment by Prytoegrian** [comment]
Ouaip ! En cas d'erreur, ça te permet de voir en une fois par où passe ton appli : https://secure.php.net/manual/fr/function.debug-print-backtrace.php
C'est très pratique quand tu veux tracer un bug bizarre (comme là).

**Comment by Prytoegrian** [comment]
Oui, plus j'y pense plus je me dis que c'est ça. Tu dois avoir un `require` ou un `include` qui se fait une première fois et quelques temps après, il se fait une seconde. Ça ne le choque pas, par contre dès qu'il croise une fonction, il dit qu'il la connaît déjà (c'est tombé sur `compter()` parce que c'est la première du fichier). 
Je ne sais pas par contre ce qui se passe pendant « *quelques temps après* »…

J'ai fait un commit qui rend unique les imports (https://github.com/wouldsmina/Libertempo/commit/459947895ea97eb5be14391b2e15aeb1cc900586) il est déjà dans develop donc @VV666 il te reste juste à patienter que develop soit dans master ; ça devrait se corriger tout seul si mon idée est bonne :-)

**Comment by wouldsmina** [comment]
J'ai fais pas mal de test ( avec ma propre base et la tienne @VV666 ) et je pense que c'est lié à la BDD.
J'ai vais  tout de meme essayé debug_print_backtrace pour voir d'ou vient le message d'apache...

**Comment by wouldsmina** [comment]
voila ou j'en suis : l'erreur se produit lorsqu'un congés est déposé en plein dans la date limite des reliquat!!

fichier fonction_conges.php ligne 2616 : 
```
			//si conges demandé est à cheval sur la date_limite_reliquat => il faut decompter le nb_jours_pris du solde, puis il faut
			//calculer le nb_jours_avant pris avant la date limite, et on le decompte des reliquats, et calculer le nb_jours_apres
			//d'apres la data limite et ne pas le décompter des reliquats !!!
			else
			{
				include 'fonctions_calcul.php' ;
				$nb_reliquats_a_deduire = compter($user_login, $num_current_periode, $date_deb, $_SESSION['config']['date_limite_reliquats'], $demi_jour_deb, "pm", null ,  $DEBUG);

**Comment by Prytoegrian** [comment]
On s'approche \o/

**Comment by wouldsmina** [comment]
Donc, l'erreur apache viens de l'include. Le commenter m’amène à un autre bug : 
$_SESSION['config']['date_limite_reliquats'] n'est pas dans le format date qu'attend la fonction compter().

**Comment by VV666** [comment]
Donc, vous penchez pour un bug de l'appli ?

**Comment by wouldsmina** [comment]
Oui, c'est un bug dans l'appli. La version qui était précédemment installer chez toi (1.6.0 revue par l'ancien tech :D), devais aussi être touché par ce bug! Je confirme aussi que les soldes ne sont pas décompté pour les personnes ayant demandé un congés à cheval sur la date limite des reliquats.
Ce bug m'amène à reflechir sur cette date limite. Est ce que, légalement, la date limite devrait prendre en compte la date de demande ou la date des congés? Est ce que cela est dépendant du règlement de l'entreprise ? Sinon on peut ajouter un paramètre dans la conf pour laisser le choix...

Pour le moment, je vais me limiter à réparer le bug, je garde les question de coté pour plus tard...

**Comment by VV666** [comment]
Ok, merci beaucoup !!!

**Comment by Prytoegrian** [comment]
Il semblerait que les congés doivent être **pris** (je l’interprète comme « demandé et accepté ») avant le 31 mai, hors convention collective et dérogation. Tu peux cependant avoir la possibilité de reporter les congés non pris.
[Source](http://www.juritravail.com/Actualite/conges-payes/Id/176791)
[Source2](http://travail-emploi.gouv.fr/informations-pratiques,89/fiches-pratiques,91/conges-et-absences-du-salarie,114/les-conges-payes,1035.html)

Donc : 
* soit on permet de coller au mieux à la loi (et tous ses cas particuliers)
* soit on fait en sorte que l'appli ne soit pas consciente de ça et ce sont les humains qui doivent prendre leur décision en tout connaissance de cause

**Comment by VV666** [comment]
Vu que chez nous, on ne fait rien comme tout le monde, je serai d'avis de laisser les humains gérer ;-)

**Comment by wouldsmina** [comment]
Ok. L'idée serait d'ajouter (en plus de date_limite_reliquat) l'option date_limite_reliquat_demande :
True pour tester la date d'une demande avec la date limite
False pour tester les dates de congés avec la date limite
Je vais déjà voir si c'est pas trop chiant a faire...

**Comment by Prytoegrian** [comment]
En fait je m'aperçois qu'il me manque des informations. Qu'est-ce-que ça changerait s'il n'y avait pas de limite de dépôt pour l'appli ?

**Comment by wouldsmina** [comment]
dans la conf, tu peux décider de reporter les soldes restant lors d'un changement d'exercice. Ces soldes peuvent être plafonné (champ à 0 pour ne pas plafonner), et limité dans le temps (0 aussi...).
donc si il n'y a plus de date, il n'y a plus de bug :D.

**Comment by Prytoegrian** [comment]
Certes ^^
Mais cette décision de report, ça aurait du sens qu'elle soit posée *au moment* de la clôture de l'exercice ? Suite à quoi les jours seront crédités automatiquement en plus du volume habituel de l'employé (comme je suppose que c'est déjà le cas).

**Comment by wouldsmina** [comment]
pas vraiment la date limite des reliquats et définie par la convention de l'entreprise, elle n'a pas vocation à changer chaque année. Et ce serait source d'erreur. 

J'ai pas beaucoup avancé sur la correction du bug, mais j'ai remarqué que la date au format jj-mm était convertie au format standard aaaa-mm-jj a chaque clôture d'exercice...

**Comment by wouldsmina** [comment]
ça devrait rouler avec ça : e52f7fdf0fe3fd4ec129f62982de28a41bb5277d

@Prytoegrian j'ai parlé de la date limite au lieu de la gestion des reliquats, mais c'est pareil au final.

**Comment by VV666** [comment]
Claire T. me dit que personne n'a de reliquat cette année .... Est-ce que c'est juste une histoire de date de fin de reliquat, que l'on ait ou pas de reliquat ?

**Comment by wouldsmina** [comment]
Dans ce cas, met 0 dans le date_limite_reliquat dans la table conges_appli, ca reglera le problème pour cette année...
Bise a claire ;)

**Comment by wouldsmina** [comment]
LVR prendre tout ses congés, je trouvais ça bizarre! Elle en a et d'autres aussi (en tout cas dans l'extraction que tu m'as transmis) ;)

**Comment by VV666** [comment]
Je me suis basé sur ce que m'a dit Claire, peut être qu'elle omettait les chef de div ^^
J'avoue ne pas avoir analysé chaque user pour voir qui avait ou non des reliquats. Le principal, c'est que le bug soit corrigé.

Je peux sans souci mettre à jour depuis la branche Master ?

**Comment by wouldsmina** [comment]
Oui, télécharge et écrase les fichier du serveur. Pas besoin de lancer la mise a jour...

**Comment by VV666** [comment]
Fait !
