### ISSUE TITLE
Vu calendrier : les demi congés validé ne sont pas coloré

### ISSUE THREAD

**Issue by VV666** [wouldsmina/Libertempo#47]
Salut, 
Lorsqu'une demande de congés est posée pour une demi journée, cette demande apparait bien dans le calendrier comme une case à moitier coloré de la couleur "en demande" (rose).
Mais une fois validé, la vua calendier affiche "CP" sur un fond blanc, ce n'est pas à demi coloré "validé" (bleu).

J'ai jeté un œil dans le css. Pour les demi CP validés, il n'y a pas de référence de ce type (sauf que ça devrait être un truc du style "td.cal-day_semaine_travail_am_valide_pm"...) : 
```
td.cal-day_semaine_travail_am_demande_pm {
    background-image: -moz-linear-gradient(right top , #ffc1ff 50%, #fff 0%);
}
```

**Comment by wouldsmina** [comment]
Bien vue ça m'a échappé...

**Comment by wouldsmina** [comment]
c'est corrigé https://github.com/wouldsmina/Libertempo/commit/cf68d8b6f63251b34ec24d89975135ad1f0aa6fe
