### ISSUE TITLE
Utilisateur > Nouvelle absence : le calcul du nombre de jour est incohérent

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#49]
Imaginons que je veuille prendre quelques congés (tous mes congés commenceront le lundi matin) : 
* Si je prends jusqu'au lundi après midi, alors j'ai 1j
* Si je prends jusqu'au mardi après midi, alors j'ai 1,5 jours
* Si je prends jusqu'au mercredi après midi, alors j'ai 2 jours

Plusieurs choses : Que la date de fin soit le mardi matin ou après midi, le nombre ne change pas.
Ensuite, je n'ai pas regardé le code, mais je perçois qu'il s'agit « juste » d'une différence entre la date de fin et celle de début, on compte donc les intervalles mathématiques. Ici, il faudrait plutôt compter les périodes, autrement dit ajouter « +1 » dès lors que tu as une différence d'au moins un jour (ou plus exactement « +0,5 » tous les 1,5j dans notre cas vu qu'il y a une granularité plus fine).

À noter qu'il ne s'agit pas uniquement du pré-calcul au moment de la sélection, le résultat final des congés montre bien ce bug.

Je me rends compte que c'est conditionné par le terme « date de fin ». Signifie-t-il « date de fin de congés » ou « date de retour » ? Un sens comme l'autre possède son propre bug de comptage.

**Comment by wouldsmina** [comment]
Bizarre ca! Tu n'aurai pas des RTT le mardi et mercredi matin? Ca donne combien du lundi matin au vendredi soir?

La date de fin correspond au dernier jour de congés.

**Comment by Prytoegrian** [comment]
Oui nickel, c'était ça, mon utilisateur de test avait bien des RTT dans tous les sens. Après suppression et vérification, le comptage est bon. Dommage que je n'avais le planning de RTT sous les yeux, j'aurais percuté tout de suite.

Par contre il y a un autre souci :-D, j'ai pu modifier le planning de RTT et le comptage des congés pris n'est pas réactualisé.

**Comment by wouldsmina** [comment]
Si tu as changé le planning RTT de l'utilisateur connecté, ferme la session. La conf est chargé au login.

**Comment by wouldsmina** [comment]
Les congés pris ne sont pas réactualisé quand tu changes le planning.

**Comment by Prytoegrian** [comment]
Je viens de faire des tests et je confirme ça, les congés pris ne changent pas après modif des RTT de l'utilisateur :-/

Je vais ouvrir un autre ticket pour en discuter là bas.

**Comment by wouldsmina** [comment]
la date de début de validité de la grille ne permet pas de reprendre les anciennes demande. Par contre, pour les futurs demandes, la date du premier jour de congés demandé doit etre supérieur à la date de début de validité de la grille. C'est pas vraiment un bug, mais on pourrait voir si l'idée d'implémenter une rétroactivité des calculs pourrait se faire...
