### ISSUE TITLE
Error in fonctions_javascript

### ISSUE THREAD

**Issue by X-Ryl669** [wouldsmina/Libertempo#5]
Sur le fichier fonctions_javascript.php autour de la ligne 93, il faut corriger le code:
```
$tabferm = isset($_SESSION["tab_j_fermeture"]) ? $_SESSION["tab_j_fermeture"] : NULL;
$tabjferies = isset($_SESSION["tab_j_feries"]) ? $_SESSION["tab_j_feries"] : NULL;
$js_tab= "[";

if(isset($tabjferies)) {
        foreach($tabjferies as $key => $jf){
                $js_tab=$js_tab.'"'.convert_jf($jf).'",';
        }
}

if(isset($tabferm)) {
        foreach($tabferm as $key => $jf){
                $js_tab=$js_tab.'"'.convert_jf($jf).'",';
        }
}
```
Au lieu de ce qu'il y a actuellement. Notamment, l'affectation $tabferm = $_SESSION["tab_j_fermeture"] est une erreur si _SESSION ne contient pas tab_j_fermeture. 
Il y a également une erreur sur le 2eme test qui teste tabjferies deux fois

**Comment by wouldsmina** [comment]
merci pour ces contributions des plus complètes.
