### ISSUE TITLE
Utilisateur > Historique des congés : le comptage ne tient pas compte d'une modification de RTT

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#50]
(déport du problème initié dans #49 )

Étant donné un utilisateur possédant des congés et dont le comptage de jours tient compte de ses RTT
Quand le responsable change l'organisation de ses RTT avec une date d'application antérieure aux congés de l'utilisateur
Alors le comptage des jours de congés ne tient pas compte de cette nouvelle configuration.

Il me semble qu'une fois que les congés sont validés on ne devrait plus y toucher (légalement, j'ignore ce que ça donnerait) donc la manière la plus simple de résoudre ça est de forcer une date d'application supérieure à toute prise de congés validée.
Pour le congés en cours de demande, je pense que les congés devraient être notifiés comme « problématique » à l'utilisateur, il devrait donc les modifier de lui-même. On force ainsi sa conscience du comptage et s'il veut revenir sur le nombre de jours ou même la prise, il peut. De la même manière, ce sont des congés qui ne peuvent pas être manipulés par le responsable.

**Comment by wouldsmina** [comment]
Ok, résumé comme ça on est d'accord. 
Forcer une date d'application supérieur à toute prise de congés validée, c'est un peu fort, informer l'admin (ou plutot le RH) de la situation serait moins bloquant. A lui d'annuler (et déposer) les congés de l'utilisateur avec le bon solde...

**Comment by wouldsmina** [comment]
Il faut que je vérifie, mais je crois que le nombre de jour est de nouveau calculé lors de la validation, à tester...

**Comment by Prytoegrian** [comment]
> Forcer une date d'application supérieur à toute prise de congés validée, c'est un peu fort, informer l'admin (ou plutot le RH) de la situation serait moins bloquant

Oui pourquoi pas. La grande interrogation c'est l'aspect légal, je ne saurais pas dire si une autre personne que l'utilisateur lui-même peut donner / modifier des congés de manière arbitraire, sans l'aval de la personne concernée. C'est pour ça que je voulais verrouiller.

**Comment by wouldsmina** [comment]
Oui, légalement c'est l'employeur qui tiens les soldes des employés à jour. L'employé à bien sur un droit de regard. Il faut donc que l'utilisateur puisse retrouver la trace de ces modifications, Les commentaires sont fait pour ça...

**Comment by wouldsmina** [comment]
> Il faut que je vérifie, mais je crois que le nombre de jour est de nouveau calculé lors de la validation, à tester...

Fait et c'est négatif. on pourrait ajouter, dans le menu de traitement des demandes, une colonnes "nombre de jours calculés" a coté de "nb jours pris" s'ils diffèrent. Cela pourrait être aussi utile si l'utilisateur a le droit de modifier le nombre de jours lors de la demande...
Je n'ai pas regardé l'aspect technique, juste une idée.

**Comment by Prytoegrian** [comment]
La question se repose pour la gestion des congés basés sur les plannings. On pourrait peut-être empêcher la modification d'un planning si des congés sont différents de « validé » sur ce planning pour au moins un utilisateur. Pour la même raison, qu'on ne puisse pas non plus modifier un utilisation en le passant d'un planning « X » à un planning « Y » sur les mêmes critères.

**Comment by wouldsmina** [comment]
je pense qu'on peut fermer ce ticket maintenant :)
