### ISSUE TITLE
Extraction de l'affichage de la logique du site

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#63]
Afin de mieux isoler la logique et les calculs de leurs présentation, il faudrait créer des vraies vues, dénuées de logique et que le moteur du site viendrait remplir. Le reste de l'application ne consistera ainsi qu'à effectuer des retours traités par la vue. 

À mon sens, c'est la meilleure première étape pour poser de bonnes bases à une structure mvc rest sans être obligé de récrire à la fois le contrôleur et le modèle dans la foulée. 

Il est possible que nous ayons besoin pour faciliter cette séparation d'un protorouteur. Je ferai une étude un peu plus approfondie.

**Comment by Prytoegrian** [comment]
@wouldsmina pas d'avis sur la question ?

**Comment by wouldsmina** [comment]
on en discute sur irc quand on a le temps ;)

**Comment by Prytoegrian** [comment]
C'est en cours... Comme pour la précédente grosse idée #26, la date de livraison est plus qu'incertaine. Je pense avoir trouvé une bonne manière de faire qui ne devrait pas trop faire tâche dans le code actuel tout en ayant une bonne tête pour la nouvelle version du code en MVC REST.
Seulement je me pose la question : dans quelle mesure je peux toucher à l'apparence pour que je puisse faire un bon code dédié à l'affichage ?

**Comment by wouldsmina** [comment]
Php_conges avait séduit beaucoup de monde grace à sa simplicité d'utilisation. Le lifting qu'il a subit n'a pas (trop) modifié la disposition des éléments. Cela permet aux utilisateurs de passer à libertempo aisément. Je veux maintenir cela dans le temps. Donc, ne fait pas de gros changement visuel. par contre si c'est pour faire evoluer le fonctionnement de l'interface sans changement visuel tu peux y aller...

**Comment by Prytoegrian** [comment]
Entendu, j'ai donc le droit de creuser le côté « simplicité d'utilisation » :-p
