### ISSUE TITLE
Même personne comme Utilisateur et Responsable

### ISSUE THREAD

**Issue by eileon** [wouldsmina/Libertempo#68]
Je suis passé de php_conges à Libertempo 1.7.0
Je suis à la fois Utilisateur et Responsable de moi-même. Autrefois sur php_conges je proposais mes congés comme Utilisateur et je les validais comme Resonsable. Avec Libertempo je pose les congés mais ils n'apparaissent plus dans Traiter toutes les demandes du mode Responsable.
Je me suis mis HR et comme ceci je peux valider et donc décompter les congés que je prends (A ce propos j'ai initialisé les valeur u_is_hr dans la base car elles ne se bsont pas automatiquement initialisées).
Ce serait bien d'avoir le même comportement qu'avec php_conges quand on est à la fois Utilisateur et Responsable

**Comment by wouldsmina** [comment]
En effet, libertempo n'autorise pas l'auto validation. Par contre la version 1.7.1 décompte automatiquement les congés des utilisateurs sans responsable ou avec le responsable virtuel.

**Comment by eileon** [comment]
Ah Ok ! 

Sinon bravo pour votre travail 



Nicolas Moulonguet 
Labor atoire Ecologie, Systématique et Evolution 
Services communs 
Bureau 115 - Bâtiment 362 - Rue du Doyen André Guinier 
91405 Orsay Cedex 







	





----- Mail original -----

De: "wouldsmina" <notifications@github.com> 
À: "wouldsmina/Libertempo" <Libertempo@noreply.github.com> 
Cc: "eileon" <nicolas.moulonguet@u-psud.fr> 
Envoyé: Jeudi 29 Octobre 2015 15:55:12 
Objet: Re: [Libertempo] Même personne comme Utilisateur et Responsable (#68) 



En effet, libertempo n'autorise pas l'auto validation. Par contre la version 1.7.1 décompte automatiquement les congés des utilisateurs sans responsable ou avec le responsable virtuel.
