### ISSUE TITLE
resp_saisie_mission mal expliqué dans la config

### ISSUE THREAD

**Issue by Patrice67** [wouldsmina/Libertempo#69]
Est-il possible d'envisager un système permettant aux responsables ou au RH de poser des jours de congés pour une autre personne ?

C'est tout particulièrement utile en ce qui concerne les absences du type "maladie".

**Comment by wouldsmina** [comment]
C'est déjà possible. Dans la page principale du RH il faut cliquer sur l'oeil au bout de la ligne d'un utilisateur. Idem pour les responsables à condition de l'autoriser dans la conf générale...

**Comment by Patrice67** [comment]
Je n'avais effectivement pas activé l'option : "resp_saisie_mission".

En effet le texte de l'option indique clairement :
- "les absences de ce type n'enlèvent pas de jours de congés !".

Du coup je pensais que cela n'autorisait pas la saisie de congés. Mais
contrairement à ce qui est indiqué, c'est possible.


// SAISIE DES ABSENCES POUR MISSIONS, FORMATIONS, CONGRES, ETC. PAR LE
RESPONSABLE
//---------------------------------------------------------------------------------------
// ( les absences de ce type n'enlèvent pas de jours de congés ! )
// si à FALSE : pas de saisie par le responsable des absences pour
mission, formation, congrès, etc.(FALSE est la valeur par défaut)
// si à TRUE : saisie par le responsable des absences pour mission,
formation, congrès, etc.
resp_saisie_mission =

Merci beaucoup !
Patrice

**Comment by wouldsmina** [comment]
Tiens, ce détail m'avait échappé. Je corrige sur la 1.7.1. merci.
