### ISSUE TITLE
How to test SMTP mail sending

### ISSUE THREAD

**Issue by X-Ryl669** [wouldsmina/Libertempo#7]
Actuellement, à part le champ pour donner le serveur SMTP, il y a aucune fonction pour tester l'envoi des emails, et les emails ne fonctionnent pas. J'ai bien vu le fichier test_mail.php, mais il n'est utilisé nulle part, je pense qu'un bouton "Tester configuration du serveur email" est manquante.

En fait, il faudrait pouvoir entrer un identifiant & mot de passe dans la configuration car les serveurs SMTP ouvert ne sont plus nombreux sur internet (spam oblige). Ils demandent tous un identifiant & mot de passe pour pouvoir envoyer un email (et idealement, une case à cocher pour activer SSL sur la connection)

**Comment by wouldsmina** [comment]
Ok, en fait il manque un morceau de la lib phpmailer! je pousses le reste de suite.

**Comment by X-Ryl669** [comment]
Malheureusement, cela ne suffit pas. Il manque un moyen dans la partie admin/configuration pour donner les identifiants / mdp de l'utilisateur qui poste l'email (le "From:" c'est à dire celui qui s'authentifie sur le serveur SMTP).
Aussi, il faut pouvoir dire à phpMailer si le serveur SMTP utilise SSL ou pas...
Et le top du top, ce serait de pouvoir envoyer un "faux" email dans la partie config/mail, avec, par exemple, un "mail demande de congé" suivant la syntaxe que l'on a mise. Du coup, cela ferait d'une pierre, deux coup, test config SMTP, et test config des emails envoyés.

**Comment by wouldsmina** [comment]
Je sais, c'est pour ça que je n'ai pas clôturé...
Je vais plutôt créer un fichier config_smtp à l'image du ldap ou du CAS. ça évitera de charger encore plus la page de conf.
Pour le test, j'ajouterai peut etre ça dans la page de conf des mails.

**Comment by wouldsmina** [comment]
Je viens de tester sans SMTP, c'est ok. J'ai poussé la nouvelle conf smtp mais je ne pourrais tester que demain...

**Comment by X-Ryl669** [comment]
J'ai un premier jet de code qui implémente cette fonctionnalité.
Je vous l'envoi ?

**Comment by wouldsmina** [comment]
Oui! avec plaisir.

**Comment by X-Ryl669** [comment]
Ok. J'ai pas GIT installé sur le server HTTP, donc c'est pas possible pour
moi de faire une PR.
Ceci dit, c'est assez simple ce que j'ai fait, ça tient en 2 fichiers
(joints).

Dans config_mail, j'ai aussi modifié le code d'alerte_mail pour qu'il envoi
aussi un message au grand responsable si un congé est validé par le
responsable (je pense que c'est bien plus utile que d'avoir le mail de
demande que le responsable peut refuser).

J'ai ajouté un mode "test" dans config_and_send_mail pour une période bidon
puisque le test ne doit pas attendre à ce que la base SQL soit dans un
quelconque état. Idéalement, il faudrait extraire le texte des messages
entrés, mais pour tester que la config mail fonctionne, c'est mieux que
rien.


2015-06-23 17:39 GMT+02:00 wouldsmina <notifications@github.com>:

**Comment by wouldsmina** [comment]
Je n'ai pas les pièces jointes (github filtre peut être les PJ). Mon mail :
wouldsmina@gmail.com.

Cdlt,

**Comment by wouldsmina** [comment]
A propos de ton mail : Dans config_mail, j'ai aussi modifié le code d'alerte_mail pour qu'il envoi
aussi un message au grand responsable si un congé est validé par le
responsable (je pense que c'est bien plus utile que d'avoir le mail de
demande que le responsable peut refuser).

Je suis pas sur de comprendre. actuellement, le grand responsable reçoit un mail pour la seconde validation lorsque le responsable accepte une demande.

**Comment by wouldsmina** [comment]
J'ai poussé tes modifications en y ajoutant mon grain de sel...
Merci, j'attends ton retour pour fermer le ticket.

**Comment by X-Ryl669** [comment]
Il y a deux modes de fonctionnement. Dans ma sté, les demandes de congés
sont validés par le responsable d'équipe, mais l'acceptation doit être
envoyée à la secrétaire pour noter les congés. Dans ce cas, j'ai simplement
activé la fonction de groupe, mais pas celle de double validation.
Le "grand responsable", c'est la secrétaire, qui est informée des
validations du responsable (mais qui n'a pas son mot à dire).

J'envisage d'ajouter une configuration pour cela, "activer grand
responsable" qui permettrait d'afficher l'UI de choix du grand responsable
même si la double validation est désactivée (actuellement, je rentre l'info
du grand responsable directement dans la BDD, à défaut d'interface pour).

Le reste fonctionne parfaitement.

**Comment by wouldsmina** [comment]
Ok. Je comprends et c'est vrai que ca peut etre utile. Par contre, il faut alterer la table config. Je vais donc implémenter cela en version 1.7.1. J'en profiterai pour supprimer le champ SMTP.

**Comment by X-Ryl669** [comment]
Ok, j'attends donc de tester la version 1.7.1 quand elle sera disponible.
