### ISSUE TITLE
Pas de mise en circuit de validation les absences exceptionnelles

### ISSUE THREAD

**Issue by pousterlus** [wouldsmina/Libertempo#70]
Bonjour,

Dans l'état actuel des choses, les absences exceptionnelles (type "Congés sans solde"), qui n'ont pas de compteur à proprement parler, ne sont pas soumis au circuit de validation.
Ce qui permet aux salariés de les poser quand ils veulent...

Y'a-t-il moyen d'appliquer le flow de validation à ces types d'absences sans forcément les rentrer dans la catégorie congés.

Merci,

-- 
Léo.

**Comment by wouldsmina** [comment]
Non ce n'est pas possible pour le moment. Par contre la 1.7.1 permettra d'informer le responsable par un mail spécifique.

**Comment by pousterlus** [comment]
Okay. Je comprends, du coup je vais mettre le SS en type "Congés" et tant pis pour le compteur qui se décrémentera...

**Comment by wouldsmina** [comment]
corrigé ici ab255a9f24fbae0cf6f6a3c9c312e9e56b66c20e
