### ISSUE TITLE
Pb installation

### ISSUE THREAD

**Issue by rayaa1991** [wouldsmina/Libertempo#704]
Bonjour, 
j'essaye d'installer la version 1.11.1 et j'ai ça comme rapport .. 

login : 
uri   : /conges/install/index.php
dump  : ../dump/sql_2018-09-13T11:18:10+00:00.dump

file  : /customers/9/f/1/lagoudiniere.be/httpd.www/conges/includes/SQL.php
line  : 86
fx    : $SQL->query
error : Table 'lagoudiniere_be.conges_config' doesn't exist
sql   : SELECT * FROM conges_config ORDER BY conf_groupe

Pouvez vous m'aider ? 
Merci d'avance !

**Comment by rayaa1991** [comment]
Personne ne sait? Je suis coincé ...

voici plus d'information : 
Server: lagoudiniere.be.mysql via TCP/IP
Software: MariaDB
Software version: 10.1.30-MariaDB-1~xenial - mariadb.org binary distribution
Protocol version: 10
User: lagoudiniere_be@10.27.22.48
Server charset: UTF-8 Unicode (utf8)

Web server
nginx/1.10.3
Database client version: libmysql - mysqlnd 5.0.10 - 20111026 - $Id: c85105d7c6f7d70d609bb4c000257868a40840ab $
PHP extension: mysqli Documentation

**Comment by wouldsmina** [comment]
Bonjour @rayaa1991,

J'ai vu à quelques reprises ce problème, mais je n'ai pas réussi à le reproduire, donc difficile à corriger. De plus, nous avons revu intégralement la procédure d'installation sur la futur version de Libertempo. 

Je te propose d'injecter le fichier /install/sql/php_conges_v1.10.sql dans la base de donnée, puis de lancer la procédure de mise à jour vers la 1.11.

**Comment by rayaa1991** [comment]
Merci, j'ai fais ce que vous avez dis. J'ai juste une erreur quand j'importe 'conges_users'
![capture](https://user-images.githubusercontent.com/43235067/45873796-90ae8a00-bd93-11e8-8f57-b5a08100b840.PNG)

**Comment by rayaa1991** [comment]
Importé php_conges_v1.10.sql dans mon phpmyadmin ?
Désolé je suis novice la dedans j'essaye d'apprendre..

**Comment by rayaa1991** [comment]
Ok, ça a fonctionné merci, j'ai Libertempo 1.10 "Kantra".
Comment faire la mise à jour maintenant ?

**Comment by wouldsmina** [comment]
Tu dois passer par la procédure d'installation qui te proposera de mettre à jour, tout simplement.

**Comment by wouldsmina** [comment]
je peux fermer ce ticket @rayaa1991 ?
