### ISSUE TITLE
Modification d'une demande de congés : recalcul faux

### ISSUE THREAD

**Issue by VV666** [wouldsmina/Libertempo#72]
Bonjour, 
j'ai trouvé un bug en faisant une demande de congé : 

demande 1 jours --> modification pour demandé que l'après midi (1/2 mjournée) --> demande devient 0 jours (à l'affichage). J'ai ensuite annulé ma demande et refaite, du coup, je ne sais pas si c'est juste un problème d'affichage et décompte bien 1/2 journée ou si ça ne décompte rien du tout.

**Comment by Prytoegrian** [comment]
Hello @VV666 ! 

J'aurais besoin de quelques précisions : 
* Lors de la seconde demande, tu as de nouveau le problème ou est-ce juste lors de la modification d'une demande ?
* Il n'y a aucune collision avec un quelconque jour de repos / chômé / etc. ?
* Le « 0 » apparaît après la soumission du formulaire ?

**Comment by wouldsmina** [comment]
Salut,
Pas réussi à reproduire sur la demo. Tu peux reproduire l'erreur?

**Comment by VV666** [comment]
Ok, je refais ça.

- Demande de 1 jours de congés (pas en conflit avec jour de repos / chômé / etc)
- Modification pour transformer la demande en demi journée **après midi**
![bug](https://cloud.githubusercontent.com/assets/13338158/11650786/584c0018-9d8c-11e5-9396-b39642fbfc73.png)
- à l'affichage, il affiche 0 jours décompté au lieu 0.5 journée (1 avant la modification).
- Annulation de la demande, c'est sur notre Libertempo de prod ;-)

**Comment by VV666** [comment]
@Prytoegrian 
- pas de soucis lors de la seconde demande : j'ai directement demandé une demi journée après midi.
- Pas de colision avec un autre style de jours de repos
- oui, lors de la modification, il calcul bien la demi journée, puis une fois validé, il affiche 0.
- même bug si je modifie la demande pour obtenir une demi journée le matin.

Bug d'affichage uniquement ?

**Comment by wouldsmina** [comment]
Ok, je confirme le bug. Je regarde de plus près...

**Comment by wouldsmina** [comment]
Bon! C'est pas un bug d'affichage, mais bien de calcul. Lorsque le champ "nombre jours pris" est verrouillé, Libertempo recalcul les jours une fois le formulaire envoyé; comme ça pas de risque qu'un utilisateur malhonnête ne modifie cela directement par l'url. 

Je n'ai pas trouvé d’où vient l'erreur! Lorsqu'on valide, la fonction compter() est appelée de la même manière que pour le calcul à la volée, elle devrait donc retourner la même valeur, mais non!
Autre chose qui m'échappe, dans les logs c'est la bonne valeur qui est inscrit, cette action est portant effectuée juste après l'update de la bdd (fonction confirmer()) avec la même variable!
Je creuse...

**Comment by wouldsmina** [comment]
Trouvé! c'est a cause d'une virgule au lieu d'un point!!! mais je sais pas encore d’où cela provient...

**Comment by wouldsmina** [comment]
en attendant de trouver, dans user_modif_demande.php tu peux remplacer : 
```
         if ($_SESSION['config']['disable_saise_champ_nb_jours_pris'])
            $new_nb_jours = compter($user_login, $p_num_to_update, $new_debut,  $new_fin, $new_demi_jour_deb, $new_demi_jour_fin, $new_comment,  $DEBUG);
        else
            $new_nb_jours = getpost_variable('new_nb_jours');
```
par
```
        if ($_SESSION['config']['disable_saise_champ_nb_jours_pris']) {
            $nb_jours = compter($user_login, $p_num_to_update, $new_debut,  $new_fin, $new_demi_jour_deb, $new_demi_jour_fin, $new_comment,  $DEBUG);
            $new_nb_jours = str_replace(',', '.', $nb_jours);
        } else
            $new_nb_jours = getpost_variable('new_nb_jours');
```

**Comment by Patrice67** [comment]
Au cas ou cela pourrait aider, j'ai rencontré un peu le même genre de soucis de virgule à la place d'un point en ajoutant une demi journée de congés à une personne par le RH. J'ai eu l'erreur : 
login : XX
uri   : /libertempo/hr/hr_index.php?onglet=traite_user
dump  : ../dump/sql_1450367010.dump

file  : /var/www/html/libertempo/fonctions_conges.php
line  : 2641

fx    : $SQL->query
error : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '5 WHERE su_login='pl'  AND su_abs_id=1' at line 1

sql   : UPDATE conges_solde_user SET su_solde=su_solde-0.5, su_reliquat=4,5 WHERE su_login='YY'  AND su_abs_id=1

**Comment by wouldsmina** [comment]
Merci @patrice67, mais ça c'est un autre bug, je t'invite à ouvrir un nouveau ticket. 
Je pensais m'être débarrassé de ce problème de virgule, mais c'est pas encore gagné!

**Comment by wouldsmina** [comment]
@VV666 est ce que tu peux essayer si tout rentre dans l'ordre en ajoutant ```setlocale(LC_NUMERIC, 'en_US');``` dans ```includes/lang_profile.php``` ligne 68. Pour moi c'est ok, mais je veux etre sur avant de corriger et clore ton ticket...

Il faut que tu retire le str_replace que je t'avais invité a mettre...

**Comment by Prytoegrian** [comment]
fail autoclose
