### ISSUE TITLE
LDAP active directory 2008

### ISSUE THREAD

**Issue by Matou25** [wouldsmina/Libertempo#73]
Bonjour,

j'ai installé libertempo sur un serveur Ubuntu 14.03, le site est en ligne et fonctionne normalement.
Par contre impossible de le lier a l'ad, le fichier de config semble ok mais aucun utilisateur n'apparait dans la fenetre d'ajout utilisateur. j'ai modifié la page authldap.php en pasant debug a 1 mais je ne vois rien de plus, le print est direct a l'ecran non?. Y a t'il un fichier log que j'ai raté ?
d'autre part, pensez vous ajouter une fonction SSO pour l'authentification?

en tout cas merci pour le travail effectué, l'interface est propre et moderne, ma responsable RH est conquisse par l'interface et l'efficacité (ce n'est pas une usine a gaz comme d'autre SIRH trop complexe pour une pme). reste plus que la liaison AD fonctionnelle pour facilité la vie des usagées et gestionnaire :-)

Cordialement

Mathias

**Comment by Matou25** [comment]
Une precision , sur le meme serveur, j'ai glpi, la liaison ad est ok et le sso aussi :-)

**Comment by wouldsmina** [comment]
Bonjour,

Lorsque tu dis AD, c'est bien l'Active Directory de chez MS? Je n'ai jamais testé avec ce type d'annuaire, uniquement avec du openLDAP. Le DEBUG, c'est pas au point. Par contre, tu dois avoir des logs sur ton serveur (/var/log/apache2/error.log).

Pour le SSO, seul la solution CAS de JASIG est implémentée, il y a déjà une demande pour intégrer oauth. Quel type de SSO utilises tu? (Fait un nouveau ticket pour le SSO stp)

Cdlt,

**Comment by Matou25** [comment]
oui c'est bien l'active directory de chez MS, si j'ai bien lu le fichier config_ldap.php ca fonctionnais dans php congé avec un ad 2003, en tout cas avec ldap browser et les memes info de connexion c'est ok.
pour le sso je crée un nouveau ticket :-)

**Comment by Matou25** [comment]
dans  /var/log/apache2/error.log
j'ai
PHP Fatal error:  Directive 'magic_quotes_gpc' is no longer available in PHP in Unknown on line 0
d'apres ce que j'ai compris ca n'existe plus dans php5

si j'ajoute un utilisateur et que la config est :  
- how_to_connect_user = ldap
- export_users_from_ldap = false
 voila l'erreur dans les log
[Thu Dec 10 14:28:08.291762 2015] [:error] [pid 2325] [client 192.168.10.116:56196] PHP Notice:  Undefined index: password1 in /usr/share/libertempo/admin/admin_ajout-user.php on line 283, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpconges200c61e9613afeb49e286d365a99f00a&onglet=ajout-user

normal il n'y a pas de champ mot de passe, il est censé verifier l'existance de l'utilisateur dans ldap non?

si on ouvre l'onglet "ajouter un utilisateur" et que la config est :  
- how_to_connect_user = ldap
- export_users_from_ldap = true

voila les erreurs:
[Thu Dec 10 14:33:12.246033 2015] [:error] [pid 2392] [client 192.168.10.116:59130] PHP Warning:  ldap_search(): Search: Bad search filter in /usr/share/libertempo/admin/admin_ajout-user.php on line 701, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpconges200c61e9613afeb49e286d365a99f00a
[Thu Dec 10 14:33:12.246065 2015] [:error] [pid 2392] [client 192.168.10.116:59130] PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /usr/share/libertempo/admin/admin_ajout-user.php on line 702, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpconges200c61e9613afeb49e286d365a99f00a
[Thu Dec 10 14:33:12.246075 2015] [:error] [pid 2392] [client 192.168.10.116:59130] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/libertempo/admin/admin_ajout-user.php on line 704, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpconges200c61e9613afeb49e286d365a99f00a

**Comment by Matou25** [comment]
j'ai ajouté 
ldap_set_option($ds, LDAP_OPT_REFERRALS, 0);
apres la ligne 689 de admin_ajout-user.php

cela semble obligatoire pour les connexions ldap vers AD MS, je ne sais pas si cela gene le openldap.
je ne connais php mais je vais essayé d'ajouter une ligne dans la config ( adms OU openldap) puis faire un si pour etre compatible ( désolé pour mon language, je ne suis pas devellopeur :-) )

du coup j'ai bien la liste des mes users dans la fentre d'ajout, j'ai une erreur avec des paramètres manquant lorsque je clique sur validé mais ca avance :-)

**Comment by wouldsmina** [comment]
Bien joué. Pour l'erreur lors de la validation, peux tu envoyer les lignes en dessous du message d'erreur (login---nom---prenom---) Je pourrais te dire pourquoi tu bloque...

**Comment by Matou25** [comment]
voila la page d'erreur 
ATTENTION : certains champs saisis ne sont pas valides ......
---------100---N---conges
25---10
0---0
0---0
0---0

**Comment by Matou25** [comment]
le pb vient peut etre de la config,  dans le log apache j'ai : 
[Fri Dec 11 09:13:01.950255 2015] [:error] [pid 16362] [client 192.168.10.116:50503] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/libertempo/admin/admin_ajout-user.php on line 56, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpcongesc4c89eb891da3f0a8a5502170d66fd05&onglet=ajout-user
[Fri Dec 11 09:13:01.950415 2015] [:error] [pid 16362] [client 192.168.10.116:50503] PHP Notice:  Undefined index: login in /usr/share/libertempo/admin/admin_ajout-user.php on line 287, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpcongesc4c89eb891da3f0a8a5502170d66fd05&onglet=ajout-user
[Fri Dec 11 09:13:01.950475 2015] [:error] [pid 16362] [client 192.168.10.116:50503] PHP Notice:  Undefined index: login in /usr/share/libertempo/admin/admin_ajout-user.php on line 294, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpcongesc4c89eb891da3f0a8a5502170d66fd05&onglet=ajout-user
[Fri Dec 11 09:13:01.950499 2015] [:error] [pid 16362] [client 192.168.10.116:50503] PHP Notice:  Undefined index: nom in /usr/share/libertempo/admin/admin_ajout-user.php on line 294, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpcongesc4c89eb891da3f0a8a5502170d66fd05&onglet=ajout-user
[Fri Dec 11 09:13:01.950517 2015] [:error] [pid 16362] [client 192.168.10.116:50503] PHP Notice:  Undefined index: prenom in /usr/share/libertempo/admin/admin_ajout-user.php on line 294, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpcongesc4c89eb891da3f0a8a5502170d66fd05&onglet=ajout-user
[Fri Dec 11 09:13:01.950530 2015] [:error] [pid 16362] [client 192.168.10.116:50503] PHP Notice:  Undefined index: login in /usr/share/libertempo/admin/admin_ajout-user.php on line 301, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpcongesc4c89eb891da3f0a8a5502170d66fd05&onglet=ajout-user
[Fri Dec 11 09:13:01.950538 2015] [:error] [pid 16362] [client 192.168.10.116:50503] PHP Notice:  Undefined index: nom in /usr/share/libertempo/admin/admin_ajout-user.php on line 302, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpcongesc4c89eb891da3f0a8a5502170d66fd05&onglet=ajout-user
[Fri Dec 11 09:13:01.950545 2015] [:error] [pid 16362] [client 192.168.10.116:50503] PHP Notice:  Undefined index: prenom in /usr/share/libertempo/admin/admin_ajout-user.php on line 303, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpcongesc4c89eb891da3f0a8a5502170d66fd05&onglet=ajout-user
[Fri Dec 11 09:13:01.950554 2015] [:error] [pid 16362] [client 192.168.10.116:50503] PHP Notice:  Undefined index: email in /usr/share/libertempo/admin/admin_ajout-user.php on line 310, referer: http://rh.clipindustrie.com/admin/admin_index.php?session=phpcongesc4c89eb891da3f0a8a5502170d66fd05&onglet=ajout-user

**Comment by wouldsmina** [comment]
```
---------100---N---conges
25---10
0---0
0---0
0---0
```
Le problème viens du fait que le login, le nom et le prénom ne sont pas transmis dans le formulaire!

```
PHP Warning: Invalid argument supplied for foreach() in /usr/share/libertempo/admin/admin_ajout-user.php on line 56,
```
La c'est la commande `$data = ldap_get_entries($ds,$sr);` qui retourne un tableau vide, donc forcément le foreach n'est pas content! Pour les autres erreurs, je me souviens les avoir déja vue, essaye de faire une création manuelle pour voir si tu as la même chose...

**Comment by Matou25** [comment]
c'est bon j'ai trouver
il fallait ajouter "ldap_set_option($ds, LDAP_OPT_REFERRALS, 0);"
apres la ligne 689 de admin_ajout-user.php
mais aussi après la ligne 44

la ligne44 c'est un traitement direct
la ligne 689 c'est une fonction 
je sais pas si il y a redondance?
le user est crée, aucune erreur dans les logs, j'attaque le sso :-)

au final la seul modification c'est l'ajout de ces deux lignes

**Comment by Matou25** [comment]
un dernier soucis dans l'import:
l'import est impossible si le prenom ou le nom contiennent des accents
j'ai lu dans un fichier qu'avec utf8_decode on supprimait le pb normalement non?

**Comment by wouldsmina** [comment]
Le problème d'accent devrait etre réglé avec la version 1.7.1

**Comment by Matou25** [comment]
ok merci

**Comment by Matou25** [comment]
pour les accents c'est ok

j'ai modifié les lignes suivante:
61            $tab_new_user[$login]['prenom']	= utf8_decode($info[$ldap_libelle_prenom][0]);
62  		$tab_new_user[$login]['nom']	= utf8_decode($info[$ldap_libelle_nom][0]);

par
61            $tab_new_user[$login]['prenom']	= $info[$ldap_libelle_prenom][0];
62  		$tab_new_user[$login]['nom']	= $info[$ldap_libelle_nom][0];

ça peut poser problème ailleurs ?

**Comment by Matou25** [comment]
bonjour,

afin que l'utilisateur puisse rentrer sur sa session après qu'il ait été ajouter dans libertempo , j'ai modifié le fichier authLDAP.php pour etre en accord avec admin_ajout-user.php.

j'ai ajouter ldap_set_option($ds, LDAP_OPT_REFERRALS, 0);
apres la

**Comment by Matou25** [comment]
pour que les mails soit envoyé corecctement:
fonctions_conges.php
après la ligne 1103 ajout de ldap_set_option($ds, LDAP_OPT_REFERRALS, 0);

j'ai fait le tour de tous les fichiers, il ne semble pas y avoir d'autre endroit a modifier

**Comment by wouldsmina** [comment]
Ok. Reste à adapter cela pour rester compatible avec OpenLDAP...

Merci pour ton aide.

**Comment by Shadok** [comment]
Je reviens sur ce ticket, n'arrivant pas à faire fonctionner la liaison LDAP entre le script et mon AD 2008 R2. J'ai bien appliqué les modifications de Matou25, mais ça ne règle pas mon problème.
J'ai détaillé mes essais et résultats ici : https://forums.gentoo.org/viewtopic-p-7871906.html#7871906

Si vous avez une suggestion, je suis preneur :)

**Comment by Shadok** [comment]
Bon, c'est résolu, il ne faut tout simplement pas préciser le port dans config_ldap_server.
ldaps://srv.domaine.tld/ suffit amplement.

**Comment by wouldsmina** [comment]
Merci du retour @shadok.
A+

**Comment by Shadok** [comment]
Est-ce prévu de l'intégrer dans le code ?
Cela marche très bien avec les modifications indiquées ici, et cela me permettra de suivre les màj tranquillement :)

**Comment by wouldsmina** [comment]
oui, tout à fait. Mais d'abord il faut que je vérifie qu'il n'y a pas d'effet de bord avec OpenLDAP...

**Comment by Shadok** [comment]
Je peux te préparer un patch pour le code actuel de LT si tu veux.

**Comment by wouldsmina** [comment]
fait une PR sur la branche 1.7, ce serait parfait.

**Comment by Shadok** [comment]
Pas besoin de PR sur la branche develop ?

**Comment by Shadok** [comment]
PR faite sur la branche 1.7.

**Comment by Prytoegrian** [comment]
J'ai noté mon désaccord en commentaire de la PR avant d'avoir vu la fin de cette conversation, dites-moi ce qu'il en est.

**Comment by Shadok** [comment]
Ecoute, j'en fais aussi une sur develop et vous vous débrouillerez entre vous :D
Je prête les gants de boxe au besoin.

**Comment by Prytoegrian** [comment]
Pas de gants à prévoir, @wouldsmina est le mainteneur principal, c'est lui le maître à bord !

**Comment by Shadok** [comment]
PR effectué sur la branche develop :)
@wouldsmina a toi de voir.

**Comment by Prytoegrian** [comment]
Je m'aperçois que j'ai peut-être été un peu sec dans le choix des mots. Désolé, ça n'était pas volontaire, ya des jours avec et des jours sans, on reste humain après tout :s 

Il est bien évident que ta contribution est acceptée comme il se doit ; là où j'ai été maladroit c'est que je voulais dire que les branches des versions n-1, n-2, etc. ne doivent jamais avoir de nouvelles fonctionnalités / améliorations afin de ne pas mettre de l'aléatoire lorsque c'est utilisé par le client. Une fois que c'est livré c'est livré (hors bugs). Dans notre cas, tout le sujet de la discussion est de qualifier le ticket. Si ça n'est pas un bug ou qu'il n'est pas bloquant, alors on fait patienter jusqu'à la prochaine livraison ; si c'est un bug bloquant, on le livre sur la 1.7 **et** la future 1.8. Ce process est uniquement dans le bug de fiabiliser l'application que vous utilisez chaque jour. 

Voilà, encore une fois désolé si j'ai manqué de délicatesse.

Nous avons fait un [wiki](https://github.com/wouldsmina/Libertempo/wiki) pour détailler ce que l'on attend d'une contribution, nous ne l'avons pas encore mis en première page.

**Comment by wouldsmina** [comment]
gros fail de ma part!! c'est bien sur la develop qu'il faut corrigé. on se fait un bisou et on en parle plus?

**Comment by Prytoegrian** [comment]
Moi j'aime pô les bisous ! :-P

![https://raleursmodedemploi.files.wordpress.com/2012/05/grincheux.jpg](https://raleursmodedemploi.files.wordpress.com/2012/05/grincheux.jpg)

**Comment by wouldsmina** [comment]
:laughing: tu as top bien choisi ton avatar en fait!!
encore désolé @Shadok j'étais a coté de mes pompes.

**Comment by wouldsmina** [comment]
corrigé https://github.com/wouldsmina/Libertempo/pull/110

**Comment by Shadok** [comment]
Sec ? Je préfère le brut pour ma part :o

Je ne vois pas où tu as cru l'être :) En tout cas, aucun problème de mon côté.
De toute façon, je n'ai fait que tester et PR le correctif de @Matou25.

Je compte tester la branche dev avec le patch sur de l'AD, mais il y a une procédure pour migrer depuis la 1.7 ? Même en reportant les fiches de configuration et créant le fichier define.php à partir de define_new.php, je dois toujours passer par une installation (je n'ai pas été plus loin, il faut déjà que je mette une version de test en place).

**Comment by wouldsmina** [comment]
il faut suivre la procédure de mise a jour. Après copie des fichiers, il faut executer la procédure d'installation qui te proposera de mettre a jour.

**Comment by Prytoegrian** [comment]
Très bonne question… Tu poses une colle là ^^
Compte tenu du fait que nous n'avons pas fait de patch de base dans cette version, la BDD ne sera pas un problème, il s'agit « juste » de mise à jour des fichiers systèmes. Par contre, je vais laisser @wouldsmina t'en dire plus.

Attention cependant, le code actuel n'a pas encore passé le stade de beta, il n'est donc pas utilisable en production…

**Comment by Shadok** [comment]
Test effectué en 1.7.1, et rien à signaler, tout semble bien fonctionner, AD inclus.

**Comment by Shadok** [comment]
J'ai un utilisateur qui a changé son mdp Windows (dans un AD sous 2008R2).
Il ne peut plus se connecter à Libertempo (la 1.7) (avec le nouveau ou l'ancien mdp).

J'ai ça à l'écran quand je teste :

> Auth par defaut
> 
> SERVEUR 0 = ldaps://srv2.lan.domaine.com
> searchdn=CN=Utilisateurs,DC=lan,DC=domaine,DC=com
> 
> filtre : samaccountname=tartampion
> 
> tartampion = CN=M tartampion,CN=Utilisateurs,DC=lan,DC=domaine,DC=com
> NON 

Une idée ?
