### ISSUE TITLE
bouton semaine suivante

### ISSUE THREAD

**Issue by VV666** [wouldsmina/Libertempo#75]
Bonjour, 
petite demande d'amélioration que je mets là, je verrai si j'ai le temps de la faire.

Pouvoir décaller par semaine et non uniquement par mois, la vu calendrier (avoir des mois à cheval). Plus pratique pour imprimer les congés de noël ;-)

**Comment by wouldsmina** [comment]
Oui, cette fonction existait avant, ca devrait etre rétabli assez facilement...

**Comment by wouldsmina** [comment]
Fait pour la prochaine version. Je te laisse adapter à ta version...
