### ISSUE TITLE
Impossible de valider les congés d'un responsable par un responsable

### ISSUE THREAD

**Issue by TexGG** [wouldsmina/Libertempo#77]
Je vais un peu faire la question/réponse ici vu que j'ai réalisé mon correctif, mais c'est pour mieux exposer le problème et ma solution.

Dans certaines conditions, il est impossible de valider les congés d'un responsable de groupe. Imaginons deux groupes avec des membres :
GRP_Tech ( FC, GG, CG, BC )
GRP_Resp ( FC, CT, OL )

Les groupes ont les responsables suivants :
GRP_Tech : resp = FC, CT
GRP_Resp : resp = CT

On remarque que CT est responsable des deux groupes pour diverses raisons, et FC uniquement du groupe GRP_Tech. On  a dans ce cas là CT qui est donc responsable de FC, et est donc à même de valider ses congés. Cependant, dans l'onglet de traitement des demandes du mode responsable, les demandes congés de FC n'apparaissent jamais. Le seul moyen de les faire apparaître est de retirer CT en tant que responsable de GRP_Tech.

**Comment by TexGG** [comment]
Le problème vient en fait de la requête présente dans la fonction *"get_list_users_des_groupes_du_resp_sauf_resp()"* du fichier *"fonctions_conges.php"*. Elle doit *"recup de la liste des users des groupes dont $resp_login est responsable mais ne remonte pas les autres responsables"*, ce qu'elle fait très bien pour le GRP_Tech, mais pas pour le GRP_Resp.

Le problème est que la restriction appliquée en deuxième partie de requête, s'applique à l'ensemble des groupes indiqués en première partie de requête. Il est possible de la corriger pour que l'on est le bon résultat dans le cas qui nous intéresse, sans pour autant modifier le comportement général.

La requête:
```sql
SELECT DISTINCT(gu_login) FROM conges_groupe_users WHERE gu_gid IN ($list_groups) AND gu_login NOT IN (SELECT gr_login FROM conges_groupe_resp WHERE gr_gid IN ($list_groups)) ORDER BY gu_login
```
devient:
```sql
SELECT DISTINCT(gu_login) FROM conges_groupe_users WHERE gu_gid IN ($list_groups) AND gu_login NOT IN (SELECT gr_login FROM conges_groupe_resp WHERE gr_gid = gu_gid) ORDER BY gu_login
```

**Comment by wouldsmina** [comment]
@TexGG j'ai réalisé les mêmes conditions sur la demo en ligne et je n'arrive pas au même conclusion.
Je t'explique ce que j'ai fait : 


gestion des utilisateurs : 
dupont albert : droit responsable. Responsable direct legrand kevin
durand paolo: responsable direct dupont albert
fabre cecile: responsable direct dupont albert
gauthier jean: responsable direct dupont albert
legrand kevin: responsable direct resp-virtuel
point pierre: responsable direct  legrand kevin
simeon georges: responsable direct  legrand kevin

gestion groupes/utilisateurs : 
réseau : dupont albert, durand paolo, fabre cecile, gauthier jean
rh : dupont albert, legrand kevin, point pierre, simeon georges

gestion groupes/responsables : 
dupont albert : réseau
legrand kevin : réseau, rh

dupont albert demande un congés,
legrand kevin peut valider sa demande.

peux tu vérifier si ta config correspond?

**Comment by wouldsmina** [comment]
@TexGG si tu rencontre toujours le problème, fais moi signe...
