### ISSUE TITLE
Un responsable sans responsable ne peut pas valider ses congés

### ISSUE THREAD

**Issue by TexGG** [wouldsmina/Libertempo#79]
Je vais un peu faire la question/réponse ici vu que j'ai réalisé mon correctif, mais c'est pour mieux exposer le problème et ma solution.

Imaginons deux groupes avec des membres :
GRP_Tech ( FC, GG, CG, BC )
GRP_Resp ( FC, CT, OL )

Les groupes ont les responsables suivants :
GRP_Tech : resp = FC, CT
GRP_Resp : resp = CT

Dans ce cas, FC peut valider les congés de GG, CG et BC, mais il ne peut pas valider les siens. En effet, ses congés doivent être validés par son responsable : CT. 
Par contre, un problème se pose dans le cas de CT : il peut valider les congés de FC et OL, mais pas les siens. Hors comme il n'a pas de responsable autre que lui-même, personne ne peut valider ses congés.

D'un point de vu fonctionnel, ce n'est pas dérangeant pour la plupart des structures car logiquement CT serait le directeur, et que celui-ci n'a de comptes à rendre à personne. Cependant, dans d'autres cas, dont le mien, un suivit des congés est nécessaire pour la gestion des payes et autres, et il faut bien que CT puisse poser des congés que ces derniers puissent être validés.

**Comment by TexGG** [comment]
Pour corriger ce problème, je suis parti du fait que si un responsable n'a pas de responsable : il est responsable de lui-même (ou alors c'est une erreur de configuration de groupe/responsable).

Donc dans ce cas il faut que si CT n'a pas de responsable connu dans l'application, il apparaisse dans sa liste de demandes de traitements de l'onglet responsable.

Pour ceci, il faut modifier la fonction *"get_list_all_users_du_resp()"* du fichier *"fonctions_conges.php"* en y insérant le code suivant:
```php
...
	// si le responsable n'a pas de responsable, ou est responsable de lui-même, on l'ajout à la liste
	$list_resps=get_list_responsables($resp_login, $DEBUG);
	if ($list_resps == "") {
		if($list_users=="")
			$list_users="'$resp_login'";
		else
			$list_users=$list_users.", '$resp_login'";
	}
...
```

Ce code fait appel à un fonction retournant l'ensemble des responsables d'un utilisateur donné:
```php
// recup de la liste des responsables de $login, ne prend pas en compte si $login est responsable de lui-même ou si un autre responsable a les mêmes droits
// renvoit une liste de login entre quotes et séparés par des virgules
function get_list_responsables($login, $DEBUG=FALSE)	
{
	$list_resps="";
	$sql1="SELECT gr_login FROM conges_groupe_resp WHERE gr_gid IN (SELECT gu_gid FROM conges_groupe_users WHERE gu_login = '$login') AND NOT gr_gid IN (SELECT gu_gid FROM conges_groupe_users, conges_groupe_resp WHERE gu_gid = gr_gid AND gu_login = gr_login AND gu_login = '$login') ORDER BY gr_login ";
	$ReqLog1 = SQL::query($sql1);
	while ($resultat1 = $ReqLog1->fetch_array())
	{
		$current_login=$resultat1["gr_login"];
		if($list_resps=="")
			$list_resps="'$current_login'";
		else
			$list_resps=$list_resps.", '$current_login'";
	}
	if( $DEBUG ) { echo "list_resps= $list_resps<br>\n" ;}
	return $list_resps;
}
```

Avec ces modifications, CT voit bien ses demandes de congés apparaître dans sa liste de traitement de demande en plus des autres demandes. Bien entendu, FC lui continue à ne voir que les demandes de ses subalternes.

**Comment by wouldsmina** [comment]
Les utilisateurs sans responsable (ou avec le resp virtuel) aurons une validation automatique  en version 1.7.1...
J'ai gardé le responsable virtuel uniquement pour la compatibilité avec php_conges.

**Comment by wouldsmina** [comment]
Pour ce qui est du responsable d'un service dépendant d'un autre service dont il n'est pas le responsable, j'y avais pensé mais je n'ai jamais testé. Je regarde cela de plus près...

**Comment by TexGG** [comment]
Au temps pour moi, je n'avais pas vu la modification automatisant la validation de congés pour les utilisateurs sans responsables. le commit correspondant au #79 est donc inutile.
