### ISSUE TITLE
SMTP server issue

### ISSUE THREAD

**Issue by X-Ryl669** [wouldsmina/Libertempo#8]
Actuellement, l'envoi de mail via config_SMTP ne fonctionne pas. J'ai cependant pu corriger ceci:
ligne 953 de fonctions_conges.php:
```
// construit et envoie le mail
function constuct_and_send_mail($objet, $mail_sender_name, $mail_sender_addr, $mail_dest_name, $mail_dest_addr, $num_periode,  $DEBUG=FALSE)
{
+        require_once( LIBRARY_PATH .'phpmailer/PHPMailerAutoload.php' );  // ajout de la classe phpmailer
        /*********************************************/
        // init du mail
        $mail = new PHPMailer();

        if (file_exists(CONFIG_PATH .'config_SMTP.php'))
        {
                include CONFIG_PATH .'config_SMTP.php';

                if( isset($config_SMTP_host) )
                {
                        $mail->IsSMTP();
-                        $mail->Host = $config_SMTP_server;
+                        $mail->Host = $config_SMTP_host;

```

J'ai un début de bouton de test dans la configuration qui fonctionne. J'ai déplacé le require_once dans la fonction qui utilise la classe incluse, car dans la fonction de test de mail que j'ai ajouté, j'appelle construct_and_send_mail seulement.

**Comment by wouldsmina** [comment]
Pour smtp_host, c'est une boulette de ma part, merci de le relever.
Je corrige ça moi-même tout a l'heure.

Inclure la librairie dans la fonction construct and send mail est en effet plus approprié.
 Je suis aussi preneur pour ta fonction test_mail (le fichier test_mail.php n'utilise pas la fonction construct_and_send_mail, il est donc sans intérêt).
Merci.
