### ISSUE TITLE
php5-mysql

### ISSUE THREAD

**Issue by BrunoSpy** [wouldsmina/Libertempo#80]
Bonjour,
php5-mysql est obsolète depuis PHP 5.5 et vient d'être supprimé dans PHP7.
Y a-t-il un projet pour passer à mysqli ou pdo-mysql ?
Cordialement

**Comment by wouldsmina** [comment]
Disons que c'est à l'étude. @prytoegrian saura certainement en dire plus...

**Comment by Prytoegrian** [comment]
Hello,

la branche de prod `master` hérite déjà de `mysqli` pour tout ce qui est requêtage et nous n'avons pas pour projet de modifier ça pour les futures versions, pas d'inquiétude donc.

Par contre, on a pas encore tenté un déploiement de l'appli sur php7 pour voir ce qui bloque. Vu que la version est encore fraîche, je suppose qu'on a un peu de temps devant nous mais ça ne coûte rien de le mettre dans la todo list.
