### ISSUE TITLE
Virgule à la place d'un point dans une une requête SQL

### ISSUE THREAD

**Issue by Patrice67** [wouldsmina/Libertempo#81]
J'ai rencontré le soucis de virgule à la place d'un point en ajoutant une demi journée de congés à une personne par le RH. 
Voici le message d'erreur :
login : XX
uri : /libertempo/hr/hr_index.php?onglet=traite_user
dump : ../dump/sql_1450367010.dump

file : /var/www/html/libertempo/fonctions_conges.php
line : 2641

fx : $SQL->query
error : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '5 WHERE su_login='YY' AND su_abs_id=1' at line 1

sql : UPDATE conges_solde_user SET su_solde=su_solde-0.5, su_reliquat=4,5 WHERE su_login='YY' AND su_abs_id=1

**Comment by wouldsmina** [comment]
@Patrice67 je vais te demander la même chose que @VV666 :smile: 


Est ce que tu peux essayer si tout rentre dans l'ordre en ajoutant setlocale(LC_NUMERIC, 'en_US'); dans includes/lang_profile.php ligne 68. Pour moi c'est ok, mais je veux etre sur avant de corriger et clore ton ticket...

Il faut que tu retire le number_format que je t'avais invité à mettre...
