### ISSUE TITLE
Migration PHPCongés - Mail - Test OK mais non fonctionnel

### ISSUE THREAD

**Issue by lesouriciergris** [wouldsmina/Libertempo#82]
Bonjour,

suite à la migration (en test) de l'applis PHPCongés en Libertempo, la saisie d'un congé renvoie une erreur 

"
Message was not sent
Mailer Error: Vous devez fournir au moins une adresse de destinataire.
"

Le test de paramétrage de la messagerie est cependant fonctionnel.

Merci

**Comment by wouldsmina** [comment]
Bonjour,

Les adresses mails sont elles récupérées par ldap ou sont elles saisies manuellement?

**Comment by lesouriciergris** [comment]
Le 07/01/2016 16:55, wouldsmina a écrit :
> Bonjour,
>
> Les adresses mails sont elles récupérées par ldap ou sont elles saisies
> manuellement?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wouldsmina/Libertempo/issues/82#issuecomment-169705707>.
>
Saisie manuelle, dans la base de données. Les mails existaient dans la 
base PHPCongés et fonctionnaient.

**Comment by wouldsmina** [comment]
Dans la config vérifie where_to_find_user_mail. As tu paramétré le fichier cfg/SMTP_config.php?

**Comment by lesouriciergris** [comment]
Le 08/01/2016 18:49, wouldsmina a écrit :
> Dans la config vérifie where_to_find_user_mail. As tu paramétré le
> fichier cfg/SMTP_config.php?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wouldsmina/Libertempo/issues/82#issuecomment-170072804>.
>
J'ai configuré cfg/SMTP_config.php
mais par contre n'ai pas mémoire d'avoir touché where_to_find_user_mail
Je regarde et vous tiens informer (dans un peu de temps)

**Comment by lesouriciergris** [comment]
Les deux informations sont correctes (vérification en base pour where_...)

**Comment by wouldsmina** [comment]
c'est très bizarre, avant l'appel à la fonction ```constuct_and_send_mail``` on vérifie que la variable ```$mail_dest_addr``` n'est pas vide. Pourtant ton erreur viens de PHPMailer, donc après le test. As tu des erreurs dans les logs apache? vérifie aussi que tu as bien transféré tous les fichiers, les droits...

**Comment by lesouriciergris** [comment]
Nouvel essai, cette fois ci le mail est arrivé mais le message d'erreur 

"Message was not sent
Mailer error ..."

apparaît. Donc le problème viendrait uniquement du traitement de la réponse à l'envoi du mail.

**Comment by wouldsmina** [comment]
Tu veux dire que tu obtiens un message d'erreur malgré l'envoi du mail?

**Comment by lesouriciergris** [comment]
Le 20/01/2016 20:00, wouldsmina a écrit :
> Tu veux dire que tu obtiens un message d'erreur malgré l'envoi du mail?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wouldsmina/Libertempo/issues/82#issuecomment-173325185>.
>
Oui

**Comment by wouldsmina** [comment]
J'oubliais le plus important. As tu des erreurs dans les logs apache?

**Comment by wouldsmina** [comment]
ce ticket et #91 semblent avoir la même racine : where_to_find_user_mail n'a pas l'air d'etre pris en compte. A creuser...

**Comment by lesouriciergris** [comment]
Trace

[Mon Feb 01 17:02:27 2016] [error] [client ] PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /var/www/libertempo/include/fonction.php on line 207,

**Comment by Prytoegrian** [comment]
Merci pour la précision. C'est le même problème que #94, je vais le corriger ce soir et faire les tests qui s'imposent. Ceci dit je veux bien que tu me donnes la version de PHP (php -v dans un cli du serveur) parce que ça pète que pour vous et ça me fait m'interroger. On est peut-être face à une incompatibilité générale et il faudrait le savoir pour en corriger le plus possible avant d'être face au mur.

Surveille ce sujet, je mettrai à jour quand j'aurai de la donnée.

**Comment by wouldsmina** [comment]
La je m'y perd. @lesouriciergris tu n'as pas de problème de clôture de session? j'ai plutot l'impression que ce sont les emails qui déconne lorsqu'ils sont tiré de la BDD.

**Comment by lesouriciergris** [comment]
Le 01/02/2016 20:07, wouldsmina a écrit :
> La je m'y perd. @lesouriciergris <https://github.com/lesouriciergris> tu
> n'as pas de problème de clôture de session? j'ai plutot l'impression que
> ce sont les emails qui déconne lorsqu'ils sont tiré de la BDD.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wouldsmina/Libertempo/issues/82#issuecomment-178133112>.
>
Seule log de Apache.
Version de php demain ;-)

**Comment by lesouriciergris** [comment]
PHP 5.3.3-7+squeeze28 with Suhosin-Patch

**Comment by Prytoegrian** [comment]
Je suis en train de pister les changelogs de PHP pour voir ce qui a peut causer ce problème. Tu feras gaffe squeeze n'est plus supportée. Je t'invite à regarder la conversation https://github.com/wouldsmina/Libertempo/issues/94#issuecomment-178161082  et à tester le microfix que j'ai posté. Si ce fix est nécessaire et suffisant pour que ça roule pour vous, on vous fera une release.

**Comment by Prytoegrian** [comment]
Après étude, le message d'erreur dans le log apache n'est pas du tout lié à ça, je vais donc laisser la main à @wouldsmina, il s'en sortira mieux

**Comment by wouldsmina** [comment]
@lesouriciergris peux tu me transmettre un dump de ta bdd: wouldsmina@tuxfamily.org
Merci.

**Comment by lesouriciergris** [comment]
J'ai testé le fix mais ce dernier n'a pas fonctionné.

Pour le dump de la bdd, je vais devoir l'anonymiser, mais dès que je peux, je le fais. Je pense Mercredi ou Jeudi.

**Comment by wouldsmina** [comment]
PHPMailer n'était pas chargé correctement dans la fonction d'envoi. J'ai corrigé sur `beta`...

**Comment by lesouriciergris** [comment]
Le 16/03/2016 21:59, wouldsmina a écrit :
> PHPMailer n'était pas chargé correctement dans la fonction d'envoi. J'ai
> corrigé sur |beta|...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/wouldsmina/Libertempo/issues/82#issuecomment-197547305>
>
Merci
