### ISSUE TITLE
Problème de recréditation des congés lors d'une annulation

### ISSUE THREAD

**Issue by TexGG** [wouldsmina/Libertempo#83]
Il arrive que lors d'une annulation de congés par le responsable (après qu'il ai été validé bien entendu), les jours ne soit pas recrédités dans le total disponible.

Après avoir débuggé un peu le code est cherché, j'ai trouvé que cela ne se produisait que pour les valeurs contenant une décimale, ex: "1.5". J'ai également réussi à déterminer raison : la requête envoyé à MySQL est "UPDATE conges_solde_user SET su_solde = su_solde+'0,5' WHERE su_login='ggervais' AND su_abs_id='1';". On remarque la virgule dans la valeur, hors MySQL traite généralement mieux les points que les virgules dans les décimales ...

Bon maintenant que j'ai un élément de raison j'ai poussé plus loin. Et avec quelques echo juste avant la fonction "annule_conges()", on obtient ça : 
type=conges
LC_NUMERIC=fr_FR
user_nb_jours_pris=0.5
user_nb_jours_pris_float=0,5
SQL::quote=0,5
UPDATE conges_solde_user SET su_solde = su_solde+'0,5' WHERE su_login='ggervais' AND su_abs_id='1';

On voit donc que le problème se produit au moment de la conversion de la string $user_nb_jours_pris en float dans $user_nb_jours_pris_float. Cela est au final due à la locale LC_NUMERIC qui n'utilise pas la numérique en_EN ou us_US mais bien française fr_FR (ça serait pareil avec un locale allemande) qui a des virgules en décimal et non des points.

N'ayant pas trop envie de changer ma locale numérique (je suis français bordel :p), il est donc nécessaire de trouver un système pour éviter ce problème de locale. Je m'orienterais bien vers la fonction "number_format()", mais je ne sais pas si cela peut s'appliquer à tout le monde ...

Code envisagé : 
```php
function annule_conges($user_login, $tab_checkbox_annule, $tab_text_annul,  $DEBUG=FALSE)
{
   ...

        $user_nb_jours_pris=$champs[1];
        $user_nb_jours_pris_float=(float) $user_nb_jours_pris ;
	$user_nb_jours_pris_format=number_format($user_nb_jours_pris_float, 2, '.', '');
        $numero=$elem_tableau['key'];
        $numero_int=(int) $numero;
        $user_type_abs_id=$champs[2];

        $motif_annul=addslashes($tab_text_annul[$numero_int]);

        if( $DEBUG ) { echo "<br><br>conges numero :$numero ---> login : $user_login --- nb de jours : $$user_nb_jours_pris_format --- type : $user_type_abs_id ---> ANNULER <br>"; }

...

        /* UPDATE table "conges_solde_user" (jours restants) */
        // on re-crédite les jours seulement pour des conges pris (pas pour les absences)
        // donc seulement si le type de l'absence qu'on annule est un "conges"
        if($tab_tout_type_abs[$user_type_abs_id]['type']=="conges")
        {
            $sql2 = 'UPDATE conges_solde_user SET su_solde = su_solde+\''.SQL::quote($$user_nb_jours_pris_format).'\' WHERE su_login=\''.SQL::quote($user_login).'\' AND su_abs_id=\''.SQL::quote($user_type_abs_id).'\';';
            //echo($sql2."<br>");
            $ReqLog2 = SQL::query($sql2);
        }
```

J'ai testé et ça fonctionne, mais là encore la question est : est-ce applicable à tout le monde ? avec n'importe quelle locale ?

**Comment by wouldsmina** [comment]
Merci pour ta contrib. il y a le même bug pour la modification d'un congés. Je vais pousser cette correction sur la branche develop. 
>J'ai testé et ça fonctionne, mais là encore la question est : est-ce applicable à tout le monde ? avec n'importe quelle locale ?

Le seul format autorisé pour mysql c'est avec le point, donc oui c'est applicable pour tous.

**Comment by Prytoegrian** [comment]
@wouldsmina Attention, ton correctif ne marche pas en l'état, tu as affecté le changement à une nouvelle variable sans l'utiliser dans ta requête.

Ensuite (et ce sera un coup de gueule), je suis vraiment sur le cul que PHP fasse des erreurs si grossières, à savoir créer des représentations de nombre **inutilisables** pour lui-même, c'est stupide et je pèse mes mots. Les calculs internes et l'affichage devraient être découplés, c'est bien à ça que servent les classes [Intl](https://secure.php.net/manual/en/book.intl.php) et notamment numberformatter dans notre cas. Mais bon.

Je n'ai pas de solution miracle, c'est pour ça que je n'ai pas répondu tout de suite. Sauf à avoir la conf générale serveur de PHP en locale en_US et stocker une conf applicative pour les présentations - ce qui serait le plus propre [et permettrait de faire sauter le select de la langue sur la connexion] -, j'ai pas mieux que dupliquer un truc du genre : 
```php
$monFloat = floatval( str_replace( ",", '.', $maVar) );  
```

En tout cas, merci @TexGG pour le travail effectué. Tu as vraiment creusé le bug et c'est cool de ta part.

**Comment by TexGG** [comment]
Au passage j'ai remarqué que suivant le fichier dans laquelle elle est appelée, la fonction "soustrait_solde_et_reliquat_user()" n'est pas appelée avec les même paralètres : dans "resp_traite_user.php" on lui passe un float, et dans "resp_traitement_demandes.php" on lui passe un string. Et qui plus est, le problème de virgule est corrigé dans cette fonction puisque qu'on a "$user_nb_jours_pris = str_replace(',', '.', $user_nb_jours_pris);" juste avant la requête à MySQL.

**Comment by wouldsmina** [comment]
> Ensuite (et ce sera un coup de gueule), je suis vraiment sur le cul que PHP fasse des erreurs si grossières, à savoir créer des représentations de nombre inutilisables pour lui-même, c'est stupide et je pèse mes mots. 

C'est plutôt mysql qui n'aime pas ce format décimal. mais le résultat est le même...

@TexGG c'est vrai que les paramètres de différent type c'est pas très classe. Encore merci pour ton aide.

**Comment by Prytoegrian** [comment]
Après discussion avec l'un de mes « sempai », mon approche est la bonne, a fortiori lorsque l'on a une appli multilingue. Il est primordial de ne pas toucher à la conf serveur et de créer une configuration applicative. Ce serait pas mal de créer un ticket pour voir à plus long terme que la correction de bug. Et si une bonne âme passe dans le coin…

**Comment by wouldsmina** [comment]
Je ne crois pas que le problème vienne de la conf serveur, mais de l'appli. En tout cas, je n'ai modifié que le GMT sur mon serveur et j'ai ce problème.

**Comment by Prytoegrian** [comment]
Hum, pardon, je viens de comprendre que le choix des mots a pu prêter à confusion. Quand je parlais de conf serveur, je parlais de conf serveur « PHP ». On est bien d'accord que c'est inhérent à l'appli. Vu que je passais dans le coin, si ça peut aider, les locales sont changées pour toutes les catégories dans le fichier `includes/lang_profile.php`

**Comment by wouldsmina** [comment]
Ok. Mais du coup, est ce qu'il est possible de modifier uniquement le format de la décimal? 

>Ce serait pas mal de créer un ticket pour voir à plus long terme que la correction de bug. Et si une bonne âme passe dans le coin…

+1

**Comment by Prytoegrian** [comment]
Ça dépend, tu voudrais la modifier dans quel sens ?

**Comment by Prytoegrian** [comment]
Tiens, j'y pense, c'est le même problème que #72

**Comment by wouldsmina** [comment]
J'ai corrigé ce bug sur [le paquet 1.7.0](http://libertempo.tuxfamily.org/downloads/) en téléchargement chez tuxfamily. Je ferais un petit article pour signaler cette correction importante.

**Comment by wouldsmina** [comment]
Tiens, j'ai oublié de faire un truc... 

Est ce que tu peux suivre la manip sur #81 stp.
