### ISSUE TITLE
Normalisation boutons de la page de traitement des utilisateurs par le responsable et le haut responsable

### ISSUE THREAD

**Issue by TexGG** [wouldsmina/Libertempo#84]
Dans la page de traitement des utilisateurs par le responsable par le responsable, les boutons "Valider" et "Abandonner" des sections "État des demandes" et "État des demandes en deuxième validation" sont affichés différemment de la section "Nouveau congé/Absence".

Un simple changement dans le code suffit à rendre le tout plus homogène (et plus beau au passage) : 
Il faut remplacer 
```php
echo "<input class=\"btn\" type=\"submit\" value=\"". _('form_submit') ."\">  &nbsp;&nbsp;&nbsp;&nbsp;  <input type=\"reset\" value=\"". _('form_cancel') ."\">\n";
```
par
```php
echo "<input class=\"btn btn-success\" type=\"submit\" value=\"". _('form_submit') ."\">";
echo "<a class=\"btn\" href=\"$PHP_SELF?session=$session\">". _('form_cancel') ."</a>\n";
```
(code repris dans "fonction_conges.php"

Et cela dans les fonctions "affiche_etat_demande_user_for_resp()" et "affiche_etat_demande_2_valid_user_for_resp()" des pages "resp_traite_user.php" et "hr_traite_user.php".

**Comment by Prytoegrian** [comment]
Ouais, je suis bien d'accord. Hésite pas à nous envoyer une petite PR, vu que tu as déjà étudié le code ce sera facile pour toi et en plus tu disais que tu n'avais pas beaucoup d'expérience avec Github, c'est l'occasion :-)

Même si c'est une PR aussi bête que 2 lignes, toutes les contributions sont bonnes à prendre !

**Comment by TexGG** [comment]
Ah désolé j'ai pas pu proposer cette modification, j'étais absent 1 semaine. Je le ferai pour la prochaine (yen a ura toujours) :p
