### ISSUE TITLE
Ligne commentée donne des warnings PHP

### ISSUE THREAD

**Issue by TexGG** [wouldsmina/Libertempo#85]
La ligne définissant la variable "$value_traite" est commentée dans la fonction "traite_demandes()". Je n'ai pas trop vu pourquoi elle était commentée vu que cela servait juste au DEBUG, mais cela provoque des messages de warnings de PHP comme quoi la valeur n'est pas définie.

**Comment by Prytoegrian** [comment]
:warning: elle sert aussi pour la journalisation des événements, ça doit être cette séquence de code qui déclenche l'erreur. Peux-tu nous donner un moyen de reproduire le bug ?

**Comment by TexGG** [comment]
Le bug apparaît brièvement avant le rechargement de la page quand on valide une demande à partir de la fiche de traitement d'un utilisateur (et pas depuis le traitement de toutes les demandes). Je suppose qu'en mode debug il reste, mais j'ai corrigé avant même d'essayer ce dernier.

**Comment by Prytoegrian** [comment]
Nickel merci, on va pouvoir vérifier tout ça. Ya de très fortes chances pour que le « commentage » soit un bug d'inattention, il y a une fonction identique dans le module *haut responsable* et la variable n'est pas commentée là bas.

**Comment by wouldsmina** [comment]
````
            $date_deb=$champs[3];
            $demi_jour_deb=$champs[4];
            $date_fin=$champs[5];
            $demi_jour_fin=$champs[6];
            $reponse=$champs[7];
            //      $value_traite=$champs[3];
````
$value_traite == $date_deb

je vais plutôt retirer $value_traite.
