### ISSUE TITLE
Bug Affichage deplacement jour absence 

### ISSUE THREAD

**Issue by HeurtierS** [wouldsmina/Libertempo#86]
Lorsque l'on déplace le  RTT programmé un autre jour l'ancienne date reste active et la nouvelle également. Après analyse du code l'erreur provient des lignes suivantes dans fonctions_conges.php:
dans la fonction:
function recup_tableau_rtt_echange($mois, $first_jour, $year,  $tab_logins = false)
while($l = $result->fetch_array()) {
		$tab_echange = array();
		$tab_echange["val_matin"] = ($l["e_absence"]=='J' || $l["e_absence"]='M' ? 'Y' : 'N');
		$tab_echange["val_aprem"] = ($l["e_absence"]=='J' || $l["e_absence"]='A' ? 'Y' : 'N');
		$tab_rtt_echange[ $l['e_date_jour'] ][ $l["e_login"] ] = $tab_echange;
	}
il faut remplacer par : 
while($l = $result->fetch_array()) {
		$tab_echange = array();
		$tab_echange["val_matin"] = ($l["e_absence"]=='J' || $l["e_absence"]=<strong>=</strong>'M' ? 'Y' : 'N');
		$tab_echange["val_aprem"] = ($l["e_absence"]=='J' || $l["e_absence"]=<strong>=</strong>'A' ? 'Y' : 'N');
		$tab_rtt_echange[ $l['e_date_jour'] ][ $l["e_login"] ] = $tab_echange;
	}

**Comment by Prytoegrian** [comment]
^^ joli ! C'est pour cette raison qu'il est préférable d'effectuer une comparaison sous la forme : 
```php
$a = 'string';
if ('check' == $a) {
...
}
```

pour pas que l'erreur au runtime soit invisible puisque c'est une expression php valide.
