### ISSUE TITLE
Add right CSS for print media

### ISSUE THREAD

**Issue by X-Ryl669** [wouldsmina/Libertempo#9]
Dans le template/reboot/menu_header.php, il faut ajouter media="screen,print" pour le CSS bootstrap.min.css et reboot.css (sinon, à l'impression, c'est très moche).
Ensuite, dans reboot.css, ajouter une ligne:
```
#main-calendar table td { border: 1px solid #000; min-width: 2em; }
```
Qui dessine les bordures des cellules du calendrier (sinon, c'est illisible).

**Comment by wouldsmina** [comment]
Merci.
