### ISSUE TITLE
Ajout de notification Mail

### ISSUE THREAD

**Issue by Dam02738** [wouldsmina/Libertempo#91]
Bonjour à tous :o)

Ayant découvert le logiciel il y a une semaine je souhaiterais le mettre ne place pour ma collectivité.
La configuration c'est déroulée parfaitement.
Mais (il y a un mais) j'aimerai ajouter une notification après la validation du grand responsable (en cas de double validation) ou au responsable pour le service RH.
Le soucis c'est que je vois pas quel code entrer car a chaque fois il me met mail error
(Je ne comprends pas le fonctionnement de "Alerte_Mail")

en espèrent avoir été assez clair. 

Merci d'avance.

**Comment by wouldsmina** [comment]
Bonjour,
Tu veux savoir comment configurer l'envoi de mail, c'est ça?

**Comment by Dam02738** [comment]
Bonsoir,
merci de l’intérêt porté à mon problème mais j'ai réussi à faire ce que je voulais en créant un nouvelle fonction "Alerte_mail2" que j'ai placée aux endroits adéquat.
En revanche j'ai 2 ou 3 questions :o) :   
pourquoi lorsqu'on met un ";" pour renseigner 2 adresses mails ça ne fonctionne pas.
Comment allez chercher une donnée dans la base sql sans faire un "mysql connect" et un "mysql select db"
Pourquoi lorsqu'on se déconnecte de l'application je me retrouve sur la page de la session expirée
et enfin comment faire pour que lorsqu'on rentre un solde lors de la création d'un user, il n'arrondisse pas (car chez nous le 0,75 est de rigueur à mon grand désarroi).
Voilà j'ai fini.
En tout cas merci beaucoup pour ce logiciel qui est super, merci pour le suivi et les renseignements qu'on trouve sur le forum.
Il ne manque plus qu'un suivi d'activité avec des feuilles d'activités agrémentées par les utilisateurs,
mais je sais que c'est compliqué à mettre en place.
en tout cas merci beaucoup.
bonne soirée.

**Comment by wouldsmina** [comment]
>j'ai réussi à faire ce que je voulais en créant un nouvelle fonction "Alerte_mail2" que j'ai placée aux endroits adéquat.

Tu partage? :smile: 
>pourquoi lorsqu'on met un ";" pour renseigner 2 adresses mails ça ne fonctionne pas.

Il faut ajouter les adresses une par une : 
````
$mail->addAddress('myfriend1@example.net', 'My Friend');
$mail->addAddress('myfriend2@example.net', 'My Friend');
...
````
C'est comme ça que [PHPMailer](https://github.com/PHPMailer/PHPMailer) fonctionne.

>Comment allez chercher une donnée dans la base sql sans faire un "mysql connect" et un "mysql select db"

C'est simple, après avoir mis la requete dans une variable : 
````
$sqlResult=SQL::query($sql);
$resultat = $sqlResult->fetch_array();
````

si ta requete retourne plusieurs résultat, il faut que tu les traites dans une boucle while : 
````	while( $l = $sqlResult->fetch_array() ) 
	{
...````

>Pourquoi lorsqu'on se déconnecte de l'application je me retrouve sur la page de la session expirée.

Normalement, tu dois retourner à la page de login. Tu as quoi dans l'url après le logout? Et dans les logs apache?

>comment faire pour que lorsqu'on rentre un solde lors de la création d'un user, il n'arrondisse pas (car chez nous le 0,75 est de rigueur à mon grand désarroi).

Il n'est tout simplement pas prévu de gérer les 1/4 de congés.

>En tout cas merci beaucoup pour ce logiciel qui est super, merci pour le suivi et les renseignements qu'on trouve sur le forum.
Il ne manque plus qu'un suivi d'activité avec des feuilles d'activités agrémentées par les utilisateurs,
mais je sais que c'est compliqué à mettre en place.
en tout cas merci beaucoup.
bonne soirée.

Merci à toi aussi. Il est vrai que l'on peut faire mieux, mais on est pas nombreux et on se concentre surtout sur le code (et il y a du boulot). Toutes les aides sont le bienvenue, même un simple ticket de bug...

**Comment by Dam02738** [comment]
Merci pour les tuyaux :o) 
Pour la fonction alerte_mail2 j'ai tout simplement repris la fonction alerte_mail existante que j'ai adaptée (j'ai juste retiré les lignes de code inutiles) mais surtout j'ai indiqué le chemin dans la base pour aller chercher la valeur de l'adresse email (d'où ma question pour la connexion à la base sql).
Ensuite j'ai ajouté deux tables dans la bases, dans la section mail : une pour activer la fonction et l'autre pour définir l'adresse mail du service RH.
J'ai ajouté les traductions dans le fichier de langue fr (celle qui m’intéresse)
ensuite j'ai placé la fonction dans le code php juste après les validations par les responsables.
Je te mettrai le code et les fichiers php que j'ai modifié quand je serai au boulot.
et pour les 1/4 de congés j'ai réussi à supprimer les arrondis mais moi je m'en sert en heures et non en jours.
d’ailleurs il serai pas mal d’ingérer les heures car pour les récupérations nous c'est en heures supp.
ex : le 20/01/2016 de telle heure à telle heure. (ça je ne sais pas faire).
A savoir que je maitrise plus le wlangage que le php.
Pour le log out ça fonctionne très bien en local mais quand je l'ai mis sur mon serveur avec redirection dns ça me met l'erreur log out. (l'url dans la config est vierge) 
encore merci pour les infos en tous cas.

**Comment by wouldsmina** [comment]
>d’ailleurs il serai pas mal d’ingérer les heures car pour les récupérations nous c'est en heures supp.

Pour le moment on se concentre surtout sur la correction de bug et la modification du code pour s'approcher le plus d'une archi mvc. 

> Pour le log out ça fonctionne très bien en local mais quand je l'ai mis sur mon serveur avec redirection dns ça me met l'erreur log out. (l'url dans la config est vierge) 

Il faut absolument renseigner le champ url_accueil_conges dans la config.

**Comment by wouldsmina** [comment]
Merci de tester beta et d'ouvrir un nouveau ticket en cas de soucis similaire

**Comment by wouldsmina** [comment]
PS : on ajoutera pas les notifications au RH, garde ton fork pour maintenir ta fonctionnalité au fil des versions si tu le souhaites...
