### ISSUE TITLE
Mise à jour Php_conges v 1.5.1 vers Libertempo 1.7.1

### ISSUE THREAD

**Issue by DreDoU** [wouldsmina/Libertempo#92]
Bonjour,

Qu'elle est la procédure à suivre pour effectuer la mise à jour de l'application Php_conges v 1.5.1 vers Libertempo 1.7.1 ?

Quelles sont les nouveautés de cette nouvelle application ? 

merci

Bonne journée

**Comment by wouldsmina** [comment]
Bonjour,
Vous pouvez consulter le site libertempo.tuxfamily.org. vous y trouverai la doc d'installation pour la version 1.7 ( la 1.7.1 est en cours d'élaboration).
Les nouveautés et changement sont nombreux, les articles vous donnerons une idée des changements, mais je n'ai pas de liste exhaustive sous la main, désolé.
