### ISSUE TITLE
Erreur à l'installation due à une collision de variables de configuration

### ISSUE THREAD

**Issue by romain1206** [wouldsmina/Libertempo#94]
bonjour 

j'ai une erreur avec libertempo j'ai un message "pas de session ouverte"

j'ai réussi a faire une capture d'écran avec le debug php

![image 5](https://cloud.githubusercontent.com/assets/16817502/12479782/e6a452b0-c03d-11e5-99a6-ea6e5aba8834.jpg)

merci d'avance

**Comment by wouldsmina** [comment]
Bonjour,

L'installation c'est bien terminé? as tu suivi la [doc d'install](http://libertempo.tuxfamily.org/documentation/install_update/)?

**Comment by romain1206** [comment]
oui j'ai bien suivi la doc

je suis passé de php conges 1.5 vers libertempo mais j'ai eu ce message

j'ai tenté une installation propre avec une base vierge et j'ai le meme soucis

**Comment by wouldsmina** [comment]
Bizarre. Sur quel version d'apache, php, mysql, OS? As tu des logs d'erreur?

**Comment by Prytoegrian** [comment]
Si je lis bien le retour d'erreur, les lignes 2 et 3 sont déclenchées à cause de la ligne 1 : l'output **c'est** le warning. Donc on peut s'en ficher, résoudre la 1 résoudra les autres.

Après, je crois qu'il y a un problème de variable qui sert à deux choses en même temps ET complètement différentes entre elles : il y a le `$_SESSION['config']` de `index:40` et le `$_SESSION` de `include/fonction:213` et +

La première vise à récupérer une configuration initiale pour la page de connexion avant que l'utilisateur se connecte et créé finalement la vraie session via session_create. La seconde est la vraie variable superglobale de session.

Si l'on s'en tient à la doc, on ne peut pas utiliser la superglobale avant session_start() et le session_destroy() doit se faire après l'initalisation de la session de session_start().

Je propose donc de renommer `$_SESSION['config']` de `index:40` en `$config` car elle serait de toute façon écrasée par `include/fonction:218`. Il faut aussi remplacer toutes ses occurences jusqu'à la ligne 191 dans le même fichier.
Du coup le if ligne 207 disparaît.

Il y a d'autres solutions mais pour pas vous perdre je vais pas les évoquer. Le code est appelé à se modifier, ça fera le job le temps qu'on le reprenne.

**Comment by wouldsmina** [comment]
@romain1206 as tu reglé ton problème?

**Comment by romain1206** [comment]
non je n'ai pas résolu mon pb.

je n'ai pas les compétences de Prytoegrian pour faire les modifs

**Comment by Prytoegrian** [comment]
Cf. https://github.com/wouldsmina/Libertempo/issues/82#issuecomment-178092481 :-)

**Comment by Prytoegrian** [comment]
Je préfère ne pas faire de branche vu que je suis incapable de reproduire le bug sur mon poste donc on va tâtonner ici. Tu peux me dire si ce diff corrige ton bug ? Si c'est le cas, on fera une vraie version de libertempo avec ce correctif.

```diff
diff --git a/index.php b/index.php
index f6527d7..40575c1 100644
--- a/index.php
+++ b/index.php
@@ -31,12 +31,13 @@ defined( '_PHP_CONGES' ) or die( 'Restricted access' );
 include INCLUDE_PATH .'fonction.php';
 include ROOT_PATH .'fonctions_conges.php'; // for init_config_tab()
+session_start();
 $_SESSION['config']=init_config_tab();      // on initialise le tableau des variables de config
````

Tant que je t'ai, tu peux me fournir toutes les infos que tu peux sur ton archi, à savoir OS, version de php (mysql et apache t'est pas obligé), si tu as tout embarqué via xampp / lampp / wampp ou si c'est installé individuellement ? Merci.

**Comment by romain1206** [comment]
je tente ca demain au boulot

mon install est debian avec les package installées un a un

**Comment by Prytoegrian** [comment]
Hum, après réflexion, ça ne **peut pas marcher** comme ça. Je vais reprendre ma première idée et vous faire une branche que je vous demanderai de tester. Vous avez installé des versions git ou release ?

**Comment by romain1206** [comment]
effectivement j'ai tenter 

meme erreur.

je suis parti d'une release mais je peux tester une git si besoin

**Comment by Prytoegrian** [comment]
fais ça s'il te plaît, c'est le plus petit diff nécessaire, normalement ça devrait rouler comme ça

```diff
diff --git a/include/fonction.php b/include/fonction.php
index f25561a..3f86765 100644
--- a/include/fonction.php
+++ b/include/fonction.php
@@ -204,7 +204,7 @@ function session_create($username)
 {
     if ($username != "")
     {
-	if(isset($_SESSION)) session_destroy();
+	if(isset($_SESSION)) unset($_SESSION);
         $session = "phpconges".md5(uniqid(rand()));
         session_name($session);
         session_id($session);
@@ -416,5 +416,3 @@ function deconnexion_CAS($url="")
 
     phpCAS::logoutWithUrl($url);
 }
```

**Comment by Prytoegrian** [comment]
Sans plus de réponse, je ferme ; les version déployés ont dû corriger. Au besoin, on ouvrira un autre ticket mais nous devons avoir une visibilité sur l'encours.
