### ISSUE TITLE
Bug update 181 vers 192

### ISSUE THREAD

**Issue by groucha17** [wouldsmina/Libertempo#948]
Bonjour,
En faisant la mise à jour du logiciel, j'ai ce bug avec ce message d'erreur.

login : 
uri   : /conges/install/upgrade_from_v1.8.1.php?etape=2&version=1.9&lang=fr_FR
dump  : ../dump/sql_2021-03-04T15:34:33+01:00.dump

file  : /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/conges/includes/SQL.php
line  : 90
fx    : $SQL->query
error : Can't DROP 'u_login'; check that column/key exists
sql   : ALTER TABLE conges_users DROP INDEX u_login;

Que faire svp ? J'ai besoin d'aide...

Cordialement,

Stéphane
Radio Campus Tours

**Comment by wouldsmina** [comment]
Bonjour,
Est ce que c'est bloquant ? D'après ce que je vois, la requête ne peut pas retirer l'index car il n'existe pas, au final la base de données se trouve dans l'état souhaité.

**Comment by groucha17** [comment]
Bonjour,
Je vous remercie pour ces informations. Je ne peux pas faire la mise à jour complètement bien que ce ne soit pas bloquant à l'usage. Cependant il y a plusieurs messages d'erreur qui s'affichent visibles sur l'imprime écran dont j'ai joint l'url. Je ne sais pas quoi faire... J'ai besoin d'aide svp...
https://stephaneberton.freeboxos.fr/nextcloud/index.php/s/yrxbRzkSJ4PCyot

**Comment by wouldsmina** [comment]
La version 1.9 est dépassée depuis bien longtemps. Les messages ne sont que des warnings ce n'est pas bloquant. Pour qu'il ne s'affiche plus, il faut désactiver le mode debug (ou verbose, je sais plus exactement) de php.
