### ISSUE TITLE
https://github.com/libertempo/api/issues/149

### ISSUE THREAD

**Issue by anthonymerzouki** [wouldsmina/Libertempo#957]
Est-ce que quelqu'un peut nous assister sur ce bug d'aPI de la dernière version svp ?
https://github.com/libertempo/api/issues/149

**Comment by wouldsmina** [comment]
Bonjour,
Je suis pas mal occupé ces derniers jours, je regarde ça dès que possible.

**Comment by wouldsmina** [comment]
je t'ai répondu sur libertempo/api#149
