### ISSUE TITLE
Impossibilité d'installer libertempo

### ISSUE THREAD

**Issue by Watachibi** [wouldsmina/Libertempo#959]
Bonjour,

Dans l'optique de mettre à jour notre version de Libertempo 1.10, cela fait plusieurs semaine que, mes collègues et moi-même essayons d'installer Libertempo 1.13 from scratch (en dédiant une VM), pour ne pas casser la version actuelle, et bénéficier de la synchronisation avec l'AD, jusqu'à présent sans succès.

Nous avons essayé sur Debian 10.9, Ubuntu 18.04 et 20.04 et ceux plusieurs fois.
Le serveur apache est fonctionnel donc le problème ne vient pas de là.

Nous arrivons sans problème jusqu'à l'installation en suivant rigoureusement votre procédure, l'installation se passe sans problème puisque le Makefile nous indique que Libertempo est installé. Mais lorsque nous lançons la page web local de Libertempo, nous obtenons toujours le même problème, impossible d'afficher l'index.php.

Devant le nombre d'heures passées sur cette installation et les échecs successifs, nous nous sentons impuissants.

Avez-vous une solution à nous proposer ? Ou une procédure alternative, qui pourrait régler notre problème ?

Nous vous en remercions infiniment d'avance.

**Comment by wouldsmina** [comment]
Bonjour,

Un message d'erreur dans les logs d'apache ?

**Comment by Watachibi** [comment]
Bonjour,

Je n'ai aucun fichier etc/log/apache/error.log donc je suppose qu'il n'a jamais été généré par Apache donc qu'Apache n'a jamais eu d'erreur.

**Comment by wouldsmina** [comment]
C'est bizarre qu'il n'y ait pas de fichier error.log. Tu as bien une ligne ErrorLog ?

Si il n'y a vraiment pas d'erreur c'est qu'il doit peut-être y avoir un problème avec les règles rewrite.

**Comment by Watachibi** [comment]
Non
Voici ce que j'ai comme répertoires logs : 
![log](https://user-images.githubusercontent.com/77613584/119148581-e9ef7f80-ba4c-11eb-91bc-fac04610f91e.PNG)

**Comment by Watachibi** [comment]
Qu'entendez-vous par des problèmes avec les règles de rewrite ? Dans le VirtualHost ?

**Comment by wouldsmina** [comment]
Oui, dans le virtualhost.
Les logs apache se trouvent dans /var/logs/apache2.

**Comment by Watachibi** [comment]
Ah, pardon
Voici ce qui se trouve dans les logs erreur d'apache
![logApache](https://user-images.githubusercontent.com/77613584/119150095-69318300-ba4e-11eb-8913-b43bf9f9db79.PNG)
![log2Apache](https://user-images.githubusercontent.com/77613584/119150336-a1d15c80-ba4e-11eb-9100-ad6893c88f02.PNG)

**Comment by wouldsmina** [comment]
Tu n'as pas d'autres fichiers d'erreur ? Vérifie dans ton vhost quel est le nom exact du fichier d'erreur.

**Comment by Watachibi** [comment]
Voici tous les logs :
![logsApache](https://user-images.githubusercontent.com/77613584/119150600-e230da80-ba4e-11eb-8b9c-96abcd88f38c.PNG)

**Comment by wouldsmina** [comment]
OK, donc en effet pas d'erreur... Tu peux copier ton vhost stp ?

**Comment by Watachibi** [comment]
Le voici : 
![vHost](https://user-images.githubusercontent.com/77613584/119151033-481d6200-ba4f-11eb-8d14-b3a0a13f6479.PNG)

**Comment by wouldsmina** [comment]
Ton libertempo est bien accessible à l'adresse http://web-1.13/ ? Tu as bien configuré cela durant l'installation de libertempo ? Si tu ne sais plus, tu peux le voir en tapant make configure.

**Comment by Watachibi** [comment]
Non, il n'est pas accessible.
Le make configure renvoie http://192.168.36.155/web-1.13

**Comment by wouldsmina** [comment]
Alors il ne faut pas mettre de serverName dans ton vhost. Mais le problème ne vient pas de la... J'ai pas d'autre idée pour le moment désolé.

**Comment by Watachibi** [comment]
Est-ce vous souhaitez que je vous envoie des fichiers ? Pour vous permettre une meilleure analyse ?

**Comment by wouldsmina** [comment]
Je vais pas avoir le temps d'aller plus loin pour l'instant... Laisse passer le week-end, j'aurai peut-être une idée d'ici là (tu peux me tutoyer, c'est plus simple ;))

**Comment by Watachibi** [comment]
D'accord, pas de soucis
Merci :)
Je croise les doigts pour que tu aies plus d'idées mardi !
Est-ce que le problème que nous avons est récurrent ?

**Comment by wouldsmina** [comment]
Non, si c'était le cas, j'aurai déjà une solution ;)
Bon week-end.

**Comment by Watachibi** [comment]
Bonjour,

As-tu trouvé une solution éventuelle à notre problème ? 
 Ou des éléments pouvant t'aider à le définir ?

**Comment by wouldsmina** [comment]
Salut,
Peut-être une piste. Est ce que tu héberges d'autres sites sur ce serveur ? Pourrais-tu définir un cname pour ton libertempo et le déclarer dans le vhost ?

**Comment by Watachibi** [comment]
Il n'y a pas d'autres site sur ce serveur apache et le serveur possède une entrée de type hôte(A).
Nous avons déclaré un cname (libertempo) et nous avons modifié le vhost en conséquence. Voici nos résultats :
![erreurWeb3](https://user-images.githubusercontent.com/77613584/119497017-5d063800-bd64-11eb-9028-bb77750d3ab5.png)
![bhostLibe](https://user-images.githubusercontent.com/77613584/119497228-9dfe4c80-bd64-11eb-9cff-cffb481e86fe.PNG)
![erreurWeb](https://user-images.githubusercontent.com/77613584/119497047-6394af80-bd64-11eb-9022-8d1a40f992c1.PNG)
![erreurWeb2](https://user-images.githubusercontent.com/77613584/119497054-64c5dc80-bd64-11eb-9c3b-ead691d00eb3.PNG)

**Comment by wouldsmina** [comment]
Tu as bien activé le vhost ? (a2ensite)

**Comment by Watachibi** [comment]
Évidemment. A moins qu'il ne faille le désactiver puis le réactiver à chaque changement ?

**Comment by wouldsmina** [comment]
Non. Il faut tout de même restart apache.

**Comment by Watachibi** [comment]
Nous arrivons enfin à accéder à la page d’accueillie ! Alléluia !

**Comment by Watachibi** [comment]
Tout fonctionne ! Merci beaucoup !
J'aurais deux dernières questions : 
Est-ce que la connexion LDAP est fonctionnelle ?
et
Est-ce que tu pourrais ajouter tes explications (cname etc) dans le tuto d'installation ?
Je pense que nous ne sommes pas les seuls dans cette situation et que cette explication pourrait en aider beaucoup.

Encore merci et bonne journée à toi :)

**Comment by wouldsmina** [comment]
Cool! 
Je crois que c'est demandé dans les pré-requis. Après je peux pas faire de pas à pas sur ce sujet, tout dépend de l'environnement de production ou est installé libertempo (type de dns, serveur dédié ou mutualisé...).

Pour ldap, il fonctionne très bien, néanmoins il faut bien connaître les paramètres à définir dans la configuration en particulier pour MS AD.

++
