### ISSUE TITLE
Admin > configuration : la variable « url_accueil_conges » ne fonctionne qu'en sous-répertoire du serveur principal

### ISSUE THREAD

**Issue by Prytoegrian** [wouldsmina/Libertempo#96]
Assez compliqué à détailler dans une courte chaîne…

En développement, je me suis posé un vhost afin d'avoir : 
* libertempo/index.php

au lieu de : 
* localhost/suiteDeRepertoiresApache/libertempo/index.php

Toute ma navigation est bonne. Le souci arrive quand je perds ma session. L'URL de la proposition de se reconnecter se base sur la chaîne insérée dans Configuration / 01 Serveur web / url_accueil_conges qui elle se comporte comme un sous-répertoire du DocumentRoot d'apache.

Ce qui m'est arrivé en dev pourrait arriver en prod, je propose donc de laisser la main à l'utilisateur de rentrer la totalité de la chaîne de l'URL, protocole compris pour autoriser toutes les architectures possibles.

**Comment by wouldsmina** [comment]
Même avec l'url complete (avec http://) dans url_accueil_conges?

**Comment by Prytoegrian** [comment]
Tsss, désolé, j'ai manqué de rigueur dans les tests
