### ISSUE TITLE
Uncaught mysqli_sql_exception: Unknown column type_natif

### ISSUE THREAD

**Issue by exyl** [wouldsmina/Libertempo#960]
Bonjour,

Je viens de faire la mise à jour depuis Kantra vers Nooma.
Quelques difficultés, mais cela fonctionne maintenant.
Par contre, le bouton Calendrier me donne une page vide.
Et cette erreur dans le fichier error.log d'apache ;
`PHP Fatal error:  Uncaught Exception: Donn\xc3\xa9e de configuration inexistante in /var/www/html/intranet/libertempo/App/Libraries/Configuration.php:481\nStack trace:\n#0 /var/www/html/intranet/libertempo/App/Libraries/Configuration.php(406): App\\Libraries\\Configuration->getValeur('afficher_types_...', '12_Fonctionneme...')\n#1 /var/www/html/intranet/libertempo/App/Libraries/Configuration.php(389): App\\Libraries\\Configuration->getGroupeFonctionnementEtablissementValeur('afficher_types_...')\n#2 /var/www/html/intranet/libertempo/calendrier.php(19): App\\Libraries\\Configuration->getQuiAfficheTypeCongesCalendrier()\n#3 /var/www/html/intranet/libertempo/calendrier.php(127): canSessionVoirTypesConges(Array, Object(App\\Libraries\\Configuration))\n#4 /var/www/html/intranet/libertempo/Public/index.php(52): require_once('/var/www/html/i...')\n#5 {main}\n  thrown in /var/www/html/intranet/libertempo/App/Libraries/Configuration.php on line 481, referer: http://libertempo.eodom.net/config/type_absence`

J'ai essayé d'ajouter un nouveau type de congé : page blanche
Et cette erreur dans le error.log : 
`PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'type_natif' in 'field list' in /var/www/html/intranet/libertempo/includes/SQL.php:151\nStack trace:\n#0 /var/www/html/intranet/libertempo/includes/SQL.php(151): mysqli->real_query('INSERT INTO con...')\n#1 [internal function]: includes\\Database->query('INSERT INTO con...')\n#2 /var/www/html/intranet/libertempo/includes/SQL.php(78): call_user_func_array(Array, Array)\n#3 /var/www/html/intranet/libertempo/config/Fonctions.php(373): includes\\SQL::__callStatic('query', Array)\n#4 /var/www/html/intranet/libertempo/config/config_type_absence.php(23): config\\Fonctions::commit_ajout(Array)\n#5 /var/www/html/intranet/libertempo/config/index.php(60): include_once('/var/www/html/i...')\n#6 /var/www/html/intranet/libertempo/Public/index.php(56): require_once('/var/www/html/i...')\n#7 {main}\n  thrown in /var/www/html/intranet/libertempo/includes/SQL.php on line 151, referer: http://libertempo.eodom.net/config/type_absence`

![image](https://user-images.githubusercontent.com/28304217/119518057-76b17a80-bd78-11eb-93c6-e55e3d9a3587.png)

Étapes de la reproduction du comportement :
méthode de connexion  : ldap

**Comportement attendu**
Une description claire et concise de l'attendu.

**Copies d'écran**
Si applicable, ajoutez des captures d'écran pour aider à expliquer le problème.

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : Windows 10
 - Navigateur et version : Chrome Version 90.0.4430.212
 - Erreur dans la console : RAS

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : Centos 7
 - Version de Libertempo : 1.13
 - Version MySQL et PHP : PHP7.4 Mysql Ver 14.14 Distrib 5.6.50,
 - Erreur dans le log du serveur : voir plus haut

**Comment by wouldsmina** [comment]
Bonjour,

Il manque un champ dans une table... La mise à jour a eu un raté on dirait. Je peux pas te dire tout de suite quel requête il faut rejouer tout de suite, désolé. Je te tiens au courant rapidement.

**Comment by wouldsmina** [comment]
Il manque ce patch : https://www.github.com/libertempo/web/tree/develop/App%2FPatchs%2FMaj%2F1.12.1.sql

mais il y a peut-être d'autres patch qui ne sont pas passés. Je te conseille de recommencer la mise à jour.

**Comment by exyl** [comment]
ca a marché pour l'ajout de type de congé
Mais le calendrier reste vide

Message d'erreur dans error_log
`PHP Fatal error:  Uncaught Exception: Donn\xc3\xa9e de configuration inexistante in /var/www/html/intranet/libertempo/App/Libraries/Configuration.php:481\nStack trace:\n#0 /var/www/html/intranet/libertempo/App/Libraries/Configuration.php(406): App\\Libraries\\Configuration->getValeur('afficher_types_...', '12_Fonctionneme...')\n#1 /var/www/html/intranet/libertempo/App/Libraries/Configuration.php(389): App\\Libraries\\Configuration->getGroupeFonctionnementEtablissementValeur('afficher_types_...')\n#2 /var/www/html/intranet/libertempo/calendrier.php(19): App\\Libraries\\Configuration->getQuiAfficheTypeCongesCalendrier()\n#3 /var/www/html/intranet/libertempo/calendrier.php(127): canSessionVoirTypesConges(Array, Object(App\\Libraries\\Configuration))\n#4 /var/www/html/intranet/libertempo/Public/index.php(52): require_once('/var/www/html/i...')\n#5 {main}\n  thrown in /var/www/html/intranet/libertempo/App/Libraries/Configuration.php on line 481, referer: http://libertempo.eodom.net/hr/page_principale`

**Comment by wouldsmina** [comment]
Tu as bien fait une make update après avoir mis à jour le code source ?

**Comment by exyl** [comment]
oui oui.
par contre le make reinstall veut supprimer la base, donc je n'ai pas été plus loin.

**Comment by wouldsmina** [comment]
Salut, 
Tu peux restaurer la base de données et refaire un update ?

**Comment by exyl** [comment]
Juste, voici ce qui se passe quand je lance un make update : 
```
[root@pbbsrvwww02 libertempo]# make update
php composer.phar install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package codacy/coverage is abandoned, you should avoid using it. No replacement was suggested.
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
npm update
App/Tools/savedb
#!/usr/bin/env php
Sauvegarde…
PHP Notice:  Trying to access array offset on value of type null in /var/www/html/intranet/libertempo/App/Tools/libraries on line 103
Sauvegarde de la DB courante…
App/Tools/update
#!/usr/bin/env php
Mise à jour…
Contrôles généraux…
PHP Notice:  Trying to access array offset on value of type null in /var/www/html/intranet/libertempo/App/Tools/libraries on line 103
Configuration de l'API
Application des nouveaux patches…
Aucune mise à jour disponible

```

**Comment by wouldsmina** [comment]
Peux-tu regarder ce qu'il y a dans conge_appli.version_last_maj ?

**Comment by exyl** [comment]
Il n'y a pas le champ :
![image](https://user-images.githubusercontent.com/28304217/120168409-1a7aaa80-c1ff-11eb-81b8-dbf1b4bed759.png)

**Comment by wouldsmina** [comment]
OK. Je te conseille de restaurer la bdd et de refaire l'update. Envoie moi le résultat si tu as encore des erreurs. Si la restauration n'est pas envisageable, tu peux essayer de passer les patches manuellement mais il faut vraiment que tu sois prudent... Bon courage :)

**Comment by exyl** [comment]
Quand tu dis restaurer la bdd, c'est faire un backup, un make reinstall, puis la restauration ?
Car malheureusement, la plateforme a été utilisé depuis quelques jours, et certains ont posé des congés.

**Comment by wouldsmina** [comment]
Alors tu n'as pas d'autres choix que d'éplucher chaque patch et exécuter ceux qui te manque.

**Comment by exyl** [comment]
tu peux me donner l'url des patchs stp ?

**Comment by wouldsmina** [comment]
https://www.github.com/libertempo/web/tree/develop/App%2FPatchs

Ou dans ton dossier App/patchs

**Comment by exyl** [comment]
Top merci, j'ai passé les 4 derniers patchs, ca fonctionne.
