### ISSUE TITLE
Affichage liste déroulante importation utilisateur

### ISSUE THREAD

**Issue by Watachibi** [wouldsmina/Libertempo#961]
Bonjour,

J'essaie actuellement d'importer des utilisateurs depuis le LDAP, cependant l'affichage de la liste déroulante rend ce travail difficile.
![liste](https://user-images.githubusercontent.com/77613584/119629073-f89fb300-be0d-11eb-921e-01e96bf8c2ce.png)

J'aimerais que l'affichage donne cela :
![listeCorrect](https://user-images.githubusercontent.com/77613584/119629734-94312380-be0e-11eb-8234-4ac3e4642257.PNG)

Est-ce possible de le modifier rapidement ?
Si non, peux-tu m'indiquer où effectuer les modifications ? (J'ai modifier via l'inspecteur pour le rendu de ce que j'aimerais)

Merci d'avance

**Comment by wouldsmina** [comment]
Salut, 
Donne moi la modification que tu as fait dans l'inspecteur, je ferai la modification dans le code. Tu utilises quel navigateur ?

**Comment by Watachibi** [comment]
J'ai testé chrome, firefox et edge.
Voila la modification que j'ai faite.
![modification](https://user-images.githubusercontent.com/77613584/119650191-d31da400-be23-11eb-9b8e-d355f19cfa8b.PNG)

**Comment by Watachibi** [comment]
Est-ce que tu pourras m'expliquer la modification que tu as effectué dans le code ?

**Comment by wouldsmina** [comment]
> J'ai testé chrome, firefox et edge.
> Voila la modification que j'ai faite.
> ![modification](https://user-images.githubusercontent.com/77613584/119650191-d31da400-be23-11eb-9b8e-d355f19cfa8b.PNG)
> 

C'est pas évident à voir comme ça. Tu peux copier/coller le code source avant et après modification stp ?

Edit : je viens seulement de voir que c'était dans le CSS. Merci.

**Comment by Watachibi** [comment]
La modifications que j'ai apportées sont temporaires.

Je n'ai pas compris ce que tu souhaitais finalement ?

**Comment by wouldsmina** [comment]
J'ai ce qu'il me faut. Je te tiens au courant.

**Comment by Watachibi** [comment]
Ok, merci !

**Comment by wouldsmina** [comment]
Merci de vérifier que ce patch : https://github.com/libertempo/web/pull/970/files corrige définitivement le problème.
++
