### ISSUE TITLE
Import de masse

### ISSUE THREAD

**Issue by Watachibi** [wouldsmina/Libertempo#962]
Bonjour,

Puisqu'il est nécessaire que l'utilisateur soit au préalable dans la base de données de Libertempo pour qu'il puisse s'y connecter :
Est-ce qu'une fonctionnalité d'import de masse depuis le LDAP existe ?
Si non, est-il possible d'ajouter la fonctionnalité d'importer massivement des utilisateurs depuis le LDAP ?

Ou, est-il possible d'ajouter la fonctionnalité d'ajouter automatiquement un utilisateur à Libertempo lors de sa première connexion avec ses identifiants LDAP ?

Merci beaucoup d'avance

**Comment by wouldsmina** [comment]
Non, il n'est malheureusement pas possible d'importer en masse. La création d'un utilisateur nécessite de paramétrer le solde des congés et le groupe auquel appartient l'utilisateur, c'est pourquoi je n'ai pas implémenté d'import massif.

**Comment by Watachibi** [comment]
D'accord, je comprends
