### ISSUE TITLE
Variables texte et langue anglaise

### ISSUE THREAD

**Issue by cyberesprit** [wouldsmina/Libertempo#97]
Bonjour,

1. Certains textes sont affichés en variable comme par exemple : **divers_date_debut** ou **divers_date_fin** ou **NB_Days_Taken** …
2. Malgré que l'installation soit en FR_fr, que dans l'administration ce soit FR_fr et que le navigateur est en FR_fr et FR, l'application reste en anglais.

Testé sur des installations toutes neuves avec Libertempo 1.7.0 et la version de github 1.7.1

Une idée ? merci ;-)

Librement

**Comment by cyberesprit** [comment]
Je vais vérifier si ça vient de là, mais j'ai ces messages dans les journaux :

```
[Tue Jan 26 11:52:38.384918 2016] [:error] [pid 12] [client 172.17.0.10:57456] PHP Warning:  mysqli::query(): Couldn't fetch Database in /var/www/libertempo/include/sql.class.php on line 137
[Tue Jan 26 11:52:38.384982 2016] [:error] [pid 12] [client 172.17.0.10:57456] PHP Warning:  Database::query(): Couldn't fetch Database in /var/www/libertempo/include/sql.class.php on line 140
[Tue Jan 26 11:52:38.385017 2016] [:error] [pid 12] [client 172.17.0.10:57456] PHP Fatal error:  Call to a member function fetch_row() on null in /var/www/libertempo/include/lang_profile.php on line 37
[Tue Jan 26 12:12:51.579784 2016] [:error] [pid 11] [client 172.17.0.10:57870] PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /var/www/libertempo/include/fonction.php on line 207, referer: https://
```

**Comment by Prytoegrian** [comment]
Salut, 

Ça ressemble à un problème de trad. Tu as la liste exhaustive des textes qui font ça ?

**Comment by cyberesprit** [comment]
Je pense avoir compris pour l'anglais, si le serveur est lui même par défaut en EN_us, alors l'application reste en EN_us. Par contre si le serveur est en FR_fr, le FR_fr et EN_us fonctionnent. Est-ce un bug ?

Je viens de faire une 3ème installation sur un serveur FR_fr et tout est bon, c'est en français et les variables ne sont plus là. Donc à priori le problème de traduction n'existe qu'en anglais (hors autre langue non testée).

Pour l'anglais il y a au moins celles-ci :

divers_date_debut
divers_date_fin
NB_Days_Taken
config_comment_url_accueil_conges
test_mail_config
test_mail_comment
mail_new_demande
mail_new_demande_resp_absent
mail_valid_conges
mail_refus_conges
mail_annul_conges
mail_prem_valid_conges

et il y  « Retour mode admin » qui reste en français.

**Comment by wouldsmina** [comment]
J'ai pas ces problèmes de trad en anglais. Ce doit aussi venir de conf serveur.

Oui, c'est un bug et tu as trouvé un début de solution. Merci.

**Comment by Prytoegrian** [comment]
Résumé des épisodes précédents : 
Pour ses trads, l'appli utilise `gettext` qui se base sur la locale définie par le système pour choisir quelle langue de trad choisir pour une clé donnée. Via la sélection de la connexion, nous forçons la locale. Problème : si la locale sélectionnée n'existe pas sur le système courant, alors il y a un fallback sur la langue anglaise. (Dites-moi si je me trompe).

Il n'y a pas de solution simple et rapide pour résoudre cela, le mieux étant de se rendre complètement indépendant du système, a fortiori vu que gettext est une extension de php qui n'est pas forcément installée.

**Comment by wouldsmina** [comment]
si c'est lié à gettext, la solution la plus simple reste de s'assurer que le serveur dispose de la locale FR_fr.
