### ISSUE TITLE
Connexion bloqué par cURL

### ISSUE THREAD

**Issue by Watachibi** [wouldsmina/Libertempo#973]
Bonjour,

J'ai passé le site hébergeant le libertempo en HTTPS grâce à un certificat privé délivré par Global Sign.
Depuis, je n'arrive plus à me connecter à Libertempo. J'obtients toujours les mêmes erreurs (J'ai épluché les forum en essayant les solutions proposées, malheureusement sans succès) que voici : 
![Erreur_libertempo](https://user-images.githubusercontent.com/77613584/121181230-11728480-c862-11eb-9eb7-f7ca0e204150.png)
L'autre étant l'erreur 60.
As-tu une quelconque idée de comment résoudre ce problème ?

Merci d'avance pour ta réponse et le temps que tu y auras consacré.

Cordialement

**Comment by wouldsmina** [comment]
Salut,

De toute évidence tu as un problème avec l'autorité de certification GlobalSign. Tu dois copier le CA dans /etc/ssl/certs/ et exécuter la commande d'update des CA... que j'ai oublié 😅
Je crois que ça commence par update-ca...

Curl est capricieux sur ce point. Bon courage.

**Comment by Watachibi** [comment]
Ok, déjà ça me donne une meilleure piste que ce que j'ai pu avoir qui me demandait de télécharger et de modifier les php.ini.

**Comment by Watachibi** [comment]
J'ai essayé ta technique.
ça semble résoudre l'erreur 70 mais maintenant je me retrouve avec cette erreur :
![pb_libe](https://user-images.githubusercontent.com/77613584/121310971-39b2bf80-c904-11eb-8e5a-59f6c00225ee.png)

Si tu as une idée de ce qui peut bloquer ?

**Comment by wouldsmina** [comment]
C'est parce que tu n'as pas saisi l'URL complète (https://libertempo.ton.domaine)

**Comment by Watachibi** [comment]
Encore une fois, merci beaucoup !
Le problème est résolu (La documentation par rapport à ce type d'erreur sur internet est ignoble)

Bonne journée et merci encore
