### ISSUE TITLE
Clôture impossible

### ISSUE THREAD

**Issue by exyl** [wouldsmina/Libertempo#974]
Hello,

J'essaie de clôturer l'année (menu clôture d'exercice, bouton Valider la cloture globale) et ca ne passe pas.
Page blanche, et aucun changement.
J'ai cette erreur dans le error.log : 
`[Thu Jun 17 14:32:17.626055 2021] [php7:error] [pid 38506] [client 192.168.2.1:57704] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '5 WHERE su_login = "askoura" AND su_abs_id = 1' at line 2 in /var/www/html/intranet/libertempo/includes/SQL.php:151\nStack trace:\n#0 /var/www/html/intranet/libertempo/includes/SQL.php(151): mysqli->real_query('UPDATE conges_s...')\n#1 [internal function]: includes\\Database->query('UPDATE conges_s...')\n#2 /var/www/html/intranet/libertempo/includes/SQL.php(114): call_user_func_array(Array, Array)\n#3 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(76): includes\\SQL->__call('query', Array)\n#4 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(59): App\\ProtoControllers\\HautResponsable\\ClotureExercice::setSoldeEmploye('askoura', 1, -12,5, Object(includes\\SQL))\n#5 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(26): App\\ProtoContro in /var/www/html/intranet/libertempo/includes/SQL.php on line 151, referer: http://libertempo.eodom.net/hr/cloture_exercice
`

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : Win 10
 - Navigateur et version :  Chrome 91.
 - Erreur dans la console : pas d'erreur

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : Centos 7
 - Version de Libertempo : 1.13
 - Version MySQL et PHP : PHP 7.4.19 & mysql  Ver 14.14 Distrib 5.6.50, for Linux (x86_64) using  EditLine wrapper
 - Erreur dans le log du serveur : Voir plus haut

**Comment by wouldsmina** [comment]
Salut,
C'est un bug qu'il faut que je corrige. Pour contourner le problème essaye d'activer les congés exceptionnels et modifie l'utilisateur askoura.

**Comment by exyl** [comment]
Salut
Qu'est ce que tu entends par activer les CP exceptionnels ?

**Comment by wouldsmina** [comment]
Regarde dans la configuration globale de libertempo ;)

**Comment by exyl** [comment]
gestion_conges_exceptionnels est à True

**Comment by wouldsmina** [comment]
Ah ! Et lorsque tu modifies l'utilisateur as tu des champs vide ?

**Comment by exyl** [comment]
Non, soit 0.00 soit des valeurs positives/négatives

**Comment by exyl** [comment]
On peut faire un teams / teamviewer ou autre si tu veux pour checker

**Comment by wouldsmina** [comment]
Pas ce soir, plutôt demain. Je vais essayer de voir ce qu'il se passe tout à l'heure. On se tient au jus

**Comment by exyl** [comment]
ok.

**Comment by wouldsmina** [comment]
Re,
Pas eu beaucoup de temps cet après-midi, désolé. Pourrais tu me dire ce que retourne le debug, en ajoutant dans le fichier [App/ProtoControllers/HautResponsable/ClotureExercice.php](https://github.com/libertempo/web/blob/1.13/App/ProtoControllers/HautResponsable/ClotureExercice.php#L76)  au dessus de la ligne 76 la ligne suivante :  `ddd($req) ;`
On verra ce que contient la requete exactement et donc comprendre pourquoi ça plante.

Pour que le debug s'affiche tu dois passer en mode debug dans le fichier cfg/env.php.

**Comment by exyl** [comment]
Dans le fichier cfg/env.php, j'ai ca : 
define('ENV', ENV_PROD);
define('LOGGER_TOKEN', '');

Comment je passe en mode DEBUG ?

**Comment by wouldsmina** [comment]
Remplace ENV_PROD par ENV_DEBUG

**Comment by exyl** [comment]
voici le retour dans error.log : 
PHP Warning:  Use of undefined constant ENV_DEBUG - assumed 'ENV_DEBUG' (this will throw an Error in a future version of PHP) in /var/www/html/intranet/libertempo/cfg/env.php on line 2, referer: http://libertempo.eodom.net/hr/cloture_exercice

[Wed Jun 23 16:30:42.528219 2021] [php7:error] [pid 1825] [client 192.168.2.1:51212] PHP Fatal error:  Uncaught Error: Call to undefined function App\\ProtoControllers\\HautResponsable\\ddd() in /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php:76\nStack trace:\n#0 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(59): App\\ProtoControllers\\HautResponsable\\ClotureExercice::setSoldeEmploye('aebora', 1, '30.00', Object(includes\\SQL))\n#1 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(26): App\\ProtoControllers\\HautResponsable\\ClotureExercice::updateSoldesEmploye('aebora', Array, 'cl\\xC3\\xB4ture exerci...', Object(includes\\SQL), Object(App\\Libraries\\Configuration))\n#2 /var/www/html/intranet/libertempo/hr/hr_cloture_year.php(28): App\\ProtoControllers\\HautResponsable\\ClotureExercice::traitementClotureEmploye(Array, Array, NULL, Object(includes\\SQL), Object(App\\Libraries\\Configuration))\n#3 /var/www/html/intranet/libertempo/hr/hr_index.php(74): require_once('/var/www/html/i...')\n#4 /var/www/html/intra in /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php on line 76, referer: http://libertempo.eodom.net/hr/cloture_exercice

**Comment by wouldsmina** [comment]
Excuse, c'est ENV_DEV qu'il faut mettre

**Comment by exyl** [comment]
`Fatal error: Uncaught Error: Call to undefined function App\ProtoControllers\HautResponsable\ddd() in /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php:76 Stack trace: #0 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(59): App\ProtoControllers\HautResponsable\ClotureExercice::setSoldeEmploye('aebora', 1, '0.00', Object(includes\SQL)) #1 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(26): App\ProtoControllers\HautResponsable\ClotureExercice::updateSoldesEmploye('aebora', Array, 'cl\xC3\xB4ture exerci...', Object(includes\SQL), Object(App\Libraries\Configuration)) #2 /var/www/html/intranet/libertempo/hr/hr_cloture_year.php(28): App\ProtoControllers\HautResponsable\ClotureExercice::traitementClotureEmploye(Array, Array, NULL, Object(includes\SQL), Object(App\Libraries\Configuration)) #3 /var/www/html/intranet/libertempo/hr/hr_index.php(74): require_once('/var/www/html/i...') #4 /var/www/html/intran in /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php on line 76`

**Comment by exyl** [comment]
J'ai l'impression que les personnes à qui on a modifié les soldes (ma rh qui voulait mettre à jour), cela a créé des lignes en plus dans la table conges_solde_user

**Comment by exyl** [comment]
Quand je filtre sur le compte aebora :
su_id	su_login	su_abs_id	su_nb_an	su_solde	su_reliquat
89	aebora	9	0	0	0
90	aebora	8	0	0	0
100	aebora	7	0	0	0
101	aebora	1	0	30	0
157	aebora	1	30	30	0
158	aebora	7	0	0	0
159	aebora	8	0	0	0
160	aebora	9	0	0	0

**Comment by wouldsmina** [comment]
Et le debug de la requête donne quoi ?

**Comment by exyl** [comment]
je te l'ai mis au-dessus.
Et j'ai ca aussi dans error_log :
[Wed Jun 23 16:44:33.266720 2021] [php7:error] [pid 1825] [client 192.168.2.1:61175] PHP Fatal error:  Uncaught Error: Call to undefined function App\\ProtoControllers\\HautResponsable\\ddd() in /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php:76\nStack trace:\n#0 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(59): App\\ProtoControllers\\HautResponsable\\ClotureExercice::setSoldeEmploye('aebora', 1, '0.00', Object(includes\\SQL))\n#1 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(26): App\\ProtoControllers\\HautResponsable\\ClotureExercice::updateSoldesEmploye('aebora', Array, 'cl\\xC3\\xB4ture exerci...', Object(includes\\SQL), Object(App\\Libraries\\Configuration))\n#2 /var/www/html/intranet/libertempo/hr/hr_cloture_year.php(28): App\\ProtoControllers\\HautResponsable\\ClotureExercice::traitementClotureEmploye(Array, Array, NULL, Object(includes\\SQL), Object(App\\Libraries\\Configuration))\n#3 /var/www/html/intranet/libertempo/hr/hr_index.php(74): require_once('/var/www/html/i...')\n#4 /var/www/html/intran in /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php on line 76, referer: http://libertempo.eodom.net/hr/cloture_exercice

**Comment by wouldsmina** [comment]
Ah, il y a un problème avec la fonction de debug :/

Mais je commence à comprendre ce qu'il se passe... Tu dois avoir des utilisateurs qui n'ont pas de solde pour certains congés. C'était pour cette raison que je t'avais demandé de modifier l'utilisateur qui bloquait... Mais il y en a certainement plusieurs. Pour corriger ce bug définitivement, je me demande si il ne serait pas possible d'utiliser REPLACE au lieu de UPDATE dans la requête sql de mise à jour du solde. Tu as une sauvegarde de ta bdd ou une instance de test ?

**Comment by exyl** [comment]
Je n'ai pas d'instance de test.
Et j'ai un backup, mais comme c'est en prod, les users peuvent faire une demande à tout moment.

**Comment by exyl** [comment]
faut-il que je repasse sur chaque user ?

**Comment by wouldsmina** [comment]
Je crains que oui... J'espère que tu n'en as pas trop.

**Comment by exyl** [comment]
non, ca va le faire.
Donc, je passe sur chaque user, et je valide leur solde, même sans changement, c'est ca ?

**Comment by exyl** [comment]
Je suis repassé sur chaque user, j'ai validé leur solde. 
Même problème.

**Comment by wouldsmina** [comment]
Mince ! C'est bizarre... Peux tu regarder dans la bdd dans la table des soldes si chaque utilisateur a bien un solde pour chaque id de congé ?

**Comment by exyl** [comment]
Oui, tout le monde a un solde pour chaque type.
J'ai vérifié aussi que quelqu'un n'est pas un solde pour un type qui n'existerait plus.

Par contre, est-ce normal que pour certains, j'ai plusieurs entrées même su_login + même su_abs_id

**Comment by wouldsmina** [comment]
Non, je pense pas que ce soit normal.

**Comment by exyl** [comment]
tu veux prendre la main pour regarder ?

**Comment by wouldsmina** [comment]
Désolé, je vais vraiment pas pouvoir... Coupure électrique cette nuit au boulot :s

**Comment by exyl** [comment]
aie, je compatis.

Du coup, je supprime les lignes en trop (les premières en terme d'index et je conserve les dernières) ?

**Comment by wouldsmina** [comment]
Si les soldes sont identiques pas de soucis, supprime celui que tu veux, par contre si il y a une différence fait gaffe de pas te tromper

**Comment by exyl** [comment]
bad news
J'ai supprimé toutes les lignes en trop.
Il ne reste plus qu'une ligne par personne et par type.
J'ai testé la clôture et : 
`Fatal error: Uncaught Error: Call to undefined function App\ProtoControllers\HautResponsable\ddd() in /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php:76 Stack trace: #0 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(59): App\ProtoControllers\HautResponsable\ClotureExercice::setSoldeEmploye('aebora', 1, '30.00', Object(includes\SQL)) #1 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(26): App\ProtoControllers\HautResponsable\ClotureExercice::updateSoldesEmploye('aebora', Array, 'cl\xC3\xB4ture exerci...', Object(includes\SQL), Object(App\Libraries\Configuration)) #2 /var/www/html/intranet/libertempo/hr/hr_cloture_year.php(28): App\ProtoControllers\HautResponsable\ClotureExercice::traitementClotureEmploye(Array, Array, NULL, Object(includes\SQL), Object(App\Libraries\Configuration)) #3 /var/www/html/intranet/libertempo/hr/hr_index.php(74): require_once('/var/www/html/i...') #4 /var/www/html/intra in /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php on line 76`

Je viens de faire un test.
Dès que je mets à jour une fiche user, cela créé des doublons.
Je passe de 4 lignes pour un user à 8
Le Pb vient peut être de là ?

**Comment by wouldsmina** [comment]
Retire la ligne de debug que je t'avais demandé d'ajouter (ddd() ;)

**Comment by exyl** [comment]
J'ai cette erreur : 
`Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '5 WHERE su_login = "askoura" AND su_abs_id = 1' at line 2 in /var/www/html/intranet/libertempo/includes/SQL.php:151 Stack trace: #0 /var/www/html/intranet/libertempo/includes/SQL.php(151): mysqli->real_query('UPDATE conges_s...') #1 [internal function]: includes\Database->query('UPDATE conges_s...') #2 /var/www/html/intranet/libertempo/includes/SQL.php(114): call_user_func_array(Array, Array) #3 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(76): includes\SQL->__call('query', Array) #4 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(59): App\ProtoControllers\HautResponsable\ClotureExercice::setSoldeEmploye('askoura', 1, -12,5, Object(includes\SQL)) #5 /var/www/html/intranet/libertempo/App/ProtoControllers/HautResponsable/ClotureExercice.php(26): App\ProtoContro in /var/www/html/intranet/libertempo/includes/SQL.php on line 151`

**Comment by exyl** [comment]
Je vois ca :`.... ercice::setSoldeEmploye('askoura', 1, -12,5, Object(includes\SQL)) ....`
Ca ne serait pas à cause des virgules ??

**Comment by wouldsmina** [comment]
Ah oui ! Il devrait y avoir des quotes autour de -12,5 !

**Comment by wouldsmina** [comment]
Mais je viens de regarder la fonction, il y a bien des quotes dans la requête sql...

**Comment by wouldsmina** [comment]
J'ai un doute... Dans [App/ProtoControllers/HautResponsable/ClotureExercice.php](https://github.com/libertempo/web/blob/1.13/App/ProtoControllers/HautResponsable/ClotureExercice.php#L73) ligne 76 remplace : 
```PHP
                  SET su_solde = ' . $soldeFutur .
                ' WHERE su_login = "' . $sql->quote($employe) .
```
PAR : 
```PHP
                  SET su_solde = "' . $soldeFutur .
                '" WHERE su_login = "' . $sql->quote($employe) .
```

**Comment by wouldsmina** [comment]
Je pense à un autre truc, je sais plus quel format fonctionne en sql 12.5 ou 12,5 ou les 2 ?

**Comment by exyl** [comment]
C'est un champ decimal, j'ai beau mettre un point, il remet une virgule.
Je vais faire la modif dans le code et reviens vers toi

**Comment by exyl** [comment]
Changement d'exercice effectué.

C'est bon ! 👍 
Merci :)

**Comment by wouldsmina** [comment]
Bien joué ! Tu peux me dire ce que tu as modifié ?
