### ISSUE TITLE
Docker traduction variable

### ISSUE THREAD

**Issue by cyberesprit** [wouldsmina/Libertempo#99]
Bonjour,

J'ai fini par mettre mon installation de Libertempo dans un conteneur avec docker et il y a un problème partiel (mais majoritaire) de traduction.

C'est en fr_FR par défaut, mais la plupart de texte reste en forme de variable.

Par exemple, à la mire de connexion, le champs mot de passe contient bien "Mot de passe", par contre le champs login contient "divers_login_maj_1" et le bouton de connexion contient "form_submit". Et c'est pareil pour presque toutes les variables textes une fois connecté.

Ça ne fait pas le même problème avec une installation hors conteneur. D'ailleurs c'est une copie d'installation hors conteneur.

Une piste ? merci ;-)

**Comment by Prytoegrian** [comment]
Si tu joues avec docker on va être pote ! :-p

Tu as résolu ton problème de #97 ? Parce que ça y ressemble étrangement. La langue du serveur (docker) est EN_us et la langue de l'appli est FR_fr c'est ça ?
Le seul distinguo dans ton process c'est la création de toute pièce d'un serveur dans docker (ses langues propres et tout le bazar). Je t'invite donc à regarder par là.

Essaie de traquer la fonction de trad aussi, voir si elle ne s'emmêle pas les pinceaux entre les différentes locales.

**Comment by cyberesprit** [comment]
Pour le #97, vu que j'ai fait l'installation au final sur un serveur en fr_FR, pour moi c'est bon, mais pas sur un serveur en en_US. Et vu que mon installation était prévu pour un conteneur au final c'est tout bon. Donc c'est résolu à moitié ;-)

Je vais vérifier la langue par défaut de mon conteneur, sauf que là le problème est légèrement différent car il se met en français par défaut, ce qui n'est pas le cas quand le serveur est en_US.

Par contre comment je peux traquer la fonction de trad ?

**Comment by Prytoegrian** [comment]
La fonction de trad se nomme `_()`, je ne saurais pas dire où elle est vu que j'ai pas mon IDE sous le coude, par contre tu peux regarder du côté de `includes/lang_profile.php`  et faire des `var_dump()` dans tous les sens pour étudier le comportement de `$loadLang`.

Je m'y perds, tu peux faire une liste des comportements bizarres selon les différentes conf ?

| Conf serveur | Conf Appli | État |
|-----|----|-----|
| FR_fr | FR_fr| ?
| FR_fr | EN_us | ?
| EN_us | FR_fr | ?
| EN_us | EN_us | ?

**Comment by cyberesprit** [comment]
Dans docker, le retour de la commande « locale » est :

```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

Je me dit que si par défaut ce n'est pas défini, c'est probablement en_US ou en_EN.

Je vais tester les différentes configuration, je peux déjà répondre à celles ci hors conteneur :

Conf serveur |	Conf Appli |	État
---------------- | ----------- | ----------
FR_fr |	 	FR_fr |	 	OK
FR_fr |	 	EN_us |	 	?
EN_us |	 	FR_fr |	 	Reste en anglais, manque certaines variables
EN_us |	 	EN_us |	 	Manque certaines variables (à vérifier)

**Comment by Prytoegrian** [comment]
Il est possible que tu aies raison mais sans pouvoir l'affirmer, il me manque des connaissances en sytème. Quoiqu'il en soit, l'appli est censée écraser complètement les locales pour poser les siennes, je comprends donc pas bien ce qu'il se passe. Y-a plus qu'à dégainer du `var_dump()` :-)

**Comment by cyberesprit** [comment]
J'ai placé des echo et un var_dump dans include/lang_profile.php :

```
_REQUEST['lang'] >
_SESSION['lang'] >
lang > fr_FR
LoadLang > false
setlocale > C
LoadLang > false
LoadLang > false
LoadLang > false
LOCALE_PATH > locale/


### FIN DE FICHIER ###

lang > fr_FR
_() > NULL 
```

Hélas ça ne m'aide pas beaucoup ;-)
Je poursuis !

**Comment by cyberesprit** [comment]
J'en ai rajouter :

```
LANG=fr_FR
LC_ALL=
_REQUEST['lang'] >
_SESSION['lang'] >
lang > fr_FR // $lang est définie grâce à la conf de la bdd
LoadLang > false
setlocale > C
LC_ALL=
LoadLang > false
LC_ALL=
LoadLang > false
LC_ALL=
LoadLang > false
LOCALE_PATH > locale/


### FIN DE FICHIER ###

lang > fr_FR
_() > NULL 
```

À priori le code n'arrive jamais à configurer LC_ALL, parce-que si je ne me trompe pas il essai de la modifier avec setlocale().

**Comment by cyberesprit** [comment]
Voilà ce que j'ai dans les journaux d'erreur apache :

```
==> /var/log/apache2/error.log <==
[Wed Feb 03 10:21:33.197968 2016] [:error] [pid 59] [client 172.17.0.10:40432] PHP Notice:  Undefined index: lang in /var/www/libertempo/include/lang_profile.php on line 52
[Wed Feb 03 10:21:33.198069 2016] [:error] [pid 59] [client 172.17.0.10:40432] PHP Notice:  Undefined variable: _SESSION in /var/www/libertempo/include/lang_profile.php on line 55
[Wed Feb 03 10:21:33.198203 2016] [:error] [pid 59] [client 172.17.0.10:40432] PHP Warning:  _() expects exactly 1 parameter, 0 given in /var/www/libertempo/include/lang_profile.php on line 132

```

Alors que je ne suis pas connecté, à la mire de connexion.

**Comment by cyberesprit** [comment]
La ligne 132 contient mon var_dump de _()

**Comment by Prytoegrian** [comment]
… J'arrive pas à reproduire, ça me fait chier pour toi. `setLocale` dit qu'elle retourne false si « the locale functionality is not implemented on your platform, the specified locale does not exist or the ~~category name is invalid~~. »

Donc c'est un problème système. Pour vérifier que la locale que tu cherches à utiliser est bien disponible, fais `locale -a`, je t'invite si ce n'est pas le cas à jouer avec [l'installateur](http://ubuntuforums.org/showthread.php?t=196414)

**Comment by cyberesprit** [comment]
Le retour de la commande « locale -a » dans le conteneur :

```
C
C.UTF-8
POSIX
```

Le même retour sur ma machine directement :

```
C
en_US.utf8
fr_FR.utf8
POSIX
```

Je vais voir en modifiant les variables système.

Je viens de voir, je vais rajouter les lignes suivantes dans le Dockerfile :

```
RUN  apt-get install -y language-pack-fr-base
ENV  LANG fr_FR.UTF-8
```

c'est une base ubuntu.

**Comment by cyberesprit** [comment]
C'est bon, la solution avec un conteneur sous Docker est d'ajouter dans le Dockerfile les lignes suivantes :

```
RUN apt-get install -y language-pack-fr-base
ENV LANG fr_FR.UTF-8
```

Après bien entendu un « apt-get update », et ne pas oublier « php-gettext » dans la liste des paquets à installer.

Merci @Prytoegrian pour ton aide ;-)

**Comment by Prytoegrian** [comment]
Je t'en prie, même si j'ai pas fait grand chose. Une fois que tu auras configuré une image aux petits oignons, ce serait pas mal que tu partages le dockerfile pour faciliter les dev (et je n'ose même pas rêver à le déployer en prod :-p)

J'essaie d'organiser mes pensées pour faire ça proprement, peut-être avoir un autre repo à côté…

**Comment by cyberesprit** [comment]
Où puis-je partager le Dockerfile ?

On peut aussi envisager de créer et partager le conteneur.
Sauf que j'utilise Docker comme on est censé l'utilisé, c'est à dire un conteneur = un service.

Donc j'ai un conteneur pour le serveur web et un conteneur lié pour la bdd.
Et aussi, toute la configuration des différents services, le site web en lui même (ici Libertempo) et les base de données sont extérieures à mes conteneurs. Mais ça doit pouvoir s'arranger !

**Comment by cyberesprit** [comment]
Je vois que ta branche est plus avancé (dans le temps tout du moins) que la branche develop.

**Comment by Prytoegrian** [comment]
Oui, c'est bien normal, `develop` est une branche de merge. Elle est donc censée être en retard sur les branches de travail. Je suis en train de bosser sur #63

Pour ta question, je voudrais en toucher un mot à @wouldsmina pour s'organiser.

**Comment by wouldsmina** [comment]
dsl je connais pas docker! c'est comme un chroot si je comprend bien. Mais ce qui me gêne le plus dans tout ça, c'est que la langue dépend aussi du serveur, alors que ce devrait être uniquement du navigateur! est ce lié a gettext? Je cherche à comprendre...

**Comment by Prytoegrian** [comment]
C'est pas vraiment un chroot parce que c'est un environnement isolé avec plusieurs logiciels, mais pouvant communiquer avec le système hote. Tu es dans un linux à ceci près que c'est une version réduite avec uniquement ce que tu as installé. On en parlera mieux sur Irc, sur mobile c'est pas pratique. 

Gettext se base sur le setlocale système mais si cette méthode demande une locale n'existant pas sur le système, boum ça fait des chocapics
