### ISSUE TITLE
Pouvoir supprimer Congés payés et RTT

### ISSUE THREAD

**Issue by AudreyOpale** [wouldsmina/Libertempo#998]
Bonjour, 
Les types de congés pré enregistrés dans Libertempo ne sont pas modifiables ou supprimables et c'est un problème.
Je voudrais notamment supprimer RTT qui est une notion qui n'existe pas en Suisse et renommer Congés payé en vacances car Congés payés est une expression très franco-française, en Suisse on dit Vacances.

idem pour les types d'absences : autre ne veut rien dire par exemple

Il serait bien de laisser la liberté de configurer les types d'absences complètement.

Et si le fait de les bloquer a un aspect légal en France alors, il faudrait pouvoir sélectionner son pays pour débloquer la fonctionnalité.

Merci

**Comment by wouldsmina** [comment]
Bonjour,

Normalement ce n'est pas possible mais une suppression dans la bdd pourrait faire l'affaire.
Cordialement.
